-- GENERATED BASELINE: public schema before application migrations.
-- Generated from the supplied Banco novo structural snapshot.
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA extensions;

CREATE TABLE IF NOT EXISTS public.apify_accounts (
    apify_accounts_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id bigint NOT NULL,
    account_name text NOT NULL,
    token_secret text NOT NULL,
    is_active boolean NOT NULL,
    connection_status text NOT NULL,
    external_username text,
    last_checked_at timestamp with time zone,
    last_used_at timestamp with time zone,
    last_error text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.apify_import_jobs (
    apify_import_jobs_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id bigint NOT NULL,
    apify_accounts_id bigint,
    apify_job_status_id bigint NOT NULL,
    apify_actor_id text,
    apify_run_id text,
    apify_dataset_id text,
    apify_search_query text,
    apify_search_location text,
    apify_quantity_total integer NOT NULL,
    apify_quantity_created integer NOT NULL,
    apify_quantity_duplicate integer NOT NULL,
    apify_quantity_blocked integer NOT NULL,
    apify_quantity_invalid integer NOT NULL,
    apify_error_message text,
    apify_started_at timestamp with time zone,
    apify_finished_at timestamp with time zone,
    apify_import_jobs_created_at timestamp with time zone NOT NULL DEFAULT now(),
    apify_import_jobs_updated_at timestamp with time zone NOT NULL DEFAULT now(),
    actor_id text NOT NULL,
    external_run_id text,
    external_dataset_id text,
    search_query text,
    location_query text,
    requested_limit integer,
    status text NOT NULL,
    total_received integer NOT NULL,
    error_message text,
    started_at timestamp with time zone NOT NULL DEFAULT now(),
    finished_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    search_terms jsonb NOT NULL,
    total_imported integer NOT NULL,
    total_duplicates integer NOT NULL,
    total_rejected integer NOT NULL,
    imported_at timestamp with time zone,
    branches_id bigint,
    branch_name text
);

CREATE TABLE IF NOT EXISTS public.branches (
    branches_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id bigint NOT NULL,
    status_id bigint NOT NULL,
    branches_name text NOT NULL,
    branches_categories jsonb,
    branches_created_at timestamp with time zone NOT NULL DEFAULT now(),
    branches_updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.channels (
    channels_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channels_name text NOT NULL,
    channels_created_at timestamp with time zone NOT NULL DEFAULT now(),
    channels_updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.chips (
    chips_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id bigint NOT NULL,
    instances_id bigint NOT NULL,
    levels_id bigint NOT NULL,
    status_id bigint NOT NULL,
    chips_name text NOT NULL,
    chips_phone text NOT NULL,
    chips_created_at timestamp with time zone NOT NULL DEFAULT now(),
    chips_updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.cities (
    cities_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    states_id bigint NOT NULL,
    cities_name text NOT NULL,
    cities_created_at timestamp with time zone NOT NULL DEFAULT now(),
    cities_updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.contact_sources (
    contact_sources_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id bigint NOT NULL,
    status_id bigint NOT NULL,
    contact_sources_name text NOT NULL,
    contact_sources_key text NOT NULL,
    contact_sources_requires_review boolean NOT NULL,
    contact_sources_default_channel_id bigint,
    contact_sources_created_at timestamp with time zone NOT NULL DEFAULT now(),
    contact_sources_updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.countries (
    countries_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    countries_name text NOT NULL,
    countries_code text NOT NULL,
    countries_created_at timestamp with time zone NOT NULL DEFAULT now(),
    countries_updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.import_rules (
    import_rules_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id bigint NOT NULL,
    status_id bigint NOT NULL,
    import_rules_min_rating numeric(2,1),
    import_rules_min_reviews integer,
    import_rules_require_name boolean NOT NULL,
    import_rules_require_phone boolean NOT NULL,
    import_rules_require_instagram boolean NOT NULL,
    import_rules_require_website boolean NOT NULL,
    import_rules_require_any_contact boolean NOT NULL,
    import_rules_deduplicate_phone boolean NOT NULL,
    import_rules_deduplicate_instagram boolean NOT NULL,
    import_rules_deduplicate_website boolean NOT NULL,
    import_rules_deduplicate_maps boolean NOT NULL,
    import_rules_created_at timestamp with time zone NOT NULL DEFAULT now(),
    import_rules_updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.instances (
    instances_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id bigint NOT NULL,
    status_id bigint NOT NULL,
    instances_name text NOT NULL,
    instances_url text,
    instances_apikey text,
    instances_created_at timestamp with time zone NOT NULL DEFAULT now(),
    instances_updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.lead_status (
    lead_status_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_status_name text NOT NULL,
    lead_status_created_at timestamp with time zone NOT NULL DEFAULT now(),
    lead_status_updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.lead_validation_attempts (
    lead_validation_attempts_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id bigint NOT NULL,
    leads_id bigint,
    channels_id bigint NOT NULL,
    chips_id bigint,
    queue_items_id bigint,
    validation_rules_id bigint,
    lead_validation_results_id bigint,
    status_id bigint NOT NULL,
    lead_validation_attempts_input_value text NOT NULL,
    lead_validation_attempts_provider text,
    lead_validation_attempts_provider_reference text,
    lead_validation_attempts_http_status integer,
    lead_validation_attempts_error_code text,
    lead_validation_attempts_error_message text,
    lead_validation_attempts_response_metadata jsonb NOT NULL,
    lead_validation_attempts_rules_snapshot jsonb NOT NULL,
    lead_validation_attempts_started_at timestamp with time zone NOT NULL DEFAULT now(),
    lead_validation_attempts_finished_at timestamp with time zone,
    lead_validation_attempts_created_at timestamp with time zone NOT NULL DEFAULT now(),
    lead_validation_attempts_updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.lead_validation_results (
    lead_validation_results_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_validation_results_key text NOT NULL,
    lead_validation_results_name text NOT NULL,
    status_id bigint NOT NULL,
    lead_validation_results_created_at timestamp with time zone NOT NULL DEFAULT now(),
    lead_validation_results_updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.leads (
    leads_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id bigint NOT NULL,
    branches_id bigint NOT NULL,
    countries_id bigint NOT NULL,
    states_id bigint,
    cities_id bigint,
    channels_id bigint,
    lead_status_id bigint NOT NULL,
    apify_import_jobs_id bigint,
    leads_name text NOT NULL,
    leads_phone text,
    leads_instagram text,
    leads_website text,
    leads_maps text,
    leads_street text,
    leads_postal_code text,
    leads_categories text[],
    leads_score numeric(3,2),
    leads_reviews_count integer,
    leads_origin text NOT NULL,
    leads_created_at timestamp with time zone NOT NULL DEFAULT now(),
    leads_updated_at timestamp with time zone NOT NULL DEFAULT now(),
    contact_sources_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.levels (
    levels_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id bigint NOT NULL,
    channels_id bigint NOT NULL,
    status_id bigint NOT NULL,
    levels_name text NOT NULL,
    levels_daily_limit integer NOT NULL,
    levels_created_at timestamp with time zone NOT NULL DEFAULT now(),
    levels_updated_at timestamp with time zone NOT NULL DEFAULT now(),
    levels_queues integer
);

CREATE TABLE IF NOT EXISTS public.queue_items (
    queue_items_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id bigint NOT NULL,
    queues_id bigint NOT NULL,
    leads_id bigint NOT NULL,
    chips_id bigint,
    socials_id bigint,
    templates_id bigint,
    status_id bigint NOT NULL,
    queue_items_position integer,
    queue_items_attempts integer NOT NULL,
    queue_items_scheduled_at timestamp with time zone,
    queue_items_started_at timestamp with time zone,
    queue_items_finished_at timestamp with time zone,
    queue_items_error_message text,
    queue_items_created_at timestamp with time zone NOT NULL DEFAULT now(),
    queue_items_updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.queues (
    queues_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id bigint NOT NULL,
    channels_id bigint NOT NULL,
    status_id bigint NOT NULL,
    queues_name text NOT NULL,
    queues_scheduled_at timestamp with time zone,
    queues_started_at timestamp with time zone,
    queues_finished_at timestamp with time zone,
    queues_created_at timestamp with time zone NOT NULL DEFAULT now(),
    queues_updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sents (
    sents_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id bigint NOT NULL,
    queue_items_id bigint,
    leads_id bigint,
    channels_id bigint,
    chips_id bigint,
    socials_id bigint,
    templates_id bigint,
    status_id bigint NOT NULL,
    sents_recipient text,
    sents_body text NOT NULL,
    sents_external_id text,
    sents_attempt integer NOT NULL,
    sents_error_message text,
    sents_sent_at timestamp with time zone,
    sents_created_at timestamp with time zone NOT NULL DEFAULT now(),
    sents_updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.socials (
    socials_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id bigint NOT NULL,
    status_id bigint NOT NULL,
    levels_id bigint NOT NULL,
    socials_name text NOT NULL,
    socials_username text NOT NULL,
    socials_created_at timestamp with time zone NOT NULL DEFAULT now(),
    socials_updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.states (
    states_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    countries_id bigint NOT NULL,
    states_name text NOT NULL,
    states_code text,
    states_created_at timestamp with time zone NOT NULL DEFAULT now(),
    states_updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.status (
    status_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_name text NOT NULL,
    status_created_at timestamp with time zone NOT NULL DEFAULT now(),
    status_updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.template_channels (
    template_channels_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_channels_name text NOT NULL,
    template_channels_created_at timestamp with time zone NOT NULL DEFAULT now(),
    template_channels_updated_at timestamp with time zone NOT NULL DEFAULT now(),
    users_id bigint NOT NULL,
    status_id bigint NOT NULL,
    template_channels_blocked_channels bigint[] NOT NULL
);

CREATE TABLE IF NOT EXISTS public.template_types (
    template_types_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id bigint NOT NULL,
    status_id bigint NOT NULL,
    template_types_name text NOT NULL,
    template_types_created_at timestamp with time zone NOT NULL DEFAULT now(),
    template_types_updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.template_variables (
    template_variables_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id bigint NOT NULL,
    status_id bigint NOT NULL,
    template_variables_name text NOT NULL,
    template_variables_key text NOT NULL,
    template_variables_source text NOT NULL,
    template_variables_default_value text NOT NULL,
    template_variables_created_at timestamp with time zone NOT NULL DEFAULT now(),
    template_variables_updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.templates (
    templates_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id bigint NOT NULL,
    branches_id bigint NOT NULL,
    status_id bigint NOT NULL,
    templates_name text NOT NULL,
    templates_message_1 text NOT NULL,
    templates_message_2 text NOT NULL,
    templates_message_3 text NOT NULL,
    templates_message_4 text NOT NULL,
    templates_created_at timestamp with time zone NOT NULL DEFAULT now(),
    templates_updated_at timestamp with time zone NOT NULL DEFAULT now(),
    template_channels_id bigint NOT NULL,
    template_types_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.users (
    users_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_user_id uuid NOT NULL,
    status_id bigint NOT NULL,
    users_created_at timestamp with time zone NOT NULL DEFAULT now(),
    users_updated_at timestamp with time zone NOT NULL DEFAULT now(),
    users_name text,
    users_avatar_path text
);

CREATE TABLE IF NOT EXISTS public.validation_rules (
    validation_rules_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id bigint NOT NULL,
    status_id bigint NOT NULL,
    validation_rules_source_id bigint NOT NULL,
    validation_rules_channel_id bigint NOT NULL,
    validation_rules_fallback_channel_id bigint NOT NULL,
    validation_rules_instagram_requires_approval boolean NOT NULL,
    validation_rules_max_technical_attempts integer NOT NULL,
    validation_rules_created_at timestamp with time zone NOT NULL DEFAULT now(),
    validation_rules_updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS users_auth_user_id_unique ON public.users USING btree (auth_user_id);
CREATE UNIQUE INDEX IF NOT EXISTS lead_validation_results_key_key ON public.lead_validation_results USING btree (lead_validation_results_key);
CREATE UNIQUE INDEX IF NOT EXISTS lead_validation_results_name_key ON public.lead_validation_results USING btree (lead_validation_results_name);
CREATE INDEX IF NOT EXISTS lead_validation_results_status_idx ON public.lead_validation_results USING btree (status_id);
CREATE UNIQUE INDEX IF NOT EXISTS lead_validation_attempts_active_unique ON public.lead_validation_attempts USING btree (users_id, leads_id, channels_id) WHERE ((leads_id IS NOT NULL) AND (status_id = ANY (ARRAY[(3)::bigint, (4)::bigint])));
CREATE UNIQUE INDEX IF NOT EXISTS lead_validation_attempts_queue_item_unique ON public.lead_validation_attempts USING btree (queue_items_id) WHERE (queue_items_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS lead_validation_attempts_user_created_idx ON public.lead_validation_attempts USING btree (users_id, lead_validation_attempts_created_at DESC);
CREATE INDEX IF NOT EXISTS lead_validation_attempts_lead_channel_idx ON public.lead_validation_attempts USING btree (leads_id, channels_id, lead_validation_attempts_created_at DESC) WHERE (leads_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS lead_validation_attempts_chip_created_idx ON public.lead_validation_attempts USING btree (chips_id, lead_validation_attempts_created_at DESC) WHERE (chips_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS lead_validation_attempts_status_created_idx ON public.lead_validation_attempts USING btree (users_id, status_id, lead_validation_attempts_created_at DESC);
CREATE INDEX IF NOT EXISTS apify_accounts_users_active_idx ON public.apify_accounts USING btree (users_id, is_active, apify_accounts_id);
CREATE UNIQUE INDEX IF NOT EXISTS apify_import_jobs_external_run_uidx ON public.apify_import_jobs USING btree (external_run_id) WHERE (external_run_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS apify_import_jobs_user_created_idx ON public.apify_import_jobs USING btree (users_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS status_status_name_key ON public.status USING btree (status_name);
CREATE INDEX IF NOT EXISTS apify_import_jobs_pending_import_idx ON public.apify_import_jobs USING btree (users_id, status, imported_at) WHERE ((status = 'succeeded'::text) AND (imported_at IS NULL));
CREATE UNIQUE INDEX IF NOT EXISTS lead_status_lead_status_name_key ON public.lead_status USING btree (lead_status_name);
CREATE UNIQUE INDEX IF NOT EXISTS users_auth_user_id_key ON public.users USING btree (auth_user_id);
CREATE UNIQUE INDEX IF NOT EXISTS countries_code_unique ON public.countries USING btree (countries_code);
CREATE UNIQUE INDEX IF NOT EXISTS states_country_name_unique ON public.states USING btree (countries_id, states_name);
CREATE UNIQUE INDEX IF NOT EXISTS states_country_code_unique ON public.states USING btree (countries_id, states_code);
CREATE UNIQUE INDEX IF NOT EXISTS cities_state_name_unique ON public.cities USING btree (states_id, cities_name);
CREATE INDEX IF NOT EXISTS apify_import_jobs_branches_id_idx ON public.apify_import_jobs USING btree (branches_id);
CREATE UNIQUE INDEX IF NOT EXISTS channels_channels_name_key ON public.channels USING btree (channels_name);
CREATE UNIQUE INDEX IF NOT EXISTS branches_user_name_unique ON public.branches USING btree (users_id, branches_name);
CREATE INDEX IF NOT EXISTS idx_apify_import_jobs_branch_status_location ON public.apify_import_jobs USING btree (branches_id, status, location_query);
CREATE UNIQUE INDEX IF NOT EXISTS levels_user_channel_name_unique ON public.levels USING btree (users_id, channels_id, levels_name);
CREATE UNIQUE INDEX IF NOT EXISTS socials_user_username_unique ON public.socials USING btree (users_id, socials_username);
CREATE UNIQUE INDEX IF NOT EXISTS instances_user_name_unique ON public.instances USING btree (users_id, instances_name);
CREATE UNIQUE INDEX IF NOT EXISTS chips_user_phone_unique ON public.chips USING btree (users_id, chips_phone);
CREATE UNIQUE INDEX IF NOT EXISTS templates_user_name_unique ON public.templates USING btree (users_id, templates_name);
CREATE UNIQUE INDEX IF NOT EXISTS apify_run_user_unique ON public.apify_import_jobs USING btree (users_id, apify_run_id);
CREATE INDEX IF NOT EXISTS leads_users_id_idx ON public.leads USING btree (users_id);
CREATE INDEX IF NOT EXISTS leads_apify_import_jobs_id_idx ON public.leads USING btree (apify_import_jobs_id);
CREATE INDEX IF NOT EXISTS import_rules_status_idx ON public.import_rules USING btree (status_id);
CREATE UNIQUE INDEX IF NOT EXISTS queues_user_name_unique ON public.queues USING btree (users_id, queues_name);
CREATE UNIQUE INDEX IF NOT EXISTS queue_items_queue_lead_unique ON public.queue_items USING btree (queues_id, leads_id);
CREATE INDEX IF NOT EXISTS queue_items_queue_status_idx ON public.queue_items USING btree (queues_id, status_id);
CREATE INDEX IF NOT EXISTS queue_items_user_status_idx ON public.queue_items USING btree (users_id, status_id);
CREATE INDEX IF NOT EXISTS leads_phone_idx ON public.leads USING btree (users_id, leads_phone) WHERE (leads_phone IS NOT NULL);
CREATE INDEX IF NOT EXISTS leads_website_idx ON public.leads USING btree (users_id, leads_website) WHERE (leads_website IS NOT NULL);
CREATE INDEX IF NOT EXISTS leads_instagram_idx ON public.leads USING btree (users_id, leads_instagram) WHERE (leads_instagram IS NOT NULL);
CREATE INDEX IF NOT EXISTS leads_maps_idx ON public.leads USING btree (users_id, leads_maps) WHERE (leads_maps IS NOT NULL);
CREATE INDEX IF NOT EXISTS leads_status_idx ON public.leads USING btree (users_id, lead_status_id);
CREATE INDEX IF NOT EXISTS users_status_idx ON public.users USING btree (status_id);
CREATE INDEX IF NOT EXISTS states_country_idx ON public.states USING btree (countries_id);
CREATE INDEX IF NOT EXISTS cities_state_idx ON public.cities USING btree (states_id);
CREATE UNIQUE INDEX IF NOT EXISTS import_rules_users_id_key ON public.import_rules USING btree (users_id);
CREATE INDEX IF NOT EXISTS branches_user_idx ON public.branches USING btree (users_id);
CREATE INDEX IF NOT EXISTS templates_user_idx ON public.templates USING btree (users_id);
CREATE INDEX IF NOT EXISTS sents_user_sent_at_idx ON public.sents USING btree (users_id, sents_sent_at DESC);
CREATE INDEX IF NOT EXISTS levels_user_channel_idx ON public.levels USING btree (users_id, channels_id);
CREATE INDEX IF NOT EXISTS sents_lead_idx ON public.sents USING btree (leads_id);
CREATE INDEX IF NOT EXISTS socials_user_idx ON public.socials USING btree (users_id);
CREATE INDEX IF NOT EXISTS apify_accounts_user_idx ON public.apify_accounts USING btree (users_id);
CREATE INDEX IF NOT EXISTS apify_jobs_user_created_idx ON public.apify_import_jobs USING btree (users_id, apify_import_jobs_created_at DESC);
CREATE INDEX IF NOT EXISTS apify_jobs_status_idx ON public.apify_import_jobs USING btree (apify_job_status_id);
CREATE INDEX IF NOT EXISTS queues_user_channel_idx ON public.queues USING btree (users_id, channels_id);
CREATE INDEX IF NOT EXISTS instances_user_idx ON public.instances USING btree (users_id);
CREATE INDEX IF NOT EXISTS chips_user_idx ON public.chips USING btree (users_id);
CREATE INDEX IF NOT EXISTS sents_queue_item_idx ON public.sents USING btree (queue_items_id);
CREATE UNIQUE INDEX IF NOT EXISTS template_variables_user_key_unique ON public.template_variables USING btree (users_id, template_variables_key);
CREATE UNIQUE INDEX IF NOT EXISTS validation_rules_users_id_key ON public.validation_rules USING btree (users_id);
CREATE INDEX IF NOT EXISTS validation_rules_source_idx ON public.validation_rules USING btree (validation_rules_source_id);
CREATE INDEX IF NOT EXISTS validation_rules_channels_idx ON public.validation_rules USING btree (validation_rules_channel_id, validation_rules_fallback_channel_id);
CREATE UNIQUE INDEX IF NOT EXISTS contact_sources_users_key_unique ON public.contact_sources USING btree (users_id, contact_sources_key);
CREATE UNIQUE INDEX IF NOT EXISTS contact_sources_users_name_unique ON public.contact_sources USING btree (users_id, contact_sources_name);
CREATE INDEX IF NOT EXISTS leads_contact_sources_id_idx ON public.leads USING btree (contact_sources_id);

CREATE OR REPLACE FUNCTION public.ensure_current_user()
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE v_auth uuid:=auth.uid(); v_id bigint;
BEGIN
  IF v_auth IS NULL THEN RAISE EXCEPTION 'authentication_required'; END IF;
  SELECT users_id INTO v_id FROM public.users WHERE auth_user_id=v_auth;
  IF v_id IS NULL THEN
    INSERT INTO public.users(auth_user_id,status_id) VALUES(v_auth,1)
    ON CONFLICT(auth_user_id) DO UPDATE SET auth_user_id=excluded.auth_user_id
    RETURNING users_id INTO v_id;
  END IF;
  RETURN v_id;
END; $$;

INSERT INTO public.status(status_id,status_name,status_created_at,status_updated_at) VALUES
(1,'ativo',now(),now()),(2,'inativo',now(),now()),(3,'pendente',now(),now()),(4,'processando',now(),now()),
(5,'concluido',now(),now()),(6,'erro',now(),now()),(7,'cancelado',now(),now()),(8,'pausado',now(),now())
ON CONFLICT(status_id) DO UPDATE SET status_name=excluded.status_name;
INSERT INTO public.lead_status(lead_status_id,lead_status_name,lead_status_created_at,lead_status_updated_at) VALUES
(1,'importado',now(),now()),(2,'validado',now(),now()),(3,'pre_envio',now(),now()),(4,'na_fila',now(),now()),
(5,'enviado',now(),now()),(6,'invalido',now(),now()),(7,'duplicado',now(),now()),(8,'arquivado',now(),now())
ON CONFLICT(lead_status_id) DO UPDATE SET lead_status_name=excluded.lead_status_name;
INSERT INTO public.channels(channels_id,channels_name,channels_created_at,channels_updated_at) VALUES
(1,'WhatsApp',now(),now()),(2,'Instagram',now(),now())
ON CONFLICT(channels_id) DO UPDATE SET channels_name=excluded.channels_name;
COMMIT;
