create table if not exists public.app_settings (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chips (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  status text,
  active boolean,
  kind text default 'chips',
  channel text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.branches (
  id bigint generated by default as identity primary key,
  slug text unique,
  name text,
  image_name text,
  data jsonb not null default '{}'::jsonb,
  status text,
  active boolean,
  kind text default 'branches',
  channel text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.templates (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  status text,
  active boolean,
  kind text default 'templates',
  channel text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.leads (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  status text,
  active boolean,
  kind text,
  channel text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pre_send_leads (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  status text,
  active boolean,
  kind text,
  channel text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.whatsapp_queue_items (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  status text,
  active boolean,
  kind text,
  channel text default 'whatsapp',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.instagram_queue_items (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  status text,
  active boolean,
  kind text,
  channel text default 'instagram',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.base_permanente (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  status text,
  active boolean,
  kind text,
  channel text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sent_contacts (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  normalized_phone text,
  site_normalized text,
  instagram_username text,
  maps_url text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lead_events (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  source text,
  action text,
  channel text,
  status text,
  active boolean,
  kind text,
  lead_id text,
  queue_item_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists chips_status_idx on public.chips(status);
create index if not exists branches_status_idx on public.branches(status);
create index if not exists templates_status_idx on public.templates(status);
create index if not exists leads_status_idx on public.leads(status);
create index if not exists pre_send_leads_status_idx on public.pre_send_leads(status);
create index if not exists pre_send_leads_channel_idx on public.pre_send_leads(channel);
create index if not exists whatsapp_queue_items_status_idx on public.whatsapp_queue_items(status);
create index if not exists instagram_queue_items_status_idx on public.instagram_queue_items(status);
create index if not exists base_permanente_status_idx on public.base_permanente(status);
create index if not exists sent_contacts_phone_idx on public.sent_contacts(normalized_phone);
create index if not exists sent_contacts_site_idx on public.sent_contacts(site_normalized);
create index if not exists sent_contacts_instagram_idx on public.sent_contacts(instagram_username);
create index if not exists lead_events_source_idx on public.lead_events(source);
create index if not exists lead_events_channel_idx on public.lead_events(channel);
create index if not exists lead_events_created_at_idx on public.lead_events(created_at desc);

create index if not exists whatsapp_queue_items_worker_idx
  on public.whatsapp_queue_items(status, ((data->>'scheduled_date')), ((data->>'batch_number')), ((data->>'position')));

create index if not exists instagram_queue_items_worker_idx
  on public.instagram_queue_items(status, ((data->>'scheduled_date')), ((data->>'batch_number')), ((data->>'position')));
