CREATE ROLE anon NOLOGIN;
CREATE ROLE authenticated NOLOGIN;
CREATE ROLE service_role NOLOGIN;
CREATE SCHEMA storage;

CREATE TABLE public.users(users_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,auth_user_id uuid,users_name text);
CREATE TABLE public.organizations(organizations_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,legacy_scope_users_id bigint NOT NULL REFERENCES public.users(users_id));
CREATE TABLE public.organization_roles(organization_roles_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,organization_roles_key text NOT NULL,status_id bigint NOT NULL DEFAULT 1);
CREATE TABLE public.permissions(permissions_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,permissions_key text UNIQUE NOT NULL,permissions_name text,permissions_category text,permissions_description text,permissions_sensitivity text NOT NULL DEFAULT 'delegable');
CREATE TABLE public.organization_role_permissions(organization_roles_id bigint REFERENCES public.organization_roles,permissions_id bigint REFERENCES public.permissions,UNIQUE(organization_roles_id,permissions_id));
CREATE TABLE public.organization_members(organization_members_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,organizations_id bigint NOT NULL REFERENCES public.organizations,users_id bigint NOT NULL REFERENCES public.users,organization_roles_id bigint REFERENCES public.organization_roles,access_level text NOT NULL,status_id bigint NOT NULL DEFAULT 1);
CREATE TABLE public.instances(instances_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,users_id bigint NOT NULL REFERENCES public.users,organizations_id bigint NOT NULL REFERENCES public.organizations,instances_name text);
CREATE TABLE public.chips(chips_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,users_id bigint NOT NULL REFERENCES public.users,organizations_id bigint NOT NULL REFERENCES public.organizations,instances_id bigint REFERENCES public.instances,chips_name text);
CREATE TABLE public.queue_items(queue_items_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,users_id bigint NOT NULL REFERENCES public.users,organizations_id bigint NOT NULL REFERENCES public.organizations,queues_id bigint,chips_id bigint REFERENCES public.chips,leads_id bigint,status_id bigint NOT NULL DEFAULT 3,dispatched_by_member_id bigint REFERENCES public.organization_members,queue_items_error_message text,queue_items_started_at timestamptz,queue_items_finished_at timestamptz,queue_items_created_at timestamptz DEFAULT now(),queue_items_updated_at timestamptz DEFAULT now());
CREATE TABLE public.sents(sents_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,users_id bigint NOT NULL REFERENCES public.users,organizations_id bigint NOT NULL REFERENCES public.organizations,queue_items_id bigint REFERENCES public.queue_items,status_id bigint NOT NULL DEFAULT 5,sent_by_member_id bigint REFERENCES public.organization_members,executed_by text NOT NULL DEFAULT 'system');
CREATE TABLE public.worker_batches(worker_batches_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,users_id bigint NOT NULL REFERENCES public.users,organizations_id bigint NOT NULL REFERENCES public.organizations,channels_id bigint NOT NULL DEFAULT 1,status_id bigint NOT NULL DEFAULT 3,worker_batches_total_items integer NOT NULL DEFAULT 0,worker_batches_processed_items integer NOT NULL DEFAULT 0,worker_batches_sent_items integer NOT NULL DEFAULT 0,worker_batches_failed_items integer NOT NULL DEFAULT 0,worker_batches_created_at timestamptz DEFAULT now(),worker_batches_updated_at timestamptz DEFAULT now());

CREATE TABLE public.conversations(
  conversations_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,users_id bigint NOT NULL REFERENCES public.users,organizations_id bigint NOT NULL REFERENCES public.organizations,
  chips_id bigint NOT NULL REFERENCES public.chips,instances_id bigint NOT NULL REFERENCES public.instances,leads_id bigint,remote_jid text NOT NULL,contact_phone text,contact_name text,contact_avatar_url text,
  conversation_status text NOT NULL DEFAULT 'open',unread_count integer NOT NULL DEFAULT 0,assigned_to_member_id bigint REFERENCES public.organization_members,last_replied_by_member_id bigint REFERENCES public.organization_members,
  last_message_at timestamptz,last_message_preview text,last_message_direction text,conversations_updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.conversation_messages(
  conversation_messages_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,users_id bigint NOT NULL REFERENCES public.users,organizations_id bigint NOT NULL REFERENCES public.organizations,
  conversations_id bigint NOT NULL REFERENCES public.conversations,chips_id bigint NOT NULL REFERENCES public.chips,instances_id bigint NOT NULL REFERENCES public.instances,leads_id bigint,
  external_message_id text,remote_jid text,direction text NOT NULL,from_me boolean NOT NULL,message_type text NOT NULL,message_body text,media_url text,media_mime_type text,media_file_name text,
  quoted_external_message_id text,message_status text NOT NULL,sent_by_member_id bigint REFERENCES public.organization_members,executed_by text NOT NULL DEFAULT 'system',provider_timestamp timestamptz,
  error_message text,raw_payload jsonb,conversation_messages_created_at timestamptz NOT NULL DEFAULT now(),conversation_messages_updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.audit_events(audit_events_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,users_id bigint,organizations_id bigint,actor_auth_user_id uuid,actor_users_id bigint,actor_member_id bigint,actor_type text,source text,action text,entity_type text,entity_id text,message text,metadata jsonb,created_at timestamptz DEFAULT now());
CREATE TABLE storage.buckets(id text PRIMARY KEY,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);

CREATE FUNCTION public.current_organization_id() RETURNS bigint LANGUAGE sql STABLE AS $$SELECT NULL::bigint$$;
CREATE FUNCTION public.has_organization_permission(text) RETURNS boolean LANGUAGE sql STABLE AS $$SELECT false$$;
CREATE FUNCTION public.append_audit_event(text,text,text,text,bigint,bigint,bigint,bigint,bigint,text,jsonb,bigint) RETURNS bigint LANGUAGE sql AS $$SELECT 1::bigint$$;

INSERT INTO public.users(users_id,auth_user_id,users_name) VALUES
 (1,'00000000-0000-0000-0000-000000000001','Scope A'),(2,'00000000-0000-0000-0000-000000000002','Samuel'),
 (3,'00000000-0000-0000-0000-000000000003','Luiz'),(4,'00000000-0000-0000-0000-000000000004','Inativo'),(5,'00000000-0000-0000-0000-000000000005','Somente leitura'),
 (6,'00000000-0000-0000-0000-000000000006','Scope B'),(7,'00000000-0000-0000-0000-000000000007','Outro tenant');
INSERT INTO public.organizations(organizations_id,legacy_scope_users_id) VALUES(10,1),(20,6);
INSERT INTO public.organization_roles(organization_roles_id,organization_roles_key,status_id) VALUES(1,'gestor',1),(2,'operador',1),(3,'visualizador',1);
INSERT INTO public.permissions(permissions_key,permissions_name,permissions_category,permissions_description,permissions_sensitivity) VALUES
 ('whatsapp.view','view','WhatsApp','view','delegable'),('whatsapp.reply','reply','WhatsApp','reply','delegable'),
 ('queues.view','queue view','Filas','view','delegable'),('queues.control','queue control','Filas','control','delegable');
INSERT INTO public.organization_role_permissions(organization_roles_id,permissions_id)
 SELECT 2,permissions_id FROM public.permissions WHERE permissions_key IN('whatsapp.view','whatsapp.reply','queues.view','queues.control');
INSERT INTO public.organization_role_permissions(organization_roles_id,permissions_id)
 SELECT 3,permissions_id FROM public.permissions WHERE permissions_key='whatsapp.view';
INSERT INTO public.organization_members(organization_members_id,organizations_id,users_id,organization_roles_id,access_level,status_id) VALUES
 (101,10,2,2,'owner',1),(102,10,3,2,'member',1),(103,10,4,2,'member',2),(104,10,5,3,'member',1),(201,20,7,2,'owner',1);
INSERT INTO public.organization_role_permissions(organization_roles_id,permissions_id)
 SELECT 1,permissions_id FROM public.permissions ON CONFLICT DO NOTHING;
INSERT INTO public.instances(instances_id,users_id,organizations_id,instances_name) VALUES(1001,1,10,'chip-a'),(2001,6,20,'chip-b');
INSERT INTO public.chips(chips_id,users_id,organizations_id,instances_id,chips_name) VALUES(501,1,10,1001,'Comercial A'),(601,6,20,2001,'Comercial B');
INSERT INTO public.queue_items(queue_items_id,users_id,organizations_id,queues_id,chips_id,leads_id,status_id,dispatched_by_member_id) VALUES(7001,1,10,1,501,9001,6,101),(7002,1,10,1,501,9002,6,101),(7003,1,10,1,501,9003,6,101);
INSERT INTO public.worker_batches(worker_batches_id,users_id,organizations_id,channels_id,status_id,worker_batches_total_items) VALUES(8001,1,10,1,3,2);
INSERT INTO public.conversations(conversations_id,users_id,organizations_id,chips_id,instances_id,remote_jid,contact_phone,contact_name,conversation_status,last_message_at,last_message_preview)
VALUES(1,1,10,501,1001,'5511999999999@s.whatsapp.net','5511999999999','Lead inicial','open',now(),'Olá'),
      (2,6,20,601,2001,'5511666666666@s.whatsapp.net','5511666666666','Outro tenant','open',now(),'Privada');
SELECT setval(pg_get_serial_sequence('public.conversations','conversations_id'),2,true);
