BEGIN;

-- ETAPA 13 — orquestração ponta a ponta da operação.

DO $stage_preflight$
DECLARE v_missing text[]:=ARRAY[]::text[]; v_name text;
BEGIN
  FOREACH v_name IN ARRAY ARRAY['platform_schema_contracts','permanent_records'] LOOP IF to_regclass('public.'||v_name) IS NULL THEN v_missing:=array_append(v_missing,'table:'||v_name);END IF;END LOOP;
  FOREACH v_name IN ARRAY ARRAY['platform_schema_health'] LOOP IF NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname=v_name) THEN v_missing:=array_append(v_missing,'function:'||v_name);END IF;END LOOP;
  IF cardinality(v_missing)>0 THEN RAISE EXCEPTION 'stage_preflight_failed:%',array_to_string(v_missing,',');END IF;
END
$stage_preflight$;

CREATE TABLE IF NOT EXISTS public.lead_orchestration_state (
  lead_orchestration_state_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizations_id bigint NOT NULL REFERENCES public.organizations(organizations_id) ON DELETE CASCADE,
  leads_id bigint NOT NULL REFERENCES public.leads(leads_id) ON DELETE CASCADE,
  orchestration_state text NOT NULL DEFAULT 'waiting_validation' CHECK(orchestration_state IN ('waiting_validation','eligible','blocked','capacity_wait','queued','dispatching','sent','responded','finalized','reconciliation_required','error')),
  routed_channel text CHECK(routed_channel IS NULL OR routed_channel IN ('whatsapp','instagram')),
  resource_id bigint,
  templates_id bigint REFERENCES public.templates(templates_id) ON DELETE SET NULL,
  queue_items_id bigint REFERENCES public.queue_items(queue_items_id) ON DELETE SET NULL,
  block_reason text,
  next_attempt_at timestamptz,
  last_evaluated_at timestamptz NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(organizations_id,leads_id)
);
CREATE INDEX IF NOT EXISTS lead_orchestration_state_pending_idx ON public.lead_orchestration_state(organizations_id,orchestration_state,next_attempt_at,last_evaluated_at);
ALTER TABLE public.lead_orchestration_state ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS lead_orchestration_state_org_select ON public.lead_orchestration_state;
CREATE POLICY lead_orchestration_state_org_select ON public.lead_orchestration_state FOR SELECT TO authenticated USING(organizations_id=public.current_organization_id() AND public.has_organization_permission('leads.view'));
REVOKE INSERT,UPDATE,DELETE ON public.lead_orchestration_state FROM anon,authenticated;GRANT SELECT ON public.lead_orchestration_state TO authenticated;GRANT ALL ON public.lead_orchestration_state TO service_role;

CREATE TABLE IF NOT EXISTS public.lead_lifecycle_events (
  lead_lifecycle_events_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizations_id bigint NOT NULL REFERENCES public.organizations(organizations_id) ON DELETE CASCADE,
  leads_id bigint NOT NULL REFERENCES public.leads(leads_id) ON DELETE CASCADE,
  event_type text NOT NULL,
  channel text,
  entity_type text,
  entity_id text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS lead_lifecycle_events_lead_idx ON public.lead_lifecycle_events(organizations_id,leads_id,created_at,lead_lifecycle_events_id);
ALTER TABLE public.lead_lifecycle_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS lead_lifecycle_events_org_select ON public.lead_lifecycle_events;
CREATE POLICY lead_lifecycle_events_org_select ON public.lead_lifecycle_events FOR SELECT TO authenticated USING(organizations_id=public.current_organization_id() AND public.has_organization_permission('leads.view'));
REVOKE INSERT,UPDATE,DELETE ON public.lead_lifecycle_events FROM anon,authenticated;GRANT SELECT ON public.lead_lifecycle_events TO authenticated;GRANT ALL ON public.lead_lifecycle_events TO service_role;

CREATE OR REPLACE FUNCTION public.service_set_orchestration_state(p_organizations_id bigint,p_leads_id bigint,p_state text,p_channel text DEFAULT NULL,p_resource_id bigint DEFAULT NULL,p_templates_id bigint DEFAULT NULL,p_queue_items_id bigint DEFAULT NULL,p_reason text DEFAULT NULL,p_metadata jsonb DEFAULT '{}'::jsonb)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
BEGIN
 IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role_required';END IF;
 INSERT INTO public.lead_orchestration_state(organizations_id,leads_id,orchestration_state,routed_channel,resource_id,templates_id,queue_items_id,block_reason,next_attempt_at,last_evaluated_at,metadata)
 VALUES(p_organizations_id,p_leads_id,p_state,p_channel,p_resource_id,p_templates_id,p_queue_items_id,p_reason,CASE WHEN p_state='capacity_wait' THEN now()+interval '10 minutes' ELSE NULL END,now(),coalesce(p_metadata,'{}'))
 ON CONFLICT(organizations_id,leads_id) DO UPDATE SET orchestration_state=excluded.orchestration_state,routed_channel=excluded.routed_channel,resource_id=excluded.resource_id,templates_id=excluded.templates_id,queue_items_id=excluded.queue_items_id,block_reason=excluded.block_reason,next_attempt_at=excluded.next_attempt_at,last_evaluated_at=now(),metadata=public.lead_orchestration_state.metadata||excluded.metadata,updated_at=now();
 INSERT INTO public.lead_lifecycle_events(organizations_id,leads_id,event_type,channel,entity_type,entity_id,payload) VALUES(p_organizations_id,p_leads_id,'orchestration:'||p_state,p_channel,'lead',p_leads_id::text,jsonb_build_object('reason',p_reason,'resourceId',p_resource_id,'templateId',p_templates_id,'queueItemId',p_queue_items_id)||coalesce(p_metadata,'{}'));
END; $$;
REVOKE ALL ON FUNCTION public.service_set_orchestration_state(bigint,bigint,text,text,bigint,bigint,bigint,text,jsonb) FROM PUBLIC,anon,authenticated;GRANT EXECUTE ON FUNCTION public.service_set_orchestration_state(bigint,bigint,text,text,bigint,bigint,bigint,text,jsonb) TO service_role;

CREATE OR REPLACE FUNCTION public.service_orchestrate_lead(p_organizations_id bigint,p_leads_id bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE l public.leads%ROWTYPE;v_channel text;v_channel_id bigint;v_resource bigint;v_template bigint;v_queue bigint;v_item bigint;v_user bigint;v_name text;v_usage integer;v_limit integer;v_reentry jsonb;v_capacity jsonb;v_existing bigint;v_has_phone boolean;v_has_instagram boolean;
BEGIN
 IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role_required';END IF;
 SELECT * INTO l FROM public.leads WHERE organizations_id=p_organizations_id AND leads_id=p_leads_id FOR UPDATE;
 IF NOT FOUND THEN RETURN jsonb_build_object('outcome','not_found');END IF;
 v_user:=l.users_id;v_has_phone:=length(regexp_replace(coalesce(l.leads_whatsapp,l.leads_phone,''),'\\D','','g'))>=10;v_has_instagram:=nullif(trim(coalesce(l.leads_instagram,'')),'') IS NOT NULL;
 IF l.lead_status_id=5 THEN PERFORM public.service_set_orchestration_state(p_organizations_id,p_leads_id,'sent',NULL,NULL,NULL,NULL,NULL,'{}');RETURN jsonb_build_object('outcome','sent');END IF;
 IF l.lead_status_id IN(6,7,8) THEN PERFORM public.service_set_orchestration_state(p_organizations_id,p_leads_id,'finalized',NULL,NULL,NULL,NULL,'lead_finalized','{}');RETURN jsonb_build_object('outcome','finalized');END IF;
 IF l.lead_status_id<>2 THEN PERFORM public.service_set_orchestration_state(p_organizations_id,p_leads_id,'waiting_validation',NULL,NULL,NULL,NULL,'lead_not_validated',jsonb_build_object('statusId',l.lead_status_id));RETURN jsonb_build_object('outcome','waiting_validation');END IF;
 IF EXISTS(SELECT 1 FROM public.contact_suppressions s WHERE s.organizations_id=p_organizations_id AND s.is_active AND (s.expires_at IS NULL OR s.expires_at>now()) AND ((s.identity_type='phone' AND s.identity_value=l.leads_normalized_phone) OR (s.identity_type='instagram' AND s.identity_value=l.leads_normalized_instagram) OR (s.identity_type='domain' AND s.identity_value=l.leads_normalized_domain) OR (s.identity_type='maps' AND s.identity_value=l.leads_normalized_maps))) THEN
   PERFORM public.service_set_orchestration_state(p_organizations_id,p_leads_id,'blocked',NULL,NULL,NULL,NULL,'contact_suppressed','{}');RETURN jsonb_build_object('outcome','blocked','reason','contact_suppressed');
 END IF;
 IF EXISTS(SELECT 1 FROM public.permanent_records pr WHERE pr.organizations_id=p_organizations_id AND pr.canonical_lead_id=coalesce(l.canonical_lead_id,l.leads_id)) THEN
   v_reentry:=public.commercial_reentry_decision(p_organizations_id,coalesce(l.canonical_lead_id,l.leads_id),now());
   IF coalesce((v_reentry->>'allowed')::boolean,false)=false THEN PERFORM public.service_set_orchestration_state(p_organizations_id,p_leads_id,'blocked',NULL,NULL,NULL,NULL,'commercial_reentry_blocked',v_reentry);RETURN jsonb_build_object('outcome','blocked','reason','commercial_reentry_blocked','decision',v_reentry);END IF;
 END IF;
 -- O canal já validado é soberano. Fallback só é usado se o registro legado não tiver canal.
 IF l.channels_id=1 AND v_has_phone THEN v_channel:='whatsapp';v_channel_id:=1;
 ELSIF l.channels_id=2 AND v_has_instagram THEN v_channel:='instagram';v_channel_id:=2;
 ELSIF v_has_phone THEN v_channel:='whatsapp';v_channel_id:=1;
 ELSIF v_has_instagram THEN v_channel:='instagram';v_channel_id:=2;
 ELSE PERFORM public.service_set_orchestration_state(p_organizations_id,p_leads_id,'blocked',NULL,NULL,NULL,NULL,'no_supported_contact','{}');RETURN jsonb_build_object('outcome','blocked','reason','no_supported_contact');END IF;

 -- Item ativo existente vence qualquer nova preparação.
 SELECT qi.queue_items_id INTO v_existing FROM public.queue_items qi JOIN public.queues q ON q.queues_id=qi.queues_id WHERE qi.organizations_id=p_organizations_id AND qi.leads_id=p_leads_id AND q.channels_id=v_channel_id AND qi.status_id IN(3,4,5,8) ORDER BY qi.queue_items_created_at DESC LIMIT 1;
 IF v_existing IS NOT NULL THEN PERFORM public.service_set_orchestration_state(p_organizations_id,p_leads_id,CASE WHEN EXISTS(SELECT 1 FROM public.queue_items WHERE queue_items_id=v_existing AND status_id=5) THEN 'sent' ELSE 'queued' END,v_channel,NULL,NULL,v_existing,NULL,'{}');RETURN jsonb_build_object('outcome','already_queued','queueItemId',v_existing,'channel',v_channel);END IF;

 IF v_channel='whatsapp' THEN
   SELECT c.chips_id,lv.levels_daily_limit INTO v_resource,v_limit FROM public.chips c JOIN public.instances i ON i.instances_id=c.instances_id AND i.organizations_id=p_organizations_id JOIN public.levels lv ON lv.levels_id=c.levels_id AND lv.organizations_id=p_organizations_id
   WHERE c.organizations_id=p_organizations_id AND c.status_id=1 AND i.status_id=1 AND lv.status_id=1
   ORDER BY (SELECT count(*) FROM public.queue_items qi WHERE qi.organizations_id=p_organizations_id AND qi.chips_id=c.chips_id AND qi.status_id IN(3,4,5,8) AND coalesce(qi.queue_items_scheduled_at,qi.queue_items_created_at)::date=current_date),c.chips_id LIMIT 1;
   IF v_resource IS NOT NULL THEN SELECT count(*) INTO v_usage FROM public.queue_items qi WHERE qi.organizations_id=p_organizations_id AND qi.chips_id=v_resource AND qi.status_id IN(3,4,5,8) AND coalesce(qi.queue_items_scheduled_at,qi.queue_items_created_at)::date=current_date;END IF;
   IF v_resource IS NULL OR coalesce(v_usage,0)>=coalesce(v_limit,0) THEN PERFORM public.service_set_orchestration_state(p_organizations_id,p_leads_id,'capacity_wait',v_channel,NULL,NULL,NULL,'whatsapp_capacity_unavailable','{}');RETURN jsonb_build_object('outcome','capacity_wait','channel',v_channel);END IF;
 ELSE
   SELECT s.socials_id,public.instagram_profile_capacity(p_organizations_id,s.socials_id,now()) INTO v_resource,v_capacity FROM public.socials s WHERE s.organizations_id=p_organizations_id AND s.status_id=1 ORDER BY s.socials_id LIMIT 1;
   IF v_resource IS NULL OR coalesce((v_capacity->>'allowed')::boolean,false)=false OR coalesce((v_capacity->>'withinWindow')::boolean,false)=false OR coalesce((v_capacity->>'remaining')::integer,0)<=0 THEN PERFORM public.service_set_orchestration_state(p_organizations_id,p_leads_id,'capacity_wait',v_channel,NULL,NULL,NULL,'instagram_capacity_unavailable',coalesce(v_capacity,'{}'));RETURN jsonb_build_object('outcome','capacity_wait','channel',v_channel);END IF;
 END IF;

 -- Template ativo do mesmo ramo. Priorizamos template explicitamente rotulado para o canal.
 SELECT t.templates_id INTO v_template FROM public.templates t LEFT JOIN public.template_channels tc ON tc.template_channels_id=t.template_channels_id WHERE t.organizations_id=p_organizations_id AND t.status_id=1 AND t.branches_id=l.branches_id ORDER BY CASE WHEN lower(coalesce(tc.template_channels_name,'')) LIKE '%'||v_channel||'%' THEN 0 ELSE 1 END,t.templates_id LIMIT 1;
 IF v_template IS NULL THEN PERFORM public.service_set_orchestration_state(p_organizations_id,p_leads_id,'blocked',v_channel,v_resource,NULL,NULL,'template_missing','{}');RETURN jsonb_build_object('outcome','blocked','reason','template_missing','channel',v_channel);END IF;

 PERFORM pg_advisory_xact_lock(hashtextextended(format('orchestrate:%s:%s:%s:%s',p_organizations_id,v_channel,v_resource,current_date),0));
 v_name:=format('Orquestração %s %s #%s',initcap(v_channel),to_char(current_date,'YYYY-MM-DD'),v_resource);
 SELECT queues_id INTO v_queue FROM public.queues WHERE organizations_id=p_organizations_id AND queues_name=v_name LIMIT 1;
 IF v_queue IS NULL THEN INSERT INTO public.queues(users_id,organizations_id,channels_id,status_id,queues_name,queues_scheduled_at) VALUES(v_user,p_organizations_id,v_channel_id,3,v_name,current_date::timestamptz) RETURNING queues_id INTO v_queue;END IF;
 INSERT INTO public.queue_items(users_id,organizations_id,queues_id,leads_id,chips_id,socials_id,templates_id,status_id,queue_items_position,queue_items_attempts,queue_items_scheduled_at)
 VALUES(v_user,p_organizations_id,v_queue,p_leads_id,CASE WHEN v_channel='whatsapp' THEN v_resource ELSE NULL END,CASE WHEN v_channel='instagram' THEN v_resource ELSE NULL END,v_template,3,(SELECT coalesce(max(queue_items_position),0)+1 FROM public.queue_items WHERE queues_id=v_queue),0,current_date::timestamptz)
 ON CONFLICT(queues_id,leads_id) DO UPDATE SET templates_id=excluded.templates_id RETURNING queue_items_id INTO v_item;
 UPDATE public.leads SET channels_id=v_channel_id,lead_status_id=4,leads_updated_at=now() WHERE leads_id=p_leads_id AND organizations_id=p_organizations_id AND lead_status_id=2;
 PERFORM public.service_set_orchestration_state(p_organizations_id,p_leads_id,'queued',v_channel,v_resource,v_template,v_item,NULL,jsonb_build_object('queueId',v_queue));
 RETURN jsonb_build_object('outcome','queued','channel',v_channel,'resourceId',v_resource,'templateId',v_template,'queueId',v_queue,'queueItemId',v_item);
EXCEPTION WHEN OTHERS THEN
 PERFORM public.service_set_orchestration_state(p_organizations_id,p_leads_id,'error',v_channel,v_resource,v_template,v_item,SQLERRM,'{}');
 RETURN jsonb_build_object('outcome','error','error',SQLERRM);
END; $$;
REVOKE ALL ON FUNCTION public.service_orchestrate_lead(bigint,bigint) FROM PUBLIC,anon,authenticated;GRANT EXECUTE ON FUNCTION public.service_orchestrate_lead(bigint,bigint) TO service_role;

CREATE OR REPLACE FUNCTION public.service_orchestrate_ready_leads(p_organizations_id bigint,p_limit integer DEFAULT 25)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE r record;v_results jsonb:='[]'::jsonb;v_result jsonb;v_limit integer:=least(greatest(coalesce(p_limit,25),1),100);
BEGIN
 IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role_required';END IF;
 FOR r IN SELECT l.leads_id FROM public.leads l LEFT JOIN public.lead_orchestration_state os ON os.organizations_id=l.organizations_id AND os.leads_id=l.leads_id WHERE l.organizations_id=p_organizations_id AND l.lead_status_id=2 AND (os.leads_id IS NULL OR os.orchestration_state IN('eligible','capacity_wait','error','waiting_validation') AND (os.next_attempt_at IS NULL OR os.next_attempt_at<=now())) ORDER BY l.leads_priority_score DESC NULLS LAST,l.leads_created_at,l.leads_id LIMIT v_limit FOR UPDATE OF l SKIP LOCKED LOOP
   v_result:=public.service_orchestrate_lead(p_organizations_id,r.leads_id);v_results:=v_results||jsonb_build_array(jsonb_build_object('leadId',r.leads_id)||v_result);
 END LOOP;
 RETURN jsonb_build_object('processed',jsonb_array_length(v_results),'results',v_results);
END; $$;
REVOKE ALL ON FUNCTION public.service_orchestrate_ready_leads(bigint,integer) FROM PUBLIC,anon,authenticated;GRANT EXECUTE ON FUNCTION public.service_orchestrate_ready_leads(bigint,integer) TO service_role;

-- Timeline automática para os principais estados do ciclo.
CREATE OR REPLACE FUNCTION public.record_lead_lifecycle_event()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE v_lead bigint;v_org bigint;v_event text;v_channel text;v_entity_id text;
BEGIN
 IF TG_TABLE_NAME='leads' THEN v_lead:=NEW.leads_id;v_org:=NEW.organizations_id;v_event:=CASE WHEN TG_OP='INSERT' THEN 'lead:captured' ELSE 'lead:status_changed' END;v_channel:=CASE NEW.channels_id WHEN 1 THEN 'whatsapp' WHEN 2 THEN 'instagram' ELSE NULL END;v_entity_id:=NEW.leads_id::text;
 ELSIF TG_TABLE_NAME='queue_items' THEN v_lead:=NEW.leads_id;v_org:=NEW.organizations_id;v_event:=CASE NEW.status_id WHEN 3 THEN 'queue:queued' WHEN 4 THEN 'queue:processing' WHEN 5 THEN 'queue:completed' WHEN 6 THEN 'queue:error' ELSE 'queue:changed' END;v_entity_id:=NEW.queue_items_id::text;
 ELSIF TG_TABLE_NAME='sents' THEN v_lead:=NEW.leads_id;v_org:=NEW.organizations_id;v_event:=CASE WHEN NEW.sents_sent_at IS NOT NULL THEN 'dispatch:sent' WHEN NEW.status_id=6 THEN 'dispatch:error' ELSE 'dispatch:changed' END;v_channel:=CASE NEW.channels_id WHEN 1 THEN 'whatsapp' WHEN 2 THEN 'instagram' ELSE NULL END;v_entity_id:=NEW.sents_id::text;
 ELSIF TG_TABLE_NAME='conversation_messages' THEN v_lead:=NEW.leads_id;v_org:=NEW.organizations_id;v_event:=CASE WHEN NEW.direction='inbound' THEN 'conversation:inbound' ELSE 'conversation:outbound' END;v_channel:='whatsapp';v_entity_id:=NEW.conversation_messages_id::text;
 END IF;
 IF v_lead IS NOT NULL AND v_org IS NOT NULL THEN INSERT INTO public.lead_lifecycle_events(organizations_id,leads_id,event_type,channel,entity_type,entity_id,payload) VALUES(v_org,v_lead,v_event,v_channel,TG_TABLE_NAME,v_entity_id,to_jsonb(NEW));END IF;
 RETURN NEW;
END; $$;
DROP TRIGGER IF EXISTS lead_lifecycle_leads ON public.leads;CREATE TRIGGER lead_lifecycle_leads AFTER INSERT OR UPDATE OF lead_status_id,channels_id ON public.leads FOR EACH ROW EXECUTE FUNCTION public.record_lead_lifecycle_event();
DROP TRIGGER IF EXISTS lead_lifecycle_queue_items ON public.queue_items;CREATE TRIGGER lead_lifecycle_queue_items AFTER INSERT OR UPDATE OF status_id ON public.queue_items FOR EACH ROW EXECUTE FUNCTION public.record_lead_lifecycle_event();
DROP TRIGGER IF EXISTS lead_lifecycle_sents ON public.sents;CREATE TRIGGER lead_lifecycle_sents AFTER INSERT OR UPDATE OF status_id,sents_sent_at ON public.sents FOR EACH ROW EXECUTE FUNCTION public.record_lead_lifecycle_event();
DROP TRIGGER IF EXISTS lead_lifecycle_conversation_messages ON public.conversation_messages;CREATE TRIGGER lead_lifecycle_conversation_messages AFTER INSERT ON public.conversation_messages FOR EACH ROW WHEN(NEW.leads_id IS NOT NULL) EXECUTE FUNCTION public.record_lead_lifecycle_event();

COMMIT;
