BEGIN;

-- ETAPA 15 — homologação final, readiness verificável e promoção Stable.

DO $stage_preflight$
DECLARE v_missing text[]:=ARRAY[]::text[]; v_name text;
BEGIN
  FOREACH v_name IN ARRAY ARRAY['platform_release_channels','lead_lifecycle_events'] LOOP IF to_regclass('public.'||v_name) IS NULL THEN v_missing:=array_append(v_missing,'table:'||v_name);END IF;END LOOP;
  FOREACH v_name IN ARRAY ARRAY['platform_release_matrix'] LOOP IF NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname=v_name) THEN v_missing:=array_append(v_missing,'function:'||v_name);END IF;END LOOP;
  IF cardinality(v_missing)>0 THEN RAISE EXCEPTION 'stage_preflight_failed:%',array_to_string(v_missing,',');END IF;
END
$stage_preflight$;

CREATE TABLE IF NOT EXISTS public.production_homologation_runs (
  production_homologation_runs_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organizations_id bigint NOT NULL REFERENCES public.organizations(organizations_id) ON DELETE CASCADE,
  started_by_member_id bigint REFERENCES public.organization_members(organization_members_id) ON DELETE SET NULL,
  release_version text NOT NULL,
  status text NOT NULL DEFAULT 'running' CHECK(status IN ('running','passed','failed','cancelled')),
  started_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  notes text,
  UNIQUE(organizations_id,production_homologation_runs_id)
);
CREATE INDEX IF NOT EXISTS production_homologation_runs_org_idx ON public.production_homologation_runs(organizations_id,started_at DESC);

CREATE TABLE IF NOT EXISTS public.production_homologation_checks (
  production_homologation_checks_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizations_id bigint NOT NULL REFERENCES public.organizations(organizations_id) ON DELETE CASCADE,
  production_homologation_runs_id uuid NOT NULL REFERENCES public.production_homologation_runs(production_homologation_runs_id) ON DELETE CASCADE,
  check_key text NOT NULL,
  section text NOT NULL,
  label text NOT NULL,
  required boolean NOT NULL DEFAULT true,
  status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','passed','failed','not_applicable')),
  evidence text,
  checked_by_member_id bigint REFERENCES public.organization_members(organization_members_id) ON DELETE SET NULL,
  checked_at timestamptz,
  sort_order integer NOT NULL DEFAULT 0,
  UNIQUE(production_homologation_runs_id,check_key)
);
CREATE INDEX IF NOT EXISTS production_homologation_checks_run_idx ON public.production_homologation_checks(organizations_id,production_homologation_runs_id,sort_order);

ALTER TABLE public.production_homologation_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.production_homologation_checks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS production_homologation_runs_org_select ON public.production_homologation_runs;
CREATE POLICY production_homologation_runs_org_select ON public.production_homologation_runs FOR SELECT TO authenticated USING(organizations_id=public.current_organization_id() AND public.has_organization_permission('monitoring.view'));
DROP POLICY IF EXISTS production_homologation_checks_org_select ON public.production_homologation_checks;
CREATE POLICY production_homologation_checks_org_select ON public.production_homologation_checks FOR SELECT TO authenticated USING(organizations_id=public.current_organization_id() AND public.has_organization_permission('monitoring.view'));
REVOKE INSERT,UPDATE,DELETE ON public.production_homologation_runs FROM anon,authenticated;
REVOKE INSERT,UPDATE,DELETE ON public.production_homologation_checks FROM anon,authenticated;
GRANT SELECT ON public.production_homologation_runs,public.production_homologation_checks TO authenticated;
GRANT ALL ON public.production_homologation_runs,public.production_homologation_checks TO service_role;

CREATE OR REPLACE FUNCTION public.start_production_homologation(p_notes text DEFAULT NULL)
RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE v_org bigint:=public.current_organization_id();v_member bigint:=public.current_organization_member_id();v_run uuid:=gen_random_uuid();
BEGIN
 PERFORM public.require_organization_permission('monitoring.manage');
 INSERT INTO public.production_homologation_runs(production_homologation_runs_id,organizations_id,started_by_member_id,release_version,notes) VALUES(v_run,v_org,v_member,'2.4.0',nullif(trim(coalesce(p_notes,'')),''));
 INSERT INTO public.production_homologation_checks(organizations_id,production_homologation_runs_id,check_key,section,label,sort_order) VALUES
 (v_org,v_run,'organization_isolation','Organizações','Isolamento entre organizações e permissões/RBAC validado',10),
 (v_org,v_run,'capture_pairing','Vinsansi Captura','Pairing por organização, configuração central e heartbeat funcionando',20),
 (v_org,v_run,'capture_resume','Vinsansi Captura','Captura real pausa/retoma sem duplicar e importa incrementalmente',30),
 (v_org,v_run,'capture_dedup','Vinsansi Captura','Duplicados e suprimidos são bloqueados antes da reentrada',40),
 (v_org,v_run,'instagram_pairing','Vinsansi Instagram','Perfil vinculado à organização e fila canônica carregada',50),
 (v_org,v_run,'instagram_resume','Vinsansi Instagram','Pausa/restart continua do checkpoint sem repetir DM',60),
 (v_org,v_run,'instagram_limits','Vinsansi Instagram','Limites, janela e capacidade por perfil respeitados',70),
 (v_org,v_run,'permanent_memory','Base Permanente','Uma identidade comercial concentra histórico, canais e resultado',80),
 (v_org,v_run,'suppression_reentry','Base Permanente','Supressão e cooldown de reentrada validados',90),
 (v_org,v_run,'whatsapp_text','WhatsApp','Envio/recebimento texto, realtime e status entregue/lido validados',100),
 (v_org,v_run,'whatsapp_identity','WhatsApp','LID/telefone converge no mesmo chip e não cruza chips',110),
 (v_org,v_run,'whatsapp_reconnect','WhatsApp','Reinício/reconexão preserva sessões e conversas',120),
 (v_org,v_run,'observability','Observabilidade','Heartbeats, alertas e diagnóstico detectam componente parado',130),
 (v_org,v_run,'recovery','Observabilidade','Recuperação controlada libera stale sem duplicar envio',140),
 (v_org,v_run,'audit_append_only','Auditoria','Auditoria append-only registra ator, organização, antes/depois',150),
 (v_org,v_run,'state_machine','Auditoria','Transições inválidas são bloqueadas pelo PostgreSQL',160),
 (v_org,v_run,'orchestration_e2e','Orquestração','Lead real percorre captura → validação → fila → envio → memória sem SQL manual',170),
 (v_org,v_run,'backup_restore','Portabilidade','Backup portátil restaurado em ambiente limpo com volumes e credenciais',180),
 (v_org,v_run,'clean_install','Portabilidade','Instalação do zero concluída sem editar código/usar terminal na operação normal',190),
 (v_org,v_run,'upgrade_existing','Portabilidade','Upgrade da base existente chega ao mesmo contrato do banco limpo',200),
 (v_org,v_run,'failure_matrix','Resiliência','Quedas de internet/processos/webhook repetido não corrompem estado nem duplicam envio',210),
 (v_org,v_run,'security_review','Segurança','RLS, service_role, secrets, CORS e rotas públicas revisados',220),
 (v_org,v_run,'performance','Performance','Volume realista de leads, filas, conversas e auditoria permanece operacional',230);
 PERFORM public.append_audit_event('production','start_homologation','production_homologation_run',v_run::text,NULL,NULL,NULL,NULL,NULL,NULL,jsonb_build_object('release','2.4.0'),NULL);
 RETURN v_run;
END; $$;
GRANT EXECUTE ON FUNCTION public.start_production_homologation(text) TO authenticated;

CREATE OR REPLACE FUNCTION public.set_production_homologation_check(p_run_id uuid,p_check_key text,p_status text,p_evidence text DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE v_org bigint:=public.current_organization_id();v_member bigint:=public.current_organization_member_id();v_status text:=lower(trim(p_status));v_required_pending integer;v_required_failed integer;
BEGIN
 PERFORM public.require_organization_permission('monitoring.manage');
 IF v_status NOT IN ('pending','passed','failed','not_applicable') THEN RAISE EXCEPTION 'homologation_status_invalid';END IF;
 UPDATE public.production_homologation_checks SET status=v_status,evidence=nullif(trim(coalesce(p_evidence,'')),''),checked_by_member_id=CASE WHEN v_status='pending' THEN NULL ELSE v_member END,checked_at=CASE WHEN v_status='pending' THEN NULL ELSE now() END WHERE organizations_id=v_org AND production_homologation_runs_id=p_run_id AND check_key=p_check_key;
 IF NOT FOUND THEN RAISE EXCEPTION 'homologation_check_not_found';END IF;
 SELECT count(*) FILTER(WHERE required AND status='pending'),count(*) FILTER(WHERE required AND status='failed') INTO v_required_pending,v_required_failed FROM public.production_homologation_checks WHERE organizations_id=v_org AND production_homologation_runs_id=p_run_id;
 UPDATE public.production_homologation_runs SET status=CASE WHEN v_required_failed>0 THEN 'failed' WHEN v_required_pending=0 THEN 'passed' ELSE 'running' END,completed_at=CASE WHEN v_required_pending=0 OR v_required_failed>0 THEN now() ELSE NULL END WHERE organizations_id=v_org AND production_homologation_runs_id=p_run_id;
 RETURN jsonb_build_object('runId',p_run_id,'pending',v_required_pending,'failed',v_required_failed,'status',CASE WHEN v_required_failed>0 THEN 'failed' WHEN v_required_pending=0 THEN 'passed' ELSE 'running' END);
END; $$;
GRANT EXECUTE ON FUNCTION public.set_production_homologation_check(uuid,text,text,text) TO authenticated;

CREATE OR REPLACE FUNCTION public.get_production_homologation_snapshot(p_run_id uuid DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path TO pg_catalog,public AS $$
DECLARE v_org bigint:=public.current_organization_id();v_run public.production_homologation_runs%ROWTYPE;v_checks jsonb;
BEGIN
 PERFORM public.require_organization_permission('monitoring.view');
 IF p_run_id IS NULL THEN SELECT * INTO v_run FROM public.production_homologation_runs WHERE organizations_id=v_org ORDER BY started_at DESC LIMIT 1;ELSE SELECT * INTO v_run FROM public.production_homologation_runs WHERE organizations_id=v_org AND production_homologation_runs_id=p_run_id;END IF;
 IF NOT FOUND THEN RETURN jsonb_build_object('run',NULL,'checks','[]'::jsonb);END IF;
 SELECT coalesce(jsonb_agg(jsonb_build_object('key',check_key,'section',section,'label',label,'required',required,'status',status,'evidence',evidence,'checkedAt',checked_at,'checkedByMemberId',checked_by_member_id) ORDER BY sort_order,production_homologation_checks_id),'[]'::jsonb) INTO v_checks FROM public.production_homologation_checks WHERE organizations_id=v_org AND production_homologation_runs_id=v_run.production_homologation_runs_id;
 RETURN jsonb_build_object('run',jsonb_build_object('id',v_run.production_homologation_runs_id,'releaseVersion',v_run.release_version,'status',v_run.status,'startedAt',v_run.started_at,'completedAt',v_run.completed_at,'notes',v_run.notes),'checks',v_checks);
END; $$;
GRANT EXECUTE ON FUNCTION public.get_production_homologation_snapshot(uuid) TO authenticated;

CREATE OR REPLACE FUNCTION public.platform_production_readiness()
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path TO pg_catalog,public AS $$
DECLARE v_org bigint:=public.current_organization_id();v_schema jsonb;v_health jsonb;v_release jsonb;v_critical integer;v_homologation jsonb;v_hstatus text;
BEGIN
 PERFORM public.require_organization_permission('monitoring.view');
 v_schema:=public.platform_schema_health();v_health:=public.get_operational_health();v_release:=public.platform_release_matrix();v_homologation:=public.get_production_homologation_snapshot(NULL);v_hstatus:=coalesce(v_homologation->'run'->>'status','not_started');
 SELECT count(*) INTO v_critical FROM public.operational_alerts WHERE organizations_id=v_org AND status<>'resolved' AND severity='critical';
 RETURN jsonb_build_object('ok',coalesce((v_schema->>'ok')::boolean,false) AND v_critical=0 AND v_hstatus='passed','schema',v_schema,'health',v_health,'releases',v_release,'homologation',v_homologation,'criticalAlerts',v_critical,'checkedAt',now());
END; $$;
GRANT EXECUTE ON FUNCTION public.platform_production_readiness() TO authenticated;

-- A Etapa 15 instala a homologação, mas NÃO promove Stable automaticamente.
-- A promoção só acontece depois de uma rodada obrigatória aprovada e readiness saudável.
UPDATE public.platform_release_channels
SET latest_version='2.4.0',
    release_channel='preview',
    update_required=CASE WHEN component_key='crm' THEN true ELSE update_required END,
    updated_at=now(),
    notes=CASE WHEN component_key='crm' THEN 'Release candidate 2.4.0 aguardando homologação final.' ELSE notes END
WHERE component_key='crm';

CREATE OR REPLACE FUNCTION public.promote_platform_stable_release()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO pg_catalog,public
AS $$
DECLARE
  v_org bigint:=public.current_organization_id();
  v_run public.production_homologation_runs%ROWTYPE;
  v_schema jsonb;
  v_critical integer:=0;
  v_release_key text:='stable-'||to_char(current_date,'YYYYMMDD');
BEGIN
  PERFORM public.require_organization_permission('monitoring.manage');
  IF NOT public.is_platform_owner(public.current_actor_user_id()) THEN RAISE EXCEPTION 'platform_owner_required_for_stable_promotion'; END IF;
  SELECT * INTO v_run
  FROM public.production_homologation_runs
  WHERE organizations_id=v_org
  ORDER BY started_at DESC
  LIMIT 1;
  IF NOT FOUND OR v_run.status<>'passed' THEN
    RAISE EXCEPTION 'production_homologation_not_passed';
  END IF;

  v_schema:=public.platform_schema_health();
  IF NOT coalesce((v_schema->>'ok')::boolean,false) THEN
    RAISE EXCEPTION 'platform_schema_not_ready';
  END IF;

  SELECT count(*) INTO v_critical
  FROM public.operational_alerts
  WHERE organizations_id=v_org
    AND status<>'resolved'
    AND severity='critical';
  IF v_critical>0 THEN
    RAISE EXCEPTION 'critical_operational_alerts:%',v_critical;
  END IF;

  UPDATE public.platform_release_channels
  SET stable_version=latest_version,
      release_channel='stable',
      update_required=false,
      updated_at=now()
  WHERE component_key IN ('manager','worker','capture','instagram','gateway','evolution');

  UPDATE public.platform_release_channels
  SET latest_version='2.4.0',
      minimum_supported_version='2.4.0',
      stable_version='2.4.0',
      release_channel='stable',
      update_required=false,
      updated_at=now(),
      notes='Vinsansi Studio Stable após homologação das Etapas 1–15.'
  WHERE component_key='crm';

  INSERT INTO public.platform_schema_releases(
    release_key,application_version,migration_count,base_schema_sha256,notes,
    schema_contract_version,minimum_application_version,is_stable,metadata
  ) VALUES(
    v_release_key,'2.4.0',21,encode(extensions.digest(v_release_key,'sha256'),'hex'),
    'Vinsansi Studio Stable — Etapas 1–15.','2026.08.24.15','2.4.0',true,
    jsonb_build_object('stages',jsonb_build_array(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15),'release','stable','textOnlyWhatsapp',true,'homologationRunId',v_run.production_homologation_runs_id,'organizationId',v_org)
  )
  ON CONFLICT(release_key) DO UPDATE
  SET application_version=excluded.application_version,
      migration_count=excluded.migration_count,
      base_schema_sha256=excluded.base_schema_sha256,
      notes=excluded.notes,
      schema_contract_version=excluded.schema_contract_version,
      minimum_application_version=excluded.minimum_application_version,
      is_stable=true,
      metadata=excluded.metadata,
      applied_at=now();

  PERFORM public.append_audit_event(
    'production','promote_stable_release','platform_schema_release',v_release_key,
    NULL,NULL,NULL,NULL,NULL,'Release promovida a Stable após homologação.',
    jsonb_build_object('release','2.4.0','run_id',v_run.production_homologation_runs_id,'organization_id',v_org),NULL
  );

  RETURN jsonb_build_object('ok',true,'release','2.4.0','releaseKey',v_release_key,'runId',v_run.production_homologation_runs_id,'promotedAt',now());
END;
$$;
GRANT EXECUTE ON FUNCTION public.promote_platform_stable_release() TO authenticated;

INSERT INTO public.platform_schema_contracts(schema_contract_version,application_version,required_tables,required_functions,retired_objects,notes)
VALUES('2026.08.24.15','2.4.0',
 ARRAY['organizations','organization_members','platform_tools','organization_tool_installations','tool_browser_pairings','leads','lead_identity_registry','contact_suppressions','queues','queue_items','sents','conversations','conversation_messages','capture_execution_events','instagram_queue_progress','permanent_records','permanent_record_events','platform_runtime_heartbeats','operational_alerts','recovery_requests','lead_orchestration_state','lead_lifecycle_events','platform_release_channels','production_homologation_runs','production_homologation_checks'],
 ARRAY['append_audit_event','service_capture_identity_gate','instagram_claim_queue_item_v2','commercial_reentry_decision','service_runtime_heartbeat','platform_schema_health','service_orchestrate_ready_leads','platform_component_compatibility','platform_release_matrix','platform_production_readiness','start_production_homologation','set_production_homologation_check','promote_platform_stable_release'],
 ARRAY['maps_extension_installations','maps_extension_pairings','instagram_claim_queue_item','instagram_update_queue_progress','get_operational_health_rbac_inner'],
 'Contrato final das Etapas 1–15. A promoção Stable depende de homologação aprovada; instalar esta migration sozinho não congela a release.')
ON CONFLICT(schema_contract_version) DO UPDATE SET application_version=excluded.application_version,required_tables=excluded.required_tables,required_functions=excluded.required_functions,retired_objects=excluded.retired_objects,notes=excluded.notes;

INSERT INTO public.platform_schema_releases(release_key,application_version,migration_count,base_schema_sha256,notes,schema_contract_version,minimum_application_version,is_stable,metadata)
VALUES('stage-15-homologation-20260824','2.4.0',21,encode(extensions.digest('stage-15-homologation-20260824','sha256'),'hex'),'Release candidate para homologação final das Etapas 1–15.','2026.08.24.15','2.4.0',false,jsonb_build_object('stages',jsonb_build_array(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15),'release','preview','textOnlyWhatsapp',true))
ON CONFLICT(release_key) DO UPDATE SET application_version=excluded.application_version,migration_count=excluded.migration_count,base_schema_sha256=excluded.base_schema_sha256,notes=excluded.notes,schema_contract_version=excluded.schema_contract_version,minimum_application_version=excluded.minimum_application_version,is_stable=false,metadata=excluded.metadata,applied_at=now();

COMMIT;
