-- R29 — nome alternativo, snapshots coerentes e reposição manual das filas.
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS leads_alternative_name text;
COMMENT ON COLUMN public.leads.leads_alternative_name IS 'Nome operacional opcional. Quando preenchido, substitui leads_name em templates/snapshots futuros sem apagar o nome original.';
ALTER TABLE public.leads DROP CONSTRAINT IF EXISTS leads_alternative_name_length_check;
ALTER TABLE public.leads ADD CONSTRAINT leads_alternative_name_length_check CHECK (leads_alternative_name IS NULL OR char_length(leads_alternative_name) <= 160);

CREATE OR REPLACE FUNCTION public.build_queue_item_payload_snapshot(p_users_id bigint,p_queues_id bigint,p_leads_id bigint,p_templates_id bigint,p_frozen_at timestamp with time zone DEFAULT now())
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'public','pg_temp' AS $function$
DECLARE v_lead public.leads%ROWTYPE;v_template public.templates%ROWTYPE;v_branch public.branches%ROWTYPE;v_channel_name text:='';v_template_channel text:='';v_template_type text:='';v_city text:='';v_state text:='';v_phone text:='';v_instagram text:='';v_site text:='';v_company_name text:='';v_media_name text:='';v_media_sha256 text:='';v_media_required boolean:=false;v_message_1 text:='';v_message_2 text:='';v_message_3 text:='';v_message_4 text:='';
BEGIN
 SELECT l.* INTO v_lead FROM public.leads l WHERE l.leads_id=p_leads_id AND l.users_id=p_users_id; IF NOT FOUND THEN RAISE EXCEPTION 'Não foi possível congelar o conteúdo: lead % não encontrado.',p_leads_id;END IF;
 SELECT t.* INTO v_template FROM public.templates t WHERE t.templates_id=p_templates_id AND t.users_id=p_users_id; IF NOT FOUND THEN RAISE EXCEPTION 'Não foi possível congelar o conteúdo: template % não encontrado.',p_templates_id;END IF;
 SELECT b.* INTO v_branch FROM public.branches b WHERE b.branches_id=v_lead.branches_id AND b.users_id=p_users_id;
 SELECT c.cities_name INTO v_city FROM public.cities c WHERE c.cities_id=v_lead.cities_id;
 SELECT coalesce(nullif(s.states_code,''),s.states_name) INTO v_state FROM public.states s WHERE s.states_id=v_lead.states_id;
 SELECT c.channels_name INTO v_channel_name FROM public.queues q JOIN public.channels c ON c.channels_id=q.channels_id WHERE q.queues_id=p_queues_id AND q.users_id=p_users_id;
 SELECT tc.template_channels_name,tt.template_types_name INTO v_template_channel,v_template_type FROM public.template_channels tc JOIN public.template_types tt ON tt.template_types_id=v_template.template_types_id AND tt.users_id=v_template.users_id WHERE tc.template_channels_id=v_template.template_channels_id AND tc.users_id=v_template.users_id;
 v_city:=coalesce(v_city,'');v_state:=coalesce(v_state,'');v_phone:=coalesce(v_lead.leads_phone,'');v_instagram:=coalesce(v_lead.leads_instagram,'');v_site:=coalesce(v_lead.leads_website,'');v_company_name:=coalesce(nullif(btrim(v_lead.leads_alternative_name),''),v_lead.leads_name,'');v_channel_name:=coalesce(v_channel_name,'');v_template_channel:=coalesce(v_template_channel,'');v_template_type:=coalesce(v_template_type,'');
 IF v_branch.branches_categories IS NOT NULL AND jsonb_typeof(v_branch.branches_categories)='object' THEN v_media_name:=trim(coalesce(v_branch.branches_categories->>'imageName',v_branch.branches_categories->>'image_name',v_branch.branches_categories->>'imagem',''));v_media_sha256:=lower(trim(coalesce(v_branch.branches_categories->>'imageSha256',v_branch.branches_categories->>'image_sha256',v_branch.branches_categories->>'sha256','')));v_media_required:=lower(trim(coalesce(v_branch.branches_categories->>'imageRequired',v_branch.branches_categories->>'image_required',CASE WHEN v_media_name<>'' THEN 'true' ELSE 'false' END))) IN('true','1','sim','yes','required','obrigatoria','obrigatório');END IF;
 v_message_1:=public.render_queue_snapshot_message(v_template.templates_message_1,v_company_name,v_branch.branches_name,v_city,v_state,v_phone,v_instagram,v_site);v_message_2:=public.render_queue_snapshot_message(v_template.templates_message_2,v_company_name,v_branch.branches_name,v_city,v_state,v_phone,v_instagram,v_site);v_message_3:=public.render_queue_snapshot_message(v_template.templates_message_3,v_company_name,v_branch.branches_name,v_city,v_state,v_phone,v_instagram,v_site);v_message_4:=public.render_queue_snapshot_message(v_template.templates_message_4,v_company_name,v_branch.branches_name,v_city,v_state,v_phone,v_instagram,v_site);
 RETURN jsonb_build_object('schema_version',1,'frozen_at',coalesce(p_frozen_at,now()),'channel',v_channel_name,'recipient',jsonb_build_object('phone',regexp_replace(v_phone,'[^0-9]+','','g'),'instagram',v_instagram),'lead',jsonb_build_object('id',v_lead.leads_id,'company_name',v_company_name,'original_company_name',coalesce(v_lead.leads_name,''),'alternative_company_name',coalesce(v_lead.leads_alternative_name,''),'branch_id',v_lead.branches_id,'branch_name',coalesce(v_branch.branches_name,''),'city',v_city,'state',v_state,'phone',v_phone,'instagram',v_instagram,'site',v_site,'maps_url',coalesce(v_lead.leads_maps,'')),'variables',jsonb_build_object('EMPRESA',v_company_name,'NOME_EMPRESA',v_company_name,'RAMO',coalesce(v_branch.branches_name,''),'CIDADE',v_city,'ESTADO',v_state,'TELEFONE',v_phone,'WHATSAPP',v_phone,'INSTAGRAM',v_instagram,'SITE',v_site),'template',jsonb_build_object('id',v_template.templates_id,'name',v_template.templates_name,'channel',v_template_channel,'type',v_template_type,'updated_at',v_template.templates_updated_at,'raw_hash',encode(extensions.digest(convert_to(concat_ws(E'\n',v_template.templates_message_1,v_template.templates_message_2,v_template.templates_message_3,v_template.templates_message_4),'UTF8'),'sha256'),'hex')),'messages',jsonb_build_object('message_1',v_message_1,'message_2',v_message_2,'message_3',v_message_3,'message_4',v_message_4),'media',jsonb_build_object('required',v_media_required,'name',v_media_name,'sha256',v_media_sha256,'branch_updated_at',v_branch.branches_updated_at,'source',CASE WHEN lower(regexp_replace(public.unaccent(trim(v_channel_name)),'[^a-z0-9]+','','g'))='instagram' THEN 'instagram-extension-local' ELSE 'worker-images' END));
END;$function$;

CREATE OR REPLACE FUNCTION public.apply_queue_item_payload_snapshot() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','pg_temp' AS $function$
DECLARE v_message_number integer;v_message text;v_allow_refresh boolean:=coalesce(current_setting('vinsansi.allow_queue_snapshot_refresh',true),'')='on';
BEGIN
 IF TG_OP='UPDATE' THEN IF NEW.leads_id IS DISTINCT FROM OLD.leads_id OR NEW.templates_id IS DISTINCT FROM OLD.templates_id OR NEW.queues_id IS DISTINCT FROM OLD.queues_id THEN RAISE EXCEPTION 'Lead, template e fila de um item preparado são imutáveis. Crie um novo item.' USING ERRCODE='23514';END IF;IF(NEW.queue_items_payload_snapshot IS DISTINCT FROM OLD.queue_items_payload_snapshot OR NEW.queue_items_payload_hash IS DISTINCT FROM OLD.queue_items_payload_hash OR NEW.queue_items_payload_created_at IS DISTINCT FROM OLD.queue_items_payload_created_at) AND NOT v_allow_refresh THEN RAISE EXCEPTION 'O conteúdo congelado do item não pode ser alterado.' USING ERRCODE='23514';END IF;RETURN NEW;END IF;
 IF NEW.templates_id IS NULL THEN RAISE EXCEPTION 'Todo item de fila precisa de um template para congelar o conteúdo.' USING ERRCODE='23514';END IF;
 NEW.queue_items_payload_created_at:=coalesce(NEW.queue_items_created_at,now());NEW.queue_items_payload_snapshot:=public.build_queue_item_payload_snapshot(NEW.users_id,NEW.queues_id,NEW.leads_id,NEW.templates_id,NEW.queue_items_payload_created_at);
 FOR v_message_number IN 1..4 LOOP v_message:=trim(coalesce(NEW.queue_items_payload_snapshot#>>ARRAY['messages',format('message_%s',v_message_number)],''));IF v_message='' THEN RAISE EXCEPTION 'O snapshot precisa conter as quatro mensagens. Mensagem % vazia.',v_message_number USING ERRCODE='23514';END IF;END LOOP;
 NEW.queue_items_payload_hash:=encode(extensions.digest(convert_to(NEW.queue_items_payload_snapshot::text,'UTF8'),'sha256'),'hex');RETURN NEW;
END;$function$;

CREATE OR REPLACE FUNCTION public.update_lead_alternative_name(p_lead_id bigint,p_alternative_name text,p_queue_item_id bigint DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public,extensions AS $function$
DECLARE v_org bigint:=public.current_organization_id();v_user bigint:=public.ensure_current_user();v_alt text:=nullif(btrim(coalesce(p_alternative_name,'')),'');v_item public.queue_items%ROWTYPE;v_snapshot jsonb;v_frozen timestamptz:=now();
BEGIN
 PERFORM public.require_organization_permission('leads.edit');IF p_lead_id IS NULL OR p_lead_id<=0 THEN RAISE EXCEPTION 'lead_id_invalid';END IF;IF v_alt IS NOT NULL AND char_length(v_alt)>160 THEN RAISE EXCEPTION 'alternative_name_too_long';END IF;
 UPDATE public.leads SET leads_alternative_name=v_alt,leads_updated_at=now() WHERE leads_id=p_lead_id AND organizations_id=v_org AND users_id=v_user;IF NOT FOUND THEN RAISE EXCEPTION 'lead_not_found_or_forbidden';END IF;
 IF p_queue_item_id IS NOT NULL THEN SELECT qi.* INTO v_item FROM public.queue_items qi WHERE qi.queue_items_id=p_queue_item_id AND qi.organizations_id=v_org AND qi.users_id=v_user AND qi.leads_id=p_lead_id FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'queue_item_not_found_or_forbidden';END IF;IF v_item.queue_items_started_at IS NOT NULL OR v_item.queue_items_finished_at IS NOT NULL THEN RAISE EXCEPTION 'queue_item_already_started';END IF;IF v_item.templates_id IS NULL THEN RAISE EXCEPTION 'queue_item_template_required';END IF;v_snapshot:=public.build_queue_item_payload_snapshot(v_item.users_id,v_item.queues_id,v_item.leads_id,v_item.templates_id,v_frozen);PERFORM set_config('vinsansi.allow_queue_snapshot_refresh','on',true);UPDATE public.queue_items SET queue_items_payload_snapshot=v_snapshot,queue_items_payload_hash=encode(extensions.digest(convert_to(v_snapshot::text,'UTF8'),'sha256'),'hex'),queue_items_payload_created_at=v_frozen,queue_items_updated_at=now() WHERE queue_items_id=v_item.queue_items_id AND organizations_id=v_org;PERFORM set_config('vinsansi.allow_queue_snapshot_refresh','off',true);END IF;
 RETURN jsonb_build_object('leadId',p_lead_id,'alternativeName',coalesce(v_alt,''),'queueItemId',p_queue_item_id,'snapshotRefreshed',p_queue_item_id IS NOT NULL);
END;$function$;
REVOKE ALL ON FUNCTION public.update_lead_alternative_name(bigint,text,bigint) FROM PUBLIC,anon;GRANT EXECUTE ON FUNCTION public.update_lead_alternative_name(bigint,text,bigint) TO authenticated;

CREATE OR REPLACE FUNCTION public.list_open_queue_review(p_channel text) RETURNS TABLE(batch_id bigint,review_item_id bigint,channel_key text,resource_id bigint,scheduled_date date,target_count integer,lead_id bigint,"position" integer,company text,branch_id bigint,branch_name text,city text,state text,phone text,whatsapp text,instagram text,website text,rating numeric,reviews integer) LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path TO pg_catalog,public AS $function$
DECLARE v_org bigint:=public.current_organization_id();v_user bigint:=public.ensure_current_user();v_channel text:=lower(trim(coalesce(p_channel,'')));
BEGIN PERFORM public.require_organization_permission('queues.view');RETURN QUERY SELECT b.queue_review_batches_id,i.queue_review_items_id,b.channel_key,b.resource_id,b.scheduled_date,b.target_count,l.leads_id,row_number()OVER(PARTITION BY b.queue_review_batches_id ORDER BY i.review_position,i.queue_review_items_id)::integer,coalesce(nullif(btrim(l.leads_alternative_name),''),l.leads_name),l.branches_id,coalesce(br.branches_name,''),coalesce(ci.cities_name,''),coalesce(st.states_code,st.states_name,''),coalesce(l.leads_phone,''),coalesce(l.leads_whatsapp,''),coalesce(l.leads_instagram,''),coalesce(l.leads_website,''),coalesce(l.leads_score,0)::numeric,coalesce(l.leads_reviews_count,0)::integer FROM public.queue_review_batches b JOIN public.queue_review_items i ON i.queue_review_batches_id=b.queue_review_batches_id AND i.review_status='open' JOIN public.leads l ON l.leads_id=i.leads_id AND l.organizations_id=b.organizations_id LEFT JOIN public.branches br ON br.branches_id=l.branches_id LEFT JOIN public.cities ci ON ci.cities_id=l.cities_id LEFT JOIN public.states st ON st.states_id=l.states_id WHERE b.organizations_id=v_org AND b.users_id=v_user AND b.review_status='open' AND b.channel_key=v_channel ORDER BY b.created_at,b.queue_review_batches_id,i.review_position;END;$function$;
REVOKE ALL ON FUNCTION public.list_open_queue_review(text) FROM PUBLIC,anon;GRANT EXECUTE ON FUNCTION public.list_open_queue_review(text) TO authenticated;
