\set ON_ERROR_STOP on

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA IF NOT EXISTS auth;
DO $$ BEGIN CREATE ROLE anon; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE ROLE authenticated; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE ROLE service_role; EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE OR REPLACE FUNCTION auth.role() RETURNS text LANGUAGE sql STABLE AS
$$ SELECT coalesce(current_setting('app.auth_role',true),'authenticated') $$;
CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS
$$ SELECT '00000000-0000-0000-0000-000000000001'::uuid $$;

CREATE TABLE public.organizations(
  organizations_id bigint PRIMARY KEY,
  legacy_scope_users_id bigint NOT NULL,
  status_id bigint NOT NULL DEFAULT 1
);
CREATE TABLE public.organization_tools(
  organizations_id bigint NOT NULL,
  tool_id text NOT NULL,
  enabled boolean NOT NULL DEFAULT true,
  PRIMARY KEY(organizations_id,tool_id)
);
CREATE TABLE public.organization_tool_installations(
  organization_tool_installations_id uuid PRIMARY KEY,
  organizations_id bigint NOT NULL,
  tool_id text NOT NULL,
  registration_status text NOT NULL,
  last_seen_at timestamptz
);
CREATE TABLE public.organization_members(
  organization_members_id bigint PRIMARY KEY,
  organizations_id bigint NOT NULL,
  status_id bigint NOT NULL
);
CREATE TABLE public.socials(
  socials_id bigint PRIMARY KEY,
  organizations_id bigint NOT NULL,
  socials_username text,
  status_id bigint NOT NULL
);
CREATE TABLE public.leads(
  leads_id bigint PRIMARY KEY,
  organizations_id bigint NOT NULL,
  lead_status_id bigint NOT NULL,
  leads_instagram text,
  leads_updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.platform_runtime_heartbeats(
  platform_runtime_heartbeats_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizations_id bigint NOT NULL,
  component_type text NOT NULL,
  component_key text NOT NULL,
  component_version text,
  runtime_status text NOT NULL DEFAULT 'online',
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  last_meaningful_activity_at timestamptz,
  metrics jsonb NOT NULL DEFAULT '{}',
  metadata jsonb NOT NULL DEFAULT '{}',
  UNIQUE(organizations_id,component_type,component_key)
);
CREATE TABLE public.worker_heartbeats(
  worker_heartbeats_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizations_id bigint NOT NULL,
  worker_id text NOT NULL,
  worker_version text NOT NULL,
  worker_status text NOT NULL DEFAULT 'online',
  started_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  metrics jsonb NOT NULL DEFAULT '{}',
  metadata jsonb NOT NULL DEFAULT '{}',
  UNIQUE(organizations_id,worker_id)
);
CREATE TABLE public.operational_alerts(
  operational_alerts_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id bigint NOT NULL,
  organizations_id bigint NOT NULL,
  alert_key text NOT NULL,
  source text NOT NULL,
  severity text NOT NULL,
  status text NOT NULL DEFAULT 'open',
  title text NOT NULL,
  message text NOT NULL,
  entity_type text,
  entity_id text,
  metadata jsonb NOT NULL DEFAULT '{}',
  first_detected_at timestamptz NOT NULL DEFAULT now(),
  last_detected_at timestamptz NOT NULL DEFAULT now(),
  acknowledged_at timestamptz,
  resolved_at timestamptz,
  UNIQUE(organizations_id,alert_key)
);
CREATE TABLE public.recovery_requests(
  recovery_requests_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id bigint NOT NULL,
  organizations_id bigint NOT NULL,
  requested_by uuid,
  scope text NOT NULL DEFAULT 'all' CHECK(scope IN('all','whatsapp','instagram')),
  status text NOT NULL DEFAULT 'pending',
  worker_id text,
  result jsonb NOT NULL DEFAULT '{}',
  error_message text,
  requested_at timestamptz NOT NULL DEFAULT now(),
  started_at timestamptz,
  finished_at timestamptz
);
CREATE TABLE public.queue_items(
  queue_items_id bigint PRIMARY KEY,
  users_id bigint NOT NULL,
  organizations_id bigint NOT NULL,
  leads_id bigint NOT NULL,
  queues_id bigint NOT NULL DEFAULT 1,
  socials_id bigint,
  templates_id bigint,
  status_id bigint NOT NULL,
  dispatched_by_member_id bigint,
  queue_items_started_at timestamptz,
  queue_items_finished_at timestamptz,
  queue_items_updated_at timestamptz NOT NULL DEFAULT now(),
  queue_items_error_message text,
  queue_items_payload_snapshot jsonb,
  queue_items_payload_hash text,
  queue_items_payload_created_at timestamptz
);
CREATE TABLE public.queue_item_dispatch_parts(
  queue_item_dispatch_parts_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id bigint NOT NULL,
  organizations_id bigint NOT NULL,
  queue_items_id bigint NOT NULL,
  queue_item_dispatch_parts_key text NOT NULL,
  queue_item_dispatch_parts_state text NOT NULL,
  queue_item_dispatch_parts_claim_token uuid,
  queue_item_dispatch_parts_error_message text,
  queue_item_dispatch_parts_updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(queue_items_id,queue_item_dispatch_parts_key)
);
CREATE TABLE public.worker_batches(
  worker_batches_id bigint PRIMARY KEY,
  organizations_id bigint NOT NULL,
  status_id bigint NOT NULL,
  worker_batches_next_run_at timestamptz,
  worker_batches_started_at timestamptz,
  worker_batches_heartbeat_at timestamptz,
  worker_batches_created_at timestamptz NOT NULL DEFAULT now(),
  worker_batches_updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.worker_batch_items(
  worker_batch_items_id bigint PRIMARY KEY,
  organizations_id bigint NOT NULL,
  queue_items_id bigint NOT NULL,
  status_id bigint NOT NULL,
  worker_batch_items_started_at timestamptz,
  worker_batch_items_finished_at timestamptz,
  worker_batch_items_error_message text,
  worker_batch_items_updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.instagram_queue_progress(
  instagram_queue_progress_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id bigint NOT NULL,
  organizations_id bigint NOT NULL,
  queue_items_id bigint NOT NULL,
  socials_id bigint NOT NULL,
  step text NOT NULL DEFAULT 'queued',
  canonical_step text,
  claim_token uuid,
  claimed_by text,
  attempts integer NOT NULL DEFAULT 0,
  last_heartbeat_at timestamptz,
  started_at timestamptz,
  finished_at timestamptz,
  error_message text,
  metadata jsonb NOT NULL DEFAULT '{}',
  organization_tool_installations_id uuid,
  dispatched_by_member_id bigint,
  profile_username text,
  frozen_payload_hash text,
  instagram_queue_progress_updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT instagram_queue_progress_queue_items_id_key UNIQUE(queue_items_id)
);
CREATE TABLE public.instagram_dispatch_events(
  instagram_dispatch_events_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id bigint NOT NULL,
  organizations_id bigint NOT NULL,
  queue_items_id bigint NOT NULL,
  socials_id bigint,
  from_step text,
  to_step text NOT NULL,
  claim_token uuid,
  actor text,
  message text,
  metadata jsonb NOT NULL DEFAULT '{}',
  organization_tool_installations_id uuid,
  organization_members_id bigint,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.instagram_profile_runtime(
  instagram_profile_runtime_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizations_id bigint NOT NULL,
  socials_id bigint NOT NULL,
  organization_tool_installations_id uuid,
  profile_username text NOT NULL,
  operational_date date NOT NULL,
  claimed_count integer NOT NULL DEFAULT 0,
  sent_count integer NOT NULL DEFAULT 0,
  invalid_count integer NOT NULL DEFAULT 0,
  error_count integer NOT NULL DEFAULT 0,
  last_claim_at timestamptz,
  last_send_at timestamptz,
  last_heartbeat_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(organizations_id,socials_id,operational_date)
);
CREATE TABLE public.sents(
  sents_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id bigint NOT NULL,
  organizations_id bigint NOT NULL,
  queue_items_id bigint,
  leads_id bigint,
  channels_id bigint,
  socials_id bigint,
  templates_id bigint,
  status_id bigint NOT NULL,
  sents_recipient text,
  sents_body text NOT NULL,
  sents_attempt integer NOT NULL DEFAULT 1,
  sents_sent_at timestamptz,
  sents_idempotency_key text,
  sents_payload_hash text,
  sent_by_member_id bigint,
  executed_by text NOT NULL DEFAULT 'system'
);
CREATE UNIQUE INDEX sents_idempotency_key_unique ON public.sents(sents_idempotency_key)
WHERE sents_idempotency_key IS NOT NULL;

CREATE OR REPLACE FUNCTION public.current_organization_id() RETURNS bigint LANGUAGE sql STABLE AS
$$ SELECT current_setting('app.organization_id')::bigint $$;
CREATE OR REPLACE FUNCTION public.ensure_current_user() RETURNS bigint LANGUAGE sql STABLE AS
$$ SELECT legacy_scope_users_id FROM public.organizations WHERE organizations_id=public.current_organization_id() $$;
CREATE OR REPLACE FUNCTION public.require_organization_permission(text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN END $$;
CREATE OR REPLACE FUNCTION public.append_audit_event(text,text,text,text,bigint,bigint,bigint,bigint,bigint,text,jsonb,bigint) RETURNS bigint LANGUAGE sql AS $$ SELECT 1::bigint $$;
CREATE OR REPLACE FUNCTION public.instagram_canonical_step(p_step text) RETURNS text LANGUAGE sql IMMUTABLE AS $$
 SELECT CASE lower(trim(coalesce(p_step,'')))
  WHEN 'profile_opened' THEN 'opening_profile' WHEN 'opening_profile' THEN 'opening_profile'
  WHEN 'dm_opened' THEN 'opening_dm' WHEN 'opening_dm' THEN 'opening_dm'
  WHEN 'messages_sending' THEN 'sending' WHEN 'media_sending' THEN 'sending' WHEN 'sending' THEN 'sending'
  WHEN 'sent' THEN 'completed' WHEN 'completed' THEN 'completed'
  WHEN 'invalid' THEN 'error' ELSE lower(trim(coalesce(p_step,''))) END
$$;
CREATE OR REPLACE FUNCTION public.instagram_profile_capacity(bigint,bigint,timestamptz) RETURNS jsonb LANGUAGE sql STABLE AS
$$ SELECT jsonb_build_object('remaining',100) $$;

CREATE OR REPLACE FUNCTION public.service_runtime_heartbeat(
  p_organizations_id bigint,p_component_type text,p_component_key text,p_component_version text DEFAULT NULL,
  p_status text DEFAULT 'online',p_installation_id uuid DEFAULT NULL,p_metrics jsonb DEFAULT '{}',
  p_metadata jsonb DEFAULT '{}',p_meaningful_activity boolean DEFAULT false
) RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE v_id bigint;
BEGIN
  IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role_required'; END IF;
  INSERT INTO public.platform_runtime_heartbeats(
    organizations_id,component_type,component_key,component_version,runtime_status,last_meaningful_activity_at,metrics,metadata
  ) VALUES(
    p_organizations_id,p_component_type,p_component_key,p_component_version,p_status,
    CASE WHEN p_meaningful_activity THEN now() ELSE NULL END,coalesce(p_metrics,'{}'),coalesce(p_metadata,'{}')
  ) ON CONFLICT(organizations_id,component_type,component_key) DO UPDATE SET
    component_version=excluded.component_version,runtime_status=excluded.runtime_status,last_seen_at=now(),
    metrics=excluded.metrics,metadata=excluded.metadata
  RETURNING platform_runtime_heartbeats_id INTO v_id;
  RETURN v_id;
END $$;
CREATE OR REPLACE FUNCTION public.service_worker_heartbeat(
  p_organizations_id bigint,p_worker_id text,p_worker_version text,p_status text DEFAULT 'online',
  p_metrics jsonb DEFAULT '{}',p_metadata jsonb DEFAULT '{}'
) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
BEGIN
  IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role_required'; END IF;
  INSERT INTO public.worker_heartbeats(organizations_id,worker_id,worker_version,worker_status,metrics,metadata)
  VALUES(p_organizations_id,p_worker_id,p_worker_version,p_status,p_metrics,p_metadata)
  ON CONFLICT(organizations_id,worker_id) DO UPDATE SET worker_version=excluded.worker_version,
    worker_status=excluded.worker_status,last_seen_at=now(),metrics=excluded.metrics,metadata=excluded.metadata;
  PERFORM public.service_runtime_heartbeat(p_organizations_id,'worker',p_worker_id,p_worker_version,p_status,NULL,p_metrics,p_metadata,false);
END $$;
CREATE OR REPLACE FUNCTION public.service_claim_recovery_request(p_organizations_id bigint,p_worker_id text)
RETURNS TABLE(recovery_requests_id bigint,organizations_id bigint,users_id bigint,scope text)
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE v_id bigint;
BEGIN
  IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role_required'; END IF;
  SELECT r.recovery_requests_id INTO v_id FROM public.recovery_requests r
  WHERE r.organizations_id=p_organizations_id AND r.status='pending'
  ORDER BY r.requested_at FOR UPDATE SKIP LOCKED LIMIT 1;
  IF v_id IS NULL THEN RETURN; END IF;
  UPDATE public.recovery_requests SET status='running',worker_id=p_worker_id,started_at=now()
  WHERE public.recovery_requests.recovery_requests_id=v_id;
  RETURN QUERY SELECT r.recovery_requests_id,r.organizations_id,r.users_id,r.scope
  FROM public.recovery_requests r WHERE r.recovery_requests_id=v_id;
END $$;
CREATE OR REPLACE FUNCTION public.service_complete_recovery_request(
  p_organizations_id bigint,p_request_id bigint,p_result jsonb,p_error text DEFAULT NULL
) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
BEGIN
  IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role_required'; END IF;
  UPDATE public.recovery_requests SET status=CASE WHEN p_error IS NULL THEN 'completed' ELSE 'failed' END,
    result=coalesce(p_result,'{}'),error_message=p_error,finished_at=now()
  WHERE recovery_requests_id=p_request_id AND organizations_id=p_organizations_id AND status='running';
END $$;

GRANT USAGE ON SCHEMA public TO authenticated,service_role;
