import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import { organizationScopedAuthHeaders, resolveOrganizationContext } from '../../organization/context.js';
type ApiRequest = { method?: string; body?: unknown; headers?: Record<string, string | string[] | undefined> };
type ApiResponse = { status(code: number): ApiResponse; json(body: unknown): void; setHeader(name: string, value: string): void };
declare const process: { env: Record<string, string | undefined> };
export const maxDuration = 60;
function envAny(...names: string[]) { for (const name of names) { const value = process.env[name]; if (String(value ?? '').trim()) return String(value).trim(); } return ''; }
function header(req: ApiRequest, name: string) { const key = Object.keys(req.headers ?? {}).find((item) => item.toLowerCase() === name.toLowerCase()); const value = key ? req.headers?.[key] : undefined; return Array.isArray(value) ? String(value[0] ?? '') : String(value ?? ''); }
function bearer(req: ApiRequest) { return header(req, 'authorization').match(/^Bearer\s+(.+)$/i)?.[1]?.trim() ?? ''; }
function send(res: ApiResponse, status: number, payload: unknown) { res.setHeader('Cache-Control', 'no-store'); return res.status(status).json(payload); }
async function auth(req: ApiRequest): Promise<{ client: SupabaseClient; userId: number }> { const token = bearer(req); const url = envAny('SUPABASE_URL','VITE_SUPABASE_URL'); const key = envAny('SUPABASE_ANON_KEY','SUPABASE_PUBLISHABLE_KEY','VITE_SUPABASE_PUBLISHABLE_KEY'); if (!token) throw new Error('auth_required'); if (!url || !key) throw new Error('supabase_auth_backend_not_configured'); const client = createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false},global:{headers:organizationScopedAuthHeaders(token,req.headers)}}); const a=await client.auth.getUser(token); if(a.error||!a.data.user) throw new Error('auth_invalid'); const organization=await resolveOrganizationContext(client); return {client,userId:organization.scopeUsersId}; }
export default async function handler(req:ApiRequest,res:ApiResponse){ if(req.method!=='POST') return send(res,405,{ok:false,error:'method_not_allowed'}); try{ await auth(req); return send(res,410,{ok:false,error:'whatsapp_direct_dispatch_discontinued',message:'O disparo direto do WhatsApp foi descontinuado. Use o fluxo persistente em /api/whatsapp/batch.'}); }catch(error){ const message=error instanceof Error?error.message:'worker_dispatch_proxy_error'; const status=message.includes('auth_')?401:message.includes('not_available')?403:message.includes('required')?400:502; return send(res,status,{ok:false,error:message,message}); } }
