-- Lead Certo V3: contrato canonico de persistencia.
-- Execute este arquivo UMA vez no SQL Editor do Supabase antes de publicar o frontend V3.
-- É autocontido: cria as tabelas canônicas ausentes, preserva tabelas antigas e copia dados legados quando existirem.

create extension if not exists pgcrypto;


-- Base canônica autocontida. Necessária quando a migração é executada em um projeto Supabase novo
-- ou em um ambiente legado que ainda não possui todas as tabelas principais.
create table if not exists public.app_settings (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chips (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  status text,
  active boolean,
  kind text default 'chips',
  channel text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.branches (
  id bigint generated by default as identity primary key,
  slug text unique,
  name text,
  image_name text,
  data jsonb not null default '{}'::jsonb,
  status text,
  active boolean,
  kind text default 'branches',
  channel text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.templates (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  status text,
  active boolean,
  kind text default 'templates',
  channel text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.leads (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  status text,
  active boolean,
  kind text,
  channel text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pre_send_leads (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  status text,
  active boolean,
  kind text,
  channel text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.whatsapp_queue_items (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  status text,
  active boolean,
  kind text,
  channel text default 'whatsapp',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.instagram_queue_items (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  status text,
  active boolean,
  kind text,
  channel text default 'instagram',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.base_permanente (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  status text,
  active boolean,
  kind text,
  channel text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sent_contacts (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  normalized_phone text,
  site_normalized text,
  instagram_username text,
  maps_url text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lead_events (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  source text,
  action text,
  channel text,
  status text,
  active boolean,
  kind text,
  lead_id text,
  queue_item_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Tabelas que nao existiam no schema anterior.
create table if not exists public.instagram_profiles (
  id text primary key,
  user_id uuid,
  username text,
  display_name text,
  active boolean not null default true,
  status text,
  daily_limit integer,
  blocks jsonb not null default '[]'::jsonb,
  block_size integer,
  interval_minutes integer,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.import_batches (
  id text primary key,
  user_id uuid,
  source text,
  quantity_total integer not null default 0,
  quantity_created integer not null default 0,
  quantity_blocked integer not null default 0,
  quantity_duplicate integer not null default 0,
  raw_metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.lead_imports (
  id text primary key,
  user_id uuid,
  import_batch_id text,
  lead_id text,
  status text,
  reason text,
  original_payload jsonb not null default '{}'::jsonb,
  normalized_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.lead_registry (
  id text primary key,
  user_id uuid,
  lead_id text,
  identity_type text not null,
  identity_value text not null,
  source_table text,
  status text,
  company_name text,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  raw_payload jsonb not null default '{}'::jsonb
);

create table if not exists public.lead_dispatch_messages (
  id text primary key,
  user_id uuid,
  lead_id text,
  chip_id uuid,
  instance text,
  phone text,
  normalized_phone text,
  direction text,
  part text,
  body text,
  status text,
  response_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Tabelas canônicas existentes: expansão de colunas exigidas pelos repositórios.
alter table public.app_settings
  add column if not exists user_id uuid,
  add column if not exists key text,
  add column if not exists value jsonb not null default '{}'::jsonb;

alter table public.chips
  add column if not exists user_id uuid,
  add column if not exists instance text,
  add column if not exists label text,
  add column if not exists name text,
  add column if not exists phone text,
  add column if not exists base_url text,
  add column if not exists evolution_url text,
  add column if not exists url text,
  add column if not exists api_key text,
  add column if not exists daily_limit integer,
  add column if not exists block_size integer,
  add column if not exists interval_seconds integer,
  add column if not exists blocks jsonb not null default '[]'::jsonb,
  add column if not exists priority integer,
  add column if not exists start_time text,
  add column if not exists end_time text,
  add column if not exists paused boolean;

alter table public.branches
  add column if not exists user_id uuid,
  add column if not exists category text,
  add column if not exists subcategories jsonb not null default '[]'::jsonb,
  add column if not exists associated_categories jsonb not null default '[]'::jsonb,
  add column if not exists order_index integer,
  add column if not exists min_rating numeric,
  add column if not exists min_reviews integer;

alter table public.templates
  add column if not exists user_id uuid,
  add column if not exists branch_id bigint,
  add column if not exists ramo_id bigint,
  add column if not exists branch_name text,
  add column if not exists template_type text,
  add column if not exists type text,
  add column if not exists part_1 text,
  add column if not exists part_2 text;

alter table public.leads
  add column if not exists user_id uuid,
  add column if not exists company_name text,
  add column if not exists phone text,
  add column if not exists website text,
  add column if not exists instagram text,
  add column if not exists instagram_url text,
  add column if not exists instagram_username text,
  add column if not exists maps_url text,
  add column if not exists current_status text,
  add column if not exists pipeline_status text,
  add column if not exists lead_channel text,
  add column if not exists lead_type text,
  add column if not exists branch_id bigint,
  add column if not exists branch_name text,
  add column if not exists branch_slug text,
  add column if not exists parent_category text,
  add column if not exists category text,
  add column if not exists category_name text,
  add column if not exists city text,
  add column if not exists state text,
  add column if not exists rating numeric,
  add column if not exists reviews_count integer,
  add column if not exists has_own_site boolean,
  add column if not exists rejected_reason text,
  add column if not exists raw_payload jsonb not null default '{}'::jsonb,
  add column if not exists crm_data jsonb not null default '{}'::jsonb,
  add column if not exists original_destination text,
  add column if not exists destination text,
  add column if not exists destination_override text,
  add column if not exists send_instagram boolean not null default false,
  add column if not exists instagram_override_reason text,
  add column if not exists override_by text,
  add column if not exists override_at timestamptz;

alter table public.pre_send_leads
  add column if not exists user_id uuid,
  add column if not exists branch_id bigint,
  add column if not exists branch_name text;

alter table public.whatsapp_queue_items
  add column if not exists user_id uuid,
  add column if not exists lead_id text,
  add column if not exists source_pre_send_id text,
  add column if not exists scheduled_date text,
  add column if not exists position integer,
  add column if not exists chip_instance text,
  add column if not exists chip_label text,
  add column if not exists lead_type text,
  add column if not exists notes text,
  add column if not exists follow_status text,
  add column if not exists last_action_at timestamptz,
  add column if not exists raw_payload jsonb not null default '{}'::jsonb,
  add column if not exists validation_attempts integer not null default 0,
  add column if not exists validation_error text,
  add column if not exists validation_status text,
  add column if not exists batch_id text,
  add column if not exists batch_number integer,
  add column if not exists company_name text,
  add column if not exists phone text,
  add column if not exists normalized_phone text,
  add column if not exists phone_normalized text,
  add column if not exists branch_id bigint,
  add column if not exists branch_name text,
  add column if not exists branch_slug text,
  add column if not exists parent_category text,
  add column if not exists destination text,
  add column if not exists original_destination text,
  add column if not exists destination_override text,
  add column if not exists send_instagram boolean not null default false,
  add column if not exists instagram_url text,
  add column if not exists instagram_username text,
  add column if not exists instagram_override_reason text,
  add column if not exists override_by text,
  add column if not exists override_at timestamptz,
  add column if not exists chip_id uuid,
  add column if not exists template_id uuid,
  add column if not exists message_1 text,
  add column if not exists message_2 text,
  add column if not exists image_url text,
  add column if not exists image_id text,
  add column if not exists retry_count integer not null default 0,
  add column if not exists error_message text,
  add column if not exists sent_at timestamptz;

alter table public.instagram_queue_items
  add column if not exists user_id uuid,
  add column if not exists lead_id text,
  add column if not exists source_pre_send_id text,
  add column if not exists scheduled_date text,
  add column if not exists position integer,
  add column if not exists profile text,
  add column if not exists profile_id text,
  add column if not exists profile_username text,
  add column if not exists block_number integer,
  add column if not exists block_size integer,
  add column if not exists lead_type text,
  add column if not exists notes text,
  add column if not exists raw_payload jsonb not null default '{}'::jsonb,
  add column if not exists batch_id text,
  add column if not exists batch_number integer,
  add column if not exists company_name text,
  add column if not exists phone text,
  add column if not exists branch_id bigint,
  add column if not exists branch_name text,
  add column if not exists branch_slug text,
  add column if not exists parent_category text,
  add column if not exists destination text,
  add column if not exists original_destination text,
  add column if not exists destination_override text,
  add column if not exists send_instagram boolean not null default false,
  add column if not exists instagram_url text,
  add column if not exists instagram_username text,
  add column if not exists instagram_override_reason text,
  add column if not exists override_by text,
  add column if not exists override_at timestamptz,
  add column if not exists template_id uuid,
  add column if not exists message_1 text,
  add column if not exists message_2 text,
  add column if not exists image_url text,
  add column if not exists image_id text,
  add column if not exists retry_count integer not null default 0,
  add column if not exists error_message text,
  add column if not exists follow_status text,
  add column if not exists last_action_at timestamptz,
  add column if not exists invalid_reason text,
  add column if not exists sent_at timestamptz;

alter table public.base_permanente
  add column if not exists user_id uuid,
  add column if not exists company_name text,
  add column if not exists phone text,
  add column if not exists normalized_phone text,
  add column if not exists website text,
  add column if not exists website_domain text,
  add column if not exists instagram_url text,
  add column if not exists instagram_username text,
  add column if not exists maps_url text,
  add column if not exists source text,
  add column if not exists notes text,
  add column if not exists last_contact_at timestamptz,
  add column if not exists raw_payload jsonb not null default '{}'::jsonb,
  add column if not exists branch_id bigint,
  add column if not exists branch_name text,
  add column if not exists branch_slug text,
  add column if not exists destination text,
  add column if not exists original_destination text,
  add column if not exists destination_override text,
  add column if not exists send_instagram boolean not null default false,
  add column if not exists instagram_override_reason text,
  add column if not exists override_by text,
  add column if not exists override_at timestamptz,
  add column if not exists category text,
  add column if not exists category_name text,
  add column if not exists city text,
  add column if not exists state text,
  add column if not exists last_channel text,
  add column if not exists source_instance text,
  add column if not exists whatsapp_sent_at timestamptz,
  add column if not exists instagram_sent_at timestamptz;

alter table public.sent_contacts
  add column if not exists user_id uuid,
  add column if not exists lead_id text,
  add column if not exists company_name text,
  add column if not exists phone text,
  add column if not exists raw_payload jsonb not null default '{}'::jsonb,
  add column if not exists dispatched_at timestamptz,
  add column if not exists block_type text,
  add column if not exists source text,
  add column if not exists active boolean not null default true,
  add column if not exists reason text;

alter table public.lead_events
  add column if not exists user_id uuid,
  add column if not exists company_name text,
  add column if not exists normalized_phone text,
  add column if not exists website text,
  add column if not exists instagram_url text,
  add column if not exists maps_url text,
  add column if not exists event_type text,
  add column if not exists message_template text,
  add column if not exists sent_at timestamptz,
  add column if not exists metadata jsonb not null default '{}'::jsonb;

-- Indices e restricoes que a camada de repositorios usa para busca/upsert.
create unique index if not exists app_settings_user_key_uidx on public.app_settings(user_id, key);
create unique index if not exists chips_user_instance_uidx on public.chips(user_id, instance) where instance is not null and instance <> '';
create unique index if not exists instagram_profiles_user_username_uidx on public.instagram_profiles(user_id, username) where username is not null and username <> '';
create unique index if not exists templates_natural_idx on public.templates(user_id, branch_id, branch_name, template_type, channel);
create unique index if not exists lead_registry_identity_uidx on public.lead_registry(user_id, identity_type, identity_value);
create index if not exists leads_user_status_idx on public.leads(user_id, status);
create index if not exists pre_send_user_status_idx on public.pre_send_leads(user_id, status);
create unique index if not exists whatsapp_queue_source_pre_send_uidx on public.whatsapp_queue_items(source_pre_send_id) where source_pre_send_id is not null and source_pre_send_id <> '';
create unique index if not exists instagram_queue_source_pre_send_uidx on public.instagram_queue_items(source_pre_send_id) where source_pre_send_id is not null and source_pre_send_id <> '';
create index if not exists whatsapp_queue_operational_idx on public.whatsapp_queue_items(user_id, status, scheduled_date, batch_number, position);
create index if not exists instagram_queue_operational_idx on public.instagram_queue_items(user_id, status, scheduled_date, batch_number, position);
create index if not exists base_permanente_user_status_idx on public.base_permanente(user_id, status);
create index if not exists lead_dispatch_messages_lead_idx on public.lead_dispatch_messages(lead_id, created_at desc);

-- Copia segura das tabelas legadas conhecidas. As antigas permanecem intactas.
do $$
begin
  if to_regclass('public.whatsapp_instances') is not null then
    execute $copy$
      insert into public.chips (id, instance, label, name, phone, active, status, kind, channel, data, created_at, updated_at)
      select
        coalesce(nullif(to_jsonb(s)->>'id', ''), gen_random_uuid()::text),
        coalesce(to_jsonb(s)->>'instance', to_jsonb(s)->>'name', ''),
        coalesce(to_jsonb(s)->>'label', to_jsonb(s)->>'name', ''),
        coalesce(to_jsonb(s)->>'name', to_jsonb(s)->>'label', ''),
        coalesce(to_jsonb(s)->>'phone', to_jsonb(s)->>'number', ''),
        coalesce((to_jsonb(s)->>'active')::boolean, true),
        coalesce(to_jsonb(s)->>'status', 'inactive'),
        'chips', 'whatsapp', to_jsonb(s),
        coalesce(nullif(to_jsonb(s)->>'created_at', '')::timestamptz, now()),
        coalesce(nullif(to_jsonb(s)->>'updated_at', '')::timestamptz, now())
      from public.whatsapp_instances s
      on conflict (id) do update set data = excluded.data, updated_at = excluded.updated_at
    $copy$;
  end if;

  if to_regclass('public.message_templates') is not null then
    execute $copy$
      insert into public.templates (id, branch_name, template_type, type, channel, part_1, part_2, active, status, kind, data, created_at, updated_at)
      select
        coalesce(nullif(to_jsonb(s)->>'id', ''), gen_random_uuid()::text),
        coalesce(to_jsonb(s)->>'branch_name', to_jsonb(s)->>'ramo', ''),
        coalesce(to_jsonb(s)->>'template_type', to_jsonb(s)->>'type', 'sem-site'),
        coalesce(to_jsonb(s)->>'type', to_jsonb(s)->>'template_type', 'sem-site'),
        coalesce(to_jsonb(s)->>'channel', 'WhatsApp'),
        coalesce(to_jsonb(s)->>'part_1', to_jsonb(s)->>'message1', ''),
        coalesce(to_jsonb(s)->>'part_2', to_jsonb(s)->>'message2', ''),
        coalesce((to_jsonb(s)->>'active')::boolean, true),
        coalesce(to_jsonb(s)->>'status', 'Ativo'),
        'templates', to_jsonb(s),
        coalesce(nullif(to_jsonb(s)->>'created_at', '')::timestamptz, now()),
        coalesce(nullif(to_jsonb(s)->>'updated_at', '')::timestamptz, now())
      from public.message_templates s
      on conflict (id) do update set data = excluded.data, updated_at = excluded.updated_at
    $copy$;
  end if;

  if to_regclass('public.pre_dispatch_items') is not null then
    execute $copy$
      insert into public.whatsapp_queue_items (id, status, active, kind, channel, data, created_at, updated_at)
      select
        coalesce(nullif(to_jsonb(s)->>'id', ''), gen_random_uuid()::text),
        coalesce(to_jsonb(s)->>'status', 'queued'), true, 'whatsapp_queue', 'whatsapp', to_jsonb(s),
        coalesce(nullif(to_jsonb(s)->>'created_at', '')::timestamptz, now()),
        coalesce(nullif(to_jsonb(s)->>'updated_at', '')::timestamptz, now())
      from public.pre_dispatch_items s
      on conflict (id) do update set data = excluded.data, status = excluded.status, updated_at = excluded.updated_at
    $copy$;
  end if;

  if to_regclass('public.instagram_dispatch_items') is not null then
    execute $copy$
      insert into public.instagram_queue_items (id, status, active, kind, channel, data, created_at, updated_at)
      select
        coalesce(nullif(to_jsonb(s)->>'id', ''), gen_random_uuid()::text),
        coalesce(to_jsonb(s)->>'status', 'queued'), true, 'instagram_queue', 'instagram', to_jsonb(s),
        coalesce(nullif(to_jsonb(s)->>'created_at', '')::timestamptz, now()),
        coalesce(nullif(to_jsonb(s)->>'updated_at', '')::timestamptz, now())
      from public.instagram_dispatch_items s
      on conflict (id) do update set data = excluded.data, status = excluded.status, updated_at = excluded.updated_at
    $copy$;
  end if;

  if to_regclass('public.dispatch_message_logs') is not null then
    execute $copy$
      insert into public.lead_dispatch_messages (id, lead_id, chip_id, instance, phone, normalized_phone, direction, part, body, status, response_payload, created_at)
      select
        coalesce(nullif(to_jsonb(s)->>'id', ''), gen_random_uuid()::text),
        coalesce(to_jsonb(s)->>'lead_id', to_jsonb(s)->>'queue_item_id', ''),
        nullif(to_jsonb(s)->>'chip_id', '')::uuid,
        coalesce(to_jsonb(s)->>'instance', to_jsonb(s)->>'chip_instance', ''),
        coalesce(to_jsonb(s)->>'phone', ''),
        coalesce(to_jsonb(s)->>'normalized_phone', to_jsonb(s)->>'phone_normalized', ''),
        coalesce(to_jsonb(s)->>'direction', 'outbound'),
        coalesce(to_jsonb(s)->>'part', ''),
        coalesce(to_jsonb(s)->>'body', to_jsonb(s)->>'message', ''),
        coalesce(to_jsonb(s)->>'status', 'sent'),
        to_jsonb(s),
        coalesce(nullif(to_jsonb(s)->>'created_at', '')::timestamptz, now())
      from public.dispatch_message_logs s
      on conflict (id) do update set response_payload = excluded.response_payload, status = excluded.status
    $copy$;
  end if;

  if to_regclass('public.contact_events') is not null then
    execute $copy$
      insert into public.lead_events (id, source, action, channel, status, lead_id, queue_item_id, data, created_at, updated_at)
      select
        coalesce(nullif(to_jsonb(s)->>'id', ''), gen_random_uuid()::text),
        coalesce(to_jsonb(s)->>'source', 'legacy'),
        coalesce(to_jsonb(s)->>'action', to_jsonb(s)->>'event_type', 'legacy_event'),
        coalesce(to_jsonb(s)->>'channel', 'whatsapp'),
        coalesce(to_jsonb(s)->>'status', 'sent'),
        to_jsonb(s)->>'lead_id', to_jsonb(s)->>'queue_item_id', to_jsonb(s),
        coalesce(nullif(to_jsonb(s)->>'created_at', '')::timestamptz, now()),
        coalesce(nullif(to_jsonb(s)->>'updated_at', '')::timestamptz, now())
      from public.contact_events s
      on conflict (id) do update set data = excluded.data, updated_at = excluded.updated_at
    $copy$;
  end if;
end $$;
