import { useEffect, useMemo, useState } from 'react';
import { Bug, Calendar, CheckSquare, List, RefreshCcw, Send, Users, X } from 'lucide-react';
import { Button, ConfirmDialog, Drawer, Field, MetricCard, SegmentedControl, SelectField, ToastViewport, type ToastItem } from '../design-system/components';
import { PageHeader } from '../design-system/layouts/PageHeader';
import { QueueReviewPanel } from '../components/QueueReviewPanel';
import { QueueFinalTable, type FinalLead } from '../components/QueueFinalTable';
import { useInstagramQueue } from '../hooks/useInstagramQueue';
import { useWhatsAppQueue } from '../hooks/useWhatsAppQueue';
import { useOrganizationContext } from '../providers/OrganizationProvider';
import type { InstagramQueueLead } from '../services/instagram-queue/types';
import { alternativeNameService } from '../services/leads/alternativeName.service';
import { permissionsFor } from '../services/permissions';
import { queueReviewService } from '../services/queue-review';
import { statusLabel } from '../services/status/status.mapper';
import { hasWhatsAppOperationalIssue } from '../services/whatsapp-queue/whatsappQueue.guards';
import type { WhatsAppQueueLead } from '../services/whatsapp-queue/types';
import { toLocalDateInputValue } from '../utils/date';

export type QueuePageProps={channel:'whatsapp'|'instagram'}; type QueueTab='Revisão'|'Fila final';
function todayInputValue(){return toLocalDateInputValue();}
function useQueueToasts(){const[toasts,setToasts]=useState<ToastItem[]>([]);const pushToast=(toast:Omit<ToastItem,'id'>)=>{const id=`toast-${Date.now()}-${Math.random().toString(16).slice(2)}`;setToasts((current)=>[{id,...toast},...current].slice(0,4));window.setTimeout(()=>setToasts((current)=>current.filter((item)=>item.id!==id)),3800);};return{toasts,setToasts,pushToast};}
function pullDescription(result:Awaited<ReturnType<typeof queueReviewService.pull>>){return[`${result.ready} pronto(s)`,`${result.reserved}/${result.requested} reservado(s)`,result.invalidatedByProvider?`${result.invalidatedByProvider} sem WhatsApp`:'',result.redirectedToInstagram?`${result.redirectedToInstagram} liberado(s) para Instagram`:'',result.technicalStop?'erro técnico liberado sem retry automático':'',result.capacityLimited?'limitado pela capacidade restante da data':'',result.exhausted?'sem elegíveis suficientes para completar o pedido':''].filter(Boolean).join(' · ');}
export function QueuePage({channel}:QueuePageProps){return channel==='instagram'?<InstagramQueuePage/>:<WhatsAppQueuePage/>;}

function WhatsAppQueuePage(){
  const{hasPermission}=useOrganizationContext();const canPrepare=hasPermission('queues.prepare');const canControl=hasPermission('queues.control');const canEditLead=hasPermission('leads.edit');const canInvalidate=hasPermission('leads.validate');
  const[activeChip,setActiveChip]=useState('');const[activeTab,setActiveTab]=useState<QueueTab>('Revisão');const[scheduledDate,setScheduledDate]=useState(todayInputValue);const[pullCount,setPullCount]=useState('15');const[confirmLead,setConfirmLead]=useState<WhatsAppQueueLead|null>(null);const[viewLead,setViewLead]=useState<WhatsAppQueueLead|null>(null);const[nameLead,setNameLead]=useState<WhatsAppQueueLead|null>(null);const[pulling,setPulling]=useState(false);const[reprocessing,setReprocessing]=useState(false);const[reviewRefreshKey,setReviewRefreshKey]=useState(0);const{toasts,setToasts,pushToast}=useQueueToasts();
  const{chips,batches,summary,loading,error,refresh,reprocess,patchLeadLocally,invalidate}=useWhatsAppQueue(activeChip,scheduledDate);
  useEffect(()=>{if(!chips.length){if(activeChip)setActiveChip('');return;}if(!activeChip||!chips.includes(activeChip))setActiveChip(chips[0]);},[activeChip,chips]);
  const finalLeads=useMemo(()=>batches.flatMap((batch)=>batch.leads),[batches]);const chipOptions=chips.map((chip)=>({label:chip,value:chip}));const scopeLabel=activeChip||'Selecione um chip';
  const handlePull=async()=>{if(!canPrepare||!activeChip)return;setPulling(true);try{const result=await queueReviewService.pull('WhatsApp',scheduledDate,activeChip,Number(pullCount));setReviewRefreshKey((v)=>v+1);pushToast({title:'Revisão WhatsApp atualizada',description:pullDescription(result)||'A revisão já está na capacidade correta.',tone:result.errors?'warning':'success'});}catch(err){pushToast({title:'Não foi possível puxar WhatsApp',description:err instanceof Error?err.message:'Tente novamente.',tone:'danger'});}finally{setPulling(false);}};
  const handleReprocess=async()=>{if(!canControl)return;const ids=finalLeads.filter((lead)=>permissionsFor('whatsapp-queue',lead.status).canRetry()).map((lead)=>lead.id);if(!ids.length){pushToast({title:'Nada para reprocessar',description:'Não há itens com erro neste chip.',tone:'warning'});return;}setReprocessing(true);try{await reprocess(ids);pushToast({title:'Itens reprocessados',description:`${ids.length} item(ns) voltaram para a fila.`,tone:'success'});}catch(err){pushToast({title:'Não foi possível reprocessar',description:err instanceof Error?err.message:'Tente novamente.',tone:'danger'});}finally{setReprocessing(false);}};
  const handleInvalidate=async()=>{if(!canInvalidate||!confirmLead)return;const lead=confirmLead;try{await invalidate(lead);setConfirmLead(null);pushToast({title:'Lead invalidado',description:`${lead.company} saiu da Fila final. A vaga ficou aberta e só será preenchida quando você clicar em Puxar WhatsApp.`,tone:'warning'});}catch(err){pushToast({title:'Não foi possível invalidar',description:err instanceof Error?err.message:'Tente novamente.',tone:'danger'});}};
  return <div className="queue-page lead-list-page queue-page--whatsapp">
    <PageHeader title="Fila WhatsApp" action={<Field label="Data" type="date" iconLeft={Calendar} min={todayInputValue()} value={scheduledDate} onChange={setScheduledDate}/>}/>
    <section className="metric-grid metric-grid--5"><MetricCard icon={Users} value={String(summary.total)} label="Total"/><MetricCard icon={List} value={String(summary.queued)} label="Em fila" tone="primary"/><MetricCard icon={Send} value={String(summary.sent)} label="Enviados" tone="success"/><MetricCard icon={CheckSquare} value={String(summary.finished)} label="Finalizados" tone="warning"/><MetricCard icon={Bug} value={String(summary.errors)} label="Erros" tone="danger"/></section>
    <div className="queue-topline queue-topline--actions queue-topline--right"><div className="queue-controls queue-controls--right">{canControl?<Button variant="secondary" iconLeft={RefreshCcw} loading={reprocessing} disabled={loading||reprocessing} onClick={()=>void handleReprocess()}>Reprocessar</Button>:null}<SelectField className="queue-inline-filter" options={chipOptions} value={activeChip} onChange={setActiveChip} placeholder="Selecione um chip"/>{canPrepare?<Field className="queue-pull-quantity" label="Qtd." type="number" min={1} max={500} value={pullCount} onChange={setPullCount}/>:null}{canPrepare?<Button loading={pulling} disabled={loading||pulling||!activeChip} onClick={()=>void handlePull()}>Puxar leads</Button>:null}</div></div>
    <div className="queue-tabs"><SegmentedControl items={['Revisão','Fila final']} active={activeTab} onChange={(item)=>setActiveTab(item as QueueTab)}/></div>
    {activeTab==='Revisão'?<QueueReviewPanel channel="WhatsApp" scheduledDate={scheduledDate} preferredResourceId={activeChip} canPrepare={canPrepare} canInvalidate={canInvalidate} refreshKey={reviewRefreshKey} onQueueChanged={refresh} onToast={(title,description,tone)=>pushToast({title,description,tone})}/>:<>{error?<div className="table-message">{error}</div>:null}{!error&&loading&&!finalLeads.length?<div className="table-message">Carregando Fila final...</div>:null}{!error&&!loading?<QueueFinalTable channel="WhatsApp" leads={finalLeads} resourceLabel={scopeLabel} canEdit={canEditLead} canInvalidate={canInvalidate} onView={(lead)=>setViewLead(lead as WhatsAppQueueLead)} onEdit={(lead)=>setNameLead(lead as WhatsAppQueueLead)} onInvalidate={(lead)=>setConfirmLead(lead as WhatsAppQueueLead)}/>:null}</>}
    <QueueItemViewDrawer lead={viewLead} onClose={()=>setViewLead(null)}/><AlternativeNameDrawer lead={nameLead} onClose={()=>setNameLead(null)} onSaved={(alternativeName)=>{if(nameLead){const original=nameLead.original_company_name||nameLead.company_name||nameLead.company;const displayName=alternativeName||original;patchLeadLocally(nameLead.id,{alternative_name:alternativeName,company:displayName,company_name:displayName});}setNameLead(null);pushToast({title:'Nome alternativo salvo',description:'O snapshot deste item foi atualizado e os próximos envios usarão o novo nome.',tone:'success'});}} onError={(message)=>pushToast({title:'Não foi possível salvar',description:message,tone:'danger'})}/>
    <ConfirmDialog open={canInvalidate&&Boolean(confirmLead)} title="Invalidar lead da fila?" description="O lead será invalidado e a vaga ficará aberta. Nenhum substituto será puxado automaticamente." confirmLabel="Invalidar" danger onClose={()=>setConfirmLead(null)} onConfirm={()=>void handleInvalidate()}/><ToastViewport toasts={toasts} onDismiss={(id)=>setToasts((current)=>current.filter((toast)=>toast.id!==id))}/>
  </div>;
}

function InstagramQueuePage(){
  const{hasPermission}=useOrganizationContext();const canPrepare=hasPermission('queues.prepare');const canControl=hasPermission('queues.control');const canEditLead=hasPermission('leads.edit');const canInvalidate=hasPermission('leads.validate');
  const[activeProfile,setActiveProfile]=useState('');const[activeTab,setActiveTab]=useState<QueueTab>('Revisão');const[scheduledDate,setScheduledDate]=useState(todayInputValue);const[pullCount,setPullCount]=useState('15');const[confirmLead,setConfirmLead]=useState<InstagramQueueLead|null>(null);const[viewLead,setViewLead]=useState<InstagramQueueLead|null>(null);const[nameLead,setNameLead]=useState<InstagramQueueLead|null>(null);const[pulling,setPulling]=useState(false);const[reprocessing,setReprocessing]=useState(false);const[reviewRefreshKey,setReviewRefreshKey]=useState(0);const{toasts,setToasts,pushToast}=useQueueToasts();
  const{profiles,batches,summary,loading,error,refresh,patchLeadLocally,invalidate,reprocess}=useInstagramQueue(activeProfile,scheduledDate);
  useEffect(()=>{if(!profiles.length){if(activeProfile)setActiveProfile('');return;}if(!activeProfile||!profiles.includes(activeProfile))setActiveProfile(profiles[0]);},[activeProfile,profiles]);
  const finalLeads=useMemo(()=>batches.flatMap((batch)=>batch.leads),[batches]);const profileOptions=profiles.map((profile)=>({label:profile,value:profile}));const scopeLabel=activeProfile||'Selecione um perfil';
  const handlePull=async()=>{if(!canPrepare||!activeProfile)return;setPulling(true);try{const result=await queueReviewService.pull('Instagram',scheduledDate,activeProfile,Number(pullCount));setReviewRefreshKey((v)=>v+1);pushToast({title:'Revisão Instagram atualizada',description:pullDescription(result)||'A revisão já está na capacidade correta.',tone:result.errors?'warning':'success'});}catch(err){pushToast({title:'Não foi possível puxar Instagram',description:err instanceof Error?err.message:'Tente novamente.',tone:'danger'});}finally{setPulling(false);}};
  const handleReprocess=async()=>{if(!canControl)return;const ids=finalLeads.filter((lead)=>permissionsFor('instagram-queue',lead.status).canRetry()).map((lead)=>lead.id);if(!ids.length){pushToast({title:'Sem erros',description:'Não há itens com erro neste perfil.',tone:'warning'});return;}setReprocessing(true);try{await reprocess(ids);pushToast({title:'Itens reprocessados',description:`${ids.length} item(ns) voltaram para a fila.`,tone:'success'});}catch(err){pushToast({title:'Não foi possível reprocessar',description:err instanceof Error?err.message:'Tente novamente.',tone:'danger'});}finally{setReprocessing(false);}};
  const handleInvalidate=async()=>{if(!canInvalidate||!confirmLead)return;const lead=confirmLead;try{await invalidate(lead);setConfirmLead(null);pushToast({title:'Lead invalidado',description:`${lead.company} saiu da Fila final. A vaga ficou aberta e só será preenchida quando você clicar em Puxar Instagram.`,tone:'warning'});}catch(err){pushToast({title:'Não foi possível invalidar',description:err instanceof Error?err.message:'Tente novamente.',tone:'danger'});}};
  return <div className="queue-page lead-list-page queue-page--instagram">
    <PageHeader title="Fila Instagram" action={<Field label="Data" type="date" iconLeft={Calendar} min={todayInputValue()} value={scheduledDate} onChange={setScheduledDate}/>}/>
    <section className="metric-grid metric-grid--5"><MetricCard icon={Users} value={String(summary.total)} label="Total"/><MetricCard icon={List} value={String(summary.queued)} label="Em fila" tone="primary"/><MetricCard icon={Send} value={String(summary.sent)} label="Enviados" tone="success"/><MetricCard icon={Bug} value={String(summary.errors)} label="Erros / reconciliação" tone="warning"/><MetricCard icon={X} value={String(summary.invalid)} label="Inválidos" tone="danger"/></section>
    <div className="queue-topline queue-topline--actions queue-topline--right"><div className="queue-controls queue-controls--right">{canControl?<Button variant="secondary" iconLeft={RefreshCcw} loading={reprocessing} disabled={loading||reprocessing} onClick={()=>void handleReprocess()}>Reprocessar</Button>:null}<SelectField className="queue-inline-filter" options={profileOptions} value={activeProfile} onChange={setActiveProfile} placeholder="Selecione um perfil"/>{canPrepare?<Field className="queue-pull-quantity" label="Qtd." type="number" min={1} max={500} value={pullCount} onChange={setPullCount}/>:null}{canPrepare?<Button loading={pulling} disabled={loading||pulling||!activeProfile} onClick={()=>void handlePull()}>Puxar leads</Button>:null}</div></div>
    <div className="queue-tabs"><SegmentedControl items={['Revisão','Fila final']} active={activeTab} onChange={(item)=>setActiveTab(item as QueueTab)}/></div>
    {activeTab==='Revisão'?<QueueReviewPanel channel="Instagram" scheduledDate={scheduledDate} preferredResourceId={activeProfile} canPrepare={canPrepare} canInvalidate={canInvalidate} refreshKey={reviewRefreshKey} onQueueChanged={refresh} onToast={(title,description,tone)=>pushToast({title,description,tone})}/>:<>{error?<div className="table-message">{error}</div>:null}{!error&&loading&&!finalLeads.length?<div className="table-message">Carregando Fila final...</div>:null}{!error&&!loading?<QueueFinalTable channel="Instagram" leads={finalLeads} resourceLabel={scopeLabel} canEdit={canEditLead} canInvalidate={canInvalidate} onView={(lead)=>setViewLead(lead as InstagramQueueLead)} onEdit={(lead)=>setNameLead(lead as InstagramQueueLead)} onInvalidate={(lead)=>setConfirmLead(lead as InstagramQueueLead)}/>:null}</>}
    <QueueItemViewDrawer lead={viewLead} onClose={()=>setViewLead(null)}/><AlternativeNameDrawer lead={nameLead} onClose={()=>setNameLead(null)} onSaved={(alternativeName)=>{if(nameLead){const original=nameLead.original_company_name||nameLead.company_name||nameLead.company;const displayName=alternativeName||original;patchLeadLocally(nameLead.id,{alternative_name:alternativeName,company:displayName,company_name:displayName});}setNameLead(null);pushToast({title:'Nome alternativo salvo',description:'O snapshot deste item foi atualizado e os próximos envios usarão o novo nome.',tone:'success'});}} onError={(message)=>pushToast({title:'Não foi possível salvar',description:message,tone:'danger'})}/>
    <ConfirmDialog open={canInvalidate&&Boolean(confirmLead)} title="Invalidar lead do Instagram?" description="O lead será invalidado e a vaga ficará aberta. Nenhum substituto será puxado automaticamente." confirmLabel="Invalidar" danger onClose={()=>setConfirmLead(null)} onConfirm={()=>void handleInvalidate()}/><ToastViewport toasts={toasts} onDismiss={(id)=>setToasts((current)=>current.filter((toast)=>toast.id!==id))}/>
  </div>;
}

function QueueItemViewDrawer({lead,onClose}:{lead:FinalLead|null;onClose:()=>void}){
  if(!lead)return <Drawer open={false} title="Detalhes" onClose={onClose}><div/></Drawer>;
  const issue=lead.channel==='whatsapp'&&hasWhatsAppOperationalIssue(lead);const contact=lead.channel==='whatsapp'?lead.phone:lead.instagram_username||lead.instagram||'';const resource=lead.channel==='whatsapp'?(lead.chip_label||lead.chip_instance||lead.chip):lead.profile;
  return <Drawer open title="Detalhes do item da fila" description="Visualização somente leitura. Para padronizar o nome, use o ícone de editar na tabela." onClose={onClose} footer={<Button variant="secondary" onClick={onClose}>Fechar</Button>}><div className="drawer-form drawer-form--readonly"><Field label="Empresa original" value={lead.original_company_name||lead.company} readOnly/><Field label="Nome alternativo" value={lead.alternative_name||'—'} readOnly/><Field label="Nome usado no envio" value={lead.company} readOnly/><Field label={lead.channel==='whatsapp'?'WhatsApp':'Instagram'} value={contact} readOnly/><Field label="Ramo" value={lead.branch||'—'} readOnly/><Field label={lead.channel==='whatsapp'?'Chip':'Perfil'} value={resource} readOnly/><Field label="Status" value={issue?'Dados incompletos':statusLabel(lead.status)} readOnly/><Field label="Posição" value={String(lead.position)} readOnly/><Field label="Agendado para" value={lead.scheduled_date} readOnly/><Field as="textarea" label="Mensagem 1" value={lead.message1||''} readOnly/><Field as="textarea" label="Mensagem 2" value={lead.message2||''} readOnly/><Field as="textarea" label="Mensagem 3" value={lead.message3||''} readOnly/><Field as="textarea" label="Mensagem 4" value={lead.message4||''} readOnly/></div></Drawer>;
}
function AlternativeNameDrawer({lead,onClose,onSaved,onError}:{lead:FinalLead|null;onClose:()=>void;onSaved:(alternativeName:string)=>void;onError:(message:string)=>void}){
  const[value,setValue]=useState('');const[saving,setSaving]=useState(false);useEffect(()=>{setValue(lead?.alternative_name??'');},[lead]);
  const save=async()=>{if(!lead)return;setSaving(true);try{const alternativeName=value.trim();await alternativeNameService.update(lead.lead_id,alternativeName,lead.id);onSaved(alternativeName);}catch(err){onError(err instanceof Error?err.message:'Tente novamente.');}finally{setSaving(false);}};
  return <Drawer open={Boolean(lead)} title="Editar nome alternativo" description="Somente este campo pode ser alterado aqui. O nome alternativo passa a ser usado nas mensagens e no snapshot enquanto o item ainda não iniciou o envio." onClose={onClose} footer={<><Button variant="secondary" onClick={onClose}>Cancelar</Button><Button loading={saving} onClick={()=>void save()}>Salvar</Button></>}>{lead?<div className="drawer-form"><Field label="Empresa original" value={lead.original_company_name||lead.company} readOnly/><Field label="Nome alternativo (opcional)" value={value} maxLength={160} placeholder="Ex.: Contabilidade Dinastia" onChange={setValue}/></div>:null}</Drawer>;
}
