import { useEffect, useMemo, useRef, useState } from 'react';
import { Bug, Calendar, CheckSquare, ClipboardCheck, List, ListPlus, RefreshCcw, Send, Users, X } from 'lucide-react';
import { Button, ConfirmDialog, Drawer, Field, MetricCard, SegmentedControl, SelectField, ToastViewport, type ToastItem } from '../design-system/components';
import { PageHeader } from '../design-system/layouts/PageHeader';
import { QueueReviewPanel } from '../components/QueueReviewPanel';
import { QueuePullDrawer } from '../components/QueuePullDrawer';
import { QueueFinalTable, type FinalLead } from '../components/QueueFinalTable';
import { useInstagramQueue } from '../hooks/useInstagramQueue';
import { useOperationalQueueDate } from '../hooks/useOperationalQueueDate';
import { useWhatsAppQueue } from '../hooks/useWhatsAppQueue';
import { useOrganizationContext } from '../providers/OrganizationProvider';
import type { InstagramQueueLead } from '../services/instagram-queue/types';
import { alternativeNameService, type AlternativeNameUpdateResult } from '../services/leads/alternativeName.service';
import { queueReviewService } from '../services/queue-review';
import { statusLabel } from '../services/status/status.mapper';
import { hasWhatsAppOperationalIssue } from '../services/whatsapp-queue/whatsappQueue.guards';
import type { WhatsAppQueueLead } from '../services/whatsapp-queue/types';
import { toLocalDateInputValue } from '../utils/date';

export type QueuePageProps={channel:'whatsapp'|'instagram';embedded?:boolean}; type QueueTab='Revisão'|'Fila final';
type QueueNotificationTarget={scheduledDate:string;resourceKey:string;tab:string};
function readQueueNotificationTarget(channel:'whatsapp'|'instagram'):QueueNotificationTarget|null{
  const key=`crm:notification:queue-target:${channel}`;
  const raw=window.sessionStorage.getItem(key);
  if(!raw)return null;
  try{const value=JSON.parse(raw) as Record<string,unknown>;return{scheduledDate:String(value.scheduledDate??''),resourceKey:String(value.resourceKey??''),tab:String(value.tab??'')};}
  catch{window.sessionStorage.removeItem(key);return null;}
}
function clearQueueNotificationTarget(channel:'whatsapp'|'instagram'){window.sessionStorage.removeItem(`crm:notification:queue-target:${channel}`);}

function todayInputValue(){return toLocalDateInputValue();}
function useQueueToasts(){const[toasts,setToasts]=useState<ToastItem[]>([]);const pushToast=(toast:Omit<ToastItem,'id'>)=>{const id=`toast-${Date.now()}-${Math.random().toString(16).slice(2)}`;setToasts((current)=>[{id,...toast},...current].slice(0,4));window.setTimeout(()=>setToasts((current)=>current.filter((item)=>item.id!==id)),3800);};return{toasts,setToasts,pushToast};}
function pullDescription(result:Awaited<ReturnType<typeof queueReviewService.pull>>){const technical=result.technicalStop?`erro técnico liberado sem retry automático${result.technicalReasons.length?`: ${result.technicalReasons.join(' | ')}`:''}`:'';return[`${result.ready} pronto(s)`,`${result.reserved} reservado(s)`,result.invalidatedByProvider?`${result.invalidatedByProvider} sem WhatsApp`:'',result.redirectedToInstagram?`${result.redirectedToInstagram} sem WhatsApp, direcionado(s) ao Instagram`:'',technical,result.exhausted?`sem elegíveis suficientes para preencher ${result.capacityToFill} vaga(s)`:'' ].filter(Boolean).join(' · ');}
export function QueuePage({channel,embedded=false}:QueuePageProps){return channel==='instagram'?<InstagramQueuePage embedded={embedded}/>:<WhatsAppQueuePage embedded={embedded}/>;}

function WhatsAppQueuePage({embedded=false}:{embedded?:boolean}){
  const{hasPermission}=useOrganizationContext();const canPrepare=hasPermission('queues.prepare');const canControl=hasPermission('queues.control');const canEditLead=hasPermission('leads.edit');const canInvalidate=hasPermission('leads.validate');
  const[activeChip,setActiveChip]=useState('');const[activeTab,setActiveTab]=useState<QueueTab>('Revisão');const[reviewCount,setReviewCount]=useState(0);const[scheduledDate,setScheduledDate]=useOperationalQueueDate();const notificationTargetRef=useRef(readQueueNotificationTarget('whatsapp'));const[confirmLead,setConfirmLead]=useState<WhatsAppQueueLead|null>(null);const[viewLead,setViewLead]=useState<WhatsAppQueueLead|null>(null);const[nameLead,setNameLead]=useState<WhatsAppQueueLead|null>(null);const[pullDrawerOpen,setPullDrawerOpen]=useState(false);const[reprocessing,setReprocessing]=useState(false);const[reviewRefreshKey,setReviewRefreshKey]=useState(0);const{toasts,setToasts,pushToast}=useQueueToasts();
  const{chips,batches,total,page,setPage,rowsPerPage,setRowsPerPage,summary,loading,refreshing,error,refresh,reprocessScope,patchLeadLocally,invalidate}=useWhatsAppQueue(activeChip,scheduledDate);
  useEffect(()=>{const target=notificationTargetRef.current;if(target?.scheduledDate)setScheduledDate(target.scheduledDate);if(target?.tab==='Fila final')setActiveTab('Fila final');},[setScheduledDate]);
  useEffect(()=>{if(!chips.length){if(activeChip)setActiveChip('');return;}const target=notificationTargetRef.current;if(target?.resourceKey&&chips.includes(target.resourceKey)){setActiveChip(target.resourceKey);notificationTargetRef.current=null;clearQueueNotificationTarget('whatsapp');return;}if(target){notificationTargetRef.current=null;clearQueueNotificationTarget('whatsapp');}if(!activeChip||!chips.includes(activeChip))setActiveChip(chips[0]);},[activeChip,chips]);
  useEffect(()=>{let active=true;if(!activeChip){setReviewCount(0);return;}void queueReviewService.count('WhatsApp',activeChip,scheduledDate).then((next)=>{if(active)setReviewCount(next);}).catch(()=>{if(active)setReviewCount(0);});return()=>{active=false;};},[activeChip,scheduledDate,reviewRefreshKey]);
  const finalLeads=useMemo(()=>batches.flatMap((batch)=>batch.leads),[batches]);const chipOptions=chips.map((chip)=>({label:chip,value:chip}));const scopeLabel=activeChip||'Selecione um chip';
  const handlePulled=(pulledChannel:'WhatsApp'|'Instagram',result:Awaited<ReturnType<typeof queueReviewService.pull>>)=>{if(pulledChannel!=='WhatsApp')return;setScheduledDate(result.scheduledDate);setActiveChip(result.resourceSelectionKey||result.resource.label);setReviewRefreshKey((v)=>v+1);pushToast({title:'Revisão WhatsApp atualizada',description:pullDescription(result)||'A revisão já está na capacidade correta.',tone:result.errors?'warning':'success'});};
  const handleReprocess=async()=>{if(!canControl)return;setReprocessing(true);try{const count=await reprocessScope();if(!count){pushToast({title:'Nada para reprocessar',description:'Não há itens com erro neste chip.',tone:'warning'});return;}pushToast({title:'Itens reprocessados',description:`${count} item(ns) voltaram para a fila.`,tone:'success'});}catch(err){pushToast({title:'Não foi possível reprocessar',description:err instanceof Error?err.message:'Tente novamente.',tone:'danger'});}finally{setReprocessing(false);}};
  const handleInvalidate=async()=>{if(!canInvalidate||!confirmLead)return;const lead=confirmLead;try{await invalidate(lead);setConfirmLead(null);pushToast({title:'Lead invalidado',description:'Lead movido para a Base Permanente.',tone:'success'});}catch(err){pushToast({title:'Não foi possível invalidar',description:err instanceof Error?err.message:'Tente novamente.',tone:'danger'});}};
  return <div className="queue-page lead-list-page queue-page--whatsapp">
    {embedded?<div className="queue-embedded-header"><div><strong>WhatsApp</strong><span>Gestão da fila e revisão do canal.</span></div><Field label="Data" type="date" iconLeft={Calendar} min={todayInputValue()} value={scheduledDate} onChange={setScheduledDate}/></div>:<PageHeader title="Fila WhatsApp" action={<Field label="Data" type="date" iconLeft={Calendar} min={todayInputValue()} value={scheduledDate} onChange={setScheduledDate}/>}/>} 
    <section className="metric-grid metric-grid--6"><MetricCard icon={Users} value={String(summary.total)} label="Total"/><MetricCard icon={ClipboardCheck} value={String(reviewCount)} label="Revisão"/><MetricCard icon={List} value={String(summary.queued)} label="Em fila" tone="primary"/><MetricCard icon={Send} value={String(summary.sent)} label="Enviados" tone="success"/><MetricCard icon={CheckSquare} value={String(summary.finished)} label="Finalizados" tone="warning"/><MetricCard icon={Bug} value={String(summary.errors)} label="Erros" tone="danger"/></section>
    <div className="queue-topline queue-topline--actions queue-topline--right"><div className="queue-controls queue-controls--right">{canControl?<Button variant="secondary" iconLeft={RefreshCcw} loading={reprocessing} disabled={loading||reprocessing} onClick={()=>void handleReprocess()}>Reprocessar</Button>:null}<SelectField className="queue-inline-filter" options={chipOptions} value={activeChip} onChange={setActiveChip} placeholder="Selecione um chip"/>{canPrepare?<Button iconLeft={ListPlus} disabled={loading} onClick={()=>setPullDrawerOpen(true)}>Puxar leads</Button>:null}</div></div>
    <div className="queue-tabs"><SegmentedControl compact items={['Revisão','Fila final']} active={activeTab} onChange={(item)=>setActiveTab(item as QueueTab)}/></div>
    {activeTab==='Revisão'?<QueueReviewPanel channel="WhatsApp" scheduledDate={scheduledDate} preferredResourceId={activeChip} canPrepare={canPrepare} canInvalidate={canInvalidate} refreshKey={reviewRefreshKey} onReviewCountChange={setReviewCount} onQueueChanged={refresh} onToast={(title,description,tone)=>pushToast({title,description,tone})}/>:<>{error?<div className="table-message">{error}</div>:null}{!error&&loading&&!finalLeads.length?<div className="table-message">Carregando Fila final...</div>:null}{!error&&!loading?<QueueFinalTable channel="WhatsApp" leads={finalLeads} total={total} page={page} rowsPerPage={rowsPerPage} refreshing={refreshing} onPageChange={setPage} onRowsPerPageChange={setRowsPerPage} resourceLabel={scopeLabel} canEdit={canEditLead} canInvalidate={canInvalidate} onView={(lead)=>setViewLead(lead as WhatsAppQueueLead)} onEdit={(lead)=>setNameLead(lead as WhatsAppQueueLead)} onInvalidate={(lead)=>setConfirmLead(lead as WhatsAppQueueLead)}/>:null}</>}
    <QueuePullDrawer open={pullDrawerOpen} initialChannel="WhatsApp" lockChannel initialDate={scheduledDate} initialResourceId={activeChip} onClose={()=>setPullDrawerOpen(false)} onPulled={handlePulled} onError={(title,description)=>pushToast({title,description,tone:'danger'})}/><QueueItemViewDrawer lead={viewLead} onClose={()=>setViewLead(null)}/><AlternativeNameDrawer lead={nameLead} onClose={()=>setNameLead(null)} onSaved={(result)=>{if(nameLead){const original=result.originalCompanyName||nameLead.original_company_name||nameLead.company;patchLeadLocally(nameLead.id,{alternative_name:result.alternativeName,company:original,original_company_name:original,company_name:result.sendCompanyName||result.alternativeName||original,message1:result.message1||nameLead.message1,message_1:result.message1||nameLead.message_1,message2:result.message2||nameLead.message2,message_2:result.message2||nameLead.message_2,message3:result.message3||nameLead.message3,message_3:result.message3||nameLead.message_3,message4:result.message4||nameLead.message4,message_4:result.message4||nameLead.message_4});}setNameLead(null);pushToast({title:'Alterações salvas',description:'Nome alternativo e mensagens foram atualizados.',tone:'success'});}} onError={(message)=>pushToast({title:'Não foi possível salvar',description:message,tone:'danger'})}/>
    <ConfirmDialog open={canInvalidate&&Boolean(confirmLead)} title="Invalidar lead da fila?" description="O lead será invalidado, os itens seguintes subirão uma posição e a capacidade ficará disponível para a próxima ação Puxar. Nenhum substituto será puxado automaticamente." confirmLabel="Invalidar" danger onClose={()=>setConfirmLead(null)} onConfirm={()=>void handleInvalidate()}/><ToastViewport toasts={toasts} onDismiss={(id)=>setToasts((current)=>current.filter((toast)=>toast.id!==id))}/>
  </div>;
}

function InstagramQueuePage({embedded=false}:{embedded?:boolean}){
  const{hasPermission}=useOrganizationContext();const canPrepare=hasPermission('queues.prepare');const canControl=hasPermission('queues.control');const canEditLead=hasPermission('leads.edit');const canInvalidate=hasPermission('leads.validate');
  const[activeProfile,setActiveProfile]=useState('');const[activeTab,setActiveTab]=useState<QueueTab>('Revisão');const[reviewCount,setReviewCount]=useState(0);const[scheduledDate,setScheduledDate]=useOperationalQueueDate();const notificationTargetRef=useRef(readQueueNotificationTarget('instagram'));const[confirmLead,setConfirmLead]=useState<InstagramQueueLead|null>(null);const[viewLead,setViewLead]=useState<InstagramQueueLead|null>(null);const[nameLead,setNameLead]=useState<InstagramQueueLead|null>(null);const[pullDrawerOpen,setPullDrawerOpen]=useState(false);const[reprocessing,setReprocessing]=useState(false);const[reviewRefreshKey,setReviewRefreshKey]=useState(0);const{toasts,setToasts,pushToast}=useQueueToasts();
  const{profiles,batches,total,page,setPage,rowsPerPage,setRowsPerPage,summary,loading,refreshing,error,refresh,patchLeadLocally,invalidate,reprocessScope}=useInstagramQueue(activeProfile,scheduledDate);
  useEffect(()=>{const target=notificationTargetRef.current;if(target?.scheduledDate)setScheduledDate(target.scheduledDate);if(target?.tab==='Fila final')setActiveTab('Fila final');},[setScheduledDate]);
  useEffect(()=>{if(!profiles.length){if(activeProfile)setActiveProfile('');return;}const target=notificationTargetRef.current;if(target?.resourceKey&&profiles.includes(target.resourceKey)){setActiveProfile(target.resourceKey);notificationTargetRef.current=null;clearQueueNotificationTarget('instagram');return;}if(target){notificationTargetRef.current=null;clearQueueNotificationTarget('instagram');}if(!activeProfile||!profiles.includes(activeProfile))setActiveProfile(profiles[0]);},[activeProfile,profiles]);
  useEffect(()=>{let active=true;if(!activeProfile){setReviewCount(0);return;}void queueReviewService.count('Instagram',activeProfile,scheduledDate).then((next)=>{if(active)setReviewCount(next);}).catch(()=>{if(active)setReviewCount(0);});return()=>{active=false;};},[activeProfile,scheduledDate,reviewRefreshKey]);
  const finalLeads=useMemo(()=>batches.flatMap((batch)=>batch.leads),[batches]);const profileOptions=profiles.map((profile)=>({label:profile,value:profile}));const scopeLabel=activeProfile||'Selecione um perfil';
  const handlePulled=(pulledChannel:'WhatsApp'|'Instagram',result:Awaited<ReturnType<typeof queueReviewService.pull>>)=>{if(pulledChannel!=='Instagram')return;setScheduledDate(result.scheduledDate);setActiveProfile(result.resourceSelectionKey||result.resource.label);setReviewRefreshKey((v)=>v+1);pushToast({title:'Revisão Instagram atualizada',description:pullDescription(result)||'A revisão já está na capacidade correta.',tone:result.errors?'warning':'success'});};
  const handleReprocess=async()=>{if(!canControl)return;setReprocessing(true);try{const count=await reprocessScope();if(!count){pushToast({title:'Sem erros',description:'Não há itens com erro neste perfil.',tone:'warning'});return;}pushToast({title:'Itens reprocessados',description:`${count} item(ns) voltaram para a fila.`,tone:'success'});}catch(err){pushToast({title:'Não foi possível reprocessar',description:err instanceof Error?err.message:'Tente novamente.',tone:'danger'});}finally{setReprocessing(false);}};
  const handleInvalidate=async()=>{if(!canInvalidate||!confirmLead)return;const lead=confirmLead;try{await invalidate(lead);setConfirmLead(null);pushToast({title:'Lead invalidado',description:'Lead movido para a Base Permanente.',tone:'success'});}catch(err){pushToast({title:'Não foi possível invalidar',description:err instanceof Error?err.message:'Tente novamente.',tone:'danger'});}};
  return <div className="queue-page lead-list-page queue-page--instagram">
    {embedded?<div className="queue-embedded-header"><div><strong>Instagram</strong><span>Gestão da fila e revisão do canal.</span></div><Field label="Data" type="date" iconLeft={Calendar} min={todayInputValue()} value={scheduledDate} onChange={setScheduledDate}/></div>:<PageHeader title="Fila Instagram" action={<Field label="Data" type="date" iconLeft={Calendar} min={todayInputValue()} value={scheduledDate} onChange={setScheduledDate}/>}/>} 
    <section className="metric-grid metric-grid--6"><MetricCard icon={Users} value={String(summary.total)} label="Total"/><MetricCard icon={ClipboardCheck} value={String(reviewCount)} label="Revisão"/><MetricCard icon={List} value={String(summary.queued)} label="Em fila" tone="primary"/><MetricCard icon={Send} value={String(summary.sent)} label="Enviados" tone="success"/><MetricCard icon={Bug} value={String(summary.errors)} label="Erros / reconciliação" tone="warning"/><MetricCard icon={X} value={String(summary.invalid)} label="Inválidos" tone="danger"/></section>
    <div className="queue-topline queue-topline--actions queue-topline--right"><div className="queue-controls queue-controls--right">{canControl?<Button variant="secondary" iconLeft={RefreshCcw} loading={reprocessing} disabled={loading||reprocessing} onClick={()=>void handleReprocess()}>Reprocessar</Button>:null}<SelectField className="queue-inline-filter" options={profileOptions} value={activeProfile} onChange={setActiveProfile} placeholder="Selecione um perfil"/>{canPrepare?<Button iconLeft={ListPlus} disabled={loading} onClick={()=>setPullDrawerOpen(true)}>Puxar leads</Button>:null}</div></div>
    <div className="queue-tabs"><SegmentedControl compact items={['Revisão','Fila final']} active={activeTab} onChange={(item)=>setActiveTab(item as QueueTab)}/></div>
    {activeTab==='Revisão'?<QueueReviewPanel channel="Instagram" scheduledDate={scheduledDate} preferredResourceId={activeProfile} canPrepare={canPrepare} canInvalidate={canInvalidate} refreshKey={reviewRefreshKey} onReviewCountChange={setReviewCount} onQueueChanged={refresh} onToast={(title,description,tone)=>pushToast({title,description,tone})}/>:<>{error?<div className="table-message">{error}</div>:null}{!error&&loading&&!finalLeads.length?<div className="table-message">Carregando Fila final...</div>:null}{!error&&!loading?<QueueFinalTable channel="Instagram" leads={finalLeads} total={total} page={page} rowsPerPage={rowsPerPage} refreshing={refreshing} onPageChange={setPage} onRowsPerPageChange={setRowsPerPage} resourceLabel={scopeLabel} canEdit={canEditLead} canInvalidate={canInvalidate} onView={(lead)=>setViewLead(lead as InstagramQueueLead)} onEdit={(lead)=>setNameLead(lead as InstagramQueueLead)} onInvalidate={(lead)=>setConfirmLead(lead as InstagramQueueLead)}/>:null}</>}
    <QueuePullDrawer open={pullDrawerOpen} initialChannel="Instagram" lockChannel initialDate={scheduledDate} initialResourceId={activeProfile} onClose={()=>setPullDrawerOpen(false)} onPulled={handlePulled} onError={(title,description)=>pushToast({title,description,tone:'danger'})}/><QueueItemViewDrawer lead={viewLead} onClose={()=>setViewLead(null)}/><AlternativeNameDrawer lead={nameLead} onClose={()=>setNameLead(null)} onSaved={(result)=>{if(nameLead){const original=result.originalCompanyName||nameLead.original_company_name||nameLead.company;patchLeadLocally(nameLead.id,{alternative_name:result.alternativeName,company:original,original_company_name:original,company_name:result.sendCompanyName||result.alternativeName||original,message1:result.message1||nameLead.message1,message_1:result.message1||nameLead.message_1,message2:result.message2||nameLead.message2,message_2:result.message2||nameLead.message_2,message3:result.message3||nameLead.message3,message_3:result.message3||nameLead.message_3,message4:result.message4||nameLead.message4,message_4:result.message4||nameLead.message_4});}setNameLead(null);pushToast({title:'Alterações salvas',description:'Nome alternativo e mensagens foram atualizados.',tone:'success'});}} onError={(message)=>pushToast({title:'Não foi possível salvar',description:message,tone:'danger'})}/>
    <ConfirmDialog open={canInvalidate&&Boolean(confirmLead)} title="Invalidar lead do Instagram?" description="O lead será invalidado, os itens seguintes subirão uma posição e a capacidade ficará disponível para a próxima ação Puxar. Nenhum substituto será puxado automaticamente." confirmLabel="Invalidar" danger onClose={()=>setConfirmLead(null)} onConfirm={()=>void handleInvalidate()}/><ToastViewport toasts={toasts} onDismiss={(id)=>setToasts((current)=>current.filter((toast)=>toast.id!==id))}/>
  </div>;
}

function QueueItemViewDrawer({lead,onClose}:{lead:FinalLead|null;onClose:()=>void}){
  if(!lead)return <Drawer open={false} title="Detalhes" onClose={onClose}><div/></Drawer>;
  const issue=lead.channel==='whatsapp'&&hasWhatsAppOperationalIssue(lead);const contact=lead.channel==='whatsapp'?lead.phone:lead.instagram_username||lead.instagram||'';const resource=lead.channel==='whatsapp'?(lead.chip_label||lead.chip_instance||lead.chip):lead.profile;
  return <Drawer open title="Detalhes do item da fila" description="Visualização somente leitura. Para padronizar o nome, use o ícone de editar na tabela." onClose={onClose} footer={<Button variant="secondary" onClick={onClose}>Fechar</Button>}><div className="drawer-form drawer-form--readonly"><Field label="Empresa original" value={lead.original_company_name||lead.company} readOnly/><Field label="Nome alternativo" value={lead.alternative_name||'—'} readOnly/><Field label="Nome usado no envio" value={lead.company_name||lead.alternative_name||lead.original_company_name||lead.company} readOnly/><Field label={lead.channel==='whatsapp'?'WhatsApp':'Instagram'} value={contact} readOnly/><Field label="Ramo" value={lead.branch||'—'} readOnly/><Field label={lead.channel==='whatsapp'?'Chip':'Perfil'} value={resource} readOnly/><Field label="Status" value={issue?'Dados incompletos':statusLabel(lead.status)} readOnly/><Field label="Posição" value={String(lead.position)} readOnly/><Field label="Agendado para" value={lead.scheduled_date} readOnly/><Field as="textarea" label="Mensagem 1" value={lead.message1||''} readOnly/><Field as="textarea" label="Mensagem 2" value={lead.message2||''} readOnly/><Field as="textarea" label="Mensagem 3" value={lead.message3||''} readOnly/><Field as="textarea" label="Mensagem 4" value={lead.message4||''} readOnly/></div></Drawer>;
}
function AlternativeNameDrawer({lead,onClose,onSaved,onError}:{lead:FinalLead|null;onClose:()=>void;onSaved:(result:AlternativeNameUpdateResult)=>void;onError:(message:string)=>void}){
  const[value,setValue]=useState('');const[saving,setSaving]=useState(false);useEffect(()=>{setValue(lead?.alternative_name??'');},[lead]);
  const save=async()=>{if(!lead)return;setSaving(true);try{const result=await alternativeNameService.update(lead.lead_id,value.trim(),lead.id);onSaved(result);}catch(err){onError(err instanceof Error?err.message:'Tente novamente.');}finally{setSaving(false);}};
  return <Drawer open={Boolean(lead)} title="Editar nome alternativo" description="Somente este campo pode ser alterado aqui. O nome alternativo passa a ser usado nas mensagens e no snapshot enquanto o item ainda não iniciou o envio." onClose={onClose} footer={<><Button variant="secondary" onClick={onClose}>Cancelar</Button><Button loading={saving} onClick={()=>void save()}>Salvar</Button></>}>{lead?<div className="drawer-form"><Field label="Empresa original" value={lead.original_company_name||lead.company} readOnly/><Field label="Nome alternativo (opcional)" value={value} maxLength={160} placeholder="Ex.: Contabilidade Dinastia" onChange={setValue}/></div>:null}</Drawer>;
}
