BEGIN;

CREATE TABLE IF NOT EXISTS public.platform_release_candidates (
  release_candidate_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  release_sequence bigint NOT NULL,
  schema_version integer NOT NULL DEFAULT 2 CHECK (schema_version = 2),
  schema_target text NOT NULL,
  security_baseline text NOT NULL,
  issued_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  production_ready boolean NOT NULL DEFAULT false,
  resume_allowed boolean NOT NULL DEFAULT false,
  manifest jsonb NOT NULL,
  canonical_manifest_sha256 text NOT NULL CHECK (canonical_manifest_sha256 ~ '^[0-9a-f]{64}$'),
  signature_algorithm text NOT NULL DEFAULT 'ed25519' CHECK (signature_algorithm='ed25519'),
  signature_base64 text NULL,
  signature_key_id text NULL,
  signature_verified_at timestamptz NULL,
  component_hashes jsonb NOT NULL DEFAULT '{}'::jsonb,
  docker_digests jsonb NOT NULL DEFAULT '{}'::jsonb,
  homologated_at timestamptz NULL,
  promoted_at timestamptz NULL,
  superseded_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (expires_at > issued_at),
  CHECK (jsonb_typeof(manifest)='object'),
  CHECK (jsonb_typeof(component_hashes)='object'),
  CHECK (jsonb_typeof(docker_digests)='object'),
  UNIQUE (release_sequence, canonical_manifest_sha256)
);

ALTER TABLE public.platform_release_candidates ADD COLUMN IF NOT EXISTS signature_key_id text NULL;
ALTER TABLE public.platform_release_candidates ADD COLUMN IF NOT EXISTS signature_verified_at timestamptz NULL;

CREATE INDEX IF NOT EXISTS platform_release_candidates_sequence_idx
ON public.platform_release_candidates(release_sequence DESC,created_at DESC);

CREATE TABLE IF NOT EXISTS public.platform_release_promotions (
  platform_release_promotions_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  release_candidate_id uuid NOT NULL REFERENCES public.platform_release_candidates(release_candidate_id) ON DELETE RESTRICT,
  release_sequence bigint NOT NULL,
  canonical_manifest_sha256 text NOT NULL,
  component_hashes jsonb NOT NULL,
  docker_digests jsonb NOT NULL,
  schema_target text NOT NULL,
  security_baseline text NOT NULL,
  promoted_at timestamptz NOT NULL DEFAULT now(),
  promoted_by text NOT NULL,
  UNIQUE(release_sequence)
);

ALTER TABLE public.platform_release_candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.platform_release_candidates FORCE ROW LEVEL SECURITY;
ALTER TABLE public.platform_release_promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.platform_release_promotions FORCE ROW LEVEL SECURITY;

COMMIT;
