BEGIN;

CREATE TABLE IF NOT EXISTS public.whatsapp_contacts (
  whatsapp_contacts_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizations_id bigint NOT NULL REFERENCES public.organizations(organizations_id) ON DELETE CASCADE,
  normalized_phone text NULL,
  display_name text NULL,
  leads_id bigint NULL REFERENCES public.leads(leads_id) ON DELETE SET NULL,
  contact_state text NOT NULL DEFAULT 'unknown' CHECK (contact_state IN ('lead','unknown','ignored')),
  ignored_at timestamptz NULL,
  ignored_by_member_id bigint NULL REFERENCES public.organization_members(organization_members_id) ON DELETE SET NULL,
  whatsapp_contacts_created_at timestamptz NOT NULL DEFAULT now(),
  whatsapp_contacts_updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (normalized_phone IS NULL OR normalized_phone ~ '^[0-9]{8,20}$'),
  CHECK ((contact_state='lead' AND leads_id IS NOT NULL) OR contact_state<>'lead')
);
CREATE UNIQUE INDEX IF NOT EXISTS whatsapp_contacts_org_phone_unique
ON public.whatsapp_contacts(organizations_id,normalized_phone) WHERE normalized_phone IS NOT NULL;
CREATE INDEX IF NOT EXISTS whatsapp_contacts_org_state_idx ON public.whatsapp_contacts(organizations_id,contact_state,whatsapp_contacts_id);
CREATE INDEX IF NOT EXISTS whatsapp_contacts_org_lead_idx ON public.whatsapp_contacts(organizations_id,leads_id) WHERE leads_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.whatsapp_contact_aliases (
  whatsapp_contact_aliases_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizations_id bigint NOT NULL REFERENCES public.organizations(organizations_id) ON DELETE CASCADE,
  whatsapp_contacts_id bigint NOT NULL REFERENCES public.whatsapp_contacts(whatsapp_contacts_id) ON DELETE CASCADE,
  instances_id bigint NULL REFERENCES public.instances(instances_id) ON DELETE CASCADE,
  chips_id bigint NULL REFERENCES public.chips(chips_id) ON DELETE CASCADE,
  alias_type text NOT NULL CHECK (alias_type IN ('phone','jid','lid')),
  alias_value text NOT NULL,
  whatsapp_contact_aliases_created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (length(btrim(alias_value)) > 0)
);
CREATE UNIQUE INDEX IF NOT EXISTS whatsapp_contact_aliases_org_alias_unique
ON public.whatsapp_contact_aliases(organizations_id,alias_type,alias_value);
CREATE INDEX IF NOT EXISTS whatsapp_contact_aliases_contact_idx
ON public.whatsapp_contact_aliases(organizations_id,whatsapp_contacts_id);

ALTER TABLE public.conversations ADD COLUMN IF NOT EXISTS whatsapp_contacts_id bigint NULL;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='conversations_whatsapp_contacts_id_fkey') THEN
    ALTER TABLE public.conversations ADD CONSTRAINT conversations_whatsapp_contacts_id_fkey
    FOREIGN KEY (whatsapp_contacts_id) REFERENCES public.whatsapp_contacts(whatsapp_contacts_id) ON DELETE RESTRICT;
  END IF;
END $$;
DROP INDEX IF EXISTS public.conversation_identity_org_chip_jid_unique;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname='conversations_users_id_chips_id_remote_jid_key' AND conrelid='public.conversations'::regclass) THEN
    ALTER TABLE public.conversations DROP CONSTRAINT conversations_users_id_chips_id_remote_jid_key;
  END IF;
END $$;
DROP INDEX IF EXISTS public.conversations_users_id_chips_id_remote_jid_key;
CREATE UNIQUE INDEX IF NOT EXISTS conversations_org_chip_contact_unique
ON public.conversations(organizations_id,chips_id,whatsapp_contacts_id) WHERE whatsapp_contacts_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS conversations_org_contact_idx
ON public.conversations(organizations_id,whatsapp_contacts_id,last_message_at DESC NULLS LAST);
ALTER TABLE public.conversations ALTER COLUMN whatsapp_contacts_id SET NOT NULL;

ALTER TABLE public.queue_items ADD COLUMN IF NOT EXISTS worker_claim_token uuid NULL;
ALTER TABLE public.queue_items ADD COLUMN IF NOT EXISTS worker_claimed_by text NULL;
ALTER TABLE public.queue_items ADD COLUMN IF NOT EXISTS worker_lease_expires_at timestamptz NULL;
ALTER TABLE public.queue_items ADD COLUMN IF NOT EXISTS worker_max_attempts integer NOT NULL DEFAULT 5;
ALTER TABLE public.queue_items ADD COLUMN IF NOT EXISTS worker_dlq_at timestamptz NULL;
ALTER TABLE public.queue_items ADD COLUMN IF NOT EXISTS worker_dlq_reason text NULL;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='queue_items_worker_max_attempts_positive') THEN
    ALTER TABLE public.queue_items ADD CONSTRAINT queue_items_worker_max_attempts_positive CHECK(worker_max_attempts BETWEEN 1 AND 20);
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS queue_items_worker_lease_idx ON public.queue_items(organizations_id,worker_lease_expires_at) WHERE worker_claim_token IS NOT NULL;
CREATE INDEX IF NOT EXISTS queue_items_worker_dlq_idx ON public.queue_items(organizations_id,worker_dlq_at) WHERE worker_dlq_at IS NOT NULL;

ALTER TABLE public.queue_item_dispatch_parts ADD COLUMN IF NOT EXISTS queue_item_dispatch_parts_operation_id text NULL;
ALTER TABLE public.queue_item_dispatch_parts ADD COLUMN IF NOT EXISTS queue_item_dispatch_parts_lease_expires_at timestamptz NULL;
ALTER TABLE public.queue_item_dispatch_parts ADD COLUMN IF NOT EXISTS queue_item_dispatch_parts_max_attempts integer NOT NULL DEFAULT 5;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname='queue_item_dispatch_parts_queue_item_dispatch_parts_state_check') THEN
    ALTER TABLE public.queue_item_dispatch_parts DROP CONSTRAINT queue_item_dispatch_parts_queue_item_dispatch_parts_state_check;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='queue_item_dispatch_parts_state_r60_check' AND conrelid='public.queue_item_dispatch_parts'::regclass) THEN
    ALTER TABLE public.queue_item_dispatch_parts ADD CONSTRAINT queue_item_dispatch_parts_state_r60_check
    CHECK (queue_item_dispatch_parts_state IN ('pending','processing','sent','failed','reconciliation_required','skipped','dlq'));
  END IF;
END $$;
CREATE UNIQUE INDEX IF NOT EXISTS queue_item_dispatch_parts_operation_unique
ON public.queue_item_dispatch_parts(organizations_id,queue_item_dispatch_parts_operation_id)
WHERE queue_item_dispatch_parts_operation_id IS NOT NULL;

-- R60 presence/typing é Realtime Presence. A tabela histórica permanece apenas até reset/migration,
-- sem novas writes pelos RPCs R60.
COMMENT ON TABLE public.conversation_presence IS 'LEGACY R59: R60 usa Realtime Presence; nenhuma API R60 escreve nesta tabela.';

COMMIT;
