import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const errors=[];const passes=[];
const expectedSql=['00_MAINTENANCE_BOOTSTRAP.sql','01_SUPPLY_CHAIN_BOOTSTRAP.sql','02_PRECHECK.sql','03_RESET_MESSAGING_HOMOLOGATION.sql','04_MESSAGING_SCHEMA_R60.sql','05_CONTACT_IDENTITY_R60.sql','06_MESSAGING_RPC_R60.sql','07_RLS_R60.sql','08_WORKER_GATING_R60.sql','09_SECURITY_ACL_R60.sql','10_PAIRING_R60.sql','10A_RETENTION_R60.sql','10B_SUPPLY_CHAIN_HARDENING_R60.sql','10C_PRODUCTION_RESUME_GATE_R60.sql','11_SCHEMA_GATE.sql','12_HOMOLOGATION_SMOKE.sql'];
const expectedResources={manager:'64639e1cdb9d730850dcd79d25547b0a2db0e3655e1dd4d38eb00df67893693d',worker:'385fb4ac59a87f77b40cd7eab0b61c78cc6804a64b6435e29593e8d506f37973',gateway:'8a8c6d8d29db16fabf6587c92062a07b19c6cff548bc6beb55d1f55e89b6f1aa',capture:'fec360d561c45770cc56ba35e756f8c3b9762277a6f8205a7a93f9ee46c822f1',instagram:'f8826927aaf2d199f1e960ce47f3934433e697c37f76289af2870971449e20d7'};
const expectedManagerZip='728a52e4deed553a1b515c0e012da4626549f9ebe13921132f491daf6e37b516';
function rel(p){return path.relative(root,p).replaceAll(path.sep,'/');}function read(p){return fs.readFileSync(path.join(root,p),'utf8');}function sha(p){return crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex');}
function ok(name,cond,detail=''){if(cond)passes.push(name);else errors.push(`${name}${detail?`: ${detail}`:''}`);}function has(file,...tokens){const s=read(file);return tokens.every(t=>s.includes(t));}
function walk(dir=root,out=[]){for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(['node_modules','.git','dist','.cache'].includes(e.name))continue;const p=path.join(dir,e.name);if(e.isDirectory())walk(p,out);else out.push(p);}return out;}
function treeHash(files){const rows=[...files].sort((a,b)=>a<b?-1:a>b?1:0).map(file=>`${file}\0${sha(file)}\n`).join('');return crypto.createHash('sha256').update(rows,'utf8').digest('hex');}
const generated=new Set(['R60_CANDIDATE_MANIFEST.json','R60_CANDIDATE_HASHES.txt']);
function canonicalSourceHash(){return treeHash(walk().map(rel).filter(f=>!generated.has(f)));}
const supplyFiles=['R60_RELEASE_MANIFEST_SCHEMA_V2.json','server/platform/release.ts','server/routes/system/public-config.ts','scripts/publish-r60-candidate.mjs','scripts/r60-node22-vercel-runtime-test.mjs','scripts/r60-supply-chain-test.mjs','scripts/r60-control-plane-test.mjs','sql/r60/01_SUPPLY_CHAIN_BOOTSTRAP.sql','sql/r60/10B_SUPPLY_CHAIN_HARDENING_R60.sql','sql/r60/10C_PRODUCTION_RESUME_GATE_R60.sql'];
function supplyHash(){return treeHash(supplyFiles);}
function orderedSql(){return crypto.createHash('sha256').update(expectedSql.map(f=>`${sha(`sql/r60/${f}`)}  sql/r60/${f}\n`).join('')).digest('hex');}

const pkg=JSON.parse(read('package.json'));ok('version:2.4.0-R60.8',pkg.version==='2.4.0-R60.8',pkg.version);ok('package:verify:r60',pkg.scripts?.['verify:r60']==='node scripts/verify-r60.mjs');ok('package:no verify:r59',!JSON.stringify(pkg.scripts||{}).toLowerCase().includes('r59'));
const sqlDir=path.join(root,'sql/r60');const actualSql=fs.readdirSync(sqlDir).filter(x=>x.endsWith('.sql'));ok('sql:16',actualSql.length===16);ok('sql:set/order names',expectedSql.every(x=>actualSql.includes(x))&&actualSql.every(x=>expectedSql.includes(x)));
const ledger=read('R60_SQL_SHA256SUMS.txt').split(/\r?\n/).filter(Boolean);const sqlMap=new Map();let ledgerOrdered='';for(const line of ledger){if(line.startsWith('ORDERED_SET_SHA256=')){ledgerOrdered=line.split('=')[1];continue;}const m=line.match(/^([0-9a-f]{64})  (sql\/r60\/.+)$/i);if(m)sqlMap.set(m[2],m[1].toLowerCase());}ok('sql:ledger16',sqlMap.size===16);for(const f of expectedSql)ok(`sql:${f}`,sqlMap.get(`sql/r60/${f}`)===sha(`sql/r60/${f}`));ok('sql:ordered',ledgerOrdered===orderedSql(),`${ledgerOrdered} != ${orderedSql()}`);

const manifest=JSON.parse(read('R60_CANDIDATE_MANIFEST.json'));const schema=JSON.parse(read('R60_RELEASE_MANIFEST_SCHEMA_V2.json'));
ok('manifest:schemaVersion2',manifest.schemaVersion===2&&schema.properties?.schemaVersion?.const===2);ok('manifest:identity',manifest.releaseId==='vinsansi-r60-seq60-r60.8'&&manifest.release==='2.4.0-R60.8'&&manifest.releaseStage==='candidate');ok('manifest:closed',manifest.productionReady===false&&manifest.resumeAllowed===false&&manifest.signature?.algorithm==='ed25519'&&manifest.signature.keyId===null&&manifest.signature.signature===null);ok('manifest:gate',manifest.releaseSequence===60&&manifest.schemaTarget==='r60'&&manifest.securityBaseline==='r60-security-baseline-v1');ok('manifest:no image digests invented',Object.keys(manifest.imageDigests||{}).length===0);ok('manifest:no production distribution invented',manifest.distribution?.manager?.url===null&&manifest.distribution?.manager?.sha256===null);
ok('manifest:versions',manifest.manager.latestVersion==='1.5.77'&&manifest.components.worker.version==='3.14.8'&&manifest.components.gateway.version==='1.2.31'&&manifest.capture.latestVersion==='1.0.53'&&manifest.instagram.latestVersion==='2.0.8'&&manifest.components.evolution.version==='0.7.2');for(const [k,v] of Object.entries(expectedResources))ok(`manifest:resource:${k}`,manifest.resources?.[k]?.sha256===v);
for(const req of schema.required||[])ok(`schema:required:${req}`,Object.hasOwn(manifest,req));ok('schema:production requires signature/digests/artifact',JSON.stringify(schema).includes('imageDigests')&&JSON.stringify(schema).includes('^https://')&&JSON.stringify(schema).includes('sha256:[0-9a-f]{64}'));

const release=read('server/platform/release.ts');ok('supply:authority candidates',release.includes("from('platform_release_candidates')"));ok('supply:no platform_tools authority read',!release.match(/from\(['"]platform_tools['"]\)[\s\S]{0,200}select\([^)]*release_manifest/i));ok('supply:platform_tools compatibility projection',release.includes('reconcileLegacyToolCatalog'));ok('supply:bootstrap bundled candidate',release.includes('directBootstrapCandidate'));ok('supply:newer bundled candidate upgrades without rollback downgrade',release.includes('shouldBootstrapBundled')&&release.includes('bundledGenerated>currentGenerated')&&release.includes('if(!shouldBootstrapBundled)return current'));ok('supply:schema2 enforced',release.includes('schemaVersion!==2')||release.includes('schemaVersion !== 2'));ok('supply:ed25519',release.includes('verifyManifestEd25519')&&release.includes('canonicalManifestSha256'));ok('supply:production fixture blocked',has('sql/r60/10B_SUPPLY_CHAIN_HARDENING_R60.sql','LOCAL_TEST_ONLY','release_downgrade_rejected','immutable_promotion_mismatch'));ok('supply:node22 vercel runtime gate',pkg.scripts?.['verify:vercel-runtime']==='node scripts/r60-node22-vercel-runtime-test.mjs'&&release.includes("with { type: 'json' }")&&has('scripts/r60-node22-vercel-runtime-test.mjs','api-system:node22-module-load-before-handler','ERR_IMPORT_ATTRIBUTE_MISSING'));
const publicConfig=read('server/routes/system/public-config.ts');ok('control-plane:public config release authority',publicConfig.includes('platformRelease')&&publicConfig.includes('loadPlatformRelease'));ok('control-plane:no release_manifest fallback',!publicConfig.includes('release_manifest'));

const snap=JSON.parse(read('scripts/r60-manager-contract-snapshot.json'));ok('contract:manager',snap.managerVersion==='1.5.77'&&snap.managerZipSha256===expectedManagerZip);ok('contract:worker/gateway',snap.workerVersion==='3.14.8'&&snap.gatewayVersion==='1.2.31');ok('contract:release gate',snap.manifestSchemaVersion===2&&snap.releaseSequence===60&&snap.schemaTarget==='r60'&&snap.securityBaseline==='r60-security-baseline-v1'&&!snap.productionReady&&!snap.resumeAllowed);for(const [k,v] of Object.entries(expectedResources))ok(`contract:resource:${k}`,snap.resourceHashes?.[k]===v);
const matrix=JSON.parse(read('scripts/r60-contract-matrix.json'));const byOp=new Map(matrix.contracts.map(x=>[x.operation,x]));for(const [op,args] of Object.entries(snap.workerRpcCalls)){const row=byOp.get(op);ok(`contract:rpc:${op}`,Boolean(row));if(row)ok(`contract:args:${op}`,JSON.stringify(row.arguments)===JSON.stringify(args),`${JSON.stringify(row.arguments)} != ${JSON.stringify(args)}`);}
ok('contract:gateway',snap.gateway.crmPath==='/api/whatsapp/evolution-webhook'&&snap.gateway.remoteJid&&snap.gateway.remoteJidAlt&&snap.gateway.dropNonDirectBeforeCrm);

const actor=read('sql/r60/06_MESSAGING_RPC_R60.sql');ok('r60:canonical contacts',has('sql/r60/04_MESSAGING_SCHEMA_R60.sql','whatsapp_contacts','whatsapp_contact_aliases','conversations_org_chip_contact_unique'));ok('r60:states',has('sql/r60/04_MESSAGING_SCHEMA_R60.sql',"'lead','unknown','ignored'"));ok('r60:unknown label',read('src/repositories/conversations/conversations.repository.ts').includes('Não cadastrado'));ok('r60:ignore restore promotion',has('sql/r60/06_MESSAGING_RPC_R60.sql','service_stage5_ignore_contact','service_stage5_restore_contact','service_stage5_promote_unknown_contact'));ok('r60:promotion permission',actor.includes("r60_require_actor(p_organizations_id,'leads.create')"));ok('r60:actor auth uid',actor.includes('auth.uid()'));ok('r60:human actor permission does not call service-only helper',!actor.match(/r60_require_actor[\s\S]{0,2600}auth_user_has_organization_permission/)&&actor.includes("p.permissions_sensitivity<>'platform_only'"));ok('r60:cursor',actor.includes('p_cursor_at timestamptz')&&actor.includes('p_before_id bigint'));
const conv=read('src/pages/ConversationsPage.tsx');ok('r60:realtime incremental',conv.includes(".on('postgres_changes'")&&conv.includes('applyConversationDelta'));ok('r60:no normal polling',! /setInterval\([^)]*syncConversationList/s.test(conv));
const convRepo=read('src/repositories/conversations/conversations.repository.ts');ok('r60:inbox no implicit auto-read',conv.includes('Abrir a Inbox não pode')&&conv.includes('? current : null'));ok('r60:inbox server search',conv.includes('debouncedSearch')&&convRepo.includes("params.set('search',search.trim())"));ok('r60:send reconciliation cannot become send failure',conv.includes('jamais pode transformar um envio confirmado')&&conv.includes("void loadMessages(selectedConversation.id, true).catch(() => undefined)"));
const webhook=read('server/routes/whatsapp/evolution-webhook.ts');ok('r60:webhook HMAC',webhook.includes('x-evolution-signature')&&webhook.includes('x-evolution-instance-id'));ok('r60:JID LID',webhook.includes('remoteJidAlt'));ok('r60:non-direct defense',webhook.includes('nonDirect')&&webhook.includes('non_operational_event'));ok('r60:text first',['[Imagem]','[Áudio]','[Figurinha]','[Documento]'].every(x=>webhook.includes(x)));
ok('r60:RLS FORCE',has('sql/r60/07_RLS_R60.sql','FORCE ROW LEVEL SECURITY','DROP POLICY IF EXISTS'));ok('r60:machine ACL',has('sql/r60/09_SECURITY_ACL_R60.sql','REVOKE ALL ON FUNCTION','service_role'));ok('r60:resume exclusive',has('sql/r60/00_MAINTENANCE_BOOTSTRAP.sql','resume_allowed_requires_service_arm_messaging_resume_gate_r60'));ok('r60:candidate cannot arm',has('sql/r60/10B_SUPPLY_CHAIN_HARDENING_R60.sql','candidate_manifest_must_be_unsigned_and_closed'));ok('r60:production gate',has('sql/r60/10C_PRODUCTION_RESUME_GATE_R60.sql','signature_verified_at','release_sequence<>60','platform_release_promotions'));

const gate=read('sql/r60/11_SCHEMA_GATE.sql');for(const t of ['organization_messaging_state','platform_release_candidates','whatsapp_contacts','whatsapp_contact_aliases','worker_claim_dispatch_job','service_arm_messaging_resume_gate_r60'])ok(`gate:${t}`,gate.includes(t));const smoke=read('sql/r60/12_HOMOLOGATION_SMOKE.sql');for(const t of ['groupDrop','broadcastDrop','newsletterDrop','unknownState','ignoredDrop','restore','promotion','jidLidSameCanonicalResolver','duplicateNoop','sameStatusNoop','statusMonotonic','crossTenantScoped','memberImpersonationBlocked','machineOnlyAcl','vaultNotBrowserExposed','candidateCannotArmResume','wrongSequenceBlocked'])ok(`smoke:${t}`,smoke.includes(`'${t}'`));

const all=walk();const text=all.filter(f=>/\.(ts|tsx|js|mjs|cjs|json|sql|md|txt|html|css)$/i.test(f));const garbage=all.filter(f=>{const r=rel(f);return /(^|\/)(node_modules|\.git)(\/|$)/.test(r)||/(^|\/)\.env$/.test(r)||/\.(log|bak|tmp|map|zip)$/i.test(r)||/(^|[-_.])(APPLY|PATCH)([-_.]|$)/i.test(path.basename(r));});ok('garbage:none',garbage.length===0,garbage.map(rel).join(','));const secrets=[];for(const f of text){const s=fs.readFileSync(f,'utf8');if(/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/.test(s))secrets.push(rel(f));if(/\bsb_secret_[A-Za-z0-9_-]{20,}\b/.test(s))secrets.push(rel(f));if(/\beyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{10,}\b/.test(s))secrets.push(rel(f));}ok('secrets:none',secrets.length===0,secrets.join(','));
const jsonErr=[];for(const f of all.filter(f=>f.endsWith('.json'))){try{JSON.parse(fs.readFileSync(f,'utf8'));}catch(e){jsonErr.push(`${rel(f)}:${e.message}`)}}ok('json:parse',jsonErr.length===0,jsonErr.join(';'));
const importErr=[];const specRe=/(?:import|export)\s+(?:[^'"()]*?\s+from\s+)?['"](\.[^'"]+)['"]|import\s*\(\s*['"](\.[^'"]+)['"]\s*\)|require\s*\(\s*['"](\.[^'"]+)['"]\s*\)/g;function resolveRelative(from,spec){const base=path.resolve(path.dirname(from),spec),c=[base];if(base.endsWith('.js')){const stem=base.slice(0,-3);c.push(stem+'.ts',stem+'.tsx',stem+'.js',stem+'.jsx')}for(const e of ['.ts','.tsx','.js','.jsx','.mjs','.cjs','.json'])c.push(base+e);for(const e of ['.ts','.tsx','.js','.jsx','.mjs','.cjs','.json'])c.push(path.join(base,'index'+e));return c.find(p=>fs.existsSync(p)&&fs.statSync(p).isFile());}function exactCase(p){const abs=path.resolve(p),parsed=path.parse(abs);let cur=parsed.root;for(const part of abs.slice(parsed.root.length).split(path.sep).filter(Boolean)){let names;try{names=fs.readdirSync(cur)}catch{return false}if(!names.includes(part))return false;cur=path.join(cur,part)}return true}for(const f of all.filter(f=>/\.(ts|tsx|js|jsx|mjs|cjs)$/.test(f))){const s=fs.readFileSync(f,'utf8');for(const m of s.matchAll(specRe)){const spec=m[1]||m[2]||m[3];if(rel(f)==='scripts/r60-node22-vercel-runtime-test.mjs'&&spec==='./data.json')continue;const found=resolveRelative(f,spec);if(!found)importErr.push(`${rel(f)} -> ${spec}`);else if(!exactCase(found))importErr.push(`${rel(f)} -> ${spec} casing`);}}ok('imports:relative/casing',importErr.length===0,importErr.slice(0,20).join(';'));

const hashesPath=path.join(root,'R60_CANDIDATE_HASHES.txt');ok('hashes:summary exists',fs.existsSync(hashesPath));if(fs.existsSync(hashesPath)){const entries=new Map(read('R60_CANDIDATE_HASHES.txt').split(/\r?\n/).map(x=>x.match(/^([A-Z0-9_]+)=([0-9a-f]{64})$/i)).filter(Boolean).map(m=>[m[1],m[2].toLowerCase()]));ok('hashes:source',entries.get('CRM_CANONICAL_SOURCE_SHA256')===canonicalSourceHash());ok('hashes:supply',entries.get('SUPPLY_CHAIN_SHA256')===supplyHash());ok('hashes:verify',entries.get('VERIFY_R60_SHA256')===sha('scripts/verify-r60.mjs'));ok('hashes:manifest',entries.get('MANIFEST_SHA256')===sha('R60_CANDIDATE_MANIFEST.json'));ok('hashes:sql',entries.get('SQL_ORDERED_SET_SHA256')===orderedSql());ok('hashes:manager zip',entries.get('MANAGER_CANDIDATE_ZIP_SHA256')===expectedManagerZip);}
if(errors.length){console.error(`verify:r60 FAIL ${passes.length} pass / ${errors.length} fail`);for(const e of errors)console.error('FAIL '+e);process.exit(1);}console.log(`verify:r60 PASS ${passes.length}/${passes.length}`);
