import fs from 'node:fs';import path from 'node:path';const root=path.resolve(import.meta.dirname,'..');const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');const exists=(p)=>fs.existsSync(path.join(root,p));const expect=(v,m)=>{if(!v)throw new Error(m)};
for(const file of ['PATCH-ETAPA-4-CONTEXTO-EXECUTORES.sql','PATCH-CORRETIVO-ETAPA-4-CONTEXTO-MEMBERSHIP.sql','APLICAR-NO-SUPABASE-v1.3.0.sql','supabase/migrations/20260822120000_executor_organization_context.sql','supabase/migrations/20260822150000_executor_membership_context_hardening.sql','server/tools/executor.ts','server/routes/tools/executor/runtime.ts','server/routes/tools/router.ts','api/tools.ts','vercel.json'])expect(exists(file),`${file} ausente`);
const sql=read('supabase/migrations/20260822120000_executor_organization_context.sql');for(const token of ['tool_installation_credentials','tool_user_sessions','tool_executor_pairings','service_executor_member_context','interval \'10 minutes\'','DROP FUNCTION IF EXISTS public.service_get_operational_settings'])expect(sql.includes(token),`Contrato SQL ausente: ${token}`);
const executor=read('server/tools/executor.ts');expect(executor.includes("crypto.subtle.digest('SHA-256'")&&executor.includes('SESSION_IDLE_DAYS = 30'),'Tokens opacos/expiração não implementados.');expect(executor.includes('service_executor_member_context'),'Contexto de membro não derivado no backend.');expect(executor.includes('organization_members_id:memberId')&&executor.includes('user_session_context_mismatch'),'Sessão humana não está pinada ao member_id canônico.');
const mapsPair=read('server/routes/maps/pair.ts');expect(mapsPair.includes('expectedMemberId:Number(current.data.authorized_by_member_id)')&&mapsPair.includes('pairing_context_incomplete'),'Pairing Maps não valida a cadeia canônica completa.');
const mapsAuthorize=read('src/pages/MapsExtensionAuthorizePage.tsx');expect(mapsAuthorize.includes('organizationId: Number(selectedOrganizationId)')&&mapsAuthorize.includes('organization.memberId !== null'),'Autorização Maps não exige organização escolhida com membership ativa.');
const worker=read('../Gerenciador/resources/worker/src/worker.js');expect(!/SUPABASE_SERVICE_ROLE_KEY|createClient\(/.test(worker),'Worker ainda recebe service_role/Supabase direto.');expect(!/users_id|p_users_id|body\.user_id/.test(worker),'Worker ainda usa users_id como tenant.');expect(worker.includes('TOOL_INSTALLATION_CREDENTIAL'),'Worker sem credencial técnica.');
const runtime=read('server/routes/tools/executor/runtime.ts');expect(runtime.includes('TABLES=new Set')&&runtime.includes("eq('organizations_id',organizationId)"),'Runtime sem allowlist/pinagem organizacional.');
const vercel=JSON.parse(read('vercel.json'));const executorRewrite=vercel.rewrites?.find((route)=>route.source==='/api/tools/executor/:action');expect(executorRewrite?.destination==='/api/tools?route=executor/:action','Roteamento Vercel do control plane ausente ou divergente.');
const router=read('server/routes/tools/router.ts');for(const action of ['config','context','heartbeat','logout','pair-exchange','pair-start','runtime','switch'])expect(router.includes(`executor/${action}`),`Dispatcher Vercel sem ação ${action}.`);
const provision=read('server/routes/system/desktop/worker-provision.ts');for(const token of ['version: 5','encryptedCloudflareTunnelToken','encryptedInstallationCredential','encryptedUserSession'])expect(provision.includes(token),`Provisionamento CRM sem ${token}.`);expect(!/encryptedServiceRoleKey|evolutionGlobalApiKey|evolutionPostgresPassword/.test(provision),'Provisionamento CRM voltou a expor segredo proibido.');
const instagram=read('../Instagram-Extension/popup.js');const maps=read('../Google-Maps-Extractor/src/platform-api.js');for(const [name,value] of [['Instagram',instagram],['Maps',maps]]){expect(value.includes('heartbeat')&&value.includes('organization'),`${name} sem contexto/heartbeat.`)}
const manager=read('../Gerenciador/src/main/config/SecureConfigService.ts');expect(manager.includes('safeStorage')&&manager.includes('TOOL_INSTALLATION_CREDENTIAL')&&!manager.includes('`SUPABASE_SERVICE_ROLE_KEY='),'Gerenciador não removeu service_role do Worker.');
console.log('Etapa 4: contratos estáticos verificados.');
