BEGIN;

-- ETAPA 7: identidade canônica, deduplicação transversal e supressão de contato.

CREATE OR REPLACE FUNCTION public.normalize_identity_phone(p_value text)
RETURNS text LANGUAGE plpgsql IMMUTABLE SET search_path TO pg_catalog AS $$
DECLARE v text := regexp_replace(coalesce(p_value,''),'[^0-9]','','g');
BEGIN
  IF v LIKE '00%' THEN v:=substr(v,3); END IF;
  IF v='' THEN RETURN ''; END IF;
  IF v LIKE '55%' THEN RETURN v; END IF;
  IF length(v) IN (10,11) THEN RETURN '55'||v; END IF;
  RETURN v;
END; $$;

CREATE OR REPLACE FUNCTION public.normalize_identity_instagram(p_value text)
RETURNS text LANGUAGE sql IMMUTABLE SET search_path TO pg_catalog AS $$
  SELECT lower(regexp_replace(split_part(split_part(regexp_replace(trim(coalesce(p_value,'')),'^https?://(www\.)?instagram\.com/','','i'), '/', 1), '?', 1),'^@','',''));
$$;

CREATE OR REPLACE FUNCTION public.normalize_identity_domain(p_value text)
RETURNS text LANGUAGE plpgsql IMMUTABLE SET search_path TO pg_catalog AS $$
DECLARE v text := lower(trim(coalesce(p_value,'')));
BEGIN
  v:=regexp_replace(v,'^https?://','','i');
  v:=regexp_replace(v,'^www\.','','i');
  v:=split_part(v,'/',1); v:=split_part(v,'?',1); v:=split_part(v,'#',1);
  IF v IN ('','google.com','google.com.br','instagram.com','facebook.com','fb.com','wa.me','whatsapp.com','bit.ly','tinyurl.com','goo.gl','t.co','linktr.ee') THEN RETURN ''; END IF;
  RETURN v;
END; $$;

CREATE OR REPLACE FUNCTION public.normalize_identity_maps(p_value text)
RETURNS text LANGUAGE sql IMMUTABLE SET search_path TO pg_catalog AS $$
  SELECT lower(regexp_replace(trim(coalesce(p_value,'')),'/+$','','g'));
$$;

ALTER TABLE public.leads
  ADD COLUMN IF NOT EXISTS leads_normalized_phone text,
  ADD COLUMN IF NOT EXISTS leads_normalized_instagram text,
  ADD COLUMN IF NOT EXISTS leads_normalized_domain text,
  ADD COLUMN IF NOT EXISTS leads_normalized_maps text,
  ADD COLUMN IF NOT EXISTS leads_identity_hash text,
  ADD COLUMN IF NOT EXISTS canonical_lead_id bigint REFERENCES public.leads(leads_id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS duplicate_reason text;

CREATE TABLE IF NOT EXISTS public.lead_identity_registry (
  lead_identity_registry_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id bigint NOT NULL REFERENCES public.users(users_id) ON DELETE CASCADE,
  identity_type text NOT NULL CHECK(identity_type IN ('phone','instagram','domain','maps')),
  identity_value text NOT NULL,
  canonical_lead_id bigint NOT NULL REFERENCES public.leads(leads_id) ON DELETE CASCADE,
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(users_id,identity_type,identity_value)
);

CREATE TABLE IF NOT EXISTS public.contact_suppressions (
  contact_suppressions_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id bigint NOT NULL REFERENCES public.users(users_id) ON DELETE CASCADE,
  identity_type text NOT NULL CHECK(identity_type IN ('phone','instagram','domain','maps')),
  identity_value text NOT NULL,
  reason text NOT NULL,
  source_lead_id bigint REFERENCES public.leads(leads_id) ON DELETE SET NULL,
  source_sent_id bigint REFERENCES public.sents(sents_id) ON DELETE SET NULL,
  is_active boolean NOT NULL DEFAULT true,
  expires_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(users_id,identity_type,identity_value)
);

CREATE INDEX IF NOT EXISTS leads_identity_phone_idx ON public.leads(users_id,leads_normalized_phone) WHERE leads_normalized_phone<>'';
CREATE INDEX IF NOT EXISTS leads_identity_instagram_idx ON public.leads(users_id,leads_normalized_instagram) WHERE leads_normalized_instagram<>'';
CREATE INDEX IF NOT EXISTS leads_identity_domain_idx ON public.leads(users_id,leads_normalized_domain) WHERE leads_normalized_domain<>'';
CREATE INDEX IF NOT EXISTS leads_identity_maps_idx ON public.leads(users_id,leads_normalized_maps) WHERE leads_normalized_maps<>'';
CREATE INDEX IF NOT EXISTS leads_canonical_idx ON public.leads(users_id,canonical_lead_id) WHERE canonical_lead_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS contact_suppressions_active_idx ON public.contact_suppressions(users_id,identity_type,identity_value) WHERE is_active;

ALTER TABLE public.lead_identity_registry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_suppressions ENABLE ROW LEVEL SECURITY;
CREATE POLICY lead_identity_registry_own_select ON public.lead_identity_registry FOR SELECT TO authenticated USING(users_id=public.ensure_current_user());
CREATE POLICY contact_suppressions_own_select ON public.contact_suppressions FOR SELECT TO authenticated USING(users_id=public.ensure_current_user());
REVOKE INSERT,UPDATE,DELETE ON public.lead_identity_registry,public.contact_suppressions FROM anon,authenticated;
GRANT SELECT ON public.lead_identity_registry,public.contact_suppressions TO authenticated;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.lead_identity_registry,public.contact_suppressions TO service_role;

INSERT INTO public.audit_transition_rules(entity_type,from_status_id,to_status_id,action_key)
VALUES ('lead',2,7,'mark_duplicate'),('lead',3,7,'mark_duplicate'),('lead',6,7,'mark_duplicate')
ON CONFLICT(entity_type,from_status_id,to_status_id) DO UPDATE SET is_active=true,action_key=excluded.action_key;

CREATE OR REPLACE FUNCTION public.prepare_lead_identity()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public,extensions AS $$
DECLARE v_canonical bigint; v_reason text;
BEGIN
  NEW.leads_normalized_phone:=public.normalize_identity_phone(NEW.leads_phone);
  NEW.leads_normalized_instagram:=public.normalize_identity_instagram(NEW.leads_instagram);
  NEW.leads_normalized_domain:=public.normalize_identity_domain(NEW.leads_website);
  NEW.leads_normalized_maps:=public.normalize_identity_maps(NEW.leads_maps);
  NEW.leads_identity_hash:=encode(extensions.digest(concat_ws('|',NEW.leads_normalized_phone,NEW.leads_normalized_instagram,NEW.leads_normalized_domain,NEW.leads_normalized_maps),'sha256'),'hex');

  SELECT r.canonical_lead_id, r.identity_type||':'||r.identity_value
  INTO v_canonical,v_reason
  FROM public.lead_identity_registry r
  WHERE r.users_id=NEW.users_id AND r.canonical_lead_id<>coalesce(NEW.leads_id,-1)
    AND ((r.identity_type='phone' AND r.identity_value=NEW.leads_normalized_phone AND NEW.leads_normalized_phone<>'')
      OR (r.identity_type='instagram' AND r.identity_value=NEW.leads_normalized_instagram AND NEW.leads_normalized_instagram<>'')
      OR (r.identity_type='domain' AND r.identity_value=NEW.leads_normalized_domain AND NEW.leads_normalized_domain<>'')
      OR (r.identity_type='maps' AND r.identity_value=NEW.leads_normalized_maps AND NEW.leads_normalized_maps<>''))
  ORDER BY r.canonical_lead_id,r.lead_identity_registry_id LIMIT 1;

  IF v_canonical IS NOT NULL THEN
    NEW.canonical_lead_id:=v_canonical; NEW.duplicate_reason:=v_reason;
    IF NEW.lead_status_id IN (1,2,3,6) THEN NEW.lead_status_id:=7; END IF;
  ELSIF NEW.canonical_lead_id=NEW.leads_id THEN
    NEW.canonical_lead_id:=NULL; NEW.duplicate_reason:=NULL;
  END IF;
  RETURN NEW;
END; $$;

CREATE OR REPLACE FUNCTION public.register_lead_identity()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE v_canonical bigint:=coalesce(NEW.canonical_lead_id,NEW.leads_id);
BEGIN
  IF NEW.leads_normalized_phone<>'' THEN INSERT INTO public.lead_identity_registry(users_id,identity_type,identity_value,canonical_lead_id) VALUES(NEW.users_id,'phone',NEW.leads_normalized_phone,v_canonical) ON CONFLICT(users_id,identity_type,identity_value) DO UPDATE SET last_seen_at=now(); END IF;
  IF NEW.leads_normalized_instagram<>'' THEN INSERT INTO public.lead_identity_registry(users_id,identity_type,identity_value,canonical_lead_id) VALUES(NEW.users_id,'instagram',NEW.leads_normalized_instagram,v_canonical) ON CONFLICT(users_id,identity_type,identity_value) DO UPDATE SET last_seen_at=now(); END IF;
  IF NEW.leads_normalized_domain<>'' THEN INSERT INTO public.lead_identity_registry(users_id,identity_type,identity_value,canonical_lead_id) VALUES(NEW.users_id,'domain',NEW.leads_normalized_domain,v_canonical) ON CONFLICT(users_id,identity_type,identity_value) DO UPDATE SET last_seen_at=now(); END IF;
  IF NEW.leads_normalized_maps<>'' THEN INSERT INTO public.lead_identity_registry(users_id,identity_type,identity_value,canonical_lead_id) VALUES(NEW.users_id,'maps',NEW.leads_normalized_maps,v_canonical) ON CONFLICT(users_id,identity_type,identity_value) DO UPDATE SET last_seen_at=now(); END IF;
  RETURN NEW;
END; $$;

CREATE OR REPLACE FUNCTION public.suppress_lead_identities(p_lead public.leads,p_reason text,p_sent_id bigint DEFAULT NULL)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
BEGIN
  INSERT INTO public.contact_suppressions(users_id,identity_type,identity_value,reason,source_lead_id,source_sent_id)
  SELECT p_lead.users_id,x.t,x.v,p_reason,p_lead.leads_id,p_sent_id
  FROM (VALUES ('phone',p_lead.leads_normalized_phone),('instagram',p_lead.leads_normalized_instagram),('domain',p_lead.leads_normalized_domain),('maps',p_lead.leads_normalized_maps)) x(t,v)
  WHERE x.v IS NOT NULL AND x.v<>''
  ON CONFLICT(users_id,identity_type,identity_value) DO UPDATE SET reason=excluded.reason,source_lead_id=excluded.source_lead_id,source_sent_id=coalesce(excluded.source_sent_id,public.contact_suppressions.source_sent_id),is_active=true,expires_at=NULL,updated_at=now();
END; $$;

CREATE OR REPLACE FUNCTION public.suppress_after_lead_sent()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
BEGIN
  IF NEW.lead_status_id=5 AND (TG_OP='INSERT' OR OLD.lead_status_id IS DISTINCT FROM NEW.lead_status_id) THEN
    PERFORM public.suppress_lead_identities(NEW,'lead_sent',NULL);
  END IF;
  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS prepare_lead_identity_trigger ON public.leads;
CREATE TRIGGER prepare_lead_identity_trigger BEFORE INSERT OR UPDATE OF leads_phone,leads_instagram,leads_website,leads_maps ON public.leads FOR EACH ROW EXECUTE FUNCTION public.prepare_lead_identity();
DROP TRIGGER IF EXISTS register_lead_identity_trigger ON public.leads;
CREATE TRIGGER register_lead_identity_trigger AFTER INSERT OR UPDATE OF leads_phone,leads_instagram,leads_website,leads_maps ON public.leads FOR EACH ROW EXECUTE FUNCTION public.register_lead_identity();
DROP TRIGGER IF EXISTS suppress_after_lead_sent_trigger ON public.leads;
CREATE TRIGGER suppress_after_lead_sent_trigger AFTER INSERT OR UPDATE OF lead_status_id ON public.leads FOR EACH ROW EXECUTE FUNCTION public.suppress_after_lead_sent();

UPDATE public.leads SET leads_phone=leads_phone,leads_instagram=leads_instagram,leads_website=leads_website,leads_maps=leads_maps;

INSERT INTO public.lead_identity_registry(users_id,identity_type,identity_value,canonical_lead_id,first_seen_at,last_seen_at)
SELECT users_id,identity_type,identity_value,min(leads_id),min(leads_created_at),max(leads_updated_at)
FROM (
 SELECT users_id,leads_id,leads_created_at,leads_updated_at,'phone'::text identity_type,leads_normalized_phone identity_value FROM public.leads WHERE leads_normalized_phone<>''
 UNION ALL SELECT users_id,leads_id,leads_created_at,leads_updated_at,'instagram',leads_normalized_instagram FROM public.leads WHERE leads_normalized_instagram<>''
 UNION ALL SELECT users_id,leads_id,leads_created_at,leads_updated_at,'domain',leads_normalized_domain FROM public.leads WHERE leads_normalized_domain<>''
 UNION ALL SELECT users_id,leads_id,leads_created_at,leads_updated_at,'maps',leads_normalized_maps FROM public.leads WHERE leads_normalized_maps<>''
) identities GROUP BY users_id,identity_type,identity_value
ON CONFLICT(users_id,identity_type,identity_value) DO NOTHING;

INSERT INTO public.contact_suppressions(users_id,identity_type,identity_value,reason,source_lead_id)
SELECT l.users_id,x.t,x.v,'historical_final_lead',l.leads_id
FROM public.leads l CROSS JOIN LATERAL (VALUES('phone',l.leads_normalized_phone),('instagram',l.leads_normalized_instagram),('domain',l.leads_normalized_domain),('maps',l.leads_normalized_maps)) x(t,v)
WHERE l.lead_status_id IN (5,8) AND x.v<>''
ON CONFLICT(users_id,identity_type,identity_value) DO UPDATE SET is_active=true,updated_at=now();

CREATE OR REPLACE FUNCTION public.check_lead_identity(p_phone text DEFAULT NULL,p_instagram text DEFAULT NULL,p_website text DEFAULT NULL,p_maps text DEFAULT NULL)
RETURNS TABLE(identity_type text,identity_value text,canonical_lead_id bigint,is_suppressed boolean,suppression_reason text)
LANGUAGE sql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
WITH input AS (
 SELECT 'phone'::text t,public.normalize_identity_phone(p_phone) v UNION ALL
 SELECT 'instagram',public.normalize_identity_instagram(p_instagram) UNION ALL
 SELECT 'domain',public.normalize_identity_domain(p_website) UNION ALL
 SELECT 'maps',public.normalize_identity_maps(p_maps)
), u AS (SELECT public.ensure_current_user() users_id)
SELECT i.t,i.v,r.canonical_lead_id,coalesce(s.is_active AND (s.expires_at IS NULL OR s.expires_at>now()),false),s.reason
FROM input i CROSS JOIN u
LEFT JOIN public.lead_identity_registry r ON r.users_id=u.users_id AND r.identity_type=i.t AND r.identity_value=i.v
LEFT JOIN public.contact_suppressions s ON s.users_id=u.users_id AND s.identity_type=i.t AND s.identity_value=i.v
WHERE i.v<>'';
$$;

GRANT EXECUTE ON FUNCTION public.check_lead_identity(text,text,text,text) TO authenticated;

COMMIT;
