BEGIN;

-- ETAPA 8: Base Permanente como memória consolidada por identidade canônica.

CREATE TABLE IF NOT EXISTS public.permanent_records (
  permanent_records_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id bigint NOT NULL REFERENCES public.users(users_id) ON DELETE CASCADE,
  canonical_lead_id bigint NOT NULL REFERENCES public.leads(leads_id) ON DELETE CASCADE,
  branches_id bigint REFERENCES public.branches(branches_id) ON DELETE SET NULL,
  states_id bigint REFERENCES public.states(states_id) ON DELETE SET NULL,
  cities_id bigint REFERENCES public.cities(cities_id) ON DELETE SET NULL,
  channels_id bigint REFERENCES public.channels(channels_id) ON DELETE SET NULL,
  last_lead_status_id bigint NOT NULL REFERENCES public.lead_status(lead_status_id),
  company_name text NOT NULL,
  normalized_phone text,
  normalized_instagram text,
  normalized_domain text,
  normalized_maps text,
  total_leads integer NOT NULL DEFAULT 1 CHECK(total_leads>=1),
  total_dispatches integer NOT NULL DEFAULT 0 CHECK(total_dispatches>=0),
  first_seen_at timestamptz NOT NULL,
  last_activity_at timestamptz NOT NULL,
  last_sent_at timestamptz,
  is_suppressed boolean NOT NULL DEFAULT false,
  commercial_outcome text,
  operator_notes text,
  record_status text NOT NULL DEFAULT 'active' CHECK(record_status IN ('active','archived')),
  archived_at timestamptz,
  permanent_records_created_at timestamptz NOT NULL DEFAULT now(),
  permanent_records_updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(users_id,canonical_lead_id)
);

CREATE TABLE IF NOT EXISTS public.permanent_record_snapshots (
  permanent_record_snapshots_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id bigint NOT NULL REFERENCES public.users(users_id) ON DELETE CASCADE,
  permanent_records_id bigint NOT NULL REFERENCES public.permanent_records(permanent_records_id) ON DELETE CASCADE,
  reason text NOT NULL,
  snapshot jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS permanent_records_activity_idx ON public.permanent_records(users_id,last_activity_at DESC);
CREATE INDEX IF NOT EXISTS permanent_records_status_idx ON public.permanent_records(users_id,last_lead_status_id,record_status);
CREATE INDEX IF NOT EXISTS permanent_record_snapshots_record_idx ON public.permanent_record_snapshots(permanent_records_id,created_at DESC);

ALTER TABLE public.permanent_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.permanent_record_snapshots ENABLE ROW LEVEL SECURITY;
CREATE POLICY permanent_records_own_select ON public.permanent_records FOR SELECT TO authenticated USING(users_id=public.ensure_current_user());
CREATE POLICY permanent_record_snapshots_own_select ON public.permanent_record_snapshots FOR SELECT TO authenticated USING(users_id=public.ensure_current_user());
REVOKE INSERT,UPDATE,DELETE ON public.permanent_records,public.permanent_record_snapshots FROM anon,authenticated;
GRANT SELECT ON public.permanent_records,public.permanent_record_snapshots TO authenticated;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.permanent_records,public.permanent_record_snapshots TO service_role;

CREATE OR REPLACE FUNCTION public.refresh_permanent_record(p_lead_id bigint,p_reason text DEFAULT 'refresh')
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE
  v_lead public.leads%ROWTYPE; v_canonical bigint; v_base public.leads%ROWTYPE;
  v_status bigint; v_total_leads integer; v_total_dispatches integer; v_first timestamptz; v_last timestamptz; v_last_sent timestamptz; v_suppressed boolean;
  v_id bigint; v_snapshot jsonb;
BEGIN
  SELECT * INTO v_lead FROM public.leads WHERE leads_id=p_lead_id;
  IF NOT FOUND THEN RETURN NULL; END IF;
  v_canonical:=coalesce(v_lead.canonical_lead_id,v_lead.leads_id);
  SELECT * INTO v_base FROM public.leads WHERE leads_id=v_canonical;
  IF NOT FOUND THEN v_base:=v_lead; v_canonical:=v_lead.leads_id; END IF;

  IF NOT EXISTS(SELECT 1 FROM public.leads l WHERE l.users_id=v_lead.users_id AND (l.leads_id=v_canonical OR l.canonical_lead_id=v_canonical) AND l.lead_status_id IN(5,6,7,8)) THEN
    RETURN NULL;
  END IF;

  SELECT l.lead_status_id,l.leads_updated_at INTO v_status,v_last
  FROM public.leads l WHERE l.users_id=v_lead.users_id AND (l.leads_id=v_canonical OR l.canonical_lead_id=v_canonical) AND l.lead_status_id IN(5,6,7,8)
  ORDER BY l.leads_updated_at DESC,l.leads_id DESC LIMIT 1;

  SELECT count(*)::integer,min(l.leads_created_at),max(l.leads_updated_at)
  INTO v_total_leads,v_first,v_last
  FROM public.leads l WHERE l.users_id=v_lead.users_id AND (l.leads_id=v_canonical OR l.canonical_lead_id=v_canonical);

  SELECT count(*)::integer,max(s.sents_sent_at)
  INTO v_total_dispatches,v_last_sent
  FROM public.sents s JOIN public.leads l ON l.leads_id=s.leads_id
  WHERE l.users_id=v_lead.users_id AND (l.leads_id=v_canonical OR l.canonical_lead_id=v_canonical) AND s.sents_sent_at IS NOT NULL;

  SELECT EXISTS(
    SELECT 1 FROM public.contact_suppressions cs
    WHERE cs.users_id=v_lead.users_id AND cs.is_active AND (cs.expires_at IS NULL OR cs.expires_at>now())
      AND ((cs.identity_type='phone' AND cs.identity_value=v_base.leads_normalized_phone)
        OR (cs.identity_type='instagram' AND cs.identity_value=v_base.leads_normalized_instagram)
        OR (cs.identity_type='domain' AND cs.identity_value=v_base.leads_normalized_domain)
        OR (cs.identity_type='maps' AND cs.identity_value=v_base.leads_normalized_maps))
  ) INTO v_suppressed;

  INSERT INTO public.permanent_records(
    users_id,canonical_lead_id,branches_id,states_id,cities_id,channels_id,last_lead_status_id,company_name,
    normalized_phone,normalized_instagram,normalized_domain,normalized_maps,total_leads,total_dispatches,
    first_seen_at,last_activity_at,last_sent_at,is_suppressed
  ) VALUES(
    v_lead.users_id,v_canonical,v_base.branches_id,v_base.states_id,v_base.cities_id,v_base.channels_id,v_status,v_base.leads_name,
    v_base.leads_normalized_phone,v_base.leads_normalized_instagram,v_base.leads_normalized_domain,v_base.leads_normalized_maps,
    greatest(v_total_leads,1),coalesce(v_total_dispatches,0),coalesce(v_first,now()),coalesce(v_last,now()),v_last_sent,coalesce(v_suppressed,false)
  )
  ON CONFLICT(users_id,canonical_lead_id) DO UPDATE SET
    branches_id=excluded.branches_id,states_id=excluded.states_id,cities_id=excluded.cities_id,channels_id=excluded.channels_id,
    last_lead_status_id=CASE WHEN public.permanent_records.record_status='archived' THEN 8 ELSE excluded.last_lead_status_id END,
    company_name=excluded.company_name,normalized_phone=excluded.normalized_phone,normalized_instagram=excluded.normalized_instagram,
    normalized_domain=excluded.normalized_domain,normalized_maps=excluded.normalized_maps,total_leads=excluded.total_leads,
    total_dispatches=excluded.total_dispatches,first_seen_at=excluded.first_seen_at,last_activity_at=excluded.last_activity_at,
    last_sent_at=excluded.last_sent_at,is_suppressed=excluded.is_suppressed,permanent_records_updated_at=now()
  RETURNING permanent_records_id INTO v_id;

  SELECT to_jsonb(pr) INTO v_snapshot FROM public.permanent_records pr WHERE pr.permanent_records_id=v_id;
  INSERT INTO public.permanent_record_snapshots(users_id,permanent_records_id,reason,snapshot)
  VALUES(v_lead.users_id,v_id,p_reason,v_snapshot);
  RETURN v_id;
END; $$;

CREATE OR REPLACE FUNCTION public.refresh_permanent_record_from_lead_trigger()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
BEGIN
  IF NEW.lead_status_id IN(5,6,7,8) OR (TG_OP='UPDATE' AND OLD.lead_status_id IN(5,6,7,8)) THEN
    PERFORM public.refresh_permanent_record(NEW.leads_id,'lead_changed');
  END IF;
  RETURN NEW;
END; $$;

CREATE OR REPLACE FUNCTION public.refresh_permanent_record_from_sent_trigger()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
BEGIN
  IF NEW.leads_id IS NOT NULL THEN PERFORM public.refresh_permanent_record(NEW.leads_id,'dispatch_changed'); END IF;
  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS refresh_permanent_record_lead_trigger ON public.leads;
CREATE TRIGGER refresh_permanent_record_lead_trigger AFTER INSERT OR UPDATE OF lead_status_id,leads_name,leads_phone,leads_instagram,leads_website,leads_maps ON public.leads FOR EACH ROW EXECUTE FUNCTION public.refresh_permanent_record_from_lead_trigger();
DROP TRIGGER IF EXISTS refresh_permanent_record_sent_trigger ON public.sents;
CREATE TRIGGER refresh_permanent_record_sent_trigger AFTER INSERT OR UPDATE OF status_id,sents_sent_at ON public.sents FOR EACH ROW EXECUTE FUNCTION public.refresh_permanent_record_from_sent_trigger();

CREATE OR REPLACE FUNCTION public.archive_permanent_record(p_canonical_lead_id bigint,p_expected_status_id bigint)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE v_users_id bigint:=public.ensure_current_user(); v_id bigint;
BEGIN
  UPDATE public.permanent_records SET record_status='archived',last_lead_status_id=8,archived_at=now(),permanent_records_updated_at=now()
  WHERE users_id=v_users_id AND canonical_lead_id=p_canonical_lead_id AND last_lead_status_id=p_expected_status_id AND record_status<>'archived'
  RETURNING permanent_records_id INTO v_id;
  IF v_id IS NOT NULL THEN
    PERFORM public.append_audit_event('base-permanente','archive_permanent_record','permanent_record',v_id::text,p_canonical_lead_id,NULL,NULL,p_expected_status_id,8,NULL,'{}'::jsonb,v_users_id);
  END IF;
  RETURN v_id;
END; $$;

CREATE OR REPLACE FUNCTION public.update_permanent_record_metadata(p_canonical_lead_id bigint,p_commercial_outcome text,p_operator_notes text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE v_users_id bigint:=public.ensure_current_user();
BEGIN
  UPDATE public.permanent_records SET commercial_outcome=nullif(trim(p_commercial_outcome),''),operator_notes=nullif(trim(p_operator_notes),''),permanent_records_updated_at=now()
  WHERE users_id=v_users_id AND canonical_lead_id=p_canonical_lead_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'permanent_record_not_found'; END IF;
END; $$;

GRANT EXECUTE ON FUNCTION public.archive_permanent_record(bigint,bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_permanent_record_metadata(bigint,text,text) TO authenticated;

DO $$ DECLARE r record; BEGIN
  FOR r IN SELECT DISTINCT coalesce(canonical_lead_id,leads_id) lead_id FROM public.leads WHERE lead_status_id IN(5,6,7,8)
  LOOP PERFORM public.refresh_permanent_record(r.lead_id,'migration_backfill'); END LOOP;
END $$;

COMMIT;
