BEGIN;

-- ETAPA 5: configurações operacionais centralizadas.
-- Substitui localStorage como fonte de verdade e disponibiliza o mesmo contrato
-- para Painel, Worker e Extensão.

CREATE TABLE IF NOT EXISTS public.user_operational_settings (
  user_operational_settings_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id bigint NOT NULL UNIQUE REFERENCES public.users(users_id) ON DELETE CASCADE,
  dispatch_settings jsonb NOT NULL DEFAULT '{
    "whatsapp":{"startTime":"13:00","endTime":"18:00","delayMinSeconds":120,"delayMaxSeconds":120,"perBatch":60,"batches":2,"batchDelayMinutes":60,"dailyLimit":120,"activeDays":["Segunda","Terca","Quarta","Quinta","Sexta"],"batchBehavior":"Respeitar lotes e janela"},
    "instagram":{"profile":"Todos","profiles":["Todos"],"startTime":"13:00","endTime":"18:00","delayMinSeconds":120,"delayMaxSeconds":120,"perBatch":15,"batches":4,"batchDelayMinutes":120,"delayMinutes":120,"dailyLimit":60,"activeDays":["Segunda","Terca","Quarta","Quinta","Sexta"],"batchBehavior":"Respeitar lotes e janela"},
    "chipLevels":{"aquecimento":{"dailyLimit":20,"batchCount":2},"iniciante":{"dailyLimit":40,"batchCount":2},"intermediario":{"dailyLimit":80,"batchCount":2},"avancado":{"dailyLimit":120,"batchCount":2}}
  }'::jsonb,
  import_settings jsonb NOT NULL DEFAULT '{
    "minRating":4,"minReviews":10,
    "safeMode":{"simulationMode":true},
    "instagramLowRating":{"enabled":true,"minRating":3.7,"maxRatingExclusive":4,"minReviews":5},
    "branchRules":[],
    "deduplication":{"enabled":true,"byPhone":true,"bySite":true,"blockBasePermanent":true,"allowSmartReimport":false,"incrementalImport":true},
    "routes":{"whatsapp":true,"instagram":true,"ownSite":true,"aggregators":true,"blockFacebookAsSite":true,"requireConfiguredCategory":true,"rejectOutOfProfile":true},
    "logs":{"enabled":true,"logRejected":true,"logRejectionReason":true}
  }'::jsonb,
  extension_runtime_config jsonb,
  operational_timezone text NOT NULL DEFAULT 'America/Sao_Paulo',
  operational_cutoff_hour smallint NOT NULL DEFAULT 22 CHECK (operational_cutoff_hour BETWEEN 0 AND 23),
  settings_version integer NOT NULL DEFAULT 1 CHECK (settings_version > 0),
  updated_by_auth_user_id uuid,
  user_operational_settings_created_at timestamptz NOT NULL DEFAULT now(),
  user_operational_settings_updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS user_operational_settings_users_idx
  ON public.user_operational_settings(users_id);

ALTER TABLE public.user_operational_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS user_operational_settings_own_select ON public.user_operational_settings;
CREATE POLICY user_operational_settings_own_select ON public.user_operational_settings
FOR SELECT TO authenticated
USING (users_id = public.ensure_current_user());

REVOKE INSERT, UPDATE, DELETE ON public.user_operational_settings FROM anon, authenticated;
GRANT SELECT ON public.user_operational_settings TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_operational_settings TO service_role;

CREATE OR REPLACE FUNCTION public.ensure_user_operational_settings(p_users_id bigint DEFAULT NULL)
RETURNS public.user_operational_settings
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO pg_catalog, public
AS $$
DECLARE
  v_users_id bigint := coalesce(p_users_id, public.ensure_current_user());
  v_row public.user_operational_settings%ROWTYPE;
BEGIN
  IF auth.role() <> 'service_role' AND v_users_id <> public.ensure_current_user() THEN
    RAISE EXCEPTION 'operational_settings_forbidden';
  END IF;

  INSERT INTO public.user_operational_settings(users_id, updated_by_auth_user_id)
  VALUES (v_users_id, auth.uid())
  ON CONFLICT (users_id) DO NOTHING;

  SELECT * INTO v_row
  FROM public.user_operational_settings
  WHERE users_id = v_users_id;

  RETURN v_row;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_user_operational_settings()
RETURNS TABLE (
  dispatch_settings jsonb,
  import_settings jsonb,
  extension_runtime_config jsonb,
  operational_timezone text,
  operational_cutoff_hour smallint,
  settings_version integer,
  updated_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO pg_catalog, public
AS $$
DECLARE
  v_row public.user_operational_settings%ROWTYPE;
BEGIN
  v_row := public.ensure_user_operational_settings(NULL);
  RETURN QUERY SELECT
    v_row.dispatch_settings,
    v_row.import_settings,
    v_row.extension_runtime_config,
    v_row.operational_timezone,
    v_row.operational_cutoff_hour,
    v_row.settings_version,
    v_row.user_operational_settings_updated_at;
END;
$$;

CREATE OR REPLACE FUNCTION public.save_dispatch_settings(p_settings jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO pg_catalog, public
AS $$
DECLARE
  v_users_id bigint := public.ensure_current_user();
  v_result jsonb;
BEGIN
  IF jsonb_typeof(p_settings) <> 'object'
    OR jsonb_typeof(p_settings->'whatsapp') <> 'object'
    OR jsonb_typeof(p_settings->'instagram') <> 'object'
    OR jsonb_typeof(p_settings->'chipLevels') <> 'object' THEN
    RAISE EXCEPTION 'dispatch_settings_invalid';
  END IF;

  PERFORM public.ensure_user_operational_settings(v_users_id);
  UPDATE public.user_operational_settings
  SET dispatch_settings = p_settings,
      settings_version = settings_version + 1,
      updated_by_auth_user_id = auth.uid(),
      user_operational_settings_updated_at = now()
  WHERE users_id = v_users_id
  RETURNING dispatch_settings INTO v_result;
  RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.reset_dispatch_settings()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO pg_catalog, public
AS $$
DECLARE
  v_users_id bigint := public.ensure_current_user();
  v_default jsonb;
BEGIN
  v_default := '{
    "whatsapp":{"startTime":"13:00","endTime":"18:00","delayMinSeconds":120,"delayMaxSeconds":120,"perBatch":60,"batches":2,"batchDelayMinutes":60,"dailyLimit":120,"activeDays":["Segunda","Terca","Quarta","Quinta","Sexta"],"batchBehavior":"Respeitar lotes e janela"},
    "instagram":{"profile":"Todos","profiles":["Todos"],"startTime":"13:00","endTime":"18:00","delayMinSeconds":120,"delayMaxSeconds":120,"perBatch":15,"batches":4,"batchDelayMinutes":120,"delayMinutes":120,"dailyLimit":60,"activeDays":["Segunda","Terca","Quarta","Quinta","Sexta"],"batchBehavior":"Respeitar lotes e janela"},
    "chipLevels":{"aquecimento":{"dailyLimit":20,"batchCount":2},"iniciante":{"dailyLimit":40,"batchCount":2},"intermediario":{"dailyLimit":80,"batchCount":2},"avancado":{"dailyLimit":120,"batchCount":2}}
  }'::jsonb;

  PERFORM public.ensure_user_operational_settings(v_users_id);
  UPDATE public.user_operational_settings
  SET dispatch_settings = v_default,
      settings_version = settings_version + 1,
      updated_by_auth_user_id = auth.uid(),
      user_operational_settings_updated_at = now()
  WHERE users_id = v_users_id;
  RETURN v_default;
END;
$$;

CREATE OR REPLACE FUNCTION public.save_import_settings(p_settings jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO pg_catalog, public
AS $$
DECLARE
  v_users_id bigint := public.ensure_current_user();
BEGIN
  IF jsonb_typeof(p_settings) <> 'object' THEN RAISE EXCEPTION 'import_settings_invalid'; END IF;
  PERFORM public.ensure_user_operational_settings(v_users_id);
  UPDATE public.user_operational_settings
  SET import_settings = p_settings,
      settings_version = settings_version + 1,
      updated_by_auth_user_id = auth.uid(),
      user_operational_settings_updated_at = now()
  WHERE users_id = v_users_id;
  RETURN p_settings;
END;
$$;

CREATE OR REPLACE FUNCTION public.reset_import_settings()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO pg_catalog, public
AS $$
DECLARE
  v_users_id bigint := public.ensure_current_user();
  v_default jsonb := '{
    "minRating":4,"minReviews":10,
    "safeMode":{"simulationMode":true},
    "instagramLowRating":{"enabled":true,"minRating":3.7,"maxRatingExclusive":4,"minReviews":5},
    "branchRules":[],
    "deduplication":{"enabled":true,"byPhone":true,"bySite":true,"blockBasePermanent":true,"allowSmartReimport":false,"incrementalImport":true},
    "routes":{"whatsapp":true,"instagram":true,"ownSite":true,"aggregators":true,"blockFacebookAsSite":true,"requireConfiguredCategory":true,"rejectOutOfProfile":true},
    "logs":{"enabled":true,"logRejected":true,"logRejectionReason":true}
  }'::jsonb;
BEGIN
  PERFORM public.ensure_user_operational_settings(v_users_id);
  UPDATE public.user_operational_settings
  SET import_settings = v_default,
      settings_version = settings_version + 1,
      updated_by_auth_user_id = auth.uid(),
      user_operational_settings_updated_at = now()
  WHERE users_id = v_users_id;
  RETURN v_default;
END;
$$;

CREATE OR REPLACE FUNCTION public.save_extension_runtime_config(p_config jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO pg_catalog, public
AS $$
DECLARE
  v_users_id bigint := public.ensure_current_user();
BEGIN
  IF p_config IS NOT NULL AND jsonb_typeof(p_config) <> 'object' THEN
    RAISE EXCEPTION 'extension_runtime_config_invalid';
  END IF;
  PERFORM public.ensure_user_operational_settings(v_users_id);
  UPDATE public.user_operational_settings
  SET extension_runtime_config = p_config,
      settings_version = settings_version + 1,
      updated_by_auth_user_id = auth.uid(),
      user_operational_settings_updated_at = now()
  WHERE users_id = v_users_id;
  RETURN p_config;
END;
$$;

CREATE OR REPLACE FUNCTION public.service_get_operational_settings(p_users_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO pg_catalog, public
AS $$
DECLARE
  v_row public.user_operational_settings%ROWTYPE;
BEGIN
  IF auth.role() <> 'service_role' THEN RAISE EXCEPTION 'service_role_required'; END IF;
  v_row := public.ensure_user_operational_settings(p_users_id);
  RETURN jsonb_build_object(
    'users_id', v_row.users_id,
    'dispatch', v_row.dispatch_settings,
    'import', v_row.import_settings,
    'extension', v_row.extension_runtime_config,
    'timezone', v_row.operational_timezone,
    'cutoffHour', v_row.operational_cutoff_hour,
    'version', v_row.settings_version,
    'updatedAt', v_row.user_operational_settings_updated_at
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.worker_defer_batch(
  p_worker_batches_id bigint,
  p_next_run_at timestamptz,
  p_reason text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO pg_catalog, public
AS $$
BEGIN
  IF auth.role() <> 'service_role' THEN RAISE EXCEPTION 'service_role_required'; END IF;
  UPDATE public.worker_batches
  SET worker_batches_next_run_at = p_next_run_at,
      worker_batches_last_error = p_reason,
      worker_batches_updated_at = now()
  WHERE worker_batches_id = p_worker_batches_id
    AND status_id = 4;
END;
$$;

GRANT EXECUTE ON FUNCTION public.ensure_user_operational_settings(bigint) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_user_operational_settings() TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_dispatch_settings(jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reset_dispatch_settings() TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_import_settings(jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reset_import_settings() TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_extension_runtime_config(jsonb) TO authenticated;
REVOKE ALL ON FUNCTION public.service_get_operational_settings(bigint) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.service_get_operational_settings(bigint) TO service_role;
REVOKE ALL ON FUNCTION public.worker_defer_batch(bigint,timestamptz,text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.worker_defer_batch(bigint,timestamptz,text) TO service_role;

INSERT INTO public.user_operational_settings(users_id)
SELECT users_id FROM public.users
ON CONFLICT (users_id) DO NOTHING;

COMMIT;
