BEGIN;

-- ETAPA 6: auditoria append-only e máquina de estados no PostgreSQL.

CREATE TABLE IF NOT EXISTS public.audit_transition_rules (
  audit_transition_rules_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type text NOT NULL CHECK (entity_type IN ('lead','queue_item')),
  from_status_id bigint NOT NULL,
  to_status_id bigint NOT NULL,
  action_key text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(entity_type, from_status_id, to_status_id)
);

CREATE TABLE IF NOT EXISTS public.audit_events (
  audit_events_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id bigint NOT NULL REFERENCES public.users(users_id) ON DELETE CASCADE,
  actor_auth_user_id uuid,
  source text NOT NULL,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id text,
  lead_id bigint REFERENCES public.leads(leads_id) ON DELETE SET NULL,
  queue_item_id bigint REFERENCES public.queue_items(queue_items_id) ON DELETE SET NULL,
  channel_id bigint REFERENCES public.channels(channels_id) ON DELETE SET NULL,
  previous_status_id bigint,
  target_status_id bigint,
  message text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  request_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS audit_events_user_created_idx
  ON public.audit_events(users_id, created_at DESC, audit_events_id DESC);
CREATE INDEX IF NOT EXISTS audit_events_lead_idx
  ON public.audit_events(users_id, lead_id, created_at DESC)
  WHERE lead_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS audit_events_queue_item_idx
  ON public.audit_events(users_id, queue_item_id, created_at DESC)
  WHERE queue_item_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS audit_events_action_idx
  ON public.audit_events(users_id, action, created_at DESC);

ALTER TABLE public.audit_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_transition_rules ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS audit_events_own_select ON public.audit_events;
CREATE POLICY audit_events_own_select ON public.audit_events
FOR SELECT TO authenticated
USING (users_id = public.ensure_current_user());

DROP POLICY IF EXISTS audit_transition_rules_read ON public.audit_transition_rules;
CREATE POLICY audit_transition_rules_read ON public.audit_transition_rules
FOR SELECT TO authenticated
USING (is_active);

REVOKE INSERT, UPDATE, DELETE ON public.audit_events FROM anon, authenticated;
GRANT SELECT ON public.audit_events, public.audit_transition_rules TO authenticated;
GRANT SELECT, INSERT ON public.audit_events TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.audit_transition_rules TO service_role;

INSERT INTO public.audit_transition_rules(entity_type,from_status_id,to_status_id,action_key)
VALUES
  ('lead',1,2,'validate_or_route'), ('lead',1,3,'route_to_pre_send'),
  ('lead',1,6,'invalidate'), ('lead',1,7,'mark_duplicate'), ('lead',1,8,'archive'),
  ('lead',2,1,'return_to_import'), ('lead',2,3,'prepare_validation'),
  ('lead',2,4,'enqueue'), ('lead',2,6,'invalidate'), ('lead',2,8,'archive'),
  ('lead',3,1,'return_to_import'), ('lead',3,2,'validation_success'),
  ('lead',3,6,'validation_failure'), ('lead',3,8,'archive'),
  ('lead',4,2,'reconcile_to_valid'), ('lead',4,5,'dispatch_success'),
  ('lead',4,6,'invalidate'), ('lead',4,8,'archive'),
  ('lead',5,8,'archive'), ('lead',6,2,'restore_valid'), ('lead',6,8,'archive'),
  ('lead',7,8,'archive'), ('lead',8,2,'restore_valid'), ('lead',8,5,'restore_sent'),
  ('lead',8,6,'restore_invalid'),
  ('queue_item',3,4,'start'), ('queue_item',3,6,'fail'), ('queue_item',3,7,'cancel'), ('queue_item',3,8,'pause'),
  ('queue_item',4,3,'recover'), ('queue_item',4,5,'complete'), ('queue_item',4,6,'fail'), ('queue_item',4,7,'cancel'), ('queue_item',4,8,'pause'),
  ('queue_item',6,3,'reprocess'), ('queue_item',6,7,'cancel'), ('queue_item',6,8,'pause'),
  ('queue_item',8,3,'resume'), ('queue_item',8,4,'resume_processing'), ('queue_item',8,6,'fail'), ('queue_item',8,7,'cancel'),
  ('queue_item',7,3,'restore')
ON CONFLICT(entity_type,from_status_id,to_status_id)
DO UPDATE SET action_key=excluded.action_key,is_active=true;

CREATE OR REPLACE FUNCTION public.append_audit_event(
  p_source text,
  p_action text,
  p_entity_type text,
  p_entity_id text DEFAULT NULL,
  p_lead_id bigint DEFAULT NULL,
  p_queue_item_id bigint DEFAULT NULL,
  p_channel_id bigint DEFAULT NULL,
  p_previous_status_id bigint DEFAULT NULL,
  p_target_status_id bigint DEFAULT NULL,
  p_message text DEFAULT NULL,
  p_metadata jsonb DEFAULT '{}'::jsonb,
  p_users_id bigint DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO pg_catalog, public
AS $$
DECLARE
  v_users_id bigint;
  v_id bigint;
BEGIN
  v_users_id := CASE WHEN auth.role()='service_role' THEN p_users_id ELSE public.ensure_current_user() END;
  IF v_users_id IS NULL THEN RAISE EXCEPTION 'audit_user_required'; END IF;
  IF auth.role()<>'service_role' AND p_users_id IS NOT NULL AND p_users_id<>v_users_id THEN
    RAISE EXCEPTION 'audit_forbidden';
  END IF;
  IF nullif(trim(coalesce(p_source,'')),'') IS NULL OR nullif(trim(coalesce(p_action,'')),'') IS NULL THEN
    RAISE EXCEPTION 'audit_source_action_required';
  END IF;

  INSERT INTO public.audit_events(
    users_id, actor_auth_user_id, source, action, entity_type, entity_id,
    lead_id, queue_item_id, channel_id, previous_status_id, target_status_id,
    message, metadata
  ) VALUES (
    v_users_id, auth.uid(), trim(p_source), trim(p_action), coalesce(nullif(trim(p_entity_type),''),'system'), p_entity_id,
    p_lead_id, p_queue_item_id, p_channel_id, p_previous_status_id, p_target_status_id,
    p_message, coalesce(p_metadata,'{}'::jsonb)
  ) RETURNING audit_events_id INTO v_id;
  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.assert_allowed_status_transition(
  p_entity_type text,
  p_from_status_id bigint,
  p_to_status_id bigint
)
RETURNS void
LANGUAGE plpgsql
STABLE
SET search_path TO pg_catalog, public
AS $$
BEGIN
  IF p_from_status_id IS NULL OR p_to_status_id IS NULL OR p_from_status_id=p_to_status_id THEN RETURN; END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.audit_transition_rules r
    WHERE r.entity_type=p_entity_type AND r.from_status_id=p_from_status_id
      AND r.to_status_id=p_to_status_id AND r.is_active
  ) THEN
    RAISE EXCEPTION 'state_transition_not_allowed:%:%->%',p_entity_type,p_from_status_id,p_to_status_id;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.audit_lead_state_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO pg_catalog, public
AS $$
BEGIN
  IF TG_OP='UPDATE' AND NEW.lead_status_id IS DISTINCT FROM OLD.lead_status_id THEN
    PERFORM public.assert_allowed_status_transition('lead',OLD.lead_status_id,NEW.lead_status_id);
  END IF;

  IF TG_OP='INSERT' THEN
    PERFORM public.append_audit_event('database','lead_created','lead',NEW.leads_id::text,NEW.leads_id,NULL,NEW.channels_id,NULL,NEW.lead_status_id,NULL,jsonb_build_object('origin',NEW.leads_origin),NEW.users_id);
  ELSIF NEW.lead_status_id IS DISTINCT FROM OLD.lead_status_id OR NEW.channels_id IS DISTINCT FROM OLD.channels_id THEN
    PERFORM public.append_audit_event(
      'database','lead_state_changed','lead',NEW.leads_id::text,NEW.leads_id,NULL,NEW.channels_id,
      OLD.lead_status_id,NEW.lead_status_id,NULL,
      jsonb_build_object('previous_channel_id',OLD.channels_id,'target_channel_id',NEW.channels_id),NEW.users_id
    );
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.audit_queue_item_state_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO pg_catalog, public
AS $$
BEGIN
  IF TG_OP='UPDATE' AND NEW.status_id IS DISTINCT FROM OLD.status_id THEN
    PERFORM public.assert_allowed_status_transition('queue_item',OLD.status_id,NEW.status_id);
  END IF;

  IF TG_OP='INSERT' THEN
    PERFORM public.append_audit_event('database','queue_item_created','queue_item',NEW.queue_items_id::text,NEW.leads_id,NEW.queue_items_id,NULL,NULL,NEW.status_id,NULL,jsonb_build_object('queue_id',NEW.queues_id,'position',NEW.queue_items_position),NEW.users_id);
  ELSIF NEW.status_id IS DISTINCT FROM OLD.status_id THEN
    PERFORM public.append_audit_event('database','queue_item_state_changed','queue_item',NEW.queue_items_id::text,NEW.leads_id,NEW.queue_items_id,NULL,OLD.status_id,NEW.status_id,NEW.queue_items_error_message,jsonb_build_object('attempts',NEW.queue_items_attempts),NEW.users_id);
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.audit_worker_batch_state_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO pg_catalog, public
AS $$
BEGIN
  IF TG_OP='INSERT' OR NEW.status_id IS DISTINCT FROM OLD.status_id THEN
    PERFORM public.append_audit_event(
      'worker','worker_batch_state_changed','worker_batch',NEW.worker_batches_id::text,NULL,NULL,NEW.channels_id,
      CASE WHEN TG_OP='UPDATE' THEN OLD.status_id ELSE NULL END,NEW.status_id,NEW.worker_batches_last_error,
      jsonb_build_object('chip_id',NEW.chips_id,'total',NEW.worker_batches_total_items,'processed',NEW.worker_batches_processed_items,'worker_id',NEW.worker_batches_worker_id),NEW.users_id
    );
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS audit_lead_state_change_trigger ON public.leads;
CREATE TRIGGER audit_lead_state_change_trigger
AFTER INSERT OR UPDATE OF lead_status_id,channels_id ON public.leads
FOR EACH ROW EXECUTE FUNCTION public.audit_lead_state_change();

DROP TRIGGER IF EXISTS audit_queue_item_state_change_trigger ON public.queue_items;
CREATE TRIGGER audit_queue_item_state_change_trigger
AFTER INSERT OR UPDATE OF status_id ON public.queue_items
FOR EACH ROW EXECUTE FUNCTION public.audit_queue_item_state_change();

DROP TRIGGER IF EXISTS audit_worker_batch_state_change_trigger ON public.worker_batches;
CREATE TRIGGER audit_worker_batch_state_change_trigger
AFTER INSERT OR UPDATE OF status_id ON public.worker_batches
FOR EACH ROW EXECUTE FUNCTION public.audit_worker_batch_state_change();

GRANT EXECUTE ON FUNCTION public.append_audit_event(text,text,text,text,bigint,bigint,bigint,bigint,bigint,text,jsonb,bigint) TO authenticated,service_role;
GRANT EXECUTE ON FUNCTION public.assert_allowed_status_transition(text,bigint,bigint) TO authenticated,service_role;

COMMIT;
