-- CRM - Vinsansi Studio v2.4.0-R36
-- Prova canônica de validação WhatsApp vinculada ao telefone atual do lead.
-- Corrige o estado impossível: provider aprovou o número, mas a Fila/Revisão não encontra prova válida.

BEGIN;

CREATE OR REPLACE FUNCTION public.normalize_whatsapp_validation_phone(p_value text)
RETURNS text
LANGUAGE plpgsql
IMMUTABLE
SET search_path TO pg_catalog,public
AS $$
DECLARE
  v_digits text:=regexp_replace(coalesce(p_value,''),'[^0-9]+','','g');
BEGIN
  IF left(v_digits,2)='00' THEN v_digits:=substr(v_digits,3); END IF;
  IF v_digits='' THEN RETURN ''; END IF;
  IF left(v_digits,2)='55' THEN RETURN v_digits; END IF;
  IF length(v_digits) IN (10,11) THEN RETURN '55'||v_digits; END IF;
  RETURN v_digits;
END
$$;

CREATE TABLE IF NOT EXISTS public.whatsapp_validation_proofs (
  whatsapp_validation_proofs_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizations_id bigint NOT NULL REFERENCES public.organizations(organizations_id) ON DELETE CASCADE,
  users_id bigint NOT NULL REFERENCES public.users(users_id) ON DELETE CASCADE,
  leads_id bigint NOT NULL REFERENCES public.leads(leads_id) ON DELETE CASCADE,
  validated_phone text NOT NULL,
  provider text NOT NULL DEFAULT 'evolution',
  provider_reference text,
  proof_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_valid boolean NOT NULL DEFAULT false,
  validated_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT whatsapp_validation_proofs_lead_unique UNIQUE(organizations_id,leads_id)
);

CREATE INDEX IF NOT EXISTS whatsapp_validation_proofs_current_idx
  ON public.whatsapp_validation_proofs(organizations_id,users_id,leads_id,is_valid,validated_phone);

ALTER TABLE public.whatsapp_validation_proofs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.whatsapp_validation_proofs FROM PUBLIC,anon,authenticated;

CREATE OR REPLACE FUNCTION public.record_current_whatsapp_validation_proof(
  p_lead_id bigint,
  p_validated_phone text,
  p_provider text DEFAULT 'evolution',
  p_provider_reference text DEFAULT NULL,
  p_is_valid boolean DEFAULT false,
  p_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO pg_catalog,public
AS $$
DECLARE
  v_org bigint:=public.current_organization_id();
  v_user bigint:=public.current_organization_scope_users_id();
  v_current_phone text;
  v_validated_phone text:=public.normalize_whatsapp_validation_phone(p_validated_phone);
  v_matches boolean:=false;
BEGIN
  PERFORM public.require_organization_permission('leads.validate');
  IF v_org IS NULL OR v_user IS NULL THEN RAISE EXCEPTION 'organization_context_required'; END IF;
  IF p_lead_id IS NULL OR p_lead_id<=0 THEN RAISE EXCEPTION 'whatsapp_validation_lead_invalid'; END IF;

  SELECT public.normalize_whatsapp_validation_phone(coalesce(nullif(trim(l.leads_whatsapp),''),l.leads_phone,''))
    INTO v_current_phone
  FROM public.leads l
  WHERE l.organizations_id=v_org AND l.users_id=v_user AND l.leads_id=p_lead_id
  LIMIT 1;

  IF NOT FOUND THEN RAISE EXCEPTION 'whatsapp_validation_lead_not_found'; END IF;
  IF coalesce(v_current_phone,'')='' THEN RAISE EXCEPTION 'whatsapp_validation_current_phone_missing'; END IF;

  v_matches:=v_validated_phone<>'' AND v_validated_phone=v_current_phone;

  INSERT INTO public.whatsapp_validation_proofs(
    organizations_id,users_id,leads_id,validated_phone,provider,provider_reference,
    proof_metadata,is_valid,validated_at,updated_at
  ) VALUES(
    v_org,v_user,p_lead_id,
    CASE WHEN v_validated_phone<>'' THEN v_validated_phone ELSE v_current_phone END,
    coalesce(nullif(trim(p_provider),''),'evolution'),nullif(trim(coalesce(p_provider_reference,'')),''),
    coalesce(p_metadata,'{}'::jsonb),coalesce(p_is_valid,false) AND v_matches,now(),now()
  )
  ON CONFLICT(organizations_id,leads_id) DO UPDATE SET
    users_id=excluded.users_id,
    validated_phone=excluded.validated_phone,
    provider=excluded.provider,
    provider_reference=excluded.provider_reference,
    proof_metadata=excluded.proof_metadata,
    is_valid=excluded.is_valid,
    validated_at=excluded.validated_at,
    updated_at=now();

  RETURN coalesce(p_is_valid,false) AND v_matches;
END
$$;

-- Substitui a consulta legada por uma prova explícita, org-scoped e vinculada ao
-- telefone atual. Alterar o telefone invalida a prova automaticamente por mismatch.
CREATE OR REPLACE FUNCTION public.current_user_whatsapp_validation_proofs(p_lead_ids bigint[])
RETURNS TABLE(lead_id bigint,has_valid_proof boolean)
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path TO pg_catalog,public
AS $$
DECLARE
  v_org bigint:=public.current_organization_id();
  v_user bigint:=public.current_organization_scope_users_id();
BEGIN
  PERFORM public.require_organization_permission('leads.view');
  IF v_org IS NULL OR v_user IS NULL THEN RETURN; END IF;

  RETURN QUERY
  SELECT l.leads_id,
         EXISTS(
           SELECT 1
           FROM public.whatsapp_validation_proofs p
           WHERE p.organizations_id=v_org
             AND p.users_id=v_user
             AND p.leads_id=l.leads_id
             AND p.is_valid=true
             AND p.validated_phone=public.normalize_whatsapp_validation_phone(
               coalesce(nullif(trim(l.leads_whatsapp),''),l.leads_phone,'')
             )
         ) AS has_valid_proof
  FROM public.leads l
  WHERE l.organizations_id=v_org
    AND l.users_id=v_user
    AND l.leads_id=ANY(coalesce(p_lead_ids,'{}'::bigint[]));
END
$$;

-- Recupera automaticamente as provas recentes já confirmadas pelo Worker antes da R36.
-- A prova só é importada quando o telefone validado continua sendo exatamente o telefone atual.
INSERT INTO public.whatsapp_validation_proofs(
  organizations_id,users_id,leads_id,validated_phone,provider,provider_reference,
  proof_metadata,is_valid,validated_at,created_at,updated_at
)
SELECT l.organizations_id,l.users_id,l.leads_id,
       public.normalize_whatsapp_validation_phone(a.lead_validation_attempts_input_value),
       coalesce(nullif(trim(a.lead_validation_attempts_provider),''),'evolution'),
       a.lead_validation_attempts_provider_reference,
       coalesce(a.lead_validation_attempts_response_metadata,'{}'::jsonb),
       true,
       coalesce(a.lead_validation_attempts_finished_at,a.lead_validation_attempts_updated_at,a.lead_validation_attempts_created_at,now()),
       coalesce(a.lead_validation_attempts_created_at,now()),now()
FROM public.leads l
JOIN LATERAL (
  SELECT a1.*
  FROM public.lead_validation_attempts a1
  WHERE a1.users_id=l.users_id
    AND a1.leads_id=l.leads_id
    AND lower(coalesce(a1.lead_validation_attempts_response_metadata->>'worker_valid','false')) IN ('true','1','yes')
    AND public.normalize_whatsapp_validation_phone(a1.lead_validation_attempts_input_value)
        = public.normalize_whatsapp_validation_phone(coalesce(nullif(trim(l.leads_whatsapp),''),l.leads_phone,''))
  ORDER BY coalesce(a1.lead_validation_attempts_finished_at,a1.lead_validation_attempts_updated_at,a1.lead_validation_attempts_created_at) DESC,
           a1.lead_validation_attempts_id DESC
  LIMIT 1
) a ON true
WHERE public.normalize_whatsapp_validation_phone(coalesce(nullif(trim(l.leads_whatsapp),''),l.leads_phone,''))<>''
ON CONFLICT(organizations_id,leads_id) DO UPDATE SET
  users_id=excluded.users_id,
  validated_phone=excluded.validated_phone,
  provider=excluded.provider,
  provider_reference=excluded.provider_reference,
  proof_metadata=excluded.proof_metadata,
  is_valid=true,
  validated_at=greatest(public.whatsapp_validation_proofs.validated_at,excluded.validated_at),
  updated_at=now();

REVOKE ALL ON FUNCTION public.normalize_whatsapp_validation_phone(text) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.record_current_whatsapp_validation_proof(bigint,text,text,text,boolean,jsonb) FROM PUBLIC,anon;
REVOKE ALL ON FUNCTION public.current_user_whatsapp_validation_proofs(bigint[]) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.record_current_whatsapp_validation_proof(bigint,text,text,text,boolean,jsonb) TO authenticated,service_role;
GRANT EXECUTE ON FUNCTION public.current_user_whatsapp_validation_proofs(bigint[]) TO authenticated,service_role;

COMMIT;
