BEGIN;

-- ETAPA 9: progresso detalhado e recuperação segura da execução Instagram.

CREATE TABLE IF NOT EXISTS public.instagram_queue_progress (
  instagram_queue_progress_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id bigint NOT NULL REFERENCES public.users(users_id) ON DELETE CASCADE,
  queue_items_id bigint NOT NULL REFERENCES public.queue_items(queue_items_id) ON DELETE CASCADE,
  socials_id bigint NOT NULL REFERENCES public.socials(socials_id) ON DELETE CASCADE,
  step text NOT NULL DEFAULT 'queued' CHECK (step IN (
    'queued','claimed','profile_opened','following','followed','dm_opened',
    'messages_sending','media_sending','sent','invalid','error','reconciliation_required'
  )),
  claim_token uuid,
  claimed_by text,
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  last_heartbeat_at timestamptz,
  started_at timestamptz,
  finished_at timestamptz,
  error_message text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  instagram_queue_progress_created_at timestamptz NOT NULL DEFAULT now(),
  instagram_queue_progress_updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(queue_items_id)
);

CREATE TABLE IF NOT EXISTS public.instagram_dispatch_events (
  instagram_dispatch_events_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id bigint NOT NULL REFERENCES public.users(users_id) ON DELETE CASCADE,
  queue_items_id bigint NOT NULL REFERENCES public.queue_items(queue_items_id) ON DELETE CASCADE,
  socials_id bigint REFERENCES public.socials(socials_id) ON DELETE SET NULL,
  from_step text,
  to_step text NOT NULL,
  claim_token uuid,
  actor text,
  message text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS instagram_progress_user_step_idx
  ON public.instagram_queue_progress(users_id, socials_id, step, instagram_queue_progress_updated_at);
CREATE INDEX IF NOT EXISTS instagram_progress_heartbeat_idx
  ON public.instagram_queue_progress(step, last_heartbeat_at)
  WHERE step NOT IN ('sent','invalid','error','reconciliation_required');
CREATE INDEX IF NOT EXISTS instagram_dispatch_events_item_idx
  ON public.instagram_dispatch_events(queue_items_id, created_at DESC);

ALTER TABLE public.instagram_queue_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.instagram_dispatch_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS instagram_queue_progress_own_select ON public.instagram_queue_progress;
CREATE POLICY instagram_queue_progress_own_select ON public.instagram_queue_progress
FOR SELECT TO authenticated USING(users_id=public.ensure_current_user());
DROP POLICY IF EXISTS instagram_dispatch_events_own_select ON public.instagram_dispatch_events;
CREATE POLICY instagram_dispatch_events_own_select ON public.instagram_dispatch_events
FOR SELECT TO authenticated USING(users_id=public.ensure_current_user());

REVOKE INSERT,UPDATE,DELETE ON public.instagram_queue_progress,public.instagram_dispatch_events FROM anon,authenticated;
GRANT SELECT ON public.instagram_queue_progress,public.instagram_dispatch_events TO authenticated;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.instagram_queue_progress,public.instagram_dispatch_events TO service_role;

CREATE OR REPLACE FUNCTION public.instagram_log_progress_event(
  p_users_id bigint,
  p_queue_item_id bigint,
  p_socials_id bigint,
  p_from_step text,
  p_to_step text,
  p_claim_token uuid,
  p_actor text,
  p_message text DEFAULT NULL,
  p_metadata jsonb DEFAULT '{}'::jsonb
) RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE v_id bigint;
BEGIN
  IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role_required'; END IF;
  INSERT INTO public.instagram_dispatch_events(
    users_id,queue_items_id,socials_id,from_step,to_step,claim_token,actor,message,metadata
  ) VALUES(
    p_users_id,p_queue_item_id,p_socials_id,p_from_step,p_to_step,p_claim_token,
    nullif(trim(coalesce(p_actor,'')),''),p_message,coalesce(p_metadata,'{}'::jsonb)
  ) RETURNING instagram_dispatch_events_id INTO v_id;
  RETURN v_id;
END; $$;

CREATE OR REPLACE FUNCTION public.instagram_claim_queue_item(
  p_users_id bigint,
  p_queue_item_id bigint,
  p_socials_id bigint,
  p_consumer_id text
) RETURNS TABLE(queue_items_id bigint, claim_token uuid, step text, attempts integer)
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE
  v_item public.queue_items%ROWTYPE;
  v_existing public.instagram_queue_progress%ROWTYPE;
  v_token uuid:=gen_random_uuid();
  v_attempts integer;
BEGIN
  IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role_required'; END IF;
  IF nullif(trim(coalesce(p_consumer_id,'')),'') IS NULL THEN RAISE EXCEPTION 'consumer_id_required'; END IF;

  SELECT * INTO v_item FROM public.queue_items qi
  WHERE qi.queue_items_id=p_queue_item_id AND qi.users_id=p_users_id AND qi.socials_id=p_socials_id
  FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'instagram_queue_item_not_found'; END IF;

  SELECT * INTO v_existing FROM public.instagram_queue_progress p
  WHERE p.queue_items_id=p_queue_item_id FOR UPDATE;

  IF FOUND AND v_existing.step IN ('sent','invalid','reconciliation_required') THEN
    RAISE EXCEPTION 'instagram_item_not_claimable:%',v_existing.step;
  END IF;
  IF v_item.status_id NOT IN (3,6) THEN
    RAISE EXCEPTION 'instagram_item_not_pending:%',v_item.status_id;
  END IF;

  v_attempts:=coalesce(v_existing.attempts,0)+1;
  INSERT INTO public.instagram_queue_progress(
    users_id,queue_items_id,socials_id,step,claim_token,claimed_by,attempts,last_heartbeat_at,started_at,finished_at,error_message,metadata
  ) VALUES(
    p_users_id,p_queue_item_id,p_socials_id,'claimed',v_token,trim(p_consumer_id),v_attempts,now(),coalesce(v_existing.started_at,now()),NULL,NULL,'{}'::jsonb
  ) ON CONFLICT(queue_items_id) DO UPDATE SET
    step='claimed',claim_token=excluded.claim_token,claimed_by=excluded.claimed_by,
    attempts=excluded.attempts,last_heartbeat_at=now(),started_at=coalesce(public.instagram_queue_progress.started_at,now()),
    finished_at=NULL,error_message=NULL,instagram_queue_progress_updated_at=now()
  RETURNING public.instagram_queue_progress.claim_token,public.instagram_queue_progress.attempts
  INTO v_token,v_attempts;

  UPDATE public.queue_items SET status_id=4,queue_items_started_at=coalesce(queue_items_started_at,now()),
    queue_items_finished_at=NULL,queue_items_error_message=NULL,queue_items_updated_at=now()
  WHERE queue_items_id=p_queue_item_id;

  PERFORM public.instagram_log_progress_event(p_users_id,p_queue_item_id,p_socials_id,coalesce(v_existing.step,'queued'),'claimed',v_token,p_consumer_id,NULL,'{}'::jsonb);
  PERFORM public.append_audit_event('instagram-extension','instagram_claimed','queue_item',p_queue_item_id::text,v_item.leads_id,p_queue_item_id,2,v_item.status_id,4,NULL,jsonb_build_object('consumer_id',p_consumer_id,'attempt',v_attempts),p_users_id);

  RETURN QUERY SELECT p_queue_item_id,v_token,'claimed'::text,v_attempts;
END; $$;

CREATE OR REPLACE FUNCTION public.instagram_update_queue_progress(
  p_users_id bigint,
  p_queue_item_id bigint,
  p_claim_token uuid,
  p_step text,
  p_message text DEFAULT NULL,
  p_metadata jsonb DEFAULT '{}'::jsonb
) RETURNS TABLE(queue_items_id bigint, step text, queue_status_id bigint, lead_status_id bigint)
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE
  v_progress public.instagram_queue_progress%ROWTYPE;
  v_item public.queue_items%ROWTYPE;
  v_target_queue bigint:=4;
  v_target_lead bigint;
  v_final boolean:=false;
  v_allowed text[]:=ARRAY['claimed','profile_opened','following','followed','dm_opened','messages_sending','media_sending','sent','invalid','error','reconciliation_required'];
BEGIN
  IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role_required'; END IF;
  IF NOT (p_step=ANY(v_allowed)) THEN RAISE EXCEPTION 'instagram_step_invalid:%',p_step; END IF;

  SELECT * INTO v_progress FROM public.instagram_queue_progress p
  WHERE p.queue_items_id=p_queue_item_id AND p.users_id=p_users_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'instagram_progress_not_found'; END IF;
  IF v_progress.claim_token IS DISTINCT FROM p_claim_token THEN RAISE EXCEPTION 'instagram_claim_token_invalid'; END IF;
  IF v_progress.step IN ('sent','invalid','reconciliation_required') AND v_progress.step<>p_step THEN
    RAISE EXCEPTION 'instagram_progress_final:%',v_progress.step;
  END IF;
  SELECT * INTO v_item FROM public.queue_items qi WHERE qi.queue_items_id=p_queue_item_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'instagram_queue_item_not_found'; END IF;

  IF p_step='sent' THEN v_target_queue:=5; v_target_lead:=5; v_final:=true;
  ELSIF p_step='invalid' THEN v_target_queue:=6; v_target_lead:=6; v_final:=true;
  ELSIF p_step IN ('error','reconciliation_required') THEN v_target_queue:=6; v_final:=true;
  END IF;

  UPDATE public.instagram_queue_progress SET
    step=p_step,last_heartbeat_at=now(),finished_at=CASE WHEN v_final THEN now() ELSE NULL END,
    error_message=CASE WHEN p_step IN ('error','invalid','reconciliation_required') THEN nullif(trim(coalesce(p_message,'')),'') ELSE NULL END,
    metadata=coalesce(metadata,'{}'::jsonb)||coalesce(p_metadata,'{}'::jsonb),instagram_queue_progress_updated_at=now()
  WHERE instagram_queue_progress_id=v_progress.instagram_queue_progress_id;

  UPDATE public.queue_items SET status_id=v_target_queue,queue_items_updated_at=now(),
    queue_items_finished_at=CASE WHEN v_final THEN now() ELSE NULL END,
    queue_items_error_message=CASE WHEN p_step IN ('error','invalid','reconciliation_required') THEN nullif(trim(coalesce(p_message,'')),'') ELSE NULL END
  WHERE queue_items_id=p_queue_item_id;

  IF v_target_lead IS NOT NULL THEN
    UPDATE public.leads SET lead_status_id=v_target_lead,leads_updated_at=now()
    WHERE leads_id=v_item.leads_id AND users_id=p_users_id AND lead_status_id=4;
  END IF;

  PERFORM public.instagram_log_progress_event(p_users_id,p_queue_item_id,v_progress.socials_id,v_progress.step,p_step,p_claim_token,v_progress.claimed_by,p_message,p_metadata);
  PERFORM public.append_audit_event('instagram-extension','instagram_step_'||p_step,'queue_item',p_queue_item_id::text,v_item.leads_id,p_queue_item_id,2,v_item.status_id,v_target_queue,p_message,jsonb_build_object('from_step',v_progress.step,'to_step',p_step),p_users_id);

  RETURN QUERY SELECT p_queue_item_id,p_step,v_target_queue,coalesce(v_target_lead,4::bigint);
END; $$;

CREATE OR REPLACE FUNCTION public.instagram_recover_stale_items(
  p_stale_before timestamptz DEFAULT now()-interval '15 minutes'
) RETURNS TABLE(queue_items_id bigint, recovery_action text)
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE r record; v_action text;
BEGIN
  IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role_required'; END IF;
  FOR r IN
    SELECT p.*,qi.leads_id FROM public.instagram_queue_progress p
    JOIN public.queue_items qi ON qi.queue_items_id=p.queue_items_id
    WHERE p.step IN ('claimed','profile_opened','following','followed','dm_opened','messages_sending','media_sending')
      AND coalesce(p.last_heartbeat_at,p.instagram_queue_progress_updated_at)<p_stale_before
    FOR UPDATE OF p,qi SKIP LOCKED
  LOOP
    IF r.step IN ('messages_sending','media_sending') THEN
      v_action:='reconciliation_required';
      UPDATE public.instagram_queue_progress SET step=v_action,error_message='stale_after_possible_dispatch',finished_at=now(),instagram_queue_progress_updated_at=now() WHERE instagram_queue_progress_id=r.instagram_queue_progress_id;
      UPDATE public.queue_items SET status_id=6,queue_items_error_message='instagram_reconciliation_required',queue_items_finished_at=now(),queue_items_updated_at=now() WHERE public.queue_items.queue_items_id=r.queue_items_id;
    ELSE
      v_action:='requeued';
      UPDATE public.instagram_queue_progress SET step='queued',claim_token=NULL,claimed_by=NULL,error_message='recovered_stale_claim',instagram_queue_progress_updated_at=now() WHERE instagram_queue_progress_id=r.instagram_queue_progress_id;
      UPDATE public.queue_items SET status_id=3,queue_items_started_at=NULL,queue_items_error_message=NULL,queue_items_finished_at=NULL,queue_items_updated_at=now() WHERE public.queue_items.queue_items_id=r.queue_items_id;
    END IF;
    INSERT INTO public.instagram_dispatch_events(users_id,queue_items_id,socials_id,from_step,to_step,actor,message)
    VALUES(r.users_id,r.queue_items_id,r.socials_id,r.step,CASE WHEN v_action='requeued' THEN 'queued' ELSE v_action END,'recovery','stale_execution_recovered');
    queue_items_id:=r.queue_items_id; recovery_action:=v_action; RETURN NEXT;
  END LOOP;
END; $$;

GRANT EXECUTE ON FUNCTION public.instagram_claim_queue_item(bigint,bigint,bigint,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.instagram_update_queue_progress(bigint,bigint,uuid,text,text,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.instagram_recover_stale_items(timestamptz) TO service_role;
REVOKE ALL ON FUNCTION public.instagram_claim_queue_item(bigint,bigint,bigint,text) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.instagram_update_queue_progress(bigint,bigint,uuid,text,text,jsonb) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.instagram_recover_stale_items(timestamptz) FROM PUBLIC,anon,authenticated;

INSERT INTO public.instagram_queue_progress(users_id,queue_items_id,socials_id,step,attempts,last_heartbeat_at,started_at,finished_at,error_message)
SELECT qi.users_id,qi.queue_items_id,qi.socials_id,
  CASE qi.status_id WHEN 3 THEN 'queued' WHEN 4 THEN 'reconciliation_required' WHEN 5 THEN 'sent' WHEN 6 THEN 'error' ELSE 'queued' END,
  coalesce(qi.queue_items_attempts,0),qi.queue_items_updated_at,qi.queue_items_started_at,qi.queue_items_finished_at,qi.queue_items_error_message
FROM public.queue_items qi WHERE qi.socials_id IS NOT NULL
ON CONFLICT(queue_items_id) DO NOTHING;

COMMIT;
