BEGIN;

-- ETAPA 3: lotes persistentes e idempotência por parte do disparo WhatsApp.
-- A migration pressupõe os catálogos canônicos:
-- status: 3=pendente, 4=processando, 5=concluído, 6=erro, 7=cancelado, 8=pausado
-- lead_status: 4=na_fila, 5=enviado

CREATE TABLE IF NOT EXISTS public.worker_batches (
  worker_batches_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id bigint NOT NULL REFERENCES public.users(users_id) ON DELETE CASCADE,
  channels_id bigint NOT NULL REFERENCES public.channels(channels_id),
  chips_id bigint NOT NULL REFERENCES public.chips(chips_id) ON DELETE CASCADE,
  status_id bigint NOT NULL REFERENCES public.status(status_id),
  worker_batches_total_items integer NOT NULL DEFAULT 0 CHECK (worker_batches_total_items >= 0),
  worker_batches_processed_items integer NOT NULL DEFAULT 0 CHECK (worker_batches_processed_items >= 0),
  worker_batches_sent_items integer NOT NULL DEFAULT 0 CHECK (worker_batches_sent_items >= 0),
  worker_batches_failed_items integer NOT NULL DEFAULT 0 CHECK (worker_batches_failed_items >= 0),
  worker_batches_next_run_at timestamp with time zone,
  worker_batches_started_at timestamp with time zone,
  worker_batches_finished_at timestamp with time zone,
  worker_batches_heartbeat_at timestamp with time zone,
  worker_batches_last_error text,
  worker_batches_worker_id text,
  worker_batches_created_at timestamp with time zone NOT NULL DEFAULT now(),
  worker_batches_updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.worker_batch_items (
  worker_batch_items_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id bigint NOT NULL REFERENCES public.users(users_id) ON DELETE CASCADE,
  worker_batches_id bigint NOT NULL REFERENCES public.worker_batches(worker_batches_id) ON DELETE CASCADE,
  queue_items_id bigint NOT NULL REFERENCES public.queue_items(queue_items_id) ON DELETE CASCADE,
  status_id bigint NOT NULL REFERENCES public.status(status_id),
  worker_batch_items_position integer NOT NULL CHECK (worker_batch_items_position > 0),
  worker_batch_items_attempts integer NOT NULL DEFAULT 0 CHECK (worker_batch_items_attempts >= 0),
  worker_batch_items_started_at timestamp with time zone,
  worker_batch_items_finished_at timestamp with time zone,
  worker_batch_items_error_message text,
  worker_batch_items_created_at timestamp with time zone NOT NULL DEFAULT now(),
  worker_batch_items_updated_at timestamp with time zone NOT NULL DEFAULT now(),
  UNIQUE (worker_batches_id, queue_items_id),
  UNIQUE (worker_batches_id, worker_batch_items_position)
);

CREATE TABLE IF NOT EXISTS public.queue_item_dispatch_parts (
  queue_item_dispatch_parts_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id bigint NOT NULL REFERENCES public.users(users_id) ON DELETE CASCADE,
  queue_items_id bigint NOT NULL REFERENCES public.queue_items(queue_items_id) ON DELETE CASCADE,
  queue_item_dispatch_parts_key text NOT NULL,
  queue_item_dispatch_parts_order integer NOT NULL CHECK (queue_item_dispatch_parts_order BETWEEN 1 AND 5),
  queue_item_dispatch_parts_state text NOT NULL DEFAULT 'pending'
    CHECK (queue_item_dispatch_parts_state IN ('pending', 'processing', 'sent', 'failed', 'reconciliation_required', 'skipped')),
  queue_item_dispatch_parts_content_hash text NOT NULL,
  queue_item_dispatch_parts_body text NOT NULL DEFAULT '',
  queue_item_dispatch_parts_attempts integer NOT NULL DEFAULT 0 CHECK (queue_item_dispatch_parts_attempts >= 0),
  queue_item_dispatch_parts_claim_token uuid,
  queue_item_dispatch_parts_external_id text,
  queue_item_dispatch_parts_claimed_at timestamp with time zone,
  queue_item_dispatch_parts_sent_at timestamp with time zone,
  queue_item_dispatch_parts_error_message text,
  queue_item_dispatch_parts_created_at timestamp with time zone NOT NULL DEFAULT now(),
  queue_item_dispatch_parts_updated_at timestamp with time zone NOT NULL DEFAULT now(),
  UNIQUE (queue_items_id, queue_item_dispatch_parts_key)
);

ALTER TABLE public.sents
  ADD COLUMN IF NOT EXISTS sents_part_key text,
  ADD COLUMN IF NOT EXISTS sents_idempotency_key text,
  ADD COLUMN IF NOT EXISTS sents_payload_hash text;

CREATE UNIQUE INDEX IF NOT EXISTS worker_batches_one_active_per_chip
  ON public.worker_batches (users_id, channels_id, chips_id)
  WHERE status_id IN (3, 4, 8);

CREATE INDEX IF NOT EXISTS worker_batches_scheduler_idx
  ON public.worker_batches (status_id, worker_batches_next_run_at, worker_batches_id)
  WHERE status_id = 4;

CREATE INDEX IF NOT EXISTS worker_batch_items_next_idx
  ON public.worker_batch_items (worker_batches_id, status_id, worker_batch_items_position);

CREATE UNIQUE INDEX IF NOT EXISTS worker_batch_items_one_active_queue_item
  ON public.worker_batch_items (queue_items_id)
  WHERE status_id IN (3, 4, 8);

CREATE INDEX IF NOT EXISTS queue_item_dispatch_parts_item_idx
  ON public.queue_item_dispatch_parts (queue_items_id, queue_item_dispatch_parts_order);

CREATE UNIQUE INDEX IF NOT EXISTS sents_idempotency_key_unique
  ON public.sents (sents_idempotency_key)
  WHERE sents_idempotency_key IS NOT NULL;

ALTER TABLE public.worker_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.worker_batch_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.queue_item_dispatch_parts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS worker_batches_own_select ON public.worker_batches;
CREATE POLICY worker_batches_own_select ON public.worker_batches
FOR SELECT TO authenticated
USING (
  users_id = (
    SELECT u.users_id FROM public.users AS u WHERE u.auth_user_id = auth.uid() LIMIT 1
  )
);

DROP POLICY IF EXISTS worker_batch_items_own_select ON public.worker_batch_items;
CREATE POLICY worker_batch_items_own_select ON public.worker_batch_items
FOR SELECT TO authenticated
USING (
  users_id = (
    SELECT u.users_id FROM public.users AS u WHERE u.auth_user_id = auth.uid() LIMIT 1
  )
);

DROP POLICY IF EXISTS queue_item_dispatch_parts_own_select ON public.queue_item_dispatch_parts;
CREATE POLICY queue_item_dispatch_parts_own_select ON public.queue_item_dispatch_parts
FOR SELECT TO authenticated
USING (
  users_id = (
    SELECT u.users_id FROM public.users AS u WHERE u.auth_user_id = auth.uid() LIMIT 1
  )
);

REVOKE INSERT, UPDATE, DELETE ON public.worker_batches FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.worker_batch_items FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.queue_item_dispatch_parts FROM authenticated;
GRANT SELECT ON public.worker_batches, public.worker_batch_items, public.queue_item_dispatch_parts TO authenticated;

CREATE OR REPLACE FUNCTION public.refresh_worker_batch_counters(p_worker_batches_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_total integer;
  v_processed integer;
  v_sent integer;
  v_failed integer;
BEGIN
  SELECT
    count(*)::integer,
    count(*) FILTER (WHERE status_id IN (5, 6, 7))::integer,
    count(*) FILTER (WHERE status_id = 5)::integer,
    count(*) FILTER (WHERE status_id = 6)::integer
  INTO v_total, v_processed, v_sent, v_failed
  FROM public.worker_batch_items
  WHERE worker_batches_id = p_worker_batches_id;

  UPDATE public.worker_batches
  SET
    worker_batches_total_items = coalesce(v_total, 0),
    worker_batches_processed_items = coalesce(v_processed, 0),
    worker_batches_sent_items = coalesce(v_sent, 0),
    worker_batches_failed_items = coalesce(v_failed, 0),
    worker_batches_updated_at = now()
  WHERE worker_batches_id = p_worker_batches_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.worker_start_whatsapp_batch(
  p_users_id bigint,
  p_chip_instance text,
  p_queue_item_ids bigint[],
  p_worker_id text DEFAULT NULL
)
RETURNS TABLE (
  batch_id bigint,
  batch_status text,
  enabled boolean,
  chip text,
  total integer,
  remaining integer,
  processed integer,
  sent integer,
  failed integer,
  next_run_at timestamp with time zone,
  started_at timestamp with time zone,
  last_error text,
  already_running boolean
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_channel_id bigint;
  v_chip_id bigint;
  v_batch_id bigint;
  v_existing public.worker_batches%ROWTYPE;
  v_requested_count integer;
  v_valid_count integer;
BEGIN
  IF p_users_id IS NULL OR nullif(trim(coalesce(p_chip_instance, '')), '') IS NULL THEN
    RAISE EXCEPTION 'batch_request_invalid';
  END IF;

  SELECT c.channels_id INTO v_channel_id
  FROM public.channels AS c
  WHERE lower(trim(c.channels_name)) = 'whatsapp'
  LIMIT 1;

  SELECT ch.chips_id INTO v_chip_id
  FROM public.chips AS ch
  JOIN public.instances AS i
    ON i.instances_id = ch.instances_id
   AND i.users_id = ch.users_id
  WHERE ch.users_id = p_users_id
    AND i.instances_name = trim(p_chip_instance)
  LIMIT 1;

  IF v_channel_id IS NULL OR v_chip_id IS NULL THEN
    RAISE EXCEPTION 'batch_chip_not_found';
  END IF;

  PERFORM pg_advisory_xact_lock(
    hashtextextended(format('worker-batch:%s:%s:%s', p_users_id, v_channel_id, v_chip_id), 0)
  );

  SELECT * INTO v_existing
  FROM public.worker_batches
  WHERE users_id = p_users_id
    AND channels_id = v_channel_id
    AND chips_id = v_chip_id
    AND status_id IN (3, 4, 8)
  ORDER BY worker_batches_id DESC
  LIMIT 1
  FOR UPDATE;

  IF v_existing.worker_batches_id IS NOT NULL THEN
    RETURN QUERY
    SELECT
      v_existing.worker_batches_id,
      CASE v_existing.status_id WHEN 8 THEN 'paused' WHEN 4 THEN 'running' ELSE 'pending' END,
      v_existing.status_id IN (3, 4, 8),
      trim(p_chip_instance),
      v_existing.worker_batches_total_items,
      greatest(v_existing.worker_batches_total_items - v_existing.worker_batches_processed_items, 0),
      v_existing.worker_batches_processed_items,
      v_existing.worker_batches_sent_items,
      v_existing.worker_batches_failed_items,
      v_existing.worker_batches_next_run_at,
      v_existing.worker_batches_started_at,
      coalesce(v_existing.worker_batches_last_error, ''),
      true;
    RETURN;
  END IF;

  SELECT count(*)::integer INTO v_requested_count
  FROM (SELECT DISTINCT unnest(coalesce(p_queue_item_ids, ARRAY[]::bigint[])) AS queue_items_id) AS requested;

  IF coalesce(v_requested_count, 0) = 0 THEN
    RAISE EXCEPTION 'batch_queue_item_ids_required';
  END IF;

  SELECT count(*)::integer INTO v_valid_count
  FROM (
    SELECT DISTINCT unnest(p_queue_item_ids) AS queue_items_id
  ) AS requested
  JOIN public.queue_items AS qi
    ON qi.queue_items_id = requested.queue_items_id
  WHERE qi.users_id = p_users_id
    AND qi.chips_id = v_chip_id
    AND qi.status_id IN (3, 8);

  IF v_valid_count <> v_requested_count THEN
    RAISE EXCEPTION 'batch_items_not_dispatchable';
  END IF;

  INSERT INTO public.worker_batches (
    users_id, channels_id, chips_id, status_id,
    worker_batches_total_items, worker_batches_next_run_at,
    worker_batches_started_at, worker_batches_heartbeat_at,
    worker_batches_worker_id
  ) VALUES (
    p_users_id, v_channel_id, v_chip_id, 4,
    v_requested_count, now(), now(), now(), nullif(trim(coalesce(p_worker_id, '')), '')
  ) RETURNING worker_batches_id INTO v_batch_id;

  INSERT INTO public.worker_batch_items (
    users_id, worker_batches_id, queue_items_id, status_id,
    worker_batch_items_position
  )
  SELECT
    p_users_id,
    v_batch_id,
    requested.queue_items_id,
    3,
    requested.ordinality::integer
  FROM unnest(p_queue_item_ids) WITH ORDINALITY AS requested(queue_items_id, ordinality)
  JOIN public.queue_items AS qi
    ON qi.queue_items_id = requested.queue_items_id
   AND qi.users_id = p_users_id
   AND qi.chips_id = v_chip_id
  GROUP BY requested.queue_items_id, requested.ordinality
  ORDER BY requested.ordinality;

  PERFORM public.refresh_worker_batch_counters(v_batch_id);

  RETURN QUERY
  SELECT
    wb.worker_batches_id,
    'running'::text,
    true,
    trim(p_chip_instance),
    wb.worker_batches_total_items,
    greatest(wb.worker_batches_total_items - wb.worker_batches_processed_items, 0),
    wb.worker_batches_processed_items,
    wb.worker_batches_sent_items,
    wb.worker_batches_failed_items,
    wb.worker_batches_next_run_at,
    wb.worker_batches_started_at,
    coalesce(wb.worker_batches_last_error, ''),
    false
  FROM public.worker_batches AS wb
  WHERE wb.worker_batches_id = v_batch_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.worker_set_whatsapp_batch_state(
  p_users_id bigint,
  p_chip_instance text,
  p_action text,
  p_worker_id text DEFAULT NULL
)
RETURNS TABLE (
  batch_id bigint,
  batch_status text,
  enabled boolean,
  chip text,
  total integer,
  remaining integer,
  processed integer,
  sent integer,
  failed integer,
  next_run_at timestamp with time zone,
  started_at timestamp with time zone,
  last_error text,
  already_running boolean
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_channel_id bigint;
  v_chip_id bigint;
  v_batch public.worker_batches%ROWTYPE;
  v_action text := lower(trim(coalesce(p_action, '')));
BEGIN
  SELECT c.channels_id INTO v_channel_id FROM public.channels AS c WHERE lower(trim(c.channels_name)) = 'whatsapp' LIMIT 1;
  SELECT ch.chips_id INTO v_chip_id
  FROM public.chips AS ch
  JOIN public.instances AS i ON i.instances_id = ch.instances_id AND i.users_id = ch.users_id
  WHERE ch.users_id = p_users_id AND i.instances_name = trim(p_chip_instance)
  LIMIT 1;

  IF v_channel_id IS NULL OR v_chip_id IS NULL THEN RAISE EXCEPTION 'batch_chip_not_found'; END IF;

  PERFORM pg_advisory_xact_lock(hashtextextended(format('worker-batch:%s:%s:%s', p_users_id, v_channel_id, v_chip_id), 0));

  SELECT * INTO v_batch
  FROM public.worker_batches
  WHERE users_id = p_users_id AND channels_id = v_channel_id AND chips_id = v_chip_id
  ORDER BY worker_batches_id DESC
  LIMIT 1
  FOR UPDATE;

  IF v_batch.worker_batches_id IS NULL THEN RAISE EXCEPTION 'batch_not_found'; END IF;

  IF v_action = 'pause' AND v_batch.status_id IN (3, 4) THEN
    UPDATE public.worker_batches SET status_id = 8, worker_batches_next_run_at = NULL, worker_batches_updated_at = now()
    WHERE worker_batches_id = v_batch.worker_batches_id;
  ELSIF v_action = 'resume' AND v_batch.status_id = 8 THEN
    UPDATE public.worker_batches SET status_id = 4, worker_batches_next_run_at = now(), worker_batches_heartbeat_at = now(),
      worker_batches_worker_id = coalesce(nullif(trim(coalesce(p_worker_id, '')), ''), worker_batches_worker_id), worker_batches_updated_at = now()
    WHERE worker_batches_id = v_batch.worker_batches_id;
  ELSIF v_action = 'stop' AND v_batch.status_id IN (3, 4, 8) THEN
    UPDATE public.worker_batches SET status_id = 7, worker_batches_next_run_at = NULL, worker_batches_finished_at = now(), worker_batches_updated_at = now()
    WHERE worker_batches_id = v_batch.worker_batches_id;
    UPDATE public.worker_batch_items SET status_id = 7, worker_batch_items_finished_at = now(), worker_batch_items_updated_at = now()
    WHERE worker_batches_id = v_batch.worker_batches_id AND status_id = 3;
  ELSIF v_action NOT IN ('state', 'status') THEN
    RAISE EXCEPTION 'batch_action_invalid';
  END IF;

  PERFORM public.refresh_worker_batch_counters(v_batch.worker_batches_id);

  RETURN QUERY
  SELECT
    wb.worker_batches_id,
    CASE wb.status_id WHEN 3 THEN 'pending' WHEN 4 THEN 'running' WHEN 5 THEN 'completed' WHEN 6 THEN 'error' WHEN 7 THEN 'stopped' WHEN 8 THEN 'paused' ELSE 'idle' END,
    wb.status_id IN (3, 4, 8),
    trim(p_chip_instance),
    wb.worker_batches_total_items,
    greatest(wb.worker_batches_total_items - wb.worker_batches_processed_items, 0),
    wb.worker_batches_processed_items,
    wb.worker_batches_sent_items,
    wb.worker_batches_failed_items,
    wb.worker_batches_next_run_at,
    wb.worker_batches_started_at,
    coalesce(wb.worker_batches_last_error, ''),
    false
  FROM public.worker_batches AS wb
  WHERE wb.worker_batches_id = v_batch.worker_batches_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.worker_claim_next_batch_item(
  p_worker_batches_id bigint,
  p_worker_id text
)
RETURNS TABLE (
  batch_item_id bigint,
  queue_item_id bigint,
  item_position integer,
  total integer,
  processed integer
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_batch public.worker_batches%ROWTYPE;
  v_item public.worker_batch_items%ROWTYPE;
BEGIN
  SELECT * INTO v_batch FROM public.worker_batches WHERE worker_batches_id = p_worker_batches_id FOR UPDATE;
  IF v_batch.worker_batches_id IS NULL OR v_batch.status_id <> 4 THEN RETURN; END IF;
  IF v_batch.worker_batches_next_run_at IS NOT NULL AND v_batch.worker_batches_next_run_at > now() THEN RETURN; END IF;

  SELECT * INTO v_item
  FROM public.worker_batch_items
  WHERE worker_batches_id = p_worker_batches_id AND status_id = 3
  ORDER BY worker_batch_items_position
  LIMIT 1
  FOR UPDATE SKIP LOCKED;

  IF v_item.worker_batch_items_id IS NULL THEN
    UPDATE public.worker_batches
    SET status_id = 5, worker_batches_finished_at = now(), worker_batches_next_run_at = NULL,
      worker_batches_heartbeat_at = now(), worker_batches_updated_at = now()
    WHERE worker_batches_id = p_worker_batches_id
      AND NOT EXISTS (
        SELECT 1 FROM public.worker_batch_items WHERE worker_batches_id = p_worker_batches_id AND status_id IN (3, 4)
      );
    RETURN;
  END IF;

  UPDATE public.worker_batch_items
  SET status_id = 4,
      worker_batch_items_attempts = worker_batch_items_attempts + 1,
      worker_batch_items_started_at = now(),
      worker_batch_items_finished_at = NULL,
      worker_batch_items_error_message = NULL,
      worker_batch_items_updated_at = now()
  WHERE worker_batch_items_id = v_item.worker_batch_items_id;

  UPDATE public.worker_batches
  SET worker_batches_worker_id = nullif(trim(coalesce(p_worker_id, '')), ''),
      worker_batches_heartbeat_at = now(),
      worker_batches_updated_at = now()
  WHERE worker_batches_id = p_worker_batches_id;

  RETURN QUERY SELECT
    v_item.worker_batch_items_id,
    v_item.queue_items_id,
    v_item.worker_batch_items_position,
    v_batch.worker_batches_total_items,
    v_batch.worker_batches_processed_items;
END;
$function$;

CREATE OR REPLACE FUNCTION public.worker_complete_batch_item(
  p_worker_batch_items_id bigint,
  p_result text,
  p_error_message text,
  p_next_run_at timestamp with time zone
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_item public.worker_batch_items%ROWTYPE;
  v_result text := lower(trim(coalesce(p_result, '')));
  v_status_id bigint;
BEGIN
  SELECT * INTO v_item FROM public.worker_batch_items WHERE worker_batch_items_id = p_worker_batch_items_id FOR UPDATE;
  IF v_item.worker_batch_items_id IS NULL THEN RAISE EXCEPTION 'batch_item_not_found'; END IF;

  v_status_id := CASE v_result WHEN 'sent' THEN 5 WHEN 'paused' THEN 8 WHEN 'stopped' THEN 7 ELSE 6 END;

  UPDATE public.worker_batch_items
  SET status_id = v_status_id,
      worker_batch_items_finished_at = now(),
      worker_batch_items_error_message = nullif(trim(coalesce(p_error_message, '')), ''),
      worker_batch_items_updated_at = now()
  WHERE worker_batch_items_id = p_worker_batch_items_id;

  PERFORM public.refresh_worker_batch_counters(v_item.worker_batches_id);

  UPDATE public.worker_batches
  SET worker_batches_next_run_at = CASE WHEN status_id = 4 THEN p_next_run_at ELSE worker_batches_next_run_at END,
      worker_batches_heartbeat_at = now(),
      worker_batches_last_error = CASE WHEN v_status_id = 6 THEN nullif(trim(coalesce(p_error_message, '')), '') ELSE worker_batches_last_error END,
      worker_batches_updated_at = now()
  WHERE worker_batches_id = v_item.worker_batches_id;

  UPDATE public.worker_batches AS wb
  SET status_id = 5, worker_batches_finished_at = now(), worker_batches_next_run_at = NULL, worker_batches_updated_at = now()
  WHERE wb.worker_batches_id = v_item.worker_batches_id
    AND wb.status_id = 4
    AND NOT EXISTS (
      SELECT 1 FROM public.worker_batch_items AS wbi
      WHERE wbi.worker_batches_id = wb.worker_batches_id AND wbi.status_id IN (3, 4)
    );
END;
$function$;

CREATE OR REPLACE FUNCTION public.worker_claim_dispatch_part(
  p_users_id bigint,
  p_queue_items_id bigint,
  p_part_key text,
  p_content_hash text,
  p_body text
)
RETURNS TABLE (
  part_id bigint,
  part_state text,
  should_send boolean,
  claim_token uuid,
  external_id text,
  attempt integer
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp', 'extensions'
AS $function$
DECLARE
  v_part public.queue_item_dispatch_parts%ROWTYPE;
  v_token uuid;
  v_order integer;
BEGIN
  IF p_part_key NOT IN ('message_1', 'message_2', 'message_3', 'message_4', 'image') THEN
    RAISE EXCEPTION 'dispatch_part_invalid';
  END IF;
  IF nullif(trim(coalesce(p_content_hash, '')), '') IS NULL THEN RAISE EXCEPTION 'dispatch_part_hash_required'; END IF;

  PERFORM 1 FROM public.queue_items WHERE queue_items_id = p_queue_items_id AND users_id = p_users_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'queue_item_not_found'; END IF;

  v_order := CASE p_part_key WHEN 'message_1' THEN 1 WHEN 'message_2' THEN 2 WHEN 'message_3' THEN 3 WHEN 'message_4' THEN 4 ELSE 5 END;

  SELECT * INTO v_part
  FROM public.queue_item_dispatch_parts
  WHERE queue_items_id = p_queue_items_id AND queue_item_dispatch_parts_key = p_part_key
  FOR UPDATE;

  IF v_part.queue_item_dispatch_parts_id IS NOT NULL THEN
    IF v_part.queue_item_dispatch_parts_content_hash <> p_content_hash THEN
      RAISE EXCEPTION 'dispatch_part_content_changed';
    END IF;
    IF v_part.queue_item_dispatch_parts_state = 'sent' THEN
      RETURN QUERY SELECT v_part.queue_item_dispatch_parts_id, 'sent'::text, false, NULL::uuid,
        v_part.queue_item_dispatch_parts_external_id, v_part.queue_item_dispatch_parts_attempts;
      RETURN;
    END IF;
    IF v_part.queue_item_dispatch_parts_state = 'reconciliation_required' THEN
      RETURN QUERY SELECT v_part.queue_item_dispatch_parts_id, 'reconciliation_required'::text, false, NULL::uuid,
        v_part.queue_item_dispatch_parts_external_id, v_part.queue_item_dispatch_parts_attempts;
      RETURN;
    END IF;
    IF v_part.queue_item_dispatch_parts_state = 'processing' THEN
      IF v_part.queue_item_dispatch_parts_claimed_at IS NULL OR v_part.queue_item_dispatch_parts_claimed_at < now() - interval '15 minutes' THEN
        UPDATE public.queue_item_dispatch_parts
        SET queue_item_dispatch_parts_state = 'reconciliation_required',
            queue_item_dispatch_parts_claim_token = NULL,
            queue_item_dispatch_parts_error_message = 'stale_processing_requires_reconciliation',
            queue_item_dispatch_parts_updated_at = now()
        WHERE queue_item_dispatch_parts_id = v_part.queue_item_dispatch_parts_id;
        RETURN QUERY SELECT v_part.queue_item_dispatch_parts_id, 'reconciliation_required'::text, false, NULL::uuid,
          v_part.queue_item_dispatch_parts_external_id, v_part.queue_item_dispatch_parts_attempts;
      ELSE
        RETURN QUERY SELECT v_part.queue_item_dispatch_parts_id, 'processing'::text, false, NULL::uuid,
          v_part.queue_item_dispatch_parts_external_id, v_part.queue_item_dispatch_parts_attempts;
      END IF;
      RETURN;
    END IF;
  END IF;

  v_token := extensions.gen_random_uuid();

  INSERT INTO public.queue_item_dispatch_parts (
    users_id, queue_items_id, queue_item_dispatch_parts_key, queue_item_dispatch_parts_order,
    queue_item_dispatch_parts_state, queue_item_dispatch_parts_content_hash,
    queue_item_dispatch_parts_body, queue_item_dispatch_parts_attempts,
    queue_item_dispatch_parts_claim_token, queue_item_dispatch_parts_claimed_at,
    queue_item_dispatch_parts_error_message
  ) VALUES (
    p_users_id, p_queue_items_id, p_part_key, v_order,
    'processing', p_content_hash, coalesce(p_body, ''), 1,
    v_token, now(), NULL
  )
  ON CONFLICT (queue_items_id, queue_item_dispatch_parts_key)
  DO UPDATE SET
    queue_item_dispatch_parts_state = 'processing',
    queue_item_dispatch_parts_body = EXCLUDED.queue_item_dispatch_parts_body,
    queue_item_dispatch_parts_attempts = public.queue_item_dispatch_parts.queue_item_dispatch_parts_attempts + 1,
    queue_item_dispatch_parts_claim_token = EXCLUDED.queue_item_dispatch_parts_claim_token,
    queue_item_dispatch_parts_claimed_at = now(),
    queue_item_dispatch_parts_error_message = NULL,
    queue_item_dispatch_parts_updated_at = now()
  WHERE public.queue_item_dispatch_parts.queue_item_dispatch_parts_state IN ('pending', 'failed')
    AND public.queue_item_dispatch_parts.queue_item_dispatch_parts_content_hash = EXCLUDED.queue_item_dispatch_parts_content_hash
  RETURNING * INTO v_part;

  IF v_part.queue_item_dispatch_parts_id IS NULL THEN
    RAISE EXCEPTION 'dispatch_part_claim_conflict';
  END IF;

  RETURN QUERY SELECT v_part.queue_item_dispatch_parts_id, v_part.queue_item_dispatch_parts_state, true,
    v_part.queue_item_dispatch_parts_claim_token, v_part.queue_item_dispatch_parts_external_id,
    v_part.queue_item_dispatch_parts_attempts;
END;
$function$;

CREATE OR REPLACE FUNCTION public.worker_complete_dispatch_part(
  p_users_id bigint,
  p_queue_items_id bigint,
  p_part_key text,
  p_claim_token uuid,
  p_outcome text,
  p_external_id text,
  p_error_message text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_part public.queue_item_dispatch_parts%ROWTYPE;
  v_item public.queue_items%ROWTYPE;
  v_outcome text := lower(trim(coalesce(p_outcome, '')));
  v_state text;
  v_status_id bigint;
  v_idempotency_key text;
  v_recipient text;
BEGIN
  IF v_outcome NOT IN ('sent', 'failed', 'reconciliation_required') THEN RAISE EXCEPTION 'dispatch_part_outcome_invalid'; END IF;

  SELECT * INTO v_part
  FROM public.queue_item_dispatch_parts
  WHERE users_id = p_users_id AND queue_items_id = p_queue_items_id
    AND queue_item_dispatch_parts_key = p_part_key
  FOR UPDATE;

  IF v_part.queue_item_dispatch_parts_id IS NULL THEN RAISE EXCEPTION 'dispatch_part_not_found'; END IF;
  IF v_part.queue_item_dispatch_parts_state = 'sent' AND v_outcome = 'sent' THEN RETURN; END IF;
  IF v_part.queue_item_dispatch_parts_state <> 'processing' OR v_part.queue_item_dispatch_parts_claim_token IS DISTINCT FROM p_claim_token THEN
    RAISE EXCEPTION 'dispatch_part_claim_lost';
  END IF;

  v_state := v_outcome;
  UPDATE public.queue_item_dispatch_parts
  SET queue_item_dispatch_parts_state = v_state,
      queue_item_dispatch_parts_external_id = nullif(trim(coalesce(p_external_id, '')), ''),
      queue_item_dispatch_parts_sent_at = CASE WHEN v_outcome = 'sent' THEN now() ELSE NULL END,
      queue_item_dispatch_parts_error_message = nullif(trim(coalesce(p_error_message, '')), ''),
      queue_item_dispatch_parts_claim_token = NULL,
      queue_item_dispatch_parts_updated_at = now()
  WHERE queue_item_dispatch_parts_id = v_part.queue_item_dispatch_parts_id;

  SELECT * INTO v_item FROM public.queue_items WHERE queue_items_id = p_queue_items_id AND users_id = p_users_id;
  v_status_id := CASE WHEN v_outcome = 'sent' THEN 5 ELSE 6 END;
  v_idempotency_key := format('queue-item:%s:%s:%s', p_queue_items_id, p_part_key, v_part.queue_item_dispatch_parts_content_hash);
  v_recipient := regexp_replace(coalesce(v_item.queue_items_payload_snapshot #>> '{recipient,phone}', ''), '[^0-9]', '', 'g');

  INSERT INTO public.sents (
    users_id, queue_items_id, leads_id, channels_id, chips_id, templates_id, status_id,
    sents_recipient, sents_body, sents_external_id, sents_attempt,
    sents_error_message, sents_sent_at, sents_created_at, sents_updated_at,
    sents_part_key, sents_idempotency_key, sents_payload_hash
  ) VALUES (
    p_users_id, p_queue_items_id, v_item.leads_id,
    (SELECT channels_id FROM public.queues WHERE queues_id = v_item.queues_id),
    v_item.chips_id, v_item.templates_id, v_status_id,
    nullif(v_recipient, ''),
    jsonb_build_object(
      'part', p_part_key,
      'body', v_part.queue_item_dispatch_parts_body,
      'payload_hash', v_item.queue_items_payload_hash,
      'payload_frozen_at', v_item.queue_items_payload_created_at
    )::text,
    nullif(trim(coalesce(p_external_id, '')), ''),
    v_part.queue_item_dispatch_parts_attempts,
    nullif(trim(coalesce(p_error_message, '')), ''),
    CASE WHEN v_outcome = 'sent' THEN now() ELSE NULL END,
    now(), now(), p_part_key, v_idempotency_key, v_item.queue_items_payload_hash
  )
  ON CONFLICT (sents_idempotency_key) WHERE sents_idempotency_key IS NOT NULL
  DO UPDATE SET
    status_id = EXCLUDED.status_id,
    sents_external_id = coalesce(EXCLUDED.sents_external_id, public.sents.sents_external_id),
    sents_attempt = greatest(public.sents.sents_attempt, EXCLUDED.sents_attempt),
    sents_error_message = EXCLUDED.sents_error_message,
    sents_sent_at = coalesce(EXCLUDED.sents_sent_at, public.sents.sents_sent_at),
    sents_updated_at = now();
END;
$function$;

CREATE OR REPLACE FUNCTION public.worker_finalize_whatsapp_queue_item(
  p_users_id bigint,
  p_queue_items_id bigint
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_item public.queue_items%ROWTYPE;
  v_required_image boolean;
  v_missing integer;
BEGIN
  SELECT * INTO v_item FROM public.queue_items
  WHERE queue_items_id = p_queue_items_id AND users_id = p_users_id
  FOR UPDATE;
  IF v_item.queue_items_id IS NULL THEN RAISE EXCEPTION 'queue_item_not_found'; END IF;
  IF v_item.status_id = 5 THEN RETURN; END IF;

  SELECT count(*)::integer INTO v_missing
  FROM (VALUES ('message_1'), ('message_2'), ('message_3'), ('message_4')) AS required(part_key)
  WHERE NOT EXISTS (
    SELECT 1 FROM public.queue_item_dispatch_parts AS p
    WHERE p.queue_items_id = p_queue_items_id
      AND p.queue_item_dispatch_parts_key = required.part_key
      AND p.queue_item_dispatch_parts_state = 'sent'
  );
  IF v_missing > 0 THEN RAISE EXCEPTION 'required_message_parts_not_sent'; END IF;

  v_required_image := coalesce((v_item.queue_items_payload_snapshot #>> '{media,required}')::boolean, false);
  IF v_required_image AND NOT EXISTS (
    SELECT 1 FROM public.queue_item_dispatch_parts AS p
    WHERE p.queue_items_id = p_queue_items_id
      AND p.queue_item_dispatch_parts_key = 'image'
      AND p.queue_item_dispatch_parts_state = 'sent'
  ) THEN
    RAISE EXCEPTION 'required_image_part_not_sent';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.queue_item_dispatch_parts AS p
    WHERE p.queue_items_id = p_queue_items_id
      AND p.queue_item_dispatch_parts_state IN ('processing', 'reconciliation_required')
  ) THEN
    RAISE EXCEPTION 'dispatch_part_reconciliation_required';
  END IF;

  UPDATE public.queue_items
  SET status_id = 5, queue_items_finished_at = now(), queue_items_error_message = NULL, queue_items_updated_at = now()
  WHERE queue_items_id = p_queue_items_id AND users_id = p_users_id;

  UPDATE public.leads
  SET lead_status_id = 5, leads_updated_at = now()
  WHERE leads_id = v_item.leads_id AND users_id = p_users_id AND lead_status_id = 4;
END;
$function$;

CREATE OR REPLACE FUNCTION public.worker_fail_whatsapp_queue_item(
  p_users_id bigint,
  p_queue_items_id bigint,
  p_error_message text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
  UPDATE public.queue_items
  SET status_id = 6,
      queue_items_error_message = nullif(trim(coalesce(p_error_message, '')), ''),
      queue_items_finished_at = now(),
      queue_items_updated_at = now()
  WHERE queue_items_id = p_queue_items_id AND users_id = p_users_id AND status_id <> 5;
END;
$function$;

CREATE OR REPLACE FUNCTION public.worker_recover_stale_whatsapp(
  p_stale_before timestamp with time zone DEFAULT (now() - interval '15 minutes')
)
RETURNS TABLE (
  recovered_items integer,
  reconciliation_items integer
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_recovered integer := 0;
  v_reconciliation integer := 0;
  v_row record;
BEGIN
  FOR v_row IN
    SELECT wbi.worker_batch_items_id, wbi.worker_batches_id, wbi.queue_items_id, qi.users_id, qi.status_id
    FROM public.worker_batch_items AS wbi
    JOIN public.queue_items AS qi ON qi.queue_items_id = wbi.queue_items_id
    WHERE wbi.status_id = 4
      AND coalesce(wbi.worker_batch_items_started_at, wbi.worker_batch_items_updated_at) < p_stale_before
    FOR UPDATE OF wbi, qi SKIP LOCKED
  LOOP
    IF v_row.status_id = 5 THEN
      UPDATE public.worker_batch_items SET status_id = 5, worker_batch_items_finished_at = now(), worker_batch_items_updated_at = now()
      WHERE worker_batch_items_id = v_row.worker_batch_items_id;
      v_recovered := v_recovered + 1;
    ELSIF EXISTS (
      SELECT 1 FROM public.queue_item_dispatch_parts AS p
      WHERE p.queue_items_id = v_row.queue_items_id AND p.queue_item_dispatch_parts_state = 'processing'
    ) THEN
      UPDATE public.queue_item_dispatch_parts
      SET queue_item_dispatch_parts_state = 'reconciliation_required',
          queue_item_dispatch_parts_claim_token = NULL,
          queue_item_dispatch_parts_error_message = 'worker_restart_after_provider_claim',
          queue_item_dispatch_parts_updated_at = now()
      WHERE queue_items_id = v_row.queue_items_id AND queue_item_dispatch_parts_state = 'processing';

      UPDATE public.queue_items SET status_id = 6,
        queue_items_error_message = 'reconciliation_required_after_worker_restart',
        queue_items_finished_at = now(), queue_items_updated_at = now()
      WHERE queue_items_id = v_row.queue_items_id AND status_id <> 5;

      UPDATE public.worker_batch_items SET status_id = 6,
        worker_batch_items_error_message = 'reconciliation_required_after_worker_restart',
        worker_batch_items_finished_at = now(), worker_batch_items_updated_at = now()
      WHERE worker_batch_items_id = v_row.worker_batch_items_id;
      v_reconciliation := v_reconciliation + 1;
    ELSE
      UPDATE public.queue_items SET status_id = 3,
        queue_items_error_message = NULL, queue_items_finished_at = NULL, queue_items_updated_at = now()
      WHERE queue_items_id = v_row.queue_items_id AND status_id = 4;

      UPDATE public.worker_batch_items SET status_id = 3,
        worker_batch_items_started_at = NULL, worker_batch_items_finished_at = NULL,
        worker_batch_items_error_message = NULL, worker_batch_items_updated_at = now()
      WHERE worker_batch_items_id = v_row.worker_batch_items_id;
      v_recovered := v_recovered + 1;
    END IF;
    PERFORM public.refresh_worker_batch_counters(v_row.worker_batches_id);
  END LOOP;

  -- Também recupera envios avulsos que não pertencem a um lote persistente.
  FOR v_row IN
    SELECT qi.queue_items_id, qi.users_id
    FROM public.queue_items AS qi
    WHERE qi.status_id = 4
      AND coalesce(qi.queue_items_started_at, qi.queue_items_updated_at) < p_stale_before
      AND NOT EXISTS (
        SELECT 1 FROM public.worker_batch_items AS wbi
        WHERE wbi.queue_items_id = qi.queue_items_id AND wbi.status_id = 4
      )
    FOR UPDATE OF qi SKIP LOCKED
  LOOP
    IF EXISTS (
      SELECT 1 FROM public.queue_item_dispatch_parts AS p
      WHERE p.queue_items_id = v_row.queue_items_id AND p.queue_item_dispatch_parts_state = 'processing'
    ) THEN
      UPDATE public.queue_item_dispatch_parts
      SET queue_item_dispatch_parts_state = 'reconciliation_required',
          queue_item_dispatch_parts_claim_token = NULL,
          queue_item_dispatch_parts_error_message = 'worker_restart_after_provider_claim',
          queue_item_dispatch_parts_updated_at = now()
      WHERE queue_items_id = v_row.queue_items_id AND queue_item_dispatch_parts_state = 'processing';

      UPDATE public.queue_items SET status_id = 6,
        queue_items_error_message = 'reconciliation_required_after_worker_restart',
        queue_items_finished_at = now(), queue_items_updated_at = now()
      WHERE queue_items_id = v_row.queue_items_id;
      v_reconciliation := v_reconciliation + 1;
    ELSE
      UPDATE public.queue_items SET status_id = 3,
        queue_items_error_message = NULL, queue_items_finished_at = NULL, queue_items_updated_at = now()
      WHERE queue_items_id = v_row.queue_items_id;
      v_recovered := v_recovered + 1;
    END IF;
  END LOOP;

  UPDATE public.worker_batches
  SET worker_batches_next_run_at = now(), worker_batches_heartbeat_at = now(), worker_batches_updated_at = now()
  WHERE status_id = 4
    AND coalesce(worker_batches_heartbeat_at, worker_batches_updated_at) < p_stale_before;

  RETURN QUERY SELECT v_recovered, v_reconciliation;
END;
$function$;

COMMENT ON TABLE public.worker_batches IS 'Estado persistente dos lotes processados pelo Worker; sobrevive a reinícios.';
COMMENT ON TABLE public.worker_batch_items IS 'Ordem e resultado individual dos itens pertencentes a um lote persistente.';
COMMENT ON TABLE public.queue_item_dispatch_parts IS 'Ledger idempotente de cada uma das quatro mensagens e da mídia de um queue_item.';
COMMENT ON FUNCTION public.worker_recover_stale_whatsapp(timestamp with time zone) IS 'Recupera execução interrompida sem reenviar automaticamente partes cujo resultado no provedor ficou incerto.';

REVOKE ALL ON FUNCTION public.refresh_worker_batch_counters(bigint) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.worker_start_whatsapp_batch(bigint, text, bigint[], text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.worker_set_whatsapp_batch_state(bigint, text, text, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.worker_claim_next_batch_item(bigint, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.worker_complete_batch_item(bigint, text, text, timestamp with time zone) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.worker_claim_dispatch_part(bigint, bigint, text, text, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.worker_complete_dispatch_part(bigint, bigint, text, uuid, text, text, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.worker_finalize_whatsapp_queue_item(bigint, bigint) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.worker_fail_whatsapp_queue_item(bigint, bigint, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.worker_recover_stale_whatsapp(timestamp with time zone) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.worker_start_whatsapp_batch(bigint, text, bigint[], text) TO service_role;
GRANT EXECUTE ON FUNCTION public.worker_set_whatsapp_batch_state(bigint, text, text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.worker_claim_next_batch_item(bigint, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.worker_complete_batch_item(bigint, text, text, timestamp with time zone) TO service_role;
GRANT EXECUTE ON FUNCTION public.worker_claim_dispatch_part(bigint, bigint, text, text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.worker_complete_dispatch_part(bigint, bigint, text, uuid, text, text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.worker_finalize_whatsapp_queue_item(bigint, bigint) TO service_role;
GRANT EXECUTE ON FUNCTION public.worker_fail_whatsapp_queue_item(bigint, bigint, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.worker_recover_stale_whatsapp(timestamp with time zone) TO service_role;

COMMIT;
