BEGIN;

-- Etapa 5 / Fase A - hotfix de identidade de conversa WhatsApp.
-- Objetivo: uma conversa privada por organizacao + chip + contato canonico.
-- JIDs @lid e JIDs telefonicos passam a ser aliases da mesma conversa quando
-- o provider entrega evidencia de equivalencia (ex.: remoteJidAlt/ChatAlt).

CREATE TABLE IF NOT EXISTS public.conversation_contact_aliases(
  conversation_contact_aliases_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizations_id bigint NOT NULL REFERENCES public.organizations(organizations_id) ON DELETE CASCADE,
  chips_id bigint NOT NULL REFERENCES public.chips(chips_id) ON DELETE CASCADE,
  conversations_id bigint NOT NULL REFERENCES public.conversations(conversations_id) ON DELETE CASCADE,
  alias_jid text NOT NULL,
  alias_kind text NOT NULL DEFAULT 'provider',
  conversation_contact_aliases_created_at timestamptz NOT NULL DEFAULT now(),
  conversation_contact_aliases_updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT conversation_contact_aliases_jid_nonempty CHECK(length(trim(alias_jid))>0),
  UNIQUE(organizations_id,chips_id,alias_jid)
);
CREATE INDEX IF NOT EXISTS conversation_contact_aliases_conversation_idx
  ON public.conversation_contact_aliases(organizations_id,conversations_id);

ALTER TABLE public.conversation_contact_aliases ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS conversation_contact_aliases_org_select ON public.conversation_contact_aliases;
CREATE POLICY conversation_contact_aliases_org_select ON public.conversation_contact_aliases FOR SELECT TO authenticated
USING(organizations_id=public.current_organization_id() AND public.has_organization_permission('whatsapp.view'));
REVOKE INSERT,UPDATE,DELETE ON public.conversation_contact_aliases FROM anon,authenticated;
GRANT SELECT ON public.conversation_contact_aliases TO authenticated;

CREATE OR REPLACE FUNCTION public.stage5_normalize_contact_jid(p_jid text)
RETURNS text
LANGUAGE plpgsql IMMUTABLE SET search_path TO pg_catalog,public AS $$
DECLARE v text:=lower(trim(coalesce(p_jid,'')));v_digits text;
BEGIN
  IF v='' THEN RETURN NULL; END IF;
  IF v LIKE '%@g.us' OR v LIKE '%@broadcast' THEN RETURN v; END IF;
  IF v ~ '@(s\.whatsapp\.net|c\.us)$' THEN
    v_digits:=regexp_replace(split_part(v,'@',1),'\D','','g');
    IF v_digits<>'' THEN RETURN v_digits||'@s.whatsapp.net'; END IF;
  END IF;
  RETURN v;
END;
$$;

CREATE OR REPLACE FUNCTION public.stage5_payload_contact_aliases(p_remote_jid text,p_raw_payload jsonb DEFAULT '{}'::jsonb)
RETURNS text[]
LANGUAGE plpgsql IMMUTABLE SET search_path TO pg_catalog,public AS $$
DECLARE v_values text[]:=ARRAY[]::text[];v text;v_candidate text;
BEGIN
  FOREACH v IN ARRAY ARRAY[
    p_remote_jid,
    p_raw_payload#>>'{key,remoteJid}',
    p_raw_payload#>>'{key,remote_jid}',
    p_raw_payload#>>'{key,remoteJidAlt}',
    p_raw_payload#>>'{key,remote_jid_alt}',
    p_raw_payload->>'remoteJid',
    p_raw_payload->>'remote_jid',
    p_raw_payload->>'remoteJidAlt',
    p_raw_payload->>'remote_jid_alt',
    p_raw_payload#>>'{Info,Chat}',
    p_raw_payload#>>'{Info,ChatAlt}'
  ] LOOP
    v_candidate:=public.stage5_normalize_contact_jid(v);
    IF v_candidate IS NOT NULL AND NOT (v_candidate=ANY(v_values)) THEN
      v_values:=array_append(v_values,v_candidate);
    END IF;
  END LOOP;
  RETURN v_values;
END;
$$;

CREATE OR REPLACE FUNCTION public.stage5_preferred_contact_jid(p_remote_jid text,p_raw_payload jsonb DEFAULT '{}'::jsonb)
RETURNS text
LANGUAGE plpgsql IMMUTABLE SET search_path TO pg_catalog,public AS $$
DECLARE v_aliases text[]:=public.stage5_payload_contact_aliases(p_remote_jid,p_raw_payload);v text;
BEGIN
  FOREACH v IN ARRAY v_aliases LOOP
    IF v ~ '@s\.whatsapp\.net$' THEN RETURN v; END IF;
  END LOOP;
  RETURN v_aliases[1];
END;
$$;

CREATE OR REPLACE FUNCTION public.stage5_merge_conversations(p_primary_conversations_id bigint,p_secondary_conversations_id bigint)
RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE v_primary public.conversations%ROWTYPE;v_secondary public.conversations%ROWTYPE;v_latest_secondary boolean;
BEGIN
  IF p_primary_conversations_id IS NULL OR p_secondary_conversations_id IS NULL OR p_primary_conversations_id=p_secondary_conversations_id THEN
    RETURN p_primary_conversations_id;
  END IF;

  SELECT * INTO v_primary FROM public.conversations WHERE conversations_id=p_primary_conversations_id FOR UPDATE;
  SELECT * INTO v_secondary FROM public.conversations WHERE conversations_id=p_secondary_conversations_id FOR UPDATE;
  IF v_primary.conversations_id IS NULL OR v_secondary.conversations_id IS NULL THEN
    RETURN coalesce(v_primary.conversations_id,v_secondary.conversations_id);
  END IF;
  IF v_primary.organizations_id<>v_secondary.organizations_id OR v_primary.chips_id<>v_secondary.chips_id THEN
    RAISE EXCEPTION 'conversation_merge_scope_mismatch';
  END IF;

  v_latest_secondary:=coalesce(v_secondary.last_message_at,'epoch'::timestamptz)>coalesce(v_primary.last_message_at,'epoch'::timestamptz);

  INSERT INTO public.conversation_member_states(
    organizations_id,conversations_id,organization_members_id,last_read_message_id,last_viewed_at,
    conversation_member_states_created_at,conversation_member_states_updated_at
  )
  SELECT organizations_id,v_primary.conversations_id,organization_members_id,last_read_message_id,last_viewed_at,
         conversation_member_states_created_at,now()
    FROM public.conversation_member_states
   WHERE conversations_id=v_secondary.conversations_id
  ON CONFLICT(organizations_id,conversations_id,organization_members_id) DO UPDATE SET
    last_read_message_id=CASE
      WHEN excluded.last_read_message_id IS NULL THEN conversation_member_states.last_read_message_id
      WHEN conversation_member_states.last_read_message_id IS NULL THEN excluded.last_read_message_id
      ELSE greatest(conversation_member_states.last_read_message_id,excluded.last_read_message_id)
    END,
    last_viewed_at=greatest(coalesce(conversation_member_states.last_viewed_at,'epoch'::timestamptz),coalesce(excluded.last_viewed_at,'epoch'::timestamptz)),
    conversation_member_states_updated_at=now();

  -- Presence e efemera (TTL de 45 s). Evitamos conflitos de sessoes ao fundir.
  DELETE FROM public.conversation_presence WHERE conversations_id=v_secondary.conversations_id;
  DELETE FROM public.conversation_member_states WHERE conversations_id=v_secondary.conversations_id;

  UPDATE public.conversation_messages
     SET conversations_id=v_primary.conversations_id,
         conversation_messages_updated_at=now()
   WHERE organizations_id=v_primary.organizations_id
     AND conversations_id=v_secondary.conversations_id;

  INSERT INTO public.conversation_contact_aliases(
    organizations_id,chips_id,conversations_id,alias_jid,alias_kind,
    conversation_contact_aliases_created_at,conversation_contact_aliases_updated_at
  )
  SELECT organizations_id,chips_id,v_primary.conversations_id,alias_jid,alias_kind,
         conversation_contact_aliases_created_at,now()
    FROM public.conversation_contact_aliases
   WHERE conversations_id=v_secondary.conversations_id
  ON CONFLICT(organizations_id,chips_id,alias_jid) DO UPDATE SET
    conversations_id=excluded.conversations_id,
    conversation_contact_aliases_updated_at=now();

  UPDATE public.conversations SET
    leads_id=coalesce(v_primary.leads_id,v_secondary.leads_id),
    contact_phone=coalesce(nullif(v_primary.contact_phone,''),nullif(v_secondary.contact_phone,'')),
    contact_name=coalesce(nullif(v_primary.contact_name,''),nullif(v_secondary.contact_name,'')),
    contact_avatar_url=coalesce(nullif(v_primary.contact_avatar_url,''),nullif(v_secondary.contact_avatar_url,'')),
    assigned_to_member_id=CASE
      WHEN v_primary.assigned_to_member_id IS NULL THEN v_secondary.assigned_to_member_id
      WHEN v_secondary.assigned_to_member_id IS NULL THEN v_primary.assigned_to_member_id
      WHEN coalesce(v_secondary.assignment_updated_at,'epoch'::timestamptz)>coalesce(v_primary.assignment_updated_at,'epoch'::timestamptz) THEN v_secondary.assigned_to_member_id
      ELSE v_primary.assigned_to_member_id
    END,
    assignment_updated_at=greatest(coalesce(v_primary.assignment_updated_at,'epoch'::timestamptz),coalesce(v_secondary.assignment_updated_at,'epoch'::timestamptz)),
    last_replied_by_member_id=coalesce(v_primary.last_replied_by_member_id,v_secondary.last_replied_by_member_id),
    conversation_status=CASE WHEN v_primary.conversation_status='open' OR v_secondary.conversation_status='open' THEN 'open' ELSE v_primary.conversation_status END,
    unread_count=coalesce(v_primary.unread_count,0)+coalesce(v_secondary.unread_count,0),
    last_message_at=CASE WHEN v_latest_secondary THEN v_secondary.last_message_at ELSE v_primary.last_message_at END,
    last_message_preview=CASE WHEN v_latest_secondary THEN v_secondary.last_message_preview ELSE v_primary.last_message_preview END,
    last_message_direction=CASE WHEN v_latest_secondary THEN v_secondary.last_message_direction ELSE v_primary.last_message_direction END,
    conversation_version=greatest(coalesce(v_primary.conversation_version,1),coalesce(v_secondary.conversation_version,1))+1,
    conversations_created_at=least(coalesce(v_primary.conversations_created_at,now()),coalesce(v_secondary.conversations_created_at,now())),
    conversations_updated_at=now()
  WHERE conversations_id=v_primary.conversations_id;

  DELETE FROM public.conversations WHERE conversations_id=v_secondary.conversations_id;
  RETURN v_primary.conversations_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.stage5_register_conversation_aliases(
  p_organizations_id bigint,p_chips_id bigint,p_conversations_id bigint,p_aliases text[]
)
RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE v_alias text;v_existing bigint;v_current bigint:=p_conversations_id;v_primary bigint;v_secondary bigint;
BEGIN
  IF v_current IS NULL THEN RETURN NULL; END IF;
  FOREACH v_alias IN ARRAY coalesce(p_aliases,ARRAY[]::text[]) LOOP
    v_alias:=public.stage5_normalize_contact_jid(v_alias);
    IF v_alias IS NULL THEN CONTINUE; END IF;
    SELECT conversations_id INTO v_existing
      FROM public.conversation_contact_aliases
     WHERE organizations_id=p_organizations_id AND chips_id=p_chips_id AND alias_jid=v_alias
     FOR UPDATE;
    IF v_existing IS NOT NULL AND v_existing<>v_current THEN
      -- Preferimos como primaria a conversa cujo remote_jid ja e telefonico;
      -- caso contrario, o menor ID mantem estabilidade historica.
      SELECT CASE
        WHEN public.stage5_normalize_contact_jid(c1.remote_jid) ~ '@s\.whatsapp\.net$' AND NOT (public.stage5_normalize_contact_jid(c2.remote_jid) ~ '@s\.whatsapp\.net$') THEN c1.conversations_id
        WHEN public.stage5_normalize_contact_jid(c2.remote_jid) ~ '@s\.whatsapp\.net$' AND NOT (public.stage5_normalize_contact_jid(c1.remote_jid) ~ '@s\.whatsapp\.net$') THEN c2.conversations_id
        ELSE least(c1.conversations_id,c2.conversations_id)
      END
      INTO v_primary
      FROM public.conversations c1 CROSS JOIN public.conversations c2
      WHERE c1.conversations_id=v_current AND c2.conversations_id=v_existing;
      v_secondary:=CASE WHEN v_primary=v_current THEN v_existing ELSE v_current END;
      v_current:=public.stage5_merge_conversations(v_primary,v_secondary);
    END IF;
    INSERT INTO public.conversation_contact_aliases(organizations_id,chips_id,conversations_id,alias_jid,alias_kind)
    VALUES(p_organizations_id,p_chips_id,v_current,v_alias,CASE WHEN v_alias ~ '@s\.whatsapp\.net$' THEN 'phone' ELSE 'provider' END)
    ON CONFLICT(organizations_id,chips_id,alias_jid) DO UPDATE SET
      conversations_id=excluded.conversations_id,
      conversation_contact_aliases_updated_at=now();
  END LOOP;
  RETURN v_current;
END;
$$;

CREATE OR REPLACE FUNCTION public.stage5_resolve_conversation_id(
  p_organizations_id bigint,p_chips_id bigint,p_remote_jid text,p_raw_payload jsonb DEFAULT '{}'::jsonb
)
RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path TO pg_catalog,public AS $$
DECLARE v_aliases text[]:=public.stage5_payload_contact_aliases(p_remote_jid,p_raw_payload);v_alias text;v_id bigint;v_preferred text:=public.stage5_preferred_contact_jid(p_remote_jid,p_raw_payload);
BEGIN
  FOREACH v_alias IN ARRAY v_aliases LOOP
    SELECT conversations_id INTO v_id FROM public.conversation_contact_aliases
     WHERE organizations_id=p_organizations_id AND chips_id=p_chips_id AND alias_jid=v_alias LIMIT 1;
    IF v_id IS NOT NULL THEN RETURN v_id; END IF;
  END LOOP;
  IF v_preferred IS NOT NULL THEN
    SELECT conversations_id INTO v_id FROM public.conversations
     WHERE organizations_id=p_organizations_id AND chips_id=p_chips_id
       AND public.stage5_normalize_contact_jid(remote_jid)=v_preferred
     ORDER BY conversations_id LIMIT 1;
  END IF;
  RETURN v_id;
END;
$$;

-- Convergencia dos duplicados ja existentes. A equivalencia so e inferida por
-- JID telefonico/alias do provider, nunca por nome exibido.
DO $merge_existing$
DECLARE r record;r2 record;v_primary bigint;v_secondary bigint;v_identity text;
BEGIN
  CREATE TEMP TABLE _stage5_identity_map ON COMMIT DROP AS
  SELECT c.conversations_id,c.organizations_id,c.chips_id,
         coalesce(
           (
             SELECT public.stage5_preferred_contact_jid(cm.remote_jid,coalesce(cm.raw_payload,'{}'::jsonb))
               FROM public.conversation_messages cm
              WHERE cm.organizations_id=c.organizations_id AND cm.conversations_id=c.conversations_id
                AND public.stage5_preferred_contact_jid(cm.remote_jid,coalesce(cm.raw_payload,'{}'::jsonb)) ~ '@s\.whatsapp\.net$'
              ORDER BY cm.conversation_messages_id DESC LIMIT 1
           ),
           public.stage5_preferred_contact_jid(c.remote_jid,'{}'::jsonb)
         ) AS identity_jid
    FROM public.conversations c;

  FOR r IN
    SELECT organizations_id,chips_id,identity_jid,array_agg(conversations_id ORDER BY conversations_id) ids
      FROM _stage5_identity_map
     WHERE identity_jid IS NOT NULL
     GROUP BY organizations_id,chips_id,identity_jid
    HAVING count(*)>1
  LOOP
    -- Preferir conversa ja gravada com JID telefonico para nao alterar o
    -- identificador usado pelos envios existentes.
    SELECT m.conversations_id INTO v_primary
      FROM _stage5_identity_map m
      JOIN public.conversations c ON c.conversations_id=m.conversations_id
     WHERE m.organizations_id=r.organizations_id AND m.chips_id=r.chips_id AND m.identity_jid=r.identity_jid
     ORDER BY (public.stage5_normalize_contact_jid(c.remote_jid) ~ '@s\.whatsapp\.net$') DESC,c.conversations_id
     LIMIT 1;
    FOREACH v_secondary IN ARRAY r.ids LOOP
      IF v_secondary<>v_primary THEN v_primary:=public.stage5_merge_conversations(v_primary,v_secondary); END IF;
    END LOOP;
  END LOOP;

  -- Registrar aliases das conversas finais a partir do remote_jid e do historico.
  FOR r IN SELECT conversations_id,organizations_id,chips_id,remote_jid FROM public.conversations LOOP
    PERFORM public.stage5_register_conversation_aliases(r.organizations_id,r.chips_id,r.conversations_id,ARRAY[public.stage5_normalize_contact_jid(r.remote_jid)]);
  END LOOP;
  FOR r IN
    SELECT cm.conversation_messages_id
      FROM public.conversation_messages cm
     ORDER BY cm.conversation_messages_id
  LOOP
    SELECT cm.conversations_id,cm.organizations_id,cm.chips_id,cm.remote_jid,cm.raw_payload
      INTO r2
      FROM public.conversation_messages cm
     WHERE cm.conversation_messages_id=r.conversation_messages_id;
    IF r2.conversations_id IS NOT NULL AND EXISTS(SELECT 1 FROM public.conversations c WHERE c.conversations_id=r2.conversations_id) THEN
      PERFORM public.stage5_register_conversation_aliases(r2.organizations_id,r2.chips_id,r2.conversations_id,public.stage5_payload_contact_aliases(r2.remote_jid,coalesce(r2.raw_payload,'{}'::jsonb)));
    END IF;
  END LOOP;
END
$merge_existing$;

-- Substitui a ingestao para resolver aliases antes de criar uma conversa.
CREATE OR REPLACE FUNCTION public.service_ingest_evolution_message(
  p_instances_id bigint,p_event_type text,p_external_message_id text,p_remote_jid text,p_from_me boolean,
  p_message_type text,p_message_body text,p_message_status text,p_contact_name text,p_provider_timestamp timestamptz,
  p_raw_payload jsonb,p_media_url text,p_media_mime_type text,p_media_file_name text,p_quoted_external_message_id text
)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE v_instance record;v_chip record;v_scope bigint;v_conversation public.conversations%ROWTYPE;v_message public.conversation_messages%ROWTYPE;
  v_direction text:=CASE WHEN p_from_me THEN 'outbound' ELSE 'inbound' END;v_member bigint;v_queue bigint;
  v_aliases text[]:=public.stage5_payload_contact_aliases(p_remote_jid,coalesce(p_raw_payload,'{}'::jsonb));
  v_canonical_jid text:=public.stage5_preferred_contact_jid(p_remote_jid,coalesce(p_raw_payload,'{}'::jsonb));
  v_conversation_id bigint;v_phone text;
BEGIN
  IF v_canonical_jid ILIKE '%@g.us' OR v_canonical_jid ILIKE '%@broadcast' THEN RETURN jsonb_build_object('ignored',true,'reason','unsupported_chat_kind'); END IF;
  SELECT i.instances_id,i.organizations_id INTO v_instance FROM public.instances i WHERE i.instances_id=p_instances_id;
  IF v_instance.instances_id IS NULL THEN RAISE EXCEPTION 'webhook_instance_not_found'; END IF;
  SELECT c.chips_id,c.instances_id INTO v_chip FROM public.chips c WHERE c.instances_id=p_instances_id AND c.organizations_id=v_instance.organizations_id ORDER BY c.chips_id LIMIT 1;
  IF v_chip.chips_id IS NULL THEN RETURN jsonb_build_object('ignored',true,'reason','webhook_chip_not_found'); END IF;
  SELECT legacy_scope_users_id INTO v_scope FROM public.organizations WHERE organizations_id=v_instance.organizations_id;
  v_phone:=CASE WHEN v_canonical_jid ~ '@s\.whatsapp\.net$' THEN regexp_replace(split_part(v_canonical_jid,'@',1),'\D','','g') ELSE NULL END;

  -- Se o webhook confirma uma mensagem que ja foi preparada pelo Worker/Main,
  -- o external_message_id e a evidencia mais forte: preservamos a conversa ja
  -- existente e apenas aprendemos os aliases observados pelo provider.
  SELECT * INTO v_message FROM public.conversation_messages
   WHERE organizations_id=v_instance.organizations_id AND instances_id=p_instances_id AND external_message_id=p_external_message_id;
  IF v_message.conversation_messages_id IS NOT NULL THEN
    v_conversation_id:=v_message.conversations_id;
  ELSE
    v_conversation_id:=public.stage5_resolve_conversation_id(v_instance.organizations_id,v_chip.chips_id,v_canonical_jid,p_raw_payload);
  END IF;

  IF v_conversation_id IS NULL THEN
    INSERT INTO public.conversations(users_id,organizations_id,chips_id,instances_id,remote_jid,contact_phone,contact_name,conversation_status,last_message_at,last_message_preview,last_message_direction,conversations_created_at,conversations_updated_at)
    VALUES(v_scope,v_instance.organizations_id,v_chip.chips_id,p_instances_id,v_canonical_jid,v_phone,nullif(p_contact_name,''),'open',coalesce(p_provider_timestamp,now()),coalesce(p_message_body,'['||p_message_type||']'),v_direction,now(),now())
    ON CONFLICT(organizations_id,chips_id,remote_jid) DO UPDATE SET contact_name=coalesce(nullif(excluded.contact_name,''),conversations.contact_name),
      contact_phone=coalesce(nullif(conversations.contact_phone,''),excluded.contact_phone),
      last_message_at=greatest(coalesce(conversations.last_message_at,'epoch'),excluded.last_message_at),
      last_message_preview=CASE WHEN excluded.last_message_at>=coalesce(conversations.last_message_at,'epoch') THEN excluded.last_message_preview ELSE conversations.last_message_preview END,
      last_message_direction=CASE WHEN excluded.last_message_at>=coalesce(conversations.last_message_at,'epoch') THEN excluded.last_message_direction ELSE conversations.last_message_direction END,
      conversations_updated_at=now()
    RETURNING conversations_id INTO v_conversation_id;
  ELSE
    UPDATE public.conversations SET
      contact_name=coalesce(nullif(p_contact_name,''),contact_name),
      contact_phone=coalesce(nullif(contact_phone,''),v_phone),
      last_message_at=greatest(coalesce(last_message_at,'epoch'),coalesce(p_provider_timestamp,now())),
      last_message_preview=CASE WHEN coalesce(p_provider_timestamp,now())>=coalesce(last_message_at,'epoch') THEN coalesce(p_message_body,'['||p_message_type||']') ELSE last_message_preview END,
      last_message_direction=CASE WHEN coalesce(p_provider_timestamp,now())>=coalesce(last_message_at,'epoch') THEN v_direction ELSE last_message_direction END,
      conversations_updated_at=now()
     WHERE conversations_id=v_conversation_id;
  END IF;

  v_conversation_id:=public.stage5_register_conversation_aliases(v_instance.organizations_id,v_chip.chips_id,v_conversation_id,v_aliases);
  SELECT * INTO v_conversation FROM public.conversations WHERE conversations_id=v_conversation_id;

  IF v_message.conversation_messages_id IS NOT NULL THEN
    UPDATE public.conversation_messages SET
      conversations_id=v_conversation.conversations_id,
      remote_jid=v_canonical_jid,
      message_status=CASE WHEN public.stage5_status_rank(p_message_status)>=public.stage5_status_rank(message_status) OR message_status IN('failed','reconciliation_required') THEN p_message_status ELSE message_status END,
      message_body=coalesce(nullif(p_message_body,''),message_body),media_url=coalesce(nullif(p_media_url,''),media_url),
      media_mime_type=coalesce(nullif(p_media_mime_type,''),media_mime_type),media_file_name=coalesce(nullif(p_media_file_name,''),media_file_name),
      raw_payload=coalesce(raw_payload,'{}')||coalesce(p_raw_payload,'{}'),conversation_messages_updated_at=now()
     WHERE conversation_messages_id=v_message.conversation_messages_id RETURNING * INTO v_message;
    RETURN jsonb_build_object('ignored',false,'merged',true,'conversationId',v_message.conversations_id,'messageId',v_message.conversation_messages_id);
  END IF;
  IF p_from_me AND to_regclass('public.queue_item_dispatch_parts') IS NOT NULL THEN
    BEGIN
      EXECUTE 'SELECT queue_items_id FROM public.queue_item_dispatch_parts WHERE external_id=$1 ORDER BY queue_item_dispatch_parts_id DESC LIMIT 1' INTO v_queue USING p_external_message_id;
      SELECT qi.dispatched_by_member_id INTO v_member FROM public.queue_items qi WHERE qi.queue_items_id=v_queue AND qi.organizations_id=v_instance.organizations_id;
    EXCEPTION WHEN undefined_column THEN NULL;
    END;
  END IF;
  INSERT INTO public.conversation_messages(users_id,organizations_id,conversations_id,chips_id,instances_id,queue_items_id,external_message_id,remote_jid,direction,from_me,
    message_type,message_body,media_url,media_mime_type,media_file_name,quoted_external_message_id,message_status,sent_by_member_id,executed_by,provider_timestamp,raw_payload,
    conversation_messages_created_at,conversation_messages_updated_at)
  VALUES(v_scope,v_instance.organizations_id,v_conversation.conversations_id,v_chip.chips_id,p_instances_id,v_queue,p_external_message_id,v_canonical_jid,v_direction,p_from_me,
    coalesce(nullif(p_message_type,''),'unsupported'),p_message_body,p_media_url,p_media_mime_type,p_media_file_name,p_quoted_external_message_id,p_message_status,
    CASE WHEN p_from_me THEN v_member ELSE NULL END,'system',p_provider_timestamp,coalesce(p_raw_payload,'{}'),now(),now()) RETURNING * INTO v_message;
  IF NOT p_from_me AND v_conversation.assigned_to_member_id IS NULL THEN
    SELECT cm.sent_by_member_id INTO v_member FROM public.conversation_messages cm
     JOIN public.organization_members m ON m.organization_members_id=cm.sent_by_member_id AND m.organizations_id=cm.organizations_id AND m.status_id=1
     WHERE cm.organizations_id=v_instance.organizations_id AND cm.conversations_id=v_conversation.conversations_id
       AND cm.direction='outbound' AND cm.executed_by='system' AND cm.sent_by_member_id IS NOT NULL
     ORDER BY cm.conversation_messages_id DESC LIMIT 1;
    IF v_member IS NOT NULL THEN
      UPDATE public.conversations SET assigned_to_member_id=v_member,assignment_updated_at=now(),conversation_version=conversation_version+1
       WHERE organizations_id=v_instance.organizations_id AND conversations_id=v_conversation.conversations_id AND assigned_to_member_id IS NULL;
    END IF;
  END IF;
  RETURN jsonb_build_object('ignored',false,'merged',false,'conversationId',v_conversation.conversations_id,'messageId',v_message.conversation_messages_id);
END;
$$;

-- Chat/contact updates tambem reaproveitam aliases ja conhecidos.
CREATE OR REPLACE FUNCTION public.service_upsert_evolution_chat(
  p_instances_id bigint,p_remote_jid text,p_contact_name text,p_contact_avatar_url text,p_unread_count integer
)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE v_instance record;v_chip bigint;v_scope bigint;v_c public.conversations%ROWTYPE;v_id bigint;v_jid text:=public.stage5_normalize_contact_jid(p_remote_jid);v_phone text;
BEGIN
  IF v_jid ILIKE '%@g.us' OR v_jid ILIKE '%@broadcast' THEN RETURN jsonb_build_object('ignored',true); END IF;
  SELECT instances_id,organizations_id INTO v_instance FROM public.instances WHERE instances_id=p_instances_id;
  IF v_instance.instances_id IS NULL THEN RETURN jsonb_build_object('ignored',true); END IF;
  SELECT chips_id INTO v_chip FROM public.chips WHERE instances_id=p_instances_id AND organizations_id=v_instance.organizations_id ORDER BY chips_id LIMIT 1;
  IF v_chip IS NULL THEN RETURN jsonb_build_object('ignored',true); END IF;
  SELECT legacy_scope_users_id INTO v_scope FROM public.organizations WHERE organizations_id=v_instance.organizations_id;
  v_id:=public.stage5_resolve_conversation_id(v_instance.organizations_id,v_chip,v_jid,'{}'::jsonb);
  v_phone:=CASE WHEN v_jid ~ '@s\.whatsapp\.net$' THEN regexp_replace(split_part(v_jid,'@',1),'\D','','g') ELSE NULL END;
  IF v_id IS NULL THEN
    INSERT INTO public.conversations(users_id,organizations_id,chips_id,instances_id,remote_jid,contact_phone,contact_name,contact_avatar_url,conversation_status,unread_count,conversations_created_at,conversations_updated_at)
    VALUES(v_scope,v_instance.organizations_id,v_chip,p_instances_id,v_jid,v_phone,p_contact_name,p_contact_avatar_url,'open',coalesce(p_unread_count,0),now(),now())
    ON CONFLICT(organizations_id,chips_id,remote_jid) DO UPDATE SET contact_name=coalesce(nullif(excluded.contact_name,''),conversations.contact_name),
      contact_avatar_url=coalesce(nullif(excluded.contact_avatar_url,''),conversations.contact_avatar_url),contact_phone=coalesce(nullif(conversations.contact_phone,''),excluded.contact_phone),
      unread_count=greatest(conversations.unread_count,excluded.unread_count),conversations_updated_at=now()
    RETURNING * INTO v_c;
  ELSE
    UPDATE public.conversations SET contact_name=coalesce(nullif(p_contact_name,''),contact_name),contact_avatar_url=coalesce(nullif(p_contact_avatar_url,''),contact_avatar_url),
      contact_phone=coalesce(nullif(contact_phone,''),v_phone),unread_count=greatest(unread_count,coalesce(p_unread_count,0)),conversations_updated_at=now()
     WHERE conversations_id=v_id RETURNING * INTO v_c;
  END IF;
  PERFORM public.stage5_register_conversation_aliases(v_instance.organizations_id,v_chip,v_c.conversations_id,ARRAY[v_jid]);
  RETURN jsonb_build_object('ignored',false,'conversationId',v_c.conversations_id);
END;
$$;

-- Envio automatico deve convergir para a mesma conversa/alias do inbound.
CREATE OR REPLACE FUNCTION public.service_stage5_converge_automatic_message(
  p_organizations_id bigint,p_queue_items_id bigint,p_external_message_id text,p_remote_jid text,p_message_body text,p_message_type text DEFAULT 'text'
)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE v_q record;v_chip record;v_scope bigint;v_c public.conversations%ROWTYPE;v_m public.conversation_messages%ROWTYPE;v_id bigint;
  v_jid text:=public.stage5_normalize_contact_jid(p_remote_jid);v_phone text;
BEGIN
  SELECT qi.queue_items_id,qi.organizations_id,qi.chips_id,qi.leads_id,qi.dispatched_by_member_id INTO v_q
   FROM public.queue_items qi WHERE qi.queue_items_id=p_queue_items_id AND qi.organizations_id=p_organizations_id;
  IF v_q.queue_items_id IS NULL THEN RAISE EXCEPTION 'automatic_message_queue_item_not_found'; END IF;
  SELECT c.chips_id,c.instances_id INTO v_chip FROM public.chips c WHERE c.chips_id=v_q.chips_id AND c.organizations_id=p_organizations_id;
  IF v_chip.chips_id IS NULL THEN RAISE EXCEPTION 'automatic_message_chip_not_found'; END IF;
  SELECT legacy_scope_users_id INTO v_scope FROM public.organizations WHERE organizations_id=p_organizations_id;
  v_phone:=CASE WHEN v_jid ~ '@s\.whatsapp\.net$' THEN regexp_replace(split_part(v_jid,'@',1),'\D','','g') ELSE NULL END;
  v_id:=public.stage5_resolve_conversation_id(p_organizations_id,v_chip.chips_id,v_jid,'{}'::jsonb);
  IF v_id IS NULL THEN
    INSERT INTO public.conversations(users_id,organizations_id,chips_id,instances_id,leads_id,remote_jid,contact_phone,conversation_status,last_message_at,last_message_preview,last_message_direction,conversations_created_at,conversations_updated_at)
    VALUES(v_scope,p_organizations_id,v_chip.chips_id,v_chip.instances_id,v_q.leads_id,v_jid,v_phone,'open',now(),p_message_body,'outbound',now(),now())
    ON CONFLICT(organizations_id,chips_id,remote_jid) DO UPDATE SET leads_id=coalesce(conversations.leads_id,excluded.leads_id),contact_phone=coalesce(nullif(conversations.contact_phone,''),excluded.contact_phone),
      last_message_at=excluded.last_message_at,last_message_preview=excluded.last_message_preview,last_message_direction='outbound',conversations_updated_at=now()
    RETURNING * INTO v_c;
  ELSE
    UPDATE public.conversations SET leads_id=coalesce(leads_id,v_q.leads_id),contact_phone=coalesce(nullif(contact_phone,''),v_phone),last_message_at=now(),
      last_message_preview=p_message_body,last_message_direction='outbound',conversations_updated_at=now()
     WHERE conversations_id=v_id RETURNING * INTO v_c;
  END IF;
  v_id:=public.stage5_register_conversation_aliases(p_organizations_id,v_chip.chips_id,v_c.conversations_id,ARRAY[v_jid]);
  SELECT * INTO v_c FROM public.conversations WHERE conversations_id=v_id;
  INSERT INTO public.conversation_messages(users_id,organizations_id,conversations_id,chips_id,instances_id,leads_id,queue_items_id,external_message_id,remote_jid,
    direction,from_me,message_type,message_body,message_status,sent_by_member_id,executed_by,provider_timestamp,conversation_messages_created_at,conversation_messages_updated_at)
  VALUES(v_scope,p_organizations_id,v_c.conversations_id,v_chip.chips_id,v_chip.instances_id,v_q.leads_id,p_queue_items_id,p_external_message_id,v_jid,
    'outbound',true,coalesce(nullif(p_message_type,''),'text'),p_message_body,'sent',v_q.dispatched_by_member_id,'system',now(),now(),now())
  ON CONFLICT(organizations_id,instances_id,external_message_id) WHERE external_message_id IS NOT NULL DO UPDATE SET
    conversations_id=excluded.conversations_id,remote_jid=excluded.remote_jid,
    queue_items_id=coalesce(conversation_messages.queue_items_id,excluded.queue_items_id),sent_by_member_id=coalesce(conversation_messages.sent_by_member_id,excluded.sent_by_member_id),
    executed_by='system',message_body=coalesce(conversation_messages.message_body,excluded.message_body),conversation_messages_updated_at=now()
  RETURNING * INTO v_m;
  RETURN jsonb_build_object('conversationId',v_c.conversations_id,'messageId',v_m.conversation_messages_id,'merged',true);
END;
$$;

REVOKE ALL ON FUNCTION public.stage5_normalize_contact_jid(text) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.stage5_payload_contact_aliases(text,jsonb) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.stage5_preferred_contact_jid(text,jsonb) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.stage5_merge_conversations(bigint,bigint) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.stage5_register_conversation_aliases(bigint,bigint,bigint,text[]) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.stage5_resolve_conversation_id(bigint,bigint,text,jsonb) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.stage5_normalize_contact_jid(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.stage5_payload_contact_aliases(text,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.stage5_preferred_contact_jid(text,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.stage5_merge_conversations(bigint,bigint) TO service_role;
GRANT EXECUTE ON FUNCTION public.stage5_register_conversation_aliases(bigint,bigint,bigint,text[]) TO service_role;
GRANT EXECUTE ON FUNCTION public.stage5_resolve_conversation_id(bigint,bigint,text,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.service_ingest_evolution_message(bigint,text,text,text,boolean,text,text,text,text,timestamptz,jsonb,text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.service_upsert_evolution_chat(bigint,text,text,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.service_stage5_converge_automatic_message(bigint,bigint,text,text,text,text) TO service_role;

COMMIT;
