BEGIN;

-- ETAPA 13: chat textual por chip, alimentado pelos webhooks da Evolution.
-- O domínio de conversas é separado de filas e de sents. O frontend possui
-- somente leitura direta; escrita e ingestão passam por RPC/backend.

CREATE UNIQUE INDEX IF NOT EXISTS chips_one_active_per_instance_unique
  ON public.chips(users_id, instances_id)
  WHERE status_id = 1;

CREATE TABLE IF NOT EXISTS public.conversations (
  conversations_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id bigint NOT NULL REFERENCES public.users(users_id) ON DELETE CASCADE,
  chips_id bigint NOT NULL REFERENCES public.chips(chips_id) ON DELETE CASCADE,
  instances_id bigint NOT NULL REFERENCES public.instances(instances_id) ON DELETE CASCADE,
  leads_id bigint REFERENCES public.leads(leads_id) ON DELETE SET NULL,
  remote_jid text NOT NULL,
  contact_phone text,
  contact_name text,
  contact_avatar_url text,
  conversation_status text NOT NULL DEFAULT 'open' CHECK (conversation_status IN ('open','archived')),
  unread_count integer NOT NULL DEFAULT 0 CHECK (unread_count >= 0),
  last_message_at timestamptz,
  last_message_preview text,
  last_message_direction text CHECK (last_message_direction IS NULL OR last_message_direction IN ('inbound','outbound')),
  last_read_at timestamptz,
  conversations_created_at timestamptz NOT NULL DEFAULT now(),
  conversations_updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(users_id, chips_id, remote_jid)
);

CREATE TABLE IF NOT EXISTS public.conversation_messages (
  conversation_messages_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id bigint NOT NULL REFERENCES public.users(users_id) ON DELETE CASCADE,
  conversations_id bigint NOT NULL REFERENCES public.conversations(conversations_id) ON DELETE CASCADE,
  chips_id bigint NOT NULL REFERENCES public.chips(chips_id) ON DELETE CASCADE,
  instances_id bigint NOT NULL REFERENCES public.instances(instances_id) ON DELETE CASCADE,
  leads_id bigint REFERENCES public.leads(leads_id) ON DELETE SET NULL,
  external_message_id text,
  client_idempotency_key uuid,
  remote_jid text NOT NULL,
  direction text NOT NULL CHECK (direction IN ('inbound','outbound')),
  from_me boolean NOT NULL DEFAULT false,
  message_type text NOT NULL DEFAULT 'text',
  message_body text,
  media_url text,
  media_mime_type text,
  media_file_name text,
  quoted_external_message_id text,
  message_status text NOT NULL DEFAULT 'pending'
    CHECK (message_status IN ('pending','sending','sent','delivered','read','failed','deleted','reconciliation_required')),
  provider_timestamp timestamptz,
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  error_message text,
  conversation_messages_created_at timestamptz NOT NULL DEFAULT now(),
  conversation_messages_updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS conversation_messages_external_unique
  ON public.conversation_messages(instances_id, external_message_id)
  WHERE external_message_id IS NOT NULL AND external_message_id <> '';
CREATE UNIQUE INDEX IF NOT EXISTS conversation_messages_client_idempotency_unique
  ON public.conversation_messages(users_id, client_idempotency_key)
  WHERE client_idempotency_key IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.conversation_message_events (
  conversation_message_events_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id bigint NOT NULL REFERENCES public.users(users_id) ON DELETE CASCADE,
  conversation_messages_id bigint NOT NULL REFERENCES public.conversation_messages(conversation_messages_id) ON DELETE CASCADE,
  event_type text NOT NULL,
  previous_status text,
  target_status text,
  external_event_id text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  conversation_message_events_created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.evolution_webhook_receipts (
  evolution_webhook_receipts_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id bigint NOT NULL REFERENCES public.users(users_id) ON DELETE CASCADE,
  instances_id bigint NOT NULL REFERENCES public.instances(instances_id) ON DELETE CASCADE,
  event_type text NOT NULL,
  external_event_id text,
  payload_hash text NOT NULL,
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  processing_status text NOT NULL DEFAULT 'received'
    CHECK (processing_status IN ('received','processed','ignored','error')),
  error_message text,
  received_at timestamptz NOT NULL DEFAULT now(),
  processed_at timestamptz,
  UNIQUE(instances_id, event_type, payload_hash)
);

CREATE INDEX IF NOT EXISTS conversations_user_activity_idx
  ON public.conversations(users_id, last_message_at DESC NULLS LAST, conversations_id DESC);
CREATE INDEX IF NOT EXISTS conversations_chip_activity_idx
  ON public.conversations(users_id, chips_id, last_message_at DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS conversations_unread_idx
  ON public.conversations(users_id, unread_count DESC, last_message_at DESC NULLS LAST)
  WHERE unread_count > 0;
CREATE INDEX IF NOT EXISTS conversation_messages_thread_idx
  ON public.conversation_messages(users_id, conversations_id, provider_timestamp DESC NULLS LAST, conversation_messages_id DESC);
CREATE INDEX IF NOT EXISTS conversation_message_events_message_idx
  ON public.conversation_message_events(users_id, conversation_messages_id, conversation_message_events_created_at DESC);
CREATE INDEX IF NOT EXISTS evolution_webhook_receipts_received_idx
  ON public.evolution_webhook_receipts(instances_id, received_at DESC);

ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_message_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evolution_webhook_receipts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS conversations_own_select ON public.conversations;
CREATE POLICY conversations_own_select ON public.conversations
FOR SELECT TO authenticated USING (users_id = public.ensure_current_user());

DROP POLICY IF EXISTS conversation_messages_own_select ON public.conversation_messages;
CREATE POLICY conversation_messages_own_select ON public.conversation_messages
FOR SELECT TO authenticated USING (users_id = public.ensure_current_user());

DROP POLICY IF EXISTS conversation_message_events_own_select ON public.conversation_message_events;
CREATE POLICY conversation_message_events_own_select ON public.conversation_message_events
FOR SELECT TO authenticated USING (users_id = public.ensure_current_user());

DROP POLICY IF EXISTS evolution_webhook_receipts_own_select ON public.evolution_webhook_receipts;
CREATE POLICY evolution_webhook_receipts_own_select ON public.evolution_webhook_receipts
FOR SELECT TO authenticated USING (users_id = public.ensure_current_user());

REVOKE INSERT, UPDATE, DELETE ON public.conversations FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.conversation_messages FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.conversation_message_events FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.evolution_webhook_receipts FROM anon, authenticated;
GRANT SELECT ON public.conversations, public.conversation_messages, public.conversation_message_events TO authenticated;
GRANT SELECT ON public.evolution_webhook_receipts TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.conversations, public.conversation_messages, public.conversation_message_events, public.evolution_webhook_receipts TO service_role;

CREATE OR REPLACE FUNCTION public.chat_message_status_rank(p_status text)
RETURNS integer
LANGUAGE sql IMMUTABLE
SET search_path TO pg_catalog
AS $$
  SELECT CASE lower(coalesce(p_status,''))
    WHEN 'pending' THEN 10
    WHEN 'reconciliation_required' THEN 15
    WHEN 'sending' THEN 20
    WHEN 'sent' THEN 30
    WHEN 'delivered' THEN 40
    WHEN 'read' THEN 50
    WHEN 'failed' THEN 25
    WHEN 'deleted' THEN 100
    ELSE 0
  END;
$$;

CREATE OR REPLACE FUNCTION public.service_ingest_evolution_message(
  p_instances_id bigint,
  p_event_type text,
  p_external_message_id text,
  p_remote_jid text,
  p_from_me boolean,
  p_message_type text,
  p_message_body text,
  p_message_status text,
  p_contact_name text DEFAULT NULL,
  p_provider_timestamp timestamptz DEFAULT NULL,
  p_raw_payload jsonb DEFAULT '{}'::jsonb,
  p_media_url text DEFAULT NULL,
  p_media_mime_type text DEFAULT NULL,
  p_media_file_name text DEFAULT NULL,
  p_quoted_external_message_id text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO pg_catalog, public
AS $$
DECLARE
  v_users_id bigint;
  v_chips_id bigint;
  v_leads_id bigint;
  v_conversation_id bigint;
  v_message_id bigint;
  v_is_new boolean := false;
  v_remote_jid text := lower(trim(coalesce(p_remote_jid,'')));
  v_external_id text := nullif(trim(coalesce(p_external_message_id,'')),'');
  v_phone text;
  v_direction text := CASE WHEN coalesce(p_from_me,false) THEN 'outbound' ELSE 'inbound' END;
  v_status text := lower(coalesce(nullif(trim(p_message_status),''), CASE WHEN p_from_me THEN 'sent' ELSE 'delivered' END));
  v_previous_status text;
  v_timestamp timestamptz := coalesce(p_provider_timestamp,now());
  v_body text := nullif(p_message_body,'');
BEGIN
  IF auth.role() <> 'service_role' THEN RAISE EXCEPTION 'service_role_required'; END IF;
  IF p_instances_id IS NULL OR v_remote_jid='' THEN RAISE EXCEPTION 'chat_instance_remote_jid_required'; END IF;
  IF v_remote_jid LIKE '%@g.us' OR v_remote_jid LIKE '%@broadcast' THEN
    RETURN jsonb_build_object('ignored',true,'reason','group_or_broadcast');
  END IF;
  IF v_external_id IS NULL THEN RAISE EXCEPTION 'external_message_id_required'; END IF;
  IF public.chat_message_status_rank(v_status)=0 THEN v_status:=CASE WHEN p_from_me THEN 'sent' ELSE 'delivered' END; END IF;

  SELECT i.users_id,c.chips_id
    INTO v_users_id,v_chips_id
  FROM public.instances i
  JOIN public.chips c ON c.instances_id=i.instances_id AND c.users_id=i.users_id
  WHERE i.instances_id=p_instances_id
  ORDER BY CASE WHEN c.status_id=1 THEN 0 ELSE 1 END,c.chips_id
  LIMIT 1;
  IF v_users_id IS NULL OR v_chips_id IS NULL THEN RAISE EXCEPTION 'chat_chip_not_found_for_instance'; END IF;

  v_phone:=CASE WHEN v_remote_jid ~* '@(s\.whatsapp\.net|c\.us)$' THEN public.normalize_identity_phone(split_part(split_part(v_remote_jid,'@',1),':',1)) ELSE '' END;
  IF v_phone<>'' THEN
    SELECT coalesce(l.canonical_lead_id,l.leads_id)
      INTO v_leads_id
    FROM public.leads l
    WHERE l.users_id=v_users_id AND l.leads_normalized_phone=v_phone
    ORDER BY CASE WHEN l.lead_status_id=5 THEN 0 ELSE 1 END,l.leads_updated_at DESC,l.leads_id DESC
    LIMIT 1;
  END IF;

  INSERT INTO public.conversations(
    users_id,chips_id,instances_id,leads_id,remote_jid,contact_phone,contact_name,
    conversation_status,last_message_at,last_message_preview,last_message_direction,conversations_updated_at
  ) VALUES (
    v_users_id,v_chips_id,p_instances_id,v_leads_id,v_remote_jid,nullif(v_phone,''),nullif(trim(coalesce(p_contact_name,'')),''),
    'open',v_timestamp,left(coalesce(v_body,'['||coalesce(nullif(p_message_type,''),'mensagem')||']'),240),v_direction,now()
  )
  ON CONFLICT(users_id,chips_id,remote_jid) DO UPDATE SET
    instances_id=excluded.instances_id,
    leads_id=coalesce(public.conversations.leads_id,excluded.leads_id),
    contact_phone=coalesce(nullif(public.conversations.contact_phone,''),excluded.contact_phone),
    contact_name=coalesce(nullif(excluded.contact_name,''),public.conversations.contact_name),
    conversation_status='open',
    conversations_updated_at=now()
  RETURNING conversations_id INTO v_conversation_id;

  SELECT m.conversation_messages_id,m.message_status
    INTO v_message_id,v_previous_status
  FROM public.conversation_messages m
  WHERE m.instances_id=p_instances_id AND m.external_message_id=v_external_id
  FOR UPDATE;

  IF v_message_id IS NULL THEN
    INSERT INTO public.conversation_messages(
      users_id,conversations_id,chips_id,instances_id,leads_id,external_message_id,remote_jid,
      direction,from_me,message_type,message_body,media_url,media_mime_type,media_file_name,
      quoted_external_message_id,message_status,provider_timestamp,raw_payload
    ) VALUES (
      v_users_id,v_conversation_id,v_chips_id,p_instances_id,v_leads_id,v_external_id,v_remote_jid,
      v_direction,coalesce(p_from_me,false),coalesce(nullif(trim(p_message_type),''),'text'),v_body,
      nullif(trim(coalesce(p_media_url,'')),''),nullif(trim(coalesce(p_media_mime_type,'')),''),nullif(trim(coalesce(p_media_file_name,'')),''),
      nullif(trim(coalesce(p_quoted_external_message_id,'')),''),v_status,v_timestamp,coalesce(p_raw_payload,'{}'::jsonb)
    ) RETURNING conversation_messages_id INTO v_message_id;
    v_is_new:=true;
  ELSE
    UPDATE public.conversation_messages m SET
      conversations_id=v_conversation_id,
      leads_id=coalesce(m.leads_id,v_leads_id),
      message_type=coalesce(nullif(trim(p_message_type),''),m.message_type),
      message_body=coalesce(v_body,m.message_body),
      media_url=coalesce(nullif(trim(coalesce(p_media_url,'')),''),m.media_url),
      media_mime_type=coalesce(nullif(trim(coalesce(p_media_mime_type,'')),''),m.media_mime_type),
      media_file_name=coalesce(nullif(trim(coalesce(p_media_file_name,'')),''),m.media_file_name),
      quoted_external_message_id=coalesce(nullif(trim(coalesce(p_quoted_external_message_id,'')),''),m.quoted_external_message_id),
      message_status=CASE WHEN public.chat_message_status_rank(v_status)>=public.chat_message_status_rank(m.message_status) THEN v_status ELSE m.message_status END,
      provider_timestamp=coalesce(p_provider_timestamp,m.provider_timestamp),
      raw_payload=coalesce(p_raw_payload,m.raw_payload),
      conversation_messages_updated_at=now()
    WHERE m.conversation_messages_id=v_message_id;
  END IF;

  INSERT INTO public.conversation_message_events(
    users_id,conversation_messages_id,event_type,previous_status,target_status,external_event_id,payload
  ) VALUES (
    v_users_id,v_message_id,lower(coalesce(nullif(trim(p_event_type),''),'message_upsert')),
    v_previous_status,v_status,v_external_id,coalesce(p_raw_payload,'{}'::jsonb)
  );

  UPDATE public.conversations c SET
    last_message_at=CASE WHEN c.last_message_at IS NULL OR v_timestamp>=c.last_message_at THEN v_timestamp ELSE c.last_message_at END,
    last_message_preview=CASE WHEN c.last_message_at IS NULL OR v_timestamp>=c.last_message_at THEN left(coalesce(v_body,'['||coalesce(nullif(p_message_type,''),'mensagem')||']'),240) ELSE c.last_message_preview END,
    last_message_direction=CASE WHEN c.last_message_at IS NULL OR v_timestamp>=c.last_message_at THEN v_direction ELSE c.last_message_direction END,
    unread_count=CASE WHEN v_is_new AND v_direction='inbound' THEN c.unread_count+1 ELSE c.unread_count END,
    conversations_updated_at=now()
  WHERE c.conversations_id=v_conversation_id;

  PERFORM public.append_audit_event(
    'evolution_webhook',CASE WHEN v_direction='inbound' THEN 'chat_message_received' ELSE 'chat_message_sent_sync' END,
    'conversation_message',v_message_id::text,v_leads_id,NULL,1,NULL,NULL,NULL,
    jsonb_build_object('conversation_id',v_conversation_id,'chip_id',v_chips_id,'external_message_id',v_external_id,'is_new',v_is_new),v_users_id
  );

  RETURN jsonb_build_object('ignored',false,'conversation_id',v_conversation_id,'message_id',v_message_id,'is_new',v_is_new);
END;
$$;

CREATE OR REPLACE FUNCTION public.service_update_evolution_message_status(
  p_instances_id bigint,
  p_external_message_id text,
  p_message_status text,
  p_event_type text DEFAULT 'messages_update',
  p_raw_payload jsonb DEFAULT '{}'::jsonb,
  p_provider_timestamp timestamptz DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO pg_catalog, public
AS $$
DECLARE
  v_message public.conversation_messages%ROWTYPE;
  v_target text:=lower(trim(coalesce(p_message_status,'')));
  v_effective text;
BEGIN
  IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role_required'; END IF;
  IF public.chat_message_status_rank(v_target)=0 THEN RETURN jsonb_build_object('updated',false,'reason','unknown_status'); END IF;
  SELECT * INTO v_message FROM public.conversation_messages
  WHERE instances_id=p_instances_id AND external_message_id=trim(coalesce(p_external_message_id,'')) FOR UPDATE;
  IF v_message.conversation_messages_id IS NULL THEN RETURN jsonb_build_object('updated',false,'reason','message_not_found'); END IF;
  v_effective:=CASE WHEN public.chat_message_status_rank(v_target)>=public.chat_message_status_rank(v_message.message_status) THEN v_target ELSE v_message.message_status END;
  UPDATE public.conversation_messages SET message_status=v_effective,provider_timestamp=coalesce(p_provider_timestamp,provider_timestamp),raw_payload=coalesce(p_raw_payload,raw_payload),conversation_messages_updated_at=now()
  WHERE conversation_messages_id=v_message.conversation_messages_id;
  INSERT INTO public.conversation_message_events(users_id,conversation_messages_id,event_type,previous_status,target_status,external_event_id,payload)
  VALUES(v_message.users_id,v_message.conversation_messages_id,lower(coalesce(nullif(trim(p_event_type),''),'messages_update')),v_message.message_status,v_effective,v_message.external_message_id,coalesce(p_raw_payload,'{}'::jsonb));
  RETURN jsonb_build_object('updated',true,'message_id',v_message.conversation_messages_id,'status',v_effective);
END;
$$;

CREATE OR REPLACE FUNCTION public.service_upsert_evolution_chat(
  p_instances_id bigint,
  p_remote_jid text,
  p_contact_name text DEFAULT NULL,
  p_contact_avatar_url text DEFAULT NULL,
  p_unread_count integer DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO pg_catalog, public
AS $$
DECLARE v_users_id bigint; v_chips_id bigint; v_leads_id bigint; v_phone text; v_id bigint; v_jid text:=lower(trim(coalesce(p_remote_jid,'')));
BEGIN
  IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role_required'; END IF;
  IF v_jid='' OR v_jid LIKE '%@g.us' OR v_jid LIKE '%@broadcast' THEN RETURN NULL; END IF;
  SELECT i.users_id,c.chips_id INTO v_users_id,v_chips_id FROM public.instances i JOIN public.chips c ON c.instances_id=i.instances_id AND c.users_id=i.users_id WHERE i.instances_id=p_instances_id ORDER BY CASE WHEN c.status_id=1 THEN 0 ELSE 1 END,c.chips_id LIMIT 1;
  IF v_users_id IS NULL THEN RAISE EXCEPTION 'chat_chip_not_found_for_instance'; END IF;
  v_phone:=CASE WHEN v_jid ~* '@(s\.whatsapp\.net|c\.us)$' THEN public.normalize_identity_phone(split_part(split_part(v_jid,'@',1),':',1)) ELSE '' END;
  SELECT coalesce(l.canonical_lead_id,l.leads_id) INTO v_leads_id FROM public.leads l WHERE l.users_id=v_users_id AND l.leads_normalized_phone=v_phone ORDER BY l.leads_updated_at DESC,l.leads_id DESC LIMIT 1;
  INSERT INTO public.conversations(users_id,chips_id,instances_id,leads_id,remote_jid,contact_phone,contact_name,contact_avatar_url,unread_count,conversations_updated_at)
  VALUES(v_users_id,v_chips_id,p_instances_id,v_leads_id,v_jid,nullif(v_phone,''),nullif(trim(coalesce(p_contact_name,'')),''),nullif(trim(coalesce(p_contact_avatar_url,'')),''),greatest(coalesce(p_unread_count,0),0),now())
  ON CONFLICT(users_id,chips_id,remote_jid) DO UPDATE SET leads_id=coalesce(public.conversations.leads_id,excluded.leads_id),contact_phone=coalesce(public.conversations.contact_phone,excluded.contact_phone),contact_name=coalesce(nullif(excluded.contact_name,''),public.conversations.contact_name),contact_avatar_url=coalesce(nullif(excluded.contact_avatar_url,''),public.conversations.contact_avatar_url),unread_count=CASE WHEN p_unread_count IS NULL THEN public.conversations.unread_count ELSE greatest(p_unread_count,0) END,conversations_updated_at=now()
  RETURNING conversations_id INTO v_id;
  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.mark_conversation_read(p_conversations_id bigint)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO pg_catalog, public
AS $$
DECLARE v_users_id bigint:=public.ensure_current_user(); v_lead_id bigint; v_updated boolean;
BEGIN
  UPDATE public.conversations SET unread_count=0,last_read_at=now(),conversations_updated_at=now()
  WHERE conversations_id=p_conversations_id AND users_id=v_users_id
  RETURNING leads_id INTO v_lead_id;
  v_updated:=FOUND;
  IF v_updated THEN
    PERFORM public.append_audit_event('panel','chat_conversation_read','conversation',p_conversations_id::text,v_lead_id,NULL,1,NULL,NULL,NULL,'{}'::jsonb,v_users_id);
  END IF;
  RETURN v_updated;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_conversation_archived(p_conversations_id bigint,p_archived boolean)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO pg_catalog, public
AS $$
DECLARE v_users_id bigint:=public.ensure_current_user(); v_updated boolean;
BEGIN
  UPDATE public.conversations SET conversation_status=CASE WHEN p_archived THEN 'archived' ELSE 'open' END,conversations_updated_at=now()
  WHERE conversations_id=p_conversations_id AND users_id=v_users_id;
  v_updated:=FOUND;
  RETURN v_updated;
END;
$$;

CREATE OR REPLACE FUNCTION public.service_prepare_outgoing_chat_message(
  p_users_id bigint,
  p_conversations_id bigint,
  p_message_body text,
  p_client_idempotency_key uuid
)
RETURNS TABLE(
  conversation_messages_id bigint,
  conversations_id bigint,
  chips_id bigint,
  instances_id bigint,
  instance_name text,
  instance_url text,
  api_key text,
  recipient text,
  remote_jid text,
  message_body text,
  message_status text,
  external_message_id text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO pg_catalog, public, vault
AS $$
DECLARE v_conversation public.conversations%ROWTYPE; v_message_id bigint; v_body text:=trim(coalesce(p_message_body,''));
BEGIN
  IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role_required'; END IF;
  IF p_users_id IS NULL OR p_client_idempotency_key IS NULL THEN RAISE EXCEPTION 'chat_outgoing_identity_required'; END IF;
  IF v_body='' OR length(v_body)>4096 THEN RAISE EXCEPTION 'chat_message_body_invalid'; END IF;
  SELECT * INTO v_conversation FROM public.conversations WHERE conversations_id=p_conversations_id AND users_id=p_users_id FOR UPDATE;
  IF v_conversation.conversations_id IS NULL THEN RAISE EXCEPTION 'chat_conversation_not_found'; END IF;
  IF v_conversation.conversation_status='archived' THEN RAISE EXCEPTION 'chat_conversation_archived'; END IF;

  SELECT m.conversation_messages_id INTO v_message_id FROM public.conversation_messages m WHERE m.users_id=p_users_id AND m.client_idempotency_key=p_client_idempotency_key;
  IF v_message_id IS NULL THEN
    INSERT INTO public.conversation_messages AS inserted(users_id,conversations_id,chips_id,instances_id,leads_id,client_idempotency_key,remote_jid,direction,from_me,message_type,message_body,message_status,provider_timestamp)
    VALUES(p_users_id,v_conversation.conversations_id,v_conversation.chips_id,v_conversation.instances_id,v_conversation.leads_id,p_client_idempotency_key,v_conversation.remote_jid,'outbound',true,'text',v_body,'pending',now())
    RETURNING inserted.conversation_messages_id INTO v_message_id;
    UPDATE public.conversations SET last_message_at=now(),last_message_preview=left(v_body,240),last_message_direction='outbound',conversations_updated_at=now() WHERE public.conversations.conversations_id=v_conversation.conversations_id;
  END IF;

  RETURN QUERY
  SELECT m.conversation_messages_id,m.conversations_id,m.chips_id,m.instances_id,i.instances_name,i.instances_url,d.decrypted_secret,
    coalesce(nullif(v_conversation.contact_phone,''),CASE WHEN v_conversation.remote_jid ~* '@(s\.whatsapp\.net|c\.us)$' THEN public.normalize_identity_phone(split_part(split_part(v_conversation.remote_jid,'@',1),':',1)) ELSE '' END),
    m.remote_jid,m.message_body,m.message_status,m.external_message_id
  FROM public.conversation_messages m
  JOIN public.instances i ON i.instances_id=m.instances_id AND i.users_id=m.users_id
  JOIN public.instance_credentials ic ON ic.instances_id=i.instances_id AND ic.users_id=i.users_id
  JOIN vault.decrypted_secrets d ON d.id=ic.vault_secret_id
  WHERE m.conversation_messages_id=v_message_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.service_complete_outgoing_chat_message(
  p_users_id bigint,
  p_conversation_messages_id bigint,
  p_status text,
  p_external_message_id text DEFAULT NULL,
  p_raw_payload jsonb DEFAULT '{}'::jsonb,
  p_error_message text DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO pg_catalog, public
AS $$
DECLARE v_message public.conversation_messages%ROWTYPE; v_existing_id bigint; v_target text:=lower(trim(coalesce(p_status,''))); v_final_id bigint;
BEGIN
  IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role_required'; END IF;
  IF public.chat_message_status_rank(v_target)=0 THEN RAISE EXCEPTION 'chat_message_status_invalid'; END IF;
  SELECT * INTO v_message FROM public.conversation_messages WHERE conversation_messages_id=p_conversation_messages_id AND users_id=p_users_id FOR UPDATE;
  IF v_message.conversation_messages_id IS NULL THEN RAISE EXCEPTION 'chat_message_not_found'; END IF;

  IF nullif(trim(coalesce(p_external_message_id,'')),'') IS NOT NULL THEN
    SELECT conversation_messages_id INTO v_existing_id FROM public.conversation_messages
    WHERE instances_id=v_message.instances_id AND external_message_id=trim(p_external_message_id) AND conversation_messages_id<>v_message.conversation_messages_id FOR UPDATE;
  END IF;

  IF v_existing_id IS NOT NULL THEN
    DELETE FROM public.conversation_messages WHERE conversation_messages_id=v_message.conversation_messages_id;
    UPDATE public.conversation_messages SET client_idempotency_key=coalesce(client_idempotency_key,v_message.client_idempotency_key),message_body=coalesce(message_body,v_message.message_body),message_status=CASE WHEN public.chat_message_status_rank(v_target)>=public.chat_message_status_rank(message_status) THEN v_target ELSE message_status END,raw_payload=coalesce(p_raw_payload,raw_payload),error_message=p_error_message,conversation_messages_updated_at=now() WHERE conversation_messages_id=v_existing_id;
    v_final_id:=v_existing_id;
  ELSE
    UPDATE public.conversation_messages SET external_message_id=coalesce(nullif(trim(coalesce(p_external_message_id,'')),''),external_message_id),message_status=v_target,raw_payload=coalesce(p_raw_payload,raw_payload),error_message=p_error_message,provider_timestamp=coalesce(provider_timestamp,now()),conversation_messages_updated_at=now() WHERE conversation_messages_id=v_message.conversation_messages_id;
    v_final_id:=v_message.conversation_messages_id;
  END IF;

  INSERT INTO public.conversation_message_events(users_id,conversation_messages_id,event_type,previous_status,target_status,external_event_id,payload)
  VALUES(p_users_id,v_final_id,'outgoing_api_result',v_message.message_status,v_target,nullif(trim(coalesce(p_external_message_id,'')),''),coalesce(p_raw_payload,'{}'::jsonb));
  PERFORM public.append_audit_event('chat_api','chat_message_outgoing_result','conversation_message',v_final_id::text,v_message.leads_id,NULL,1,NULL,NULL,p_error_message,jsonb_build_object('status',v_target,'external_message_id',p_external_message_id),p_users_id);
  RETURN v_final_id;
END;
$$;

REVOKE ALL ON FUNCTION public.service_ingest_evolution_message(bigint,text,text,text,boolean,text,text,text,text,timestamptz,jsonb,text,text,text,text) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.service_update_evolution_message_status(bigint,text,text,text,jsonb,timestamptz) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.service_upsert_evolution_chat(bigint,text,text,text,integer) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.service_prepare_outgoing_chat_message(bigint,bigint,text,uuid) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.service_complete_outgoing_chat_message(bigint,bigint,text,text,jsonb,text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.service_ingest_evolution_message(bigint,text,text,text,boolean,text,text,text,text,timestamptz,jsonb,text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.service_update_evolution_message_status(bigint,text,text,text,jsonb,timestamptz) TO service_role;
GRANT EXECUTE ON FUNCTION public.service_upsert_evolution_chat(bigint,text,text,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.service_prepare_outgoing_chat_message(bigint,bigint,text,uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.service_complete_outgoing_chat_message(bigint,bigint,text,text,jsonb,text) TO service_role;

REVOKE ALL ON FUNCTION public.mark_conversation_read(bigint) FROM PUBLIC,anon;
REVOKE ALL ON FUNCTION public.set_conversation_archived(bigint,boolean) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.mark_conversation_read(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_conversation_archived(bigint,boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.chat_message_status_rank(text) TO authenticated,service_role;

INSERT INTO public.platform_schema_releases(
  release_key,application_version,migration_count,base_schema_sha256,notes
) VALUES(
  'stage-13-chat-20260802','5.0.0',13,
  '14824eb8aaeccfeab8fd1a480ef8e26662a723f10771e489ccef729a6ef407b4',
  'Plataforma estabilizada até a Etapa 12 e chat textual por chip na Etapa 13.'
) ON CONFLICT(release_key) DO UPDATE SET
  application_version=excluded.application_version,
  migration_count=excluded.migration_count,
  base_schema_sha256=excluded.base_schema_sha256,
  notes=excluded.notes,
  applied_at=now();

CREATE OR REPLACE FUNCTION public.platform_schema_health()
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE
  v_missing_tables text[]:=ARRAY[]::text[];
  v_missing_functions text[]:=ARRAY[]::text[];
  v_table text;
  v_function text;
BEGIN
  FOREACH v_table IN ARRAY ARRAY[
    'users','leads','queues','queue_items','sents','worker_batches','worker_batch_items',
    'queue_item_dispatch_parts','user_operational_settings','audit_events','lead_identity_registry',
    'contact_suppressions','permanent_records','instagram_queue_progress','instagram_dispatch_events',
    'worker_heartbeats','operational_alerts','recovery_requests','conversations','conversation_messages',
    'conversation_message_events','evolution_webhook_receipts'
  ] LOOP
    IF to_regclass('public.'||v_table) IS NULL THEN v_missing_tables:=array_append(v_missing_tables,v_table); END IF;
  END LOOP;
  FOREACH v_function IN ARRAY ARRAY[
    'ensure_current_user','prepare_queue_items','save_instance_secure','save_apify_account',
    'append_audit_event','check_lead_identity','refresh_permanent_record',
    'instagram_claim_queue_item','instagram_update_queue_progress','get_operational_health',
    'service_ingest_evolution_message','service_prepare_outgoing_chat_message','mark_conversation_read'
  ] LOOP
    IF NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname=v_function) THEN
      v_missing_functions:=array_append(v_missing_functions,v_function);
    END IF;
  END LOOP;
  RETURN jsonb_build_object(
    'ok',cardinality(v_missing_tables)=0 AND cardinality(v_missing_functions)=0,
    'missing_tables',to_jsonb(v_missing_tables),
    'missing_functions',to_jsonb(v_missing_functions),
    'checked_at',now()
  );
END; $$;
GRANT EXECUTE ON FUNCTION public.platform_schema_health() TO authenticated,service_role;

COMMIT;
