BEGIN;

-- ETAPA 11 — observabilidade tenant-aware, saúde, alertas e recuperação controlada.

DO $stage_preflight$
DECLARE v_missing text[]:=ARRAY[]::text[]; v_name text;
BEGIN
  FOREACH v_name IN ARRAY ARRAY['organization_tool_installations','worker_heartbeats'] LOOP IF to_regclass('public.'||v_name) IS NULL THEN v_missing:=array_append(v_missing,'table:'||v_name);END IF;END LOOP;
  FOREACH v_name IN ARRAY ARRAY['append_audit_event'] LOOP IF NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname=v_name) THEN v_missing:=array_append(v_missing,'function:'||v_name);END IF;END LOOP;
  IF cardinality(v_missing)>0 THEN RAISE EXCEPTION 'stage_preflight_failed:%',array_to_string(v_missing,',');END IF;
END
$stage_preflight$;

CREATE TABLE IF NOT EXISTS public.platform_runtime_heartbeats (
  platform_runtime_heartbeats_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizations_id bigint NOT NULL REFERENCES public.organizations(organizations_id) ON DELETE CASCADE,
  organization_tool_installations_id uuid REFERENCES public.organization_tool_installations(organization_tool_installations_id) ON DELETE SET NULL,
  component_type text NOT NULL CHECK(component_type IN ('worker','manager','gateway','evolution','capture','instagram','realtime')),
  component_key text NOT NULL,
  component_version text,
  runtime_status text NOT NULL DEFAULT 'online' CHECK(runtime_status IN ('online','degraded','stopping','offline','error','incompatible')),
  started_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  last_meaningful_activity_at timestamptz,
  metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE(organizations_id,component_type,component_key)
);
CREATE INDEX IF NOT EXISTS platform_runtime_heartbeats_seen_idx ON public.platform_runtime_heartbeats(organizations_id,last_seen_at DESC);
CREATE INDEX IF NOT EXISTS platform_runtime_heartbeats_component_idx ON public.platform_runtime_heartbeats(organizations_id,component_type,runtime_status,last_seen_at DESC);
ALTER TABLE public.platform_runtime_heartbeats ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS platform_runtime_heartbeats_org_select ON public.platform_runtime_heartbeats;
CREATE POLICY platform_runtime_heartbeats_org_select ON public.platform_runtime_heartbeats FOR SELECT TO authenticated
USING(organizations_id=public.current_organization_id() AND public.has_organization_permission('monitoring.view'));
REVOKE INSERT,UPDATE,DELETE ON public.platform_runtime_heartbeats FROM anon,authenticated;
GRANT SELECT ON public.platform_runtime_heartbeats TO authenticated;
GRANT ALL ON public.platform_runtime_heartbeats TO service_role;

-- Heartbeat legado do Worker passa a ser tenant-aware. Registros antigos sem tenant são efêmeros e podem ser descartados.
ALTER TABLE public.worker_heartbeats ADD COLUMN IF NOT EXISTS organizations_id bigint REFERENCES public.organizations(organizations_id) ON DELETE CASCADE;
DELETE FROM public.worker_heartbeats WHERE organizations_id IS NULL;
ALTER TABLE public.worker_heartbeats ALTER COLUMN organizations_id SET NOT NULL;
ALTER TABLE public.worker_heartbeats DROP CONSTRAINT IF EXISTS worker_heartbeats_worker_id_key;
CREATE UNIQUE INDEX IF NOT EXISTS worker_heartbeats_org_worker_uidx ON public.worker_heartbeats(organizations_id,worker_id);
ALTER TABLE public.worker_heartbeats ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS worker_heartbeats_authenticated_read ON public.worker_heartbeats;
DROP POLICY IF EXISTS worker_heartbeats_org_select ON public.worker_heartbeats;
CREATE POLICY worker_heartbeats_org_select ON public.worker_heartbeats FOR SELECT TO authenticated
USING(organizations_id=public.current_organization_id() AND public.has_organization_permission('monitoring.view'));
REVOKE INSERT,UPDATE,DELETE ON public.worker_heartbeats FROM anon,authenticated;
GRANT SELECT ON public.worker_heartbeats TO authenticated;
GRANT ALL ON public.worker_heartbeats TO service_role;

-- Tabelas antigas de alerta/recovery já recebem organizations_id na Etapa 2; reforça índices e RLS por tenant.
CREATE UNIQUE INDEX IF NOT EXISTS operational_alerts_org_key_uidx ON public.operational_alerts(organizations_id,alert_key);
CREATE INDEX IF NOT EXISTS operational_alerts_org_open_idx ON public.operational_alerts(organizations_id,severity,last_detected_at DESC) WHERE status<>'resolved';
CREATE INDEX IF NOT EXISTS recovery_requests_org_pending_idx ON public.recovery_requests(organizations_id,status,requested_at) WHERE status IN ('pending','running');
ALTER TABLE public.operational_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recovery_requests ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS operational_alerts_own_select ON public.operational_alerts;
DROP POLICY IF EXISTS operational_alerts_org_select ON public.operational_alerts;
CREATE POLICY operational_alerts_org_select ON public.operational_alerts FOR SELECT TO authenticated
USING(organizations_id=public.current_organization_id() AND public.has_organization_permission('monitoring.view'));
DROP POLICY IF EXISTS recovery_requests_own_select ON public.recovery_requests;
DROP POLICY IF EXISTS recovery_requests_org_select ON public.recovery_requests;
CREATE POLICY recovery_requests_org_select ON public.recovery_requests FOR SELECT TO authenticated
USING(organizations_id=public.current_organization_id() AND public.has_organization_permission('monitoring.view'));

-- Registro canônico de qualquer componente. O servidor fixa a organização a partir da credencial da instalação.
CREATE OR REPLACE FUNCTION public.service_runtime_heartbeat(
  p_organizations_id bigint,
  p_component_type text,
  p_component_key text,
  p_component_version text DEFAULT NULL,
  p_status text DEFAULT 'online',
  p_installation_id uuid DEFAULT NULL,
  p_metrics jsonb DEFAULT '{}'::jsonb,
  p_metadata jsonb DEFAULT '{}'::jsonb,
  p_meaningful_activity boolean DEFAULT false
) RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE v_id bigint; v_type text:=lower(trim(coalesce(p_component_type,''))); v_status text:=lower(trim(coalesce(p_status,'online')));
BEGIN
  IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role_required'; END IF;
  IF NOT EXISTS(SELECT 1 FROM public.organizations WHERE organizations_id=p_organizations_id AND status_id=1) THEN RAISE EXCEPTION 'organization_not_active'; END IF;
  IF v_type NOT IN ('worker','manager','gateway','evolution','capture','instagram','realtime') THEN RAISE EXCEPTION 'runtime_component_invalid'; END IF;
  IF v_status NOT IN ('online','degraded','stopping','offline','error','incompatible') THEN RAISE EXCEPTION 'runtime_status_invalid'; END IF;
  IF nullif(trim(coalesce(p_component_key,'')),'') IS NULL THEN RAISE EXCEPTION 'runtime_component_key_required'; END IF;
  IF p_installation_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.organization_tool_installations i WHERE i.organization_tool_installations_id=p_installation_id AND i.organizations_id=p_organizations_id AND i.registration_status='registered') THEN RAISE EXCEPTION 'runtime_installation_scope_mismatch'; END IF;
  INSERT INTO public.platform_runtime_heartbeats(organizations_id,organization_tool_installations_id,component_type,component_key,component_version,runtime_status,last_meaningful_activity_at,metrics,metadata)
  VALUES(p_organizations_id,p_installation_id,v_type,trim(p_component_key),nullif(trim(coalesce(p_component_version,'')),''),v_status,CASE WHEN p_meaningful_activity THEN now() ELSE NULL END,coalesce(p_metrics,'{}'::jsonb),coalesce(p_metadata,'{}'::jsonb))
  ON CONFLICT(organizations_id,component_type,component_key) DO UPDATE SET
    organization_tool_installations_id=coalesce(excluded.organization_tool_installations_id,public.platform_runtime_heartbeats.organization_tool_installations_id),
    component_version=coalesce(excluded.component_version,public.platform_runtime_heartbeats.component_version),
    runtime_status=excluded.runtime_status,last_seen_at=now(),
    last_meaningful_activity_at=CASE WHEN p_meaningful_activity THEN now() ELSE public.platform_runtime_heartbeats.last_meaningful_activity_at END,
    metrics=excluded.metrics,metadata=public.platform_runtime_heartbeats.metadata||excluded.metadata
  RETURNING platform_runtime_heartbeats_id INTO v_id;
  RETURN v_id;
END; $$;
REVOKE ALL ON FUNCTION public.service_runtime_heartbeat(bigint,text,text,text,text,uuid,jsonb,jsonb,boolean) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.service_runtime_heartbeat(bigint,text,text,text,text,uuid,jsonb,jsonb,boolean) TO service_role;

-- Substitui o heartbeat legado do Worker por uma assinatura com tenant explícito.
DROP FUNCTION IF EXISTS public.service_worker_heartbeat(text,text,text,jsonb,jsonb);
CREATE OR REPLACE FUNCTION public.service_worker_heartbeat(
  p_organizations_id bigint,p_worker_id text,p_worker_version text,p_status text DEFAULT 'online',p_metrics jsonb DEFAULT '{}'::jsonb,p_metadata jsonb DEFAULT '{}'::jsonb
) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
BEGIN
  IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role_required'; END IF;
  INSERT INTO public.worker_heartbeats(organizations_id,worker_id,worker_version,worker_status,metrics,metadata)
  VALUES(p_organizations_id,trim(p_worker_id),trim(p_worker_version),p_status,coalesce(p_metrics,'{}'::jsonb),coalesce(p_metadata,'{}'::jsonb))
  ON CONFLICT(organizations_id,worker_id) DO UPDATE SET worker_version=excluded.worker_version,worker_status=excluded.worker_status,last_seen_at=now(),metrics=excluded.metrics,metadata=excluded.metadata;
  PERFORM public.service_runtime_heartbeat(p_organizations_id,'worker',trim(p_worker_id),p_worker_version,p_status,NULL,p_metrics,p_metadata,false);
END; $$;
REVOKE ALL ON FUNCTION public.service_worker_heartbeat(bigint,text,text,text,jsonb,jsonb) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.service_worker_heartbeat(bigint,text,text,text,jsonb,jsonb) TO service_role;

-- Recovery por organização. Nenhum Worker pode reclamar pedido de outro tenant.
CREATE OR REPLACE FUNCTION public.request_operational_recovery(p_scope text DEFAULT 'all')
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE v_org bigint:=public.current_organization_id(); v_user bigint:=public.ensure_current_user(); v_id bigint; v_scope text:=lower(trim(coalesce(p_scope,'all')));
BEGIN
  PERFORM public.require_organization_permission('monitoring.manage');
  IF v_scope NOT IN('all','whatsapp','instagram','capture','realtime','tools') THEN RAISE EXCEPTION 'recovery_scope_invalid'; END IF;
  SELECT recovery_requests_id INTO v_id FROM public.recovery_requests WHERE organizations_id=v_org AND status IN('pending','running') ORDER BY requested_at DESC LIMIT 1;
  IF v_id IS NOT NULL THEN RETURN v_id; END IF;
  INSERT INTO public.recovery_requests(users_id,organizations_id,requested_by,scope) VALUES(v_user,v_org,auth.uid(),v_scope) RETURNING recovery_requests_id INTO v_id;
  PERFORM public.append_audit_event('monitoring','recovery_requested','recovery_request',v_id::text,NULL,NULL,NULL,NULL,NULL,NULL,jsonb_build_object('scope',v_scope,'organization_id',v_org),v_user);
  RETURN v_id;
END; $$;
GRANT EXECUTE ON FUNCTION public.request_operational_recovery(text) TO authenticated;

DROP FUNCTION IF EXISTS public.service_claim_recovery_request(text);
CREATE OR REPLACE FUNCTION public.service_claim_recovery_request(p_organizations_id bigint,p_worker_id text)
RETURNS TABLE(recovery_requests_id bigint,organizations_id bigint,users_id bigint,scope text)
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE v_id bigint;
BEGIN
  IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role_required'; END IF;
  SELECT r.recovery_requests_id INTO v_id FROM public.recovery_requests r WHERE r.organizations_id=p_organizations_id AND r.status='pending' ORDER BY r.requested_at FOR UPDATE SKIP LOCKED LIMIT 1;
  IF v_id IS NULL THEN RETURN; END IF;
  UPDATE public.recovery_requests SET status='running',worker_id=p_worker_id,started_at=now() WHERE public.recovery_requests.recovery_requests_id=v_id;
  RETURN QUERY SELECT r.recovery_requests_id,r.organizations_id,r.users_id,r.scope FROM public.recovery_requests r WHERE r.recovery_requests_id=v_id;
END; $$;
REVOKE ALL ON FUNCTION public.service_claim_recovery_request(bigint,text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.service_claim_recovery_request(bigint,text) TO service_role;

DROP FUNCTION IF EXISTS public.service_complete_recovery_request(bigint,jsonb,text);
CREATE OR REPLACE FUNCTION public.service_complete_recovery_request(p_organizations_id bigint,p_request_id bigint,p_result jsonb,p_error text DEFAULT NULL)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
BEGIN
  IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role_required'; END IF;
  UPDATE public.recovery_requests SET status=CASE WHEN p_error IS NULL THEN 'completed' ELSE 'failed' END,result=coalesce(p_result,'{}'::jsonb),error_message=p_error,finished_at=now()
  WHERE recovery_requests_id=p_request_id AND organizations_id=p_organizations_id AND status='running';
END; $$;
REVOKE ALL ON FUNCTION public.service_complete_recovery_request(bigint,bigint,jsonb,text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.service_complete_recovery_request(bigint,bigint,jsonb,text) TO service_role;

-- Alertas derivados da verdade operacional. Idempotente: abre/atualiza e resolve quando a condição some.
-- Contrato legado possuía o mesmo tipo bigint com nome de parâmetro p_users_id.
-- PostgreSQL não permite alterar nome de parâmetro via CREATE OR REPLACE;
-- removemos a função antiga e recriamos o contrato tenant-aware explicitamente.
DROP FUNCTION IF EXISTS public.refresh_operational_alerts(bigint);
CREATE OR REPLACE FUNCTION public.refresh_operational_alerts(p_organizations_id bigint)
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE v_user bigint; v_count integer:=0; v_value bigint; v_now timestamptz:=now();
BEGIN
  IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role_required'; END IF;
  SELECT legacy_scope_users_id INTO v_user FROM public.organizations WHERE organizations_id=p_organizations_id;
  IF v_user IS NULL THEN RAISE EXCEPTION 'organization_not_found'; END IF;

  SELECT count(*) INTO v_value FROM public.queue_items WHERE organizations_id=p_organizations_id AND status_id=4 AND queue_items_updated_at<v_now-interval '15 minutes';
  IF v_value>0 THEN
    INSERT INTO public.operational_alerts(users_id,organizations_id,alert_key,source,severity,title,message,metadata)
    VALUES(v_user,p_organizations_id,'stale_queue_items','queues','critical','Itens travados em processamento',v_value||' item(ns) estão processando há mais de 15 minutos.',jsonb_build_object('count',v_value))
    ON CONFLICT(organizations_id,alert_key) DO UPDATE SET status='open',last_detected_at=v_now,message=excluded.message,metadata=excluded.metadata,resolved_at=NULL;
    v_count:=v_count+1;
  ELSE UPDATE public.operational_alerts SET status='resolved',resolved_at=v_now WHERE organizations_id=p_organizations_id AND alert_key='stale_queue_items' AND status<>'resolved'; END IF;

  SELECT count(*) INTO v_value FROM public.queue_item_dispatch_parts WHERE organizations_id=p_organizations_id AND queue_item_dispatch_parts_state='reconciliation_required';
  IF v_value>0 THEN
    INSERT INTO public.operational_alerts(users_id,organizations_id,alert_key,source,severity,title,message,metadata)
    VALUES(v_user,p_organizations_id,'whatsapp_reconciliation','worker','warning','WhatsApp requer reconciliação',v_value||' parte(s) possuem resultado incerto.',jsonb_build_object('count',v_value))
    ON CONFLICT(organizations_id,alert_key) DO UPDATE SET status='open',last_detected_at=v_now,message=excluded.message,metadata=excluded.metadata,resolved_at=NULL;
    v_count:=v_count+1;
  ELSE UPDATE public.operational_alerts SET status='resolved',resolved_at=v_now WHERE organizations_id=p_organizations_id AND alert_key='whatsapp_reconciliation' AND status<>'resolved'; END IF;

  SELECT count(*) INTO v_value FROM public.instagram_queue_progress WHERE organizations_id=p_organizations_id AND canonical_step='reconciliation_required';
  IF v_value>0 THEN
    INSERT INTO public.operational_alerts(users_id,organizations_id,alert_key,source,severity,title,message,metadata)
    VALUES(v_user,p_organizations_id,'instagram_reconciliation','instagram','warning','Instagram requer reconciliação',v_value||' item(ns) possuem resultado incerto.',jsonb_build_object('count',v_value))
    ON CONFLICT(organizations_id,alert_key) DO UPDATE SET status='open',last_detected_at=v_now,message=excluded.message,metadata=excluded.metadata,resolved_at=NULL;
    v_count:=v_count+1;
  ELSE UPDATE public.operational_alerts SET status='resolved',resolved_at=v_now WHERE organizations_id=p_organizations_id AND alert_key='instagram_reconciliation' AND status<>'resolved'; END IF;

  -- Worker é obrigatório quando o WhatsApp Manager está habilitado.
  IF EXISTS(SELECT 1 FROM public.organization_tools WHERE organizations_id=p_organizations_id AND tool_id='vinsansi_whatsapp_manager' AND enabled) THEN
    SELECT count(*) INTO v_value FROM public.platform_runtime_heartbeats WHERE organizations_id=p_organizations_id AND component_type='worker' AND last_seen_at>v_now-interval '2 minutes' AND runtime_status IN('online','degraded');
    IF v_value=0 THEN
      INSERT INTO public.operational_alerts(users_id,organizations_id,alert_key,source,severity,title,message,metadata)
      VALUES(v_user,p_organizations_id,'worker_heartbeat_missing','worker','critical','Worker sem heartbeat','Nenhum Worker da organização comunicou nos últimos 2 minutos.','{}'::jsonb)
      ON CONFLICT(organizations_id,alert_key) DO UPDATE SET status='open',last_detected_at=v_now,message=excluded.message,resolved_at=NULL;
      v_count:=v_count+1;
    ELSE UPDATE public.operational_alerts SET status='resolved',resolved_at=v_now WHERE organizations_id=p_organizations_id AND alert_key='worker_heartbeat_missing' AND status<>'resolved'; END IF;
  END IF;

  -- Instalações registradas das ferramentas locais devem reportar presença.
  SELECT count(*) INTO v_value FROM public.organization_tool_installations i
  WHERE i.organizations_id=p_organizations_id AND i.registration_status='registered' AND i.tool_id IN('vinsansi_capture','vinsansi_instagram')
    AND (i.last_seen_at IS NULL OR i.last_seen_at<v_now-interval '3 minutes');
  IF v_value>0 THEN
    INSERT INTO public.operational_alerts(users_id,organizations_id,alert_key,source,severity,title,message,metadata)
    VALUES(v_user,p_organizations_id,'tool_installation_stale','tools','warning','Ferramenta local sem comunicação',v_value||' instalação(ões) não comunicaram nos últimos 3 minutos.',jsonb_build_object('count',v_value))
    ON CONFLICT(organizations_id,alert_key) DO UPDATE SET status='open',last_detected_at=v_now,message=excluded.message,metadata=excluded.metadata,resolved_at=NULL;
    v_count:=v_count+1;
  ELSE UPDATE public.operational_alerts SET status='resolved',resolved_at=v_now WHERE organizations_id=p_organizations_id AND alert_key='tool_installation_stale' AND status<>'resolved'; END IF;

  RETURN v_count;
END; $$;
REVOKE ALL ON FUNCTION public.refresh_operational_alerts(bigint) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.refresh_operational_alerts(bigint) TO service_role;


-- Recuperação stale com escopo por organização; nunca toca execução de outro tenant.
CREATE OR REPLACE FUNCTION public.worker_recover_stale_whatsapp_v2(p_organizations_id bigint,p_stale_before timestamptz DEFAULT now()-interval '15 minutes')
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE r record;v_recovered integer:=0;v_reconciliation integer:=0;
BEGIN
 IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role_required';END IF;
 FOR r IN SELECT qi.queue_items_id FROM public.queue_items qi WHERE qi.organizations_id=p_organizations_id AND qi.status_id=4 AND coalesce(qi.queue_items_started_at,qi.queue_items_updated_at)<p_stale_before FOR UPDATE OF qi SKIP LOCKED LOOP
   IF EXISTS(SELECT 1 FROM public.queue_item_dispatch_parts p WHERE p.organizations_id=p_organizations_id AND p.queue_items_id=r.queue_items_id AND p.queue_item_dispatch_parts_state='processing') THEN
     UPDATE public.queue_item_dispatch_parts SET queue_item_dispatch_parts_state='reconciliation_required',queue_item_dispatch_parts_claim_token=NULL,queue_item_dispatch_parts_error_message='worker_restart_after_provider_claim',queue_item_dispatch_parts_updated_at=now() WHERE organizations_id=p_organizations_id AND queue_items_id=r.queue_items_id AND queue_item_dispatch_parts_state='processing';
     UPDATE public.queue_items SET status_id=6,queue_items_error_message='reconciliation_required_after_worker_restart',queue_items_finished_at=now(),queue_items_updated_at=now() WHERE organizations_id=p_organizations_id AND queue_items_id=r.queue_items_id;
     UPDATE public.worker_batch_items SET status_id=6,worker_batch_items_error_message='reconciliation_required_after_worker_restart',worker_batch_items_finished_at=now(),worker_batch_items_updated_at=now() WHERE organizations_id=p_organizations_id AND queue_items_id=r.queue_items_id AND status_id=4;
     v_reconciliation:=v_reconciliation+1;
   ELSE
     UPDATE public.queue_items SET status_id=3,queue_items_error_message=NULL,queue_items_started_at=NULL,queue_items_finished_at=NULL,queue_items_updated_at=now() WHERE organizations_id=p_organizations_id AND queue_items_id=r.queue_items_id;
     UPDATE public.worker_batch_items SET status_id=3,worker_batch_items_started_at=NULL,worker_batch_items_finished_at=NULL,worker_batch_items_error_message=NULL,worker_batch_items_updated_at=now() WHERE organizations_id=p_organizations_id AND queue_items_id=r.queue_items_id AND status_id=4;
     v_recovered:=v_recovered+1;
   END IF;
 END LOOP;
 UPDATE public.worker_batches SET worker_batches_next_run_at=now(),worker_batches_heartbeat_at=now(),worker_batches_updated_at=now() WHERE organizations_id=p_organizations_id AND worker_batches_status='running' AND worker_batches_heartbeat_at<p_stale_before;
 RETURN jsonb_build_object('recovered_items',v_recovered,'reconciliation_items',v_reconciliation);
END; $$;
REVOKE ALL ON FUNCTION public.worker_recover_stale_whatsapp_v2(bigint,timestamptz) FROM PUBLIC,anon,authenticated;GRANT EXECUTE ON FUNCTION public.worker_recover_stale_whatsapp_v2(bigint,timestamptz) TO service_role;

CREATE OR REPLACE FUNCTION public.instagram_recover_stale_items_v2(p_organizations_id bigint,p_stale_before timestamptz DEFAULT now()-interval '15 minutes')
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE r record;v_requeued integer:=0;v_reconciliation integer:=0;v_next text;
BEGIN
 IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role_required';END IF;
 FOR r IN SELECT p.instagram_queue_progress_id,p.queue_items_id,p.socials_id,p.canonical_step,p.claim_token FROM public.instagram_queue_progress p WHERE p.organizations_id=p_organizations_id AND p.canonical_step IN('claimed','opening_profile','following','followed','opening_dm','sending') AND coalesce(p.last_heartbeat_at,p.instagram_queue_progress_updated_at)<p_stale_before FOR UPDATE OF p SKIP LOCKED LOOP
   IF r.canonical_step='sending' THEN
     v_next:='reconciliation_required';v_reconciliation:=v_reconciliation+1;
     UPDATE public.instagram_queue_progress SET canonical_step=v_next,step=v_next,error_message='stale_after_possible_dispatch',finished_at=now(),instagram_queue_progress_updated_at=now() WHERE instagram_queue_progress_id=r.instagram_queue_progress_id;
     UPDATE public.queue_items SET status_id=6,queue_items_error_message='instagram_reconciliation_required',queue_items_finished_at=now(),queue_items_updated_at=now() WHERE organizations_id=p_organizations_id AND queue_items_id=r.queue_items_id;
   ELSE
     v_next:='queued';v_requeued:=v_requeued+1;
     UPDATE public.instagram_queue_progress SET canonical_step='queued',step='queued',claim_token=NULL,claimed_by=NULL,error_message='recovered_stale_claim',instagram_queue_progress_updated_at=now() WHERE instagram_queue_progress_id=r.instagram_queue_progress_id;
     UPDATE public.queue_items SET status_id=3,queue_items_started_at=NULL,queue_items_error_message=NULL,queue_items_finished_at=NULL,queue_items_updated_at=now() WHERE organizations_id=p_organizations_id AND queue_items_id=r.queue_items_id;
   END IF;
   INSERT INTO public.instagram_dispatch_events(users_id,organizations_id,queue_items_id,socials_id,from_step,to_step,actor,message) SELECT qi.users_id,p_organizations_id,r.queue_items_id,r.socials_id,r.canonical_step,v_next,'recovery','stale_execution_recovered' FROM public.queue_items qi WHERE qi.queue_items_id=r.queue_items_id;
 END LOOP;
 RETURN jsonb_build_object('requeued',v_requeued,'reconciliation',v_reconciliation);
END; $$;
REVOKE ALL ON FUNCTION public.instagram_recover_stale_items_v2(bigint,timestamptz) FROM PUBLIC,anon,authenticated;GRANT EXECUTE ON FUNCTION public.instagram_recover_stale_items_v2(bigint,timestamptz) TO service_role;

-- Saúde operacional completa e tenant-aware.
CREATE OR REPLACE FUNCTION public.get_operational_health()
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path TO pg_catalog,public AS $$
DECLARE v_org bigint:=public.current_organization_id(); v_result jsonb;
BEGIN
  PERFORM public.require_organization_permission('monitoring.view');
  SELECT jsonb_build_object(
    'checkedAt',now(),
    'organizationId',v_org,
    'workers',jsonb_build_object(
      'online',(SELECT count(*) FROM public.platform_runtime_heartbeats WHERE organizations_id=v_org AND component_type='worker' AND last_seen_at>now()-interval '2 minutes' AND runtime_status='online'),
      'stale',(SELECT count(*) FROM public.platform_runtime_heartbeats WHERE organizations_id=v_org AND component_type='worker' AND last_seen_at<=now()-interval '2 minutes')
    ),
    'components',coalesce((SELECT jsonb_agg(jsonb_build_object('type',component_type,'key',component_key,'version',component_version,'status',CASE WHEN last_seen_at<=now()-interval '3 minutes' THEN 'offline' ELSE runtime_status END,'lastSeenAt',last_seen_at,'lastActivityAt',last_meaningful_activity_at,'metrics',metrics,'metadata',metadata) ORDER BY component_type,component_key) FROM public.platform_runtime_heartbeats WHERE organizations_id=v_org),'[]'::jsonb),
    'queues',jsonb_build_object(
      'pending',(SELECT count(*) FROM public.queue_items WHERE organizations_id=v_org AND status_id=3),
      'processing',(SELECT count(*) FROM public.queue_items WHERE organizations_id=v_org AND status_id=4),
      'staleProcessing',(SELECT count(*) FROM public.queue_items WHERE organizations_id=v_org AND status_id=4 AND queue_items_updated_at<now()-interval '15 minutes'),
      'errors',(SELECT count(*) FROM public.queue_items WHERE organizations_id=v_org AND status_id=6)
    ),
    'reconciliation',jsonb_build_object(
      'whatsapp',(SELECT count(*) FROM public.queue_item_dispatch_parts WHERE organizations_id=v_org AND queue_item_dispatch_parts_state='reconciliation_required'),
      'instagram',(SELECT count(*) FROM public.instagram_queue_progress WHERE organizations_id=v_org AND canonical_step='reconciliation_required')
    ),
    'batches',jsonb_build_object(
      'active',(SELECT count(*) FROM public.worker_batches WHERE organizations_id=v_org AND worker_batches_status IN('queued','running','paused')),
      'stale',(SELECT count(*) FROM public.worker_batches WHERE organizations_id=v_org AND worker_batches_status='running' AND worker_batches_heartbeat_at<now()-interval '15 minutes')
    ),
    'tools',jsonb_build_object(
      'registered',(SELECT count(*) FROM public.organization_tool_installations WHERE organizations_id=v_org AND registration_status='registered'),
      'stale',(SELECT count(*) FROM public.organization_tool_installations WHERE organizations_id=v_org AND registration_status='registered' AND (last_seen_at IS NULL OR last_seen_at<now()-interval '3 minutes'))
    ),
    'alerts',jsonb_build_object(
      'open',(SELECT count(*) FROM public.operational_alerts WHERE organizations_id=v_org AND status<>'resolved'),
      'critical',(SELECT count(*) FROM public.operational_alerts WHERE organizations_id=v_org AND status<>'resolved' AND severity='critical')
    ),
    'latestRecovery',(SELECT to_jsonb(r) FROM public.recovery_requests r WHERE r.organizations_id=v_org ORDER BY r.requested_at DESC LIMIT 1)
  ) INTO v_result;
  RETURN v_result;
END; $$;
GRANT EXECUTE ON FUNCTION public.get_operational_health() TO authenticated;

COMMIT;
