BEGIN;

-- ETAPA 10: manifesto verificável do schema e diagnóstico de baseline.
CREATE TABLE IF NOT EXISTS public.platform_schema_releases (
  platform_schema_releases_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  release_key text NOT NULL UNIQUE,
  application_version text NOT NULL,
  migration_count integer NOT NULL CHECK(migration_count>0),
  base_schema_sha256 text NOT NULL CHECK(length(base_schema_sha256)=64),
  notes text,
  applied_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.platform_schema_releases ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS platform_schema_releases_read ON public.platform_schema_releases;
CREATE POLICY platform_schema_releases_read ON public.platform_schema_releases
FOR SELECT TO authenticated USING(true);
REVOKE INSERT,UPDATE,DELETE ON public.platform_schema_releases FROM anon,authenticated;
GRANT SELECT ON public.platform_schema_releases TO authenticated;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.platform_schema_releases TO service_role;

INSERT INTO public.platform_schema_releases(
  release_key,application_version,migration_count,base_schema_sha256,notes
) VALUES(
  'stage-10-baseline-20260802','4.4.0',11,
  '14824eb8aaeccfeab8fd1a480ef8e26662a723f10771e489ccef729a6ef407b4',
  'Baseline pública + migrations cumulativas até a Etapa 10.'
) ON CONFLICT(release_key) DO UPDATE SET
  application_version=excluded.application_version,
  migration_count=excluded.migration_count,
  base_schema_sha256=excluded.base_schema_sha256,
  notes=excluded.notes,
  applied_at=now();

CREATE OR REPLACE FUNCTION public.platform_schema_health()
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE
  v_missing_tables text[]:=ARRAY[]::text[];
  v_missing_functions text[]:=ARRAY[]::text[];
  v_table text;
  v_function text;
BEGIN
  FOREACH v_table IN ARRAY ARRAY[
    'users','leads','queues','queue_items','sents','worker_batches','worker_batch_items',
    'queue_item_dispatch_parts','user_operational_settings','audit_events','lead_identity_registry',
    'contact_suppressions','permanent_records','instagram_queue_progress','instagram_dispatch_events'
  ] LOOP
    IF to_regclass('public.'||v_table) IS NULL THEN v_missing_tables:=array_append(v_missing_tables,v_table); END IF;
  END LOOP;
  FOREACH v_function IN ARRAY ARRAY[
    'ensure_current_user','prepare_queue_items','save_instance_secure','save_apify_account',
    'append_audit_event','check_lead_identity','refresh_permanent_record',
    'instagram_claim_queue_item','instagram_update_queue_progress'
  ] LOOP
    IF NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname=v_function) THEN
      v_missing_functions:=array_append(v_missing_functions,v_function);
    END IF;
  END LOOP;
  RETURN jsonb_build_object(
    'ok',cardinality(v_missing_tables)=0 AND cardinality(v_missing_functions)=0,
    'missing_tables',to_jsonb(v_missing_tables),
    'missing_functions',to_jsonb(v_missing_functions),
    'checked_at',now()
  );
END; $$;
GRANT EXECUTE ON FUNCTION public.platform_schema_health() TO authenticated,service_role;

COMMIT;
