BEGIN;

-- Credencial mínima para executar o Tunnel local do desktop.
-- O conteúdo sensível (<TUNNEL-UUID>.json) fica no Supabase Vault; a tabela
-- pública guarda somente metadados e o UUID do secret.
CREATE TABLE IF NOT EXISTS public.desktop_tunnel_credentials (
  desktop_tunnel_credentials_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id bigint NOT NULL UNIQUE REFERENCES public.users(users_id) ON DELETE CASCADE,
  tunnel_id uuid NOT NULL,
  tunnel_name text NOT NULL,
  evolution_public_url text NOT NULL,
  evolution_service_url text NOT NULL,
  worker_public_url text NOT NULL,
  worker_service_url text NOT NULL,
  vault_secret_id uuid NOT NULL,
  desktop_tunnel_credentials_created_at timestamptz NOT NULL DEFAULT now(),
  desktop_tunnel_credentials_updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.desktop_tunnel_credentials ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.desktop_tunnel_credentials FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.desktop_tunnel_credentials TO service_role;

CREATE OR REPLACE FUNCTION public.service_save_desktop_tunnel_credential(
  p_users_id bigint,
  p_tunnel_id uuid,
  p_tunnel_name text,
  p_credentials_json text,
  p_evolution_public_url text,
  p_evolution_service_url text,
  p_worker_public_url text,
  p_worker_service_url text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO pg_catalog, public, vault
AS $$
DECLARE
  v_payload jsonb;
  v_secret_id uuid;
  v_tunnel_name text := trim(coalesce(p_tunnel_name, ''));
  v_evolution_public_url text := rtrim(trim(coalesce(p_evolution_public_url, '')), '/');
  v_evolution_service_url text := rtrim(trim(coalesce(p_evolution_service_url, '')), '/');
  v_worker_public_url text := rtrim(trim(coalesce(p_worker_public_url, '')), '/');
  v_worker_service_url text := rtrim(trim(coalesce(p_worker_service_url, '')), '/');
BEGIN
  IF p_users_id IS NULL OR NOT EXISTS (SELECT 1 FROM public.users u WHERE u.users_id = p_users_id) THEN
    RAISE EXCEPTION 'desktop_tunnel_user_not_found';
  END IF;
  IF p_tunnel_id IS NULL OR v_tunnel_name = '' THEN
    RAISE EXCEPTION 'desktop_tunnel_metadata_invalid';
  END IF;
  IF char_length(coalesce(p_credentials_json, '')) < 40 OR char_length(p_credentials_json) > 16384 THEN
    RAISE EXCEPTION 'desktop_tunnel_credentials_invalid';
  END IF;
  BEGIN
    v_payload := p_credentials_json::jsonb;
  EXCEPTION WHEN others THEN
    RAISE EXCEPTION 'desktop_tunnel_credentials_invalid';
  END;
  IF nullif(trim(coalesce(v_payload->>'AccountTag', '')), '') IS NULL
     OR nullif(trim(coalesce(v_payload->>'TunnelSecret', '')), '') IS NULL
     OR lower(trim(coalesce(v_payload->>'TunnelID', ''))) <> lower(p_tunnel_id::text) THEN
    RAISE EXCEPTION 'desktop_tunnel_credentials_invalid';
  END IF;
  IF v_evolution_public_url !~* '^https://[^[:space:]]+$'
     OR v_worker_public_url !~* '^https://[^[:space:]]+$'
     OR v_evolution_service_url !~* '^https?://(localhost|127[.]0[.]0[.]1)(:[0-9]{1,5})?(/.*)?$'
     OR v_worker_service_url !~* '^https?://(localhost|127[.]0[.]0[.]1)(:[0-9]{1,5})?(/.*)?$' THEN
    RAISE EXCEPTION 'desktop_tunnel_routes_invalid';
  END IF;

  SELECT c.vault_secret_id
  INTO v_secret_id
  FROM public.desktop_tunnel_credentials c
  WHERE c.users_id = p_users_id
  FOR UPDATE;

  IF v_secret_id IS NULL THEN
    v_secret_id := vault.create_secret(
      p_credentials_json,
      NULL,
      format('Vinsansi Desktop - Cloudflare Tunnel %s (%s)', p_tunnel_id, v_tunnel_name)
    );
  ELSE
    PERFORM vault.update_secret(
      v_secret_id,
      p_credentials_json,
      NULL,
      format('Vinsansi Desktop - Cloudflare Tunnel %s (%s)', p_tunnel_id, v_tunnel_name)
    );
  END IF;

  INSERT INTO public.desktop_tunnel_credentials(
    users_id, tunnel_id, tunnel_name,
    evolution_public_url, evolution_service_url,
    worker_public_url, worker_service_url,
    vault_secret_id,
    desktop_tunnel_credentials_created_at,
    desktop_tunnel_credentials_updated_at
  ) VALUES (
    p_users_id, p_tunnel_id, v_tunnel_name,
    v_evolution_public_url, v_evolution_service_url,
    v_worker_public_url, v_worker_service_url,
    v_secret_id, now(), now()
  )
  ON CONFLICT (users_id) DO UPDATE SET
    tunnel_id = EXCLUDED.tunnel_id,
    tunnel_name = EXCLUDED.tunnel_name,
    evolution_public_url = EXCLUDED.evolution_public_url,
    evolution_service_url = EXCLUDED.evolution_service_url,
    worker_public_url = EXCLUDED.worker_public_url,
    worker_service_url = EXCLUDED.worker_service_url,
    vault_secret_id = EXCLUDED.vault_secret_id,
    desktop_tunnel_credentials_updated_at = now();
END;
$$;

CREATE OR REPLACE FUNCTION public.service_get_desktop_tunnel_credential(p_users_id bigint)
RETURNS TABLE(
  users_id bigint,
  tunnel_id uuid,
  tunnel_name text,
  evolution_public_url text,
  evolution_service_url text,
  worker_public_url text,
  worker_service_url text,
  credentials_json text
)
LANGUAGE sql
SECURITY DEFINER
SET search_path TO pg_catalog, public, vault
AS $$
  SELECT
    c.users_id,
    c.tunnel_id,
    c.tunnel_name,
    c.evolution_public_url,
    c.evolution_service_url,
    c.worker_public_url,
    c.worker_service_url,
    d.decrypted_secret AS credentials_json
  FROM public.desktop_tunnel_credentials c
  JOIN vault.decrypted_secrets d ON d.id = c.vault_secret_id
  WHERE c.users_id = p_users_id
  LIMIT 1;
$$;

REVOKE ALL ON FUNCTION public.service_save_desktop_tunnel_credential(bigint, uuid, text, text, text, text, text, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.service_get_desktop_tunnel_credential(bigint) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.service_save_desktop_tunnel_credential(bigint, uuid, text, text, text, text, text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.service_get_desktop_tunnel_credential(bigint) TO service_role;

COMMIT;
