BEGIN;

-- ETAPA 11: observabilidade, heartbeats, alertas e recuperação controlada.
CREATE TABLE IF NOT EXISTS public.worker_heartbeats (
  worker_heartbeats_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worker_id text NOT NULL UNIQUE,
  worker_version text NOT NULL,
  worker_status text NOT NULL DEFAULT 'online' CHECK(worker_status IN('online','degraded','stopping','offline')),
  started_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS public.operational_alerts (
  operational_alerts_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id bigint NOT NULL REFERENCES public.users(users_id) ON DELETE CASCADE,
  alert_key text NOT NULL,
  source text NOT NULL,
  severity text NOT NULL CHECK(severity IN('info','warning','critical')),
  status text NOT NULL DEFAULT 'open' CHECK(status IN('open','acknowledged','resolved')),
  title text NOT NULL,
  message text NOT NULL,
  entity_type text,
  entity_id text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  first_detected_at timestamptz NOT NULL DEFAULT now(),
  last_detected_at timestamptz NOT NULL DEFAULT now(),
  acknowledged_at timestamptz,
  resolved_at timestamptz,
  UNIQUE(users_id,alert_key)
);

CREATE TABLE IF NOT EXISTS public.recovery_requests (
  recovery_requests_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id bigint NOT NULL REFERENCES public.users(users_id) ON DELETE CASCADE,
  requested_by uuid,
  scope text NOT NULL DEFAULT 'all' CHECK(scope IN('all','whatsapp','instagram')),
  status text NOT NULL DEFAULT 'pending' CHECK(status IN('pending','running','completed','failed')),
  worker_id text,
  result jsonb NOT NULL DEFAULT '{}'::jsonb,
  error_message text,
  requested_at timestamptz NOT NULL DEFAULT now(),
  started_at timestamptz,
  finished_at timestamptz
);

CREATE INDEX IF NOT EXISTS worker_heartbeats_seen_idx ON public.worker_heartbeats(last_seen_at DESC);
CREATE INDEX IF NOT EXISTS operational_alerts_open_idx ON public.operational_alerts(users_id,severity,last_detected_at DESC) WHERE status<>'resolved';
CREATE INDEX IF NOT EXISTS recovery_requests_pending_idx ON public.recovery_requests(status,requested_at) WHERE status='pending';

ALTER TABLE public.worker_heartbeats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.operational_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recovery_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY worker_heartbeats_authenticated_read ON public.worker_heartbeats FOR SELECT TO authenticated USING(true);
CREATE POLICY operational_alerts_own_select ON public.operational_alerts FOR SELECT TO authenticated USING(users_id=public.ensure_current_user());
CREATE POLICY recovery_requests_own_select ON public.recovery_requests FOR SELECT TO authenticated USING(users_id=public.ensure_current_user());
REVOKE INSERT,UPDATE,DELETE ON public.worker_heartbeats,public.operational_alerts,public.recovery_requests FROM anon,authenticated;
GRANT SELECT ON public.worker_heartbeats,public.operational_alerts,public.recovery_requests TO authenticated;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.worker_heartbeats,public.operational_alerts,public.recovery_requests TO service_role;

CREATE OR REPLACE FUNCTION public.service_worker_heartbeat(
  p_worker_id text,p_worker_version text,p_status text DEFAULT 'online',p_metrics jsonb DEFAULT '{}'::jsonb,p_metadata jsonb DEFAULT '{}'::jsonb
) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
BEGIN
  IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role_required'; END IF;
  INSERT INTO public.worker_heartbeats(worker_id,worker_version,worker_status,metrics,metadata)
  VALUES(trim(p_worker_id),trim(p_worker_version),p_status,coalesce(p_metrics,'{}'::jsonb),coalesce(p_metadata,'{}'::jsonb))
  ON CONFLICT(worker_id) DO UPDATE SET worker_version=excluded.worker_version,worker_status=excluded.worker_status,
    last_seen_at=now(),metrics=excluded.metrics,metadata=excluded.metadata;
END; $$;

CREATE OR REPLACE FUNCTION public.request_operational_recovery(p_scope text DEFAULT 'all')
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE v_user bigint:=public.ensure_current_user(); v_id bigint;
BEGIN
  IF p_scope NOT IN('all','whatsapp','instagram') THEN RAISE EXCEPTION 'recovery_scope_invalid'; END IF;
  IF EXISTS(SELECT 1 FROM public.recovery_requests WHERE users_id=v_user AND status IN('pending','running')) THEN
    SELECT recovery_requests_id INTO v_id FROM public.recovery_requests WHERE users_id=v_user AND status IN('pending','running') ORDER BY requested_at DESC LIMIT 1;
    RETURN v_id;
  END IF;
  INSERT INTO public.recovery_requests(users_id,requested_by,scope) VALUES(v_user,auth.uid(),p_scope) RETURNING recovery_requests_id INTO v_id;
  PERFORM public.append_audit_event('monitoring','recovery_requested','recovery_request',v_id::text,NULL,NULL,NULL,NULL,NULL,NULL,jsonb_build_object('scope',p_scope),v_user);
  RETURN v_id;
END; $$;

CREATE OR REPLACE FUNCTION public.service_claim_recovery_request(p_worker_id text)
RETURNS TABLE(recovery_requests_id bigint,users_id bigint,scope text)
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE v_id bigint;
BEGIN
  IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role_required'; END IF;
  SELECT r.recovery_requests_id INTO v_id FROM public.recovery_requests r WHERE r.status='pending' ORDER BY r.requested_at FOR UPDATE SKIP LOCKED LIMIT 1;
  IF v_id IS NULL THEN RETURN; END IF;
  UPDATE public.recovery_requests SET status='running',worker_id=p_worker_id,started_at=now() WHERE public.recovery_requests.recovery_requests_id=v_id;
  RETURN QUERY SELECT r.recovery_requests_id,r.users_id,r.scope FROM public.recovery_requests r WHERE r.recovery_requests_id=v_id;
END; $$;

CREATE OR REPLACE FUNCTION public.service_complete_recovery_request(p_request_id bigint,p_result jsonb,p_error text DEFAULT NULL)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
BEGIN
  IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role_required'; END IF;
  UPDATE public.recovery_requests SET status=CASE WHEN p_error IS NULL THEN 'completed' ELSE 'failed' END,
    result=coalesce(p_result,'{}'::jsonb),error_message=p_error,finished_at=now()
  WHERE recovery_requests_id=p_request_id AND status='running';
END; $$;

CREATE OR REPLACE FUNCTION public.get_operational_health()
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE v_user bigint:=public.ensure_current_user(); v_result jsonb;
BEGIN
  SELECT jsonb_build_object(
    'checkedAt',now(),
    'workers',jsonb_build_object(
      'online',(SELECT count(*) FROM public.worker_heartbeats WHERE last_seen_at>now()-interval '2 minutes' AND worker_status='online'),
      'stale',(SELECT count(*) FROM public.worker_heartbeats WHERE last_seen_at<=now()-interval '2 minutes')
    ),
    'queues',jsonb_build_object(
      'pending',(SELECT count(*) FROM public.queue_items WHERE users_id=v_user AND status_id=3),
      'processing',(SELECT count(*) FROM public.queue_items WHERE users_id=v_user AND status_id=4),
      'staleProcessing',(SELECT count(*) FROM public.queue_items WHERE users_id=v_user AND status_id=4 AND queue_items_updated_at<now()-interval '15 minutes'),
      'errors',(SELECT count(*) FROM public.queue_items WHERE users_id=v_user AND status_id=6)
    ),
    'reconciliation',jsonb_build_object(
      'whatsapp',(SELECT count(*) FROM public.queue_item_dispatch_parts p WHERE p.users_id=v_user AND p.queue_item_dispatch_parts_state='reconciliation_required'),
      'instagram',(SELECT count(*) FROM public.instagram_queue_progress p WHERE p.users_id=v_user AND p.step='reconciliation_required')
    ),
    'batches',jsonb_build_object(
      'active',(SELECT count(*) FROM public.worker_batches WHERE users_id=v_user AND worker_batches_status IN('queued','running','paused')),
      'stale',(SELECT count(*) FROM public.worker_batches WHERE users_id=v_user AND worker_batches_status='running' AND worker_batches_heartbeat_at<now()-interval '15 minutes')
    ),
    'alerts',jsonb_build_object(
      'open',(SELECT count(*) FROM public.operational_alerts WHERE users_id=v_user AND status<>'resolved'),
      'critical',(SELECT count(*) FROM public.operational_alerts WHERE users_id=v_user AND status<>'resolved' AND severity='critical')
    ),
    'latestRecovery',(SELECT to_jsonb(r) FROM public.recovery_requests r WHERE r.users_id=v_user ORDER BY r.requested_at DESC LIMIT 1)
  ) INTO v_result;
  RETURN v_result;
END; $$;

CREATE OR REPLACE FUNCTION public.refresh_operational_alerts(p_users_id bigint)
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE v_count integer:=0; v_value bigint;
BEGIN
  IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role_required'; END IF;
  SELECT count(*) INTO v_value FROM public.queue_items WHERE users_id=p_users_id AND status_id=4 AND queue_items_updated_at<now()-interval '15 minutes';
  IF v_value>0 THEN
    INSERT INTO public.operational_alerts(users_id,alert_key,source,severity,title,message,metadata)
    VALUES(p_users_id,'stale_queue_items','queues','critical','Itens travados em processamento',v_value||' item(ns) estão processando há mais de 15 minutos.',jsonb_build_object('count',v_value))
    ON CONFLICT(users_id,alert_key) DO UPDATE SET status='open',last_detected_at=now(),message=excluded.message,metadata=excluded.metadata,resolved_at=NULL;
    v_count:=v_count+1;
  ELSE UPDATE public.operational_alerts SET status='resolved',resolved_at=now() WHERE users_id=p_users_id AND alert_key='stale_queue_items' AND status<>'resolved'; END IF;
  SELECT count(*) INTO v_value FROM public.queue_item_dispatch_parts WHERE users_id=p_users_id AND queue_item_dispatch_parts_state='reconciliation_required';
  IF v_value>0 THEN
    INSERT INTO public.operational_alerts(users_id,alert_key,source,severity,title,message,metadata)
    VALUES(p_users_id,'whatsapp_reconciliation','worker','warning','WhatsApp requer reconciliação',v_value||' parte(s) possuem resultado incerto.',jsonb_build_object('count',v_value))
    ON CONFLICT(users_id,alert_key) DO UPDATE SET status='open',last_detected_at=now(),message=excluded.message,metadata=excluded.metadata,resolved_at=NULL;
    v_count:=v_count+1;
  ELSE UPDATE public.operational_alerts SET status='resolved',resolved_at=now() WHERE users_id=p_users_id AND alert_key='whatsapp_reconciliation' AND status<>'resolved'; END IF;
  SELECT count(*) INTO v_value FROM public.instagram_queue_progress WHERE users_id=p_users_id AND step='reconciliation_required';
  IF v_value>0 THEN
    INSERT INTO public.operational_alerts(users_id,alert_key,source,severity,title,message,metadata)
    VALUES(p_users_id,'instagram_reconciliation','instagram','warning','Instagram requer reconciliação',v_value||' item(ns) possuem resultado incerto.',jsonb_build_object('count',v_value))
    ON CONFLICT(users_id,alert_key) DO UPDATE SET status='open',last_detected_at=now(),message=excluded.message,metadata=excluded.metadata,resolved_at=NULL;
    v_count:=v_count+1;
  ELSE UPDATE public.operational_alerts SET status='resolved',resolved_at=now() WHERE users_id=p_users_id AND alert_key='instagram_reconciliation' AND status<>'resolved'; END IF;
  RETURN v_count;
END; $$;

GRANT EXECUTE ON FUNCTION public.request_operational_recovery(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_operational_health() TO authenticated;
GRANT EXECUTE ON FUNCTION public.service_worker_heartbeat(text,text,text,jsonb,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.service_claim_recovery_request(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.service_complete_recovery_request(bigint,jsonb,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.refresh_operational_alerts(bigint) TO service_role;
REVOKE ALL ON FUNCTION public.service_worker_heartbeat(text,text,text,jsonb,jsonb) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.service_claim_recovery_request(text) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.service_complete_recovery_request(bigint,jsonb,text) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.refresh_operational_alerts(bigint) FROM PUBLIC,anon,authenticated;

COMMIT;
