BEGIN;

-- ETAPA 10 — Base Permanente como memória comercial canônica por organização.

DO $stage_preflight$
DECLARE v_missing text[]:=ARRAY[]::text[]; v_name text;
BEGIN
  FOREACH v_name IN ARRAY ARRAY['lead_identity_registry','contact_suppressions','permanent_records'] LOOP IF to_regclass('public.'||v_name) IS NULL THEN v_missing:=array_append(v_missing,'table:'||v_name);END IF;END LOOP;
  IF cardinality(v_missing)>0 THEN RAISE EXCEPTION 'stage_preflight_failed:%',array_to_string(v_missing,',');END IF;
END
$stage_preflight$;

ALTER TABLE public.permanent_records
 ADD COLUMN IF NOT EXISTS organizations_id bigint,
 ADD COLUMN IF NOT EXISTS first_capture_at timestamptz,
 ADD COLUMN IF NOT EXISTS last_capture_at timestamptz,
 ADD COLUMN IF NOT EXISTS capture_occurrences integer NOT NULL DEFAULT 0 CHECK(capture_occurrences>=0),
 ADD COLUMN IF NOT EXISTS contact_channels text[] NOT NULL DEFAULT '{}',
 ADD COLUMN IF NOT EXISTS last_contact_at timestamptz,
 ADD COLUMN IF NOT EXISTS last_contact_result text,
 ADD COLUMN IF NOT EXISTS outcome_updated_at timestamptz,
 ADD COLUMN IF NOT EXISTS outcome_updated_by_member_id bigint REFERENCES public.organization_members(organization_members_id) ON DELETE SET NULL;
ALTER TABLE public.permanent_record_snapshots ADD COLUMN IF NOT EXISTS organizations_id bigint;
UPDATE public.permanent_records p SET organizations_id=l.organizations_id FROM public.leads l WHERE p.organizations_id IS NULL AND l.leads_id=p.canonical_lead_id;
UPDATE public.permanent_record_snapshots s SET organizations_id=p.organizations_id FROM public.permanent_records p WHERE s.organizations_id IS NULL AND p.permanent_records_id=s.permanent_records_id;
DO $$ BEGIN
 IF EXISTS(SELECT 1 FROM public.permanent_records WHERE organizations_id IS NULL) THEN RAISE EXCEPTION 'permanent_records_organization_backfill_incomplete'; END IF;
 IF EXISTS(SELECT 1 FROM public.permanent_record_snapshots WHERE organizations_id IS NULL) THEN RAISE EXCEPTION 'permanent_snapshots_organization_backfill_incomplete'; END IF;
END $$;
ALTER TABLE public.permanent_records ALTER COLUMN organizations_id SET NOT NULL;
ALTER TABLE public.permanent_record_snapshots ALTER COLUMN organizations_id SET NOT NULL;
ALTER TABLE public.permanent_records DROP CONSTRAINT IF EXISTS permanent_records_users_id_canonical_lead_id_key;
CREATE UNIQUE INDEX IF NOT EXISTS permanent_records_org_canonical_uidx ON public.permanent_records(organizations_id,canonical_lead_id);
CREATE INDEX IF NOT EXISTS permanent_records_org_identity_idx ON public.permanent_records(organizations_id,normalized_phone,normalized_instagram,normalized_domain,normalized_maps);
CREATE INDEX IF NOT EXISTS permanent_records_org_outcome_idx ON public.permanent_records(organizations_id,commercial_outcome,last_activity_at DESC);

CREATE TABLE IF NOT EXISTS public.commercial_outcomes (
 commercial_outcome_key text PRIMARY KEY,
 display_name text NOT NULL,
 suppress_contact boolean NOT NULL DEFAULT false,
 allow_reentry boolean NOT NULL DEFAULT true,
 minimum_reentry_days integer CHECK(minimum_reentry_days IS NULL OR minimum_reentry_days>=0),
 sort_order integer NOT NULL,
 status_id bigint NOT NULL DEFAULT 1 REFERENCES public.status(status_id)
);
INSERT INTO public.commercial_outcomes(commercial_outcome_key,display_name,suppress_contact,allow_reentry,minimum_reentry_days,sort_order) VALUES
 ('no_response','Sem resposta',false,true,30,10),
 ('responded','Respondeu',false,true,14,20),
 ('interested','Interessado',false,true,7,30),
 ('not_interested','Não interessado',false,true,90,40),
 ('client','Cliente',true,false,NULL,50),
 ('wrong_contact','Contato incorreto',true,false,NULL,60),
 ('closed_business','Empresa fechada',true,false,NULL,70),
 ('do_not_contact','Não contatar',true,false,NULL,80)
ON CONFLICT(commercial_outcome_key) DO UPDATE SET display_name=excluded.display_name,suppress_contact=excluded.suppress_contact,allow_reentry=excluded.allow_reentry,minimum_reentry_days=excluded.minimum_reentry_days,sort_order=excluded.sort_order;
GRANT SELECT ON public.commercial_outcomes TO authenticated,service_role;

CREATE TABLE IF NOT EXISTS public.permanent_record_events (
 permanent_record_events_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 organizations_id bigint NOT NULL REFERENCES public.organizations(organizations_id) ON DELETE RESTRICT,
 permanent_records_id bigint NOT NULL REFERENCES public.permanent_records(permanent_records_id) ON DELETE CASCADE,
 canonical_lead_id bigint NOT NULL REFERENCES public.leads(leads_id) ON DELETE RESTRICT,
 organization_members_id bigint REFERENCES public.organization_members(organization_members_id) ON DELETE SET NULL,
 event_type text NOT NULL CHECK(event_type IN ('capture_seen','lead_finalized','dispatch','conversation','outcome_changed','suppressed','unsuppressed','archived','reentry_allowed','reentry_blocked','metadata_changed')),
 channel text,
 result text,
 payload jsonb NOT NULL DEFAULT '{}'::jsonb,
 created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS permanent_record_events_record_idx ON public.permanent_record_events(organizations_id,permanent_records_id,created_at DESC);
ALTER TABLE public.permanent_record_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS permanent_record_events_org_select ON public.permanent_record_events;
CREATE POLICY permanent_record_events_org_select ON public.permanent_record_events FOR SELECT TO authenticated USING(organizations_id=public.current_organization_id() AND public.has_organization_permission('leads.view'));
REVOKE INSERT,UPDATE,DELETE ON public.permanent_record_events FROM anon,authenticated;GRANT SELECT ON public.permanent_record_events TO authenticated;GRANT ALL ON public.permanent_record_events TO service_role;

-- Memória de captura agrega ocorrências da Captura oficial sem criar novo lead.
CREATE OR REPLACE FUNCTION public.service_record_capture_memory(p_organizations_id bigint,p_canonical_lead_id bigint,p_payload jsonb DEFAULT '{}'::jsonb)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE v_id bigint;
BEGIN
 IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role_required';END IF;
 SELECT permanent_records_id INTO v_id FROM public.permanent_records WHERE organizations_id=p_organizations_id AND canonical_lead_id=p_canonical_lead_id FOR UPDATE;
 IF v_id IS NULL THEN PERFORM public.refresh_permanent_record(p_canonical_lead_id,'capture_memory');SELECT permanent_records_id INTO v_id FROM public.permanent_records WHERE organizations_id=p_organizations_id AND canonical_lead_id=p_canonical_lead_id;END IF;
 IF v_id IS NULL THEN RETURN NULL; END IF;
 UPDATE public.permanent_records SET first_capture_at=coalesce(first_capture_at,now()),last_capture_at=now(),capture_occurrences=capture_occurrences+1,last_activity_at=greatest(last_activity_at,now()),permanent_records_updated_at=now() WHERE permanent_records_id=v_id;
 INSERT INTO public.permanent_record_events(organizations_id,permanent_records_id,canonical_lead_id,event_type,payload) VALUES(p_organizations_id,v_id,p_canonical_lead_id,'capture_seen',coalesce(p_payload,'{}'));
 RETURN v_id;
END; $$;
REVOKE ALL ON FUNCTION public.service_record_capture_memory(bigint,bigint,jsonb) FROM PUBLIC,anon,authenticated;GRANT EXECUTE ON FUNCTION public.service_record_capture_memory(bigint,bigint,jsonb) TO service_role;

-- Atualiza o refresh legado para respeitar tenant e registrar snapshot/evento.
CREATE OR REPLACE FUNCTION public.refresh_permanent_record(p_lead_id bigint,p_reason text DEFAULT 'refresh')
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE v_lead public.leads%ROWTYPE;v_canonical bigint;v_base public.leads%ROWTYPE;v_status bigint;v_total integer;v_dispatch integer;v_first timestamptz;v_last timestamptz;v_last_sent timestamptz;v_suppressed boolean;v_id bigint;v_snapshot jsonb;v_channels text[];
BEGIN
 SELECT * INTO v_lead FROM public.leads WHERE leads_id=p_lead_id;IF NOT FOUND THEN RETURN NULL;END IF;v_canonical:=coalesce(v_lead.canonical_lead_id,v_lead.leads_id);
 SELECT * INTO v_base FROM public.leads WHERE leads_id=v_canonical AND organizations_id=v_lead.organizations_id;IF NOT FOUND THEN v_base:=v_lead;v_canonical:=v_lead.leads_id;END IF;
 IF NOT EXISTS(SELECT 1 FROM public.leads l WHERE l.organizations_id=v_lead.organizations_id AND (l.leads_id=v_canonical OR l.canonical_lead_id=v_canonical) AND l.lead_status_id IN(5,6,7,8)) THEN RETURN NULL;END IF;
 SELECT l.lead_status_id,l.leads_updated_at INTO v_status,v_last FROM public.leads l WHERE l.organizations_id=v_lead.organizations_id AND (l.leads_id=v_canonical OR l.canonical_lead_id=v_canonical) AND l.lead_status_id IN(5,6,7,8) ORDER BY l.leads_updated_at DESC,l.leads_id DESC LIMIT 1;
 SELECT count(*)::integer,min(l.leads_created_at),max(l.leads_updated_at) INTO v_total,v_first,v_last FROM public.leads l WHERE l.organizations_id=v_lead.organizations_id AND (l.leads_id=v_canonical OR l.canonical_lead_id=v_canonical);
 SELECT count(*)::integer,max(s.sents_sent_at),coalesce(array_agg(DISTINCT c.channels_name) FILTER(WHERE c.channels_name IS NOT NULL),'{}') INTO v_dispatch,v_last_sent,v_channels FROM public.sents s JOIN public.leads l ON l.leads_id=s.leads_id LEFT JOIN public.channels c ON c.channels_id=s.channels_id WHERE l.organizations_id=v_lead.organizations_id AND (l.leads_id=v_canonical OR l.canonical_lead_id=v_canonical) AND s.sents_sent_at IS NOT NULL;
 SELECT EXISTS(SELECT 1 FROM public.contact_suppressions cs WHERE cs.organizations_id=v_lead.organizations_id AND cs.is_active AND (cs.expires_at IS NULL OR cs.expires_at>now()) AND ((cs.identity_type='phone' AND cs.identity_value=v_base.leads_normalized_phone) OR (cs.identity_type='instagram' AND cs.identity_value=v_base.leads_normalized_instagram) OR (cs.identity_type='domain' AND cs.identity_value=v_base.leads_normalized_domain) OR (cs.identity_type='maps' AND cs.identity_value=v_base.leads_normalized_maps))) INTO v_suppressed;
 INSERT INTO public.permanent_records(users_id,organizations_id,canonical_lead_id,branches_id,states_id,cities_id,channels_id,last_lead_status_id,company_name,normalized_phone,normalized_instagram,normalized_domain,normalized_maps,total_leads,total_dispatches,first_seen_at,last_activity_at,last_sent_at,last_contact_at,contact_channels,is_suppressed)
 VALUES(v_lead.users_id,v_lead.organizations_id,v_canonical,v_base.branches_id,v_base.states_id,v_base.cities_id,v_base.channels_id,v_status,v_base.leads_name,v_base.leads_normalized_phone,v_base.leads_normalized_instagram,v_base.leads_normalized_domain,v_base.leads_normalized_maps,greatest(v_total,1),coalesce(v_dispatch,0),coalesce(v_first,now()),coalesce(v_last,now()),v_last_sent,v_last_sent,coalesce(v_channels,'{}'),coalesce(v_suppressed,false))
 ON CONFLICT(organizations_id,canonical_lead_id) DO UPDATE SET branches_id=excluded.branches_id,states_id=excluded.states_id,cities_id=excluded.cities_id,channels_id=excluded.channels_id,last_lead_status_id=CASE WHEN public.permanent_records.record_status='archived' THEN 8 ELSE excluded.last_lead_status_id END,company_name=excluded.company_name,normalized_phone=excluded.normalized_phone,normalized_instagram=excluded.normalized_instagram,normalized_domain=excluded.normalized_domain,normalized_maps=excluded.normalized_maps,total_leads=excluded.total_leads,total_dispatches=excluded.total_dispatches,first_seen_at=excluded.first_seen_at,last_activity_at=excluded.last_activity_at,last_sent_at=excluded.last_sent_at,last_contact_at=excluded.last_contact_at,contact_channels=excluded.contact_channels,is_suppressed=excluded.is_suppressed,permanent_records_updated_at=now()
 RETURNING permanent_records_id INTO v_id;
 SELECT to_jsonb(pr) INTO v_snapshot FROM public.permanent_records pr WHERE pr.permanent_records_id=v_id;
 INSERT INTO public.permanent_record_snapshots(users_id,organizations_id,permanent_records_id,reason,snapshot) VALUES(v_lead.users_id,v_lead.organizations_id,v_id,p_reason,v_snapshot);
 INSERT INTO public.permanent_record_events(organizations_id,permanent_records_id,canonical_lead_id,event_type,payload) VALUES(v_lead.organizations_id,v_id,v_canonical,CASE WHEN p_reason='dispatch_changed' THEN 'dispatch' ELSE 'lead_finalized' END,jsonb_build_object('reason',p_reason,'statusId',v_status)) ON CONFLICT DO NOTHING;
 RETURN v_id;
END; $$;

CREATE OR REPLACE FUNCTION public.update_permanent_record_metadata(p_canonical_lead_id bigint,p_commercial_outcome text,p_operator_notes text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE v_org bigint:=public.current_organization_id();v_member bigint:=public.current_organization_member_id();v_id bigint;v_old text;v_users bigint;v_suppress boolean;
BEGIN
 PERFORM public.require_organization_permission('leads.edit');
 IF nullif(trim(coalesce(p_commercial_outcome,'')),'') IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.commercial_outcomes WHERE commercial_outcome_key=trim(p_commercial_outcome) AND status_id=1) THEN RAISE EXCEPTION 'commercial_outcome_invalid';END IF;
 SELECT permanent_records_id,commercial_outcome,users_id INTO v_id,v_old,v_users FROM public.permanent_records WHERE organizations_id=v_org AND canonical_lead_id=p_canonical_lead_id FOR UPDATE;IF v_id IS NULL THEN RAISE EXCEPTION 'permanent_record_not_found';END IF;
 UPDATE public.permanent_records SET commercial_outcome=nullif(trim(p_commercial_outcome),''),operator_notes=nullif(trim(p_operator_notes),''),outcome_updated_at=now(),outcome_updated_by_member_id=v_member,permanent_records_updated_at=now() WHERE permanent_records_id=v_id;
 INSERT INTO public.permanent_record_events(organizations_id,permanent_records_id,canonical_lead_id,organization_members_id,event_type,result,payload) VALUES(v_org,v_id,p_canonical_lead_id,v_member,'outcome_changed',nullif(trim(p_commercial_outcome),''),jsonb_build_object('previous',v_old,'notesChanged',true));
 SELECT suppress_contact INTO v_suppress FROM public.commercial_outcomes WHERE commercial_outcome_key=trim(p_commercial_outcome);
 IF coalesce(v_suppress,false) THEN
   INSERT INTO public.contact_suppressions(users_id,organizations_id,identity_type,identity_value,reason,is_active,source_lead_id)
   SELECT v_users,v_org,x.identity_type,x.identity_value,'commercial_outcome:'||trim(p_commercial_outcome),true,p_canonical_lead_id FROM (VALUES('phone',(SELECT normalized_phone FROM public.permanent_records WHERE permanent_records_id=v_id)),('instagram',(SELECT normalized_instagram FROM public.permanent_records WHERE permanent_records_id=v_id)),('domain',(SELECT normalized_domain FROM public.permanent_records WHERE permanent_records_id=v_id)),('maps',(SELECT normalized_maps FROM public.permanent_records WHERE permanent_records_id=v_id))) x(identity_type,identity_value) WHERE nullif(x.identity_value,'') IS NOT NULL ON CONFLICT(organizations_id,identity_type,identity_value) DO UPDATE SET is_active=true,reason=excluded.reason,expires_at=NULL,updated_at=now();
 END IF;
END; $$;
GRANT EXECUTE ON FUNCTION public.update_permanent_record_metadata(bigint,text,text) TO authenticated;

CREATE OR REPLACE FUNCTION public.commercial_reentry_decision(p_organizations_id bigint,p_canonical_lead_id bigint,p_at timestamptz DEFAULT now())
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path TO pg_catalog,public AS $$
DECLARE r public.permanent_records%ROWTYPE;o public.commercial_outcomes%ROWTYPE;v_age integer;
BEGIN
 IF auth.role()<>'service_role' AND p_organizations_id<>public.current_organization_id() THEN RAISE EXCEPTION 'organization_access_denied';END IF;
 SELECT * INTO r FROM public.permanent_records WHERE organizations_id=p_organizations_id AND canonical_lead_id=p_canonical_lead_id;IF NOT FOUND THEN RETURN jsonb_build_object('allowed',true,'reason','not_seen');END IF;
 IF r.is_suppressed THEN RETURN jsonb_build_object('allowed',false,'reason','suppressed','outcome',r.commercial_outcome);END IF;
 IF r.commercial_outcome IS NULL THEN RETURN jsonb_build_object('allowed',true,'reason','no_outcome');END IF;
 SELECT * INTO o FROM public.commercial_outcomes WHERE commercial_outcome_key=r.commercial_outcome AND status_id=1;IF NOT FOUND THEN RETURN jsonb_build_object('allowed',true,'reason','unknown_outcome');END IF;
 IF NOT o.allow_reentry THEN RETURN jsonb_build_object('allowed',false,'reason','outcome_blocks_reentry','outcome',o.commercial_outcome_key);END IF;
 v_age:=floor(extract(epoch from (p_at-coalesce(r.last_contact_at,r.last_activity_at)))/86400)::integer;
 RETURN jsonb_build_object('allowed',o.minimum_reentry_days IS NULL OR v_age>=o.minimum_reentry_days,'reason',CASE WHEN o.minimum_reentry_days IS NULL OR v_age>=o.minimum_reentry_days THEN 'cooldown_completed' ELSE 'cooldown_active' END,'daysSinceContact',v_age,'minimumDays',o.minimum_reentry_days,'outcome',o.commercial_outcome_key);
END; $$;
GRANT EXECUTE ON FUNCTION public.commercial_reentry_decision(bigint,bigint,timestamptz) TO authenticated,service_role;


CREATE OR REPLACE FUNCTION public.archive_permanent_record(p_canonical_lead_id bigint,p_expected_status_id bigint)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog,public AS $$
DECLARE v_org bigint:=public.current_organization_id();v_user bigint:=public.ensure_current_user();v_member bigint:=public.current_organization_member_id();v_id bigint;
BEGIN
 PERFORM public.require_organization_permission('leads.delete');
 UPDATE public.permanent_records SET record_status='archived',last_lead_status_id=8,archived_at=now(),permanent_records_updated_at=now()
 WHERE organizations_id=v_org AND canonical_lead_id=p_canonical_lead_id AND last_lead_status_id=p_expected_status_id AND record_status<>'archived' RETURNING permanent_records_id INTO v_id;
 IF v_id IS NOT NULL THEN
   INSERT INTO public.permanent_record_events(organizations_id,permanent_records_id,canonical_lead_id,organization_members_id,event_type,payload) VALUES(v_org,v_id,p_canonical_lead_id,v_member,'archived',jsonb_build_object('expectedStatusId',p_expected_status_id));
   PERFORM public.append_audit_event('base-permanente','archive_permanent_record','permanent_record',v_id::text,p_canonical_lead_id,NULL,NULL,p_expected_status_id,8,NULL,jsonb_build_object('organization_id',v_org),v_user);
 END IF;
 RETURN v_id;
END; $$;
GRANT EXECUTE ON FUNCTION public.archive_permanent_record(bigint,bigint) TO authenticated;

-- RLS tenant-aware.
ALTER TABLE public.permanent_records ENABLE ROW LEVEL SECURITY;ALTER TABLE public.permanent_record_snapshots ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS permanent_records_own_select ON public.permanent_records;DROP POLICY IF EXISTS permanent_records_org_select ON public.permanent_records;CREATE POLICY permanent_records_org_select ON public.permanent_records FOR SELECT TO authenticated USING(organizations_id=public.current_organization_id() AND public.has_organization_permission('leads.view'));
DROP POLICY IF EXISTS permanent_record_snapshots_own_select ON public.permanent_record_snapshots;DROP POLICY IF EXISTS permanent_record_snapshots_org_select ON public.permanent_record_snapshots;CREATE POLICY permanent_record_snapshots_org_select ON public.permanent_record_snapshots FOR SELECT TO authenticated USING(organizations_id=public.current_organization_id() AND public.has_organization_permission('leads.view'));

DO $$ DECLARE r record; BEGIN FOR r IN SELECT DISTINCT coalesce(canonical_lead_id,leads_id) lead_id FROM public.leads WHERE lead_status_id IN(5,6,7,8) LOOP PERFORM public.refresh_permanent_record(r.lead_id,'stage10_backfill'); END LOOP; END $$;

COMMIT;
