import { createClient, type SupabaseClient } from '@supabase/supabase-js';
type ApiRequest = { method?: string; body?: unknown; headers?: Record<string, string | string[] | undefined> };
type ApiResponse = { status(code: number): ApiResponse; json(body: unknown): void; setHeader(name: string, value: string): void };
type RecordValue = Record<string, unknown>;
declare const process: { env: Record<string, string | undefined> };
export const maxDuration = 60;
function envAny(...names: string[]) { for (const name of names) { const value = process.env[name]; if (String(value ?? '').trim()) return String(value).trim(); } return ''; }
function bodyRecord(body: unknown): RecordValue { if (typeof body === 'string') { try { return JSON.parse(body) as RecordValue; } catch { return {}; } } return body && typeof body === 'object' && !Array.isArray(body) ? body as RecordValue : {}; }
function header(req: ApiRequest, name: string) { const key = Object.keys(req.headers ?? {}).find((item) => item.toLowerCase() === name.toLowerCase()); const value = key ? req.headers?.[key] : undefined; return Array.isArray(value) ? String(value[0] ?? '') : String(value ?? ''); }
function bearer(req: ApiRequest) { return header(req, 'authorization').match(/^Bearer\s+(.+)$/i)?.[1]?.trim() ?? ''; }
function idsOf(value: unknown) { return Array.from(new Set((Array.isArray(value) ? value : []).map(Number).filter(Number.isSafeInteger))); }
function send(res: ApiResponse, status: number, payload: unknown) { res.setHeader('Cache-Control', 'no-store'); return res.status(status).json(payload); }
async function auth(req: ApiRequest): Promise<{ client: SupabaseClient; userId: number }> { const token = bearer(req); const url = envAny('SUPABASE_URL','VITE_SUPABASE_URL'); const key = envAny('SUPABASE_ANON_KEY','SUPABASE_PUBLISHABLE_KEY','VITE_SUPABASE_PUBLISHABLE_KEY'); if (!token) throw new Error('auth_required'); if (!url || !key) throw new Error('supabase_auth_backend_not_configured'); const client = createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:`Bearer ${token}`}}}); const a=await client.auth.getUser(token); if(a.error||!a.data.user) throw new Error('auth_invalid'); const u=await client.from('users').select('users_id').eq('auth_user_id',a.data.user.id).maybeSingle(); if(u.error||!u.data?.users_id) throw new Error('public_user_not_found'); return {client,userId:Number(u.data.users_id)}; }
async function callWorker(ids:number[], userId:number) { const base=envAny('WHATSAPP_WORKER_DISPATCH_URL'); const token=envAny('WHATSAPP_WORKER_DISPATCH_TOKEN','WHATSAPP_WORKER_BATCH_TOKEN','WHATSAPP_VALIDATION_WORKER_TOKEN'); if(!base) throw new Error('worker_dispatch_backend_not_configured'); if(!token) throw new Error('worker_dispatch_token_not_configured'); const controller=new AbortController(); const timer=setTimeout(()=>controller.abort(),55000); try{ const response=await fetch(base,{method:'POST',headers:{'Content-Type':'application/json','X-Worker-Token':token},body:JSON.stringify({user_id:userId,queue_item_ids:ids}),signal:controller.signal}); const payload=await response.json().catch(()=>null); if(!response.ok||(payload?.ok===false&&!Array.isArray(payload?.results))) throw new Error(String(payload?.message??payload?.error??`worker_http_${response.status}`)); return payload; } finally{clearTimeout(timer);} }
export default async function handler(req:ApiRequest,res:ApiResponse){ if(req.method!=='POST') return send(res,405,{ok:false,error:'method_not_allowed'}); try{ const ids=idsOf(bodyRecord(req.body).queue_item_ids??bodyRecord(req.body).ids); if(!ids.length) return send(res,400,{ok:false,error:'queue_item_ids_required'}); const context=await auth(req); const owned=await context.client.from('queue_items').select('queue_items_id').eq('users_id',context.userId).in('queue_items_id',ids); if(owned.error) throw new Error(owned.error.message); if((owned.data??[]).length!==ids.length) throw new Error('queue_item_not_available_for_current_user'); return send(res,200,await callWorker(ids,context.userId)); }catch(error){ const message=error instanceof Error?error.message:'worker_dispatch_proxy_error'; const status=message.includes('auth_')?401:message.includes('not_available')?403:message.includes('required')?400:502; return send(res,status,{ok:false,error:message,message}); } }
