import { createClient } from '@supabase/supabase-js';
type Req={method?:string;body?:unknown;headers?:Record<string,string|string[]|undefined>;query?:Record<string,string|string[]|undefined>};
type Res={status(n:number):Res;json(v:unknown):void;setHeader(n:string,v:string):void;end():void};
declare const process:{env:Record<string,string|undefined>};
type J=Record<string,unknown>;
class NoRealtime{constructor(){throw new Error('Realtime indisponivel nesta rota.')}}
const env=(...n:string[])=>n.map(k=>process.env[k]?.trim()).find(Boolean)||'';
const txt=(v:unknown)=>String(v??'').trim();
const obj=(v:unknown):J=>v&&typeof v==='object'&&!Array.isArray(v)?v as J:{};
function client(){const u=env('SUPABASE_URL','VITE_SUPABASE_URL'),k=env('SUPABASE_SERVICE_ROLE_KEY');if(!u||!k)throw new Error('Supabase nao configurado.');return createClient(u,k,{auth:{persistSession:false,autoRefreshToken:false},realtime:{transport:NoRealtime as never}})}
const leadsTable=()=>env('SUPABASE_TABLE_IMPORT_LEADS','VITE_SUPABASE_TABLE_IMPORT_LEADS')||'leads';
const baseTable=()=>env('SUPABASE_TABLE_BASE_PERMANENTE','VITE_SUPABASE_TABLE_BASE_PERMANENTE')||'base_permanente';
function hdr(req:Req,n:string){const h=req.headers||{};const v=h[n]??h[n.toLowerCase()]??h[n.toUpperCase()];return Array.isArray(v)?txt(v[0]):txt(v)}
function auth(req:Req){const e=env('SITE_LEADS_EXTENSION_SECRET','EXTENSION_SECRET');if(!e||hdr(req,'x-site-leads-extension-secret')!==e)throw new Error('Secret invalido.');}
function cors(res:Res){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, x-site-leads-extension-secret');res.setHeader('Cache-Control','no-store')}
function body(v:unknown):J{if(typeof v==='string'){try{return obj(JSON.parse(v))}catch{return {}}}return obj(v)}
const first=(...v:unknown[])=>v.map(txt).find(Boolean)||'';
function values(r:J,keys:string[]){const out:string[]=[];const walk=(v:unknown,d=0)=>{if(d>3||v==null)return;if(typeof v==='string'){if(v.trim())out.push(v.trim());return}if(Array.isArray(v)){v.forEach(x=>walk(x,d+1));return}if(typeof v==='object')for(const [k,x] of Object.entries(v as J))if(keys.includes(k.toLowerCase()))walk(x,d+1);};walk(r);return out}
function normUrl(v:unknown){let s=txt(v);if(!s)return'';if(!/^https?:\/\//i.test(s))s='https://'+s;try{const u=new URL(s);u.hash='';u.hostname=u.hostname.toLowerCase().replace(/^www\./,'');u.pathname=u.pathname.replace(/\/+$/,'')||'/';for(const k of [...u.searchParams.keys()])if(/^(utm_|fbclid$|gclid$|igsh$)/i.test(k))u.searchParams.delete(k);return `${u.protocol}//${u.hostname}${u.pathname}${u.searchParams.toString()?'?'+u.searchParams.toString():''}`}catch{return''}}
function rowInfo(r:J){const d=obj(r.data),c=obj(r.crm_data),raw=obj(r.raw_payload);const name=first(r.company_name,r.company,r.name,d.company_name,d.company,d.title,raw.title);const branch=first(r.branch_name,r.category_name,r.category,d.branch_name,d.branch,d.ramo,raw.categoryName);const site=first(r.website,r.site,d.website,d.site,c.website,c.site,raw.website,raw.site,values(r,['website','site','website_url','site_url'])[0]);const maps=first(r.maps_url,r.google_maps_url,d.maps_url,d.url,c.maps_url,raw.url,values(r,['maps_url','google_maps_url','mapsurl','url'])[0]);const insta=first(r.instagram_url,r.instagram,d.instagram_url,d.instagram,c.instagram_url,raw.instagram);const dest=first(r.destination,r.destination_override,r.original_destination,d.destination,d.destino,d.destination_override,c.destination,raw.destination);return{id:txt(r.id),name,branch,site,maps,instagram:insta,status:first(r.status,d.status).toLowerCase(),destination:dest.toLowerCase(),raw:r}}
function isPending(i:ReturnType<typeof rowInfo>){return ['pending','review','em aguarde','aguardando'].includes(i.status)}
function isSite(i:ReturnType<typeof rowInfo>){return ['com site','com-site','website','site'].includes(i.destination)||!!i.site}
function isInstagram(i:ReturnType<typeof rowInfo>){return i.destination==='instagram'||txt(obj(i.raw.data).send_instagram)==='true'}
function missing(m:string){return m.match(/column ["']?([\w]+)["']?.*does not exist/i)?.[1]||m.match(/Could not find the ['"]([\w]+)['"] column/i)?.[1]||''}
async function updateFlex(c:ReturnType<typeof client>,table:string,id:string,p:J){const q={...p};for(let n=0;n<25;n++){const {error}=await c.from(table).update(q).eq('id',id);if(!error)return;const k=missing(error.message);if(!k||!(k in q))throw new Error(error.message);delete q[k]}throw new Error('Falha de compatibilidade de schema.')}
async function upsertFlex(c:ReturnType<typeof client>,table:string,p:J){const q={...p};for(let n=0;n<30;n++){const {error}=await c.from(table).upsert(q,{onConflict:'id'});if(!error)return;const k=missing(error.message);if(!k||!(k in q))throw new Error(error.message);delete q[k]}throw new Error('Falha ao gravar Base Permanente.')}
function basePayload(i:ReturnType<typeof rowInfo>,now:string){const r=i.raw,d=obj(r.data);const data={...d,status:'invalid',destination:'Com site',destino:'Com site',send_instagram:false,sourceLeadId:i.id,invalidatedBy:'extension-control-center',invalidatedAt:now};return{id:`site-invalid-${i.id}`,user_id:r.user_id??d.user_id??null,company_name:i.name,phone:first(r.phone,d.phone,d.telefone),website:i.site,status:'invalid',source:'Extensao Gestao',notes:'Invalidado manualmente pela extensão.',raw_payload:data,data,active:true,kind:'base_permanente',branch_name:i.branch,destination:'Com site',send_instagram:false,updated_at:now}}
async function list(req:Req){const type=txt(req.query?.type||'site').toLowerCase(),branch=txt(req.query?.branch||'');const c=client();const {data,error}=await c.from(leadsTable()).select('*').in('status',['pending','review','approved']);if(error)throw new Error(error.message);let rows=(data||[]).map(r=>rowInfo(r as J)).filter(isPending);rows=rows.filter(type==='instagram'?isInstagram:isSite);if(branch&&branch.toLowerCase()!=='todos')rows=rows.filter(x=>x.branch.toLowerCase()===branch.toLowerCase());return{success:true,items:rows.map(x=>({id:x.id,name:x.name,branch:x.branch,status:x.status,site:x.site,mapsUrl:x.maps,instagram:x.instagram,destination:x.destination})),branches:[...new Set(rows.map(x=>x.branch).filter(Boolean))].sort()}}
async function action(payload:J){const action=txt(payload.action);const id=txt(payload.leadId);if(!id)throw new Error('leadId obrigatorio.');const c=client();const {data,error}=await c.from(leadsTable()).select('*').eq('id',id).maybeSingle();if(error||!data)throw new Error(error?.message||'Lead nao encontrado.');const i=rowInfo(data as J),now=new Date().toISOString(),d=obj(i.raw.data),crm=obj(i.raw.crm_data),raw=obj(i.raw.raw_payload);
 if(action==='approve_site'||action==='invalidate_site'){const invalid=action==='invalidate_site';if(invalid)await upsertFlex(c,baseTable(),basePayload(i,now));const common={status:invalid?'invalid':'approved',destination:'Com site',destino:'Com site',destination_override:'Com site',send_instagram:false,instagram_override_reason:null,extension_action:action,extension_action_at:now};await updateFlex(c,leadsTable(),id,{status:common.status,destination:'Com site',destination_override:'Com site',send_instagram:false,data:{...d,...common},crm_data:{...crm,...common},raw_payload:{...raw,...common},updated_at:now});return{success:true,status:common.status}}
 if(action==='approve_instagram'){const instagramUrl=normUrl(payload.instagramUrl);if(!instagramUrl||!new URL(instagramUrl).hostname.endsWith('instagram.com'))throw new Error('Perfil do Instagram invalido.');const common={status:'approved',destination:'Instagram',destino:'Instagram',destination_override:'Instagram',send_instagram:true,instagram_url:instagramUrl,instagram:instagramUrl,instagram_approved_by:'extension-control-center',instagram_approved_at:now};await updateFlex(c,leadsTable(),id,{status:'approved',destination:'Instagram',destination_override:'Instagram',send_instagram:true,instagram_url:instagramUrl,instagram:instagramUrl,data:{...d,...common},crm_data:{...crm,...common},raw_payload:{...raw,...common},updated_at:now});return{success:true,status:'approved',instagramUrl}}
 throw new Error('Acao invalida.');}
export default async function handler(req:Req,res:Res){cors(res);if(req.method==='OPTIONS')return res.status(204).end();try{auth(req);if(req.method==='GET')return res.status(200).json(await list(req));if(req.method==='POST')return res.status(200).json(await action(body(req.body)));return res.status(405).json({success:false,error:'method_not_allowed'})}catch(e){const m=e instanceof Error?e.message:'Erro';return res.status(/secret/i.test(m)?401:400).json({success:false,error:m})}}
